### ISSUE TITLE
Monitor not work?

### ISSUE THREAD

**Issue by yesmider** [Legedric/ptmagic#1]
I install this project as the steps on wiki, PTMagic.dll is running looking good.
But Monitor.dll seens not work,I try to connect to http://localhost:5000/,nothing show up.
I also try to change the port in settings.general.json, then run monitor again,but the port not changed.

**Comment by krims0n32** [comment]
# dotnet Monitor/Monitor.dll 
Error:
  An assembly specified in the application dependencies manifest (Monitor.deps.json) was not found:
    package: 'Microsoft.AspNetCore.Mvc.Abstractions', version: '2.0.2'
    path: 'lib/netstandard2.0/Microsoft.AspNetCore.Mvc.Abstractions.dll'
  This assembly was expected to be in the local runtime store as the application was published using the following target manifest files:
    aspnetcore-store-2.0.5.xml

**Comment by Legedric** [comment]
When you started the monitor by running the file "Start PTMagic Monitor.cmd", did you maybe close the window?
You need to have this window open as this is basically the web server providing the monitor services.

Just minimize it but leave it open.

So it should look something like this:
![image](https://user-images.githubusercontent.com/8308141/36315826-ed0cac1a-1338-11e8-9722-79ff9891bb27.png)

**Comment by yesmider** [comment]
I didn't close anything.
![default](https://user-images.githubusercontent.com/23432951/36315924-dd728050-1373-11e8-9d6b-66fd30fc70f8.png)

**Comment by Legedric** [comment]
So you do not even see an error page? Just the error 500 Chrome is giving to you?

**Comment by yesmider** [comment]
yes.

**Comment by yesmider** [comment]
I found what's wrong here,monitor use the port same as my other bot.
But there is a new problem,  I have no way to change monitor's port.

**Comment by Legedric** [comment]
Ah ok, yes. That's a known issue. The port specified in the settings is (as of now) not being used peoperly. This will get fixed in an upcoming update.

Until then, the monitor has to run on port 5000.

I will update this issue as soon as we released a fix for that.

**Comment by Legedric** [comment]
The current re-upload includes a fix for this issue. Please check if you are now able to change the port in your settings.general.json file.
