### ISSUE TITLE
Error MEssage ... something is wrong with your bot ...

### ISSUE THREAD

**Issue by agaji** [Legedric/ptmagic#100]
since upgrading to 1.0.3 i have started getting intermittent errors throughout the day. i will look at the cmd screen and its stuck in a loop telling me that something is wrong with the bot ... if it does this more than 3x restart the bot .... keeps repeating the message.

not sure what is happening. 
ive gone back to running pt without magic to see if something is wrong and its been running fine.
so im assuming something is happening when writing to properties?

thank you for this program however, much appreciated for the community support!

**Comment by Legedric** [comment]
Please provide screenshots of those errors. From what you are saying, messages like "telling me that something is wrong with the bot" so not exist in our project.

**Comment by agaji** [comment]
my apologies...the error message appears on my pt bot when i have magic running. i changed the interval minutes that magic checks market from 1 to 5 and have not had the problem occur overnight. i will change the interval back to 1 and let it run. i will capture the screen shot and post today.
thank you for your response
