### ISSUE TITLE
Take into account deposits and withdrawals to calculate balance

### ISSUE THREAD

**Issue by aditya9787** [Legedric/ptmagic#101]
Is there currently a way to account for the deposits and withdrawals while PT was running. Just putting starting balance gives the wrong calculations as I have many deposits and withdrawals after that.

**Comment by Legedric** [comment]
Currently we do not ask for API keys, which would be necessary to achieve that. We may consider adding this with a future update, but there are no plans to make that a priority at the moment.

**Comment by aditya9787** [comment]
I have PT Tracker. You have to manually add your deposits and withdrawals with dates and it calculates from there. Doesn't access the API

**Comment by Legedric** [comment]
Ah ok that's a different story, thanks.

**Comment by aditya9787** [comment]
This is the code if it helps. So it has starting value but also has dates with deposits and withdrawals.

  "General": {
    "StartingValue": "0.015",
	"Currency": "BTC",
	"UserId": "XXXXX",
	"LicenseKey": "XXXXXXXXXXXXXXX",
	"ExchangeName": "Binance",
	"BotName": "PT Tracker"
  },
  "Transfers": {
   "01/12/2018": "0.02338048",
   "01/14/2018": "0.02500000",
   "01/15/2018": "0.04474166",
   "01/24/2018": "0.02746191",
   "01/26/2018": "0.02713321",
   "01/29/2018": "0.02414216",
   "01/31/2018": "0.02690776",
   "02/06/2018": "0.12660826",
   "02/08/2018": "0.02534202",
   "02/12/2018": "0.02826396",
   "02/14/2018": "-0.00119060",
   "02/14/2018": "0.03066504",
   "02/16/2018": "0.01119954",
   "02/18/2018": "0.00284647"
  }
}

**Comment by Legedric** [comment]
Thanks, although we will not copy that behaviour from them.

**Comment by Zamboniman** [comment]
I'd be fine with the ability to just manually add in deposits and withdrawals.

**Comment by nickorooster** [comment]
This would be a great feature as I regularly deposit crypto, so the tracker currently has my daily average percentage at lower than it should be (as I've updated my "starting balance" by what I put in so that at least the current stats are accurate).

**Comment by smoochy** [comment]
Same here like nicko.

From time to time I feed BTC which I mined into binance to trade with that. As I am working with ALL_max_cost_percentage overtime this is generating more and more revenue.

But PTM needs to make its calculations based on correct numbers. Which is unforuntately not the case, whenever coins are deposited or withdrawn.

Something very handy would be, to enable a Deposits & Withdraws section in the settings menu.
There you can enter values like 0.004 or -0.001.
In addition there is an overview of past withdraws and deposits, which could also be edited.

**Comment by HojouFotytu** [comment]
Agreed.   Otherwise the %Gain, the most important part of the sales analyzer, is never really correct. 

An additional field in the settings menu under "Start Balance" where you can update with + or - amounts ?  Then perhaps an additional widget on the dashboard or sales analyzer, with a fly-out similar to the sales manager "Last 10 days" where you can see a list of all manual balance updates?

This would also be really useful for those of us doing manual trades that affect our balance.

**Comment by sorentorp** [comment]
Is there any way to "upvote" this issue?

I too think it should be added.

**Comment by dorianbanks** [comment]
100% this is the primary item needed.
Stats quickly become useless if you miss a deposit or withdrawal....which is 20% the usefulness of PTm.
