### ISSUE TITLE
PTMagic Update fail

### ISSUE THREAD

**Issue by mikdesign02** [Legedric/ptmagic#102]
![ptm](https://user-images.githubusercontent.com/34874555/36469249-82fda9ba-16de-11e8-887c-f8bb96020207.JPG)
Hi,

As requested i downloaded the new version 1.0.3 unzipped et copy pasted the Monitor files in my Monitor directory . I restarted twice TPMagic but it's still telling me that i'm running the old version. Can you tell me what is wrong?

**Comment by SPANDOOS** [comment]
Try to rename\backup your _data and _logs folder one by one. I just deleted mine so it had to rebuild from scratch and it fixed this for me as well.

**Comment by Legedric** [comment]
So you stopped the bot, copied everything over, started again and it tells you you are still running 1.0.2?
That's next to impossible as the version is nailed down in its assembly.

**Comment by Zamboniman** [comment]
According to what you wrote you only copied the files in the Monitor directory.

This is incorrect.

As per the update instructions you need to copy *all* of the files, *including* those in the Monitor directory over to your PTMagic directory. It sounds like you copied *just* the files in the Monitor directory over.

**Comment by mikdesign02** [comment]
Hi,
Yes i did as it's was notice in the PTMagic update instructions. You should modify the update instructions in the Github they didnt mention to copy  all the files including the monitor folder.  

Envoyé depuis Yahoo Mail pour Android 
 
  Le mer., févr. 21, 2018 à 14:16, Zamboniman<notifications@github.com> a écrit :   
According to what you wrote you only copied the files in the Monitor directory.

This is incorrect.

As per the update instructions you need to copy all of the files, including those in the Monitor directory over to your PTMagic directory. It sounds like you copied just the files in the Monitor directory over.

**Comment by Zamboniman** [comment]
>You should modify the update instructions in the Github they didnt mention to copy  all the files including the monitor folder.  

No, you are not correct.

From the update instructions, Step 4:

Copy all files (including the folder "Monitor") located in "PT Magic" into your PT Magic directoy and select "Yes" if you are asked to overwrite existing files

**Comment by mikdesign02** [comment]
Finely i copyed and pasted all the files including the Monitor folder and then i delected the _log folder and it's working now. No need to delecte the _data folder. 

Envoyé depuis Yahoo Mail pour Android 
 
  Le mer., févr. 21, 2018 à 14:16, Zamboniman<notifications@github.com> a écrit :   
According to what you wrote you only copied the files in the Monitor directory.

This is incorrect.

As per the update instructions you need to copy all of the files, including those in the Monitor directory over to your PTMagic directory. It sounds like you copied just the files in the Monitor directory over.
