### ISSUE TITLE
Could not load file or assembly 'System.Private.Xml

### ISSUE THREAD

**Issue by Ridonia** [Legedric/ptmagic#104]
Never change a running system....

I've had PTMagic running for 24h just fine.
Then I decided to upgrade from Version 1.0.2 to 1.0.3
Copied everything over and tried to Start it again but running in the following ErrorMsg:
`1|PTMagic  | 2018-02-21 10:38 +01:00: 
1|PTMagic  | 2018-02-21 10:38 +01:00: Unhandled Exception:
1|PTMagic  | 2018-02-21 10:38 +01:00:  
1|PTMagic  | 2018-02-21 10:38 +01:00: System.IO.FileLoadException: Could not load file or assembly 'System.Private.Xml, Version=4.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'. Access is denied.
1|PTMagic  |    at NLog.Config.XmlLoggingConfiguration..ctor(String fileName, Boolean ignoreErrors, LogFactory logFactory)
1|PTMagic  |    at NLog.Extensions.Logging.ConfigureExtensions.ConfigureNLog(ILoggerFactory loggerFactory, String configFileRelativePath)
1|PTMagic  |    at Globals.ServiceHelper.BuildLoggerService(String basePath) in D:\Tools\PTMagic\Globals\ServiceHelper.cs:line 27
1|PTMagic  |    at Globals.ServiceHelper.BuildLoggerService() in D:\Tools\PTMagic\Globals\ServiceHelper.cs:line 10
1|PTMagic  |    at PTMagic.Program.Main(String[] args) in D:\Tools\PTMagic\PTMagic\Program.cs:line 17`

After that I even downgraded back to 1.0.2 and still got the same error.
Any ideas?

**Comment by Soeski** [comment]
I see D:\Tools\PTMagic and D:\Tools\PTMagic\PTMagic .... maybe there is a problem in that regard?

**Comment by Ridonia** [comment]
SOLVED
@Soeski  Not really - there is no editable file directing to that Path and since I'm running on Linux, this Path does not exist.

**Got this problem solved by deleting _logs and _data folder**
