### ISSUE TITLE
price infinity showing

### ISSUE THREAD

**Issue by mfcholdings** [Legedric/ptmagic#106]
![1](https://user-images.githubusercontent.com/36377757/36478486-32dbe466-1705-11e8-8f42-a3a239b58cc0.png)

**Comment by mfcholdings** [comment]
today gain in percent is incorrect and then it shows infinity on the others..  please help me to update thanks

**Comment by Legedric** [comment]
Did you set a start balance in your settings.general.json?
If not it will be "0" and a division by 0 returns infinity.
