### ISSUE TITLE
Auto blacklist new listed pairs on exchange

### ISSUE THREAD

**Issue by DomoKB** [Legedric/ptmagic#107]
New listed pairs on an exchange tends to dip very quickly.   We do not want the bot to buy these losing pairs.  It would be good to have PT Magic automatically set these pairs to sell-only mode for a user defined time duration eg. 30 days since listed, then remove SOM afterwards.

New listings can be parsed from Binance:
https://support.binance.com/hc/en-us/sections/115000106672-New-Listings

There already exist a project called binance-auto-blacklist but it will conflict with PT Magic, so it cannot be used.

**Comment by Legedric** [comment]
We will consider adding this in a future update.

**Comment by HojouFotytu** [comment]
Can confirm that the add-on stops working with PTmagic.  PTmagic overwrites the lines added by auto-blacklist add-on.  I found out tonight when PT bought a new coin that was in free fall.  I think there isn't enough data for analyzer to use market trends to block them.

This is a pretty standard add-on that the majority of the community uses, for good reason.  The conflict with PTmagic could potentially be very expensive.

**Comment by Zamboniman** [comment]
Ok, here's what I did.

I downloaded the source code for the auto blacklist addon here:

https://github.com/bennettca/binance-auto-blacklist

And changed the directory from trading to Default, then recompiled it with maven. I then put the config file and the jar executable in the PTMagic  _presets directory and ran it from there. This now changes the PTMagic default files, which gets copied over to Profit Trailer as warranted.

I'll test this for a bit, but it seems to be working for the time being.

**Comment by smoochy** [comment]
Nice workaround @Zamboniman. There is just one issue, I figured out: The header information, which PTM writes into the pairs.properties of the ./trading/pairs.properties file. If that header is present, the pairs.properties from _presets does not get copied over into /trading, when changes are made to the PTM pairs.properties.

**Comment by Zamboniman** [comment]
Yup. This could potentially delay adding new coins to the running PAIRS file until the next change.

I suppose one could run the original auto blacklist simultaneously in Profit Trailer, but that's rather kludgy. Might be a solution for the time being though.

**Comment by Tosko4** [comment]
@Legedric Looks good, milestone is undecided still. Any confirmation if it's going to be in the next release?

**Comment by Legedric** [comment]
Please look at the right hand side, it clearly says: Milestone 1.3.0

**Comment by Tosko4** [comment]
Sorry, was looking at Legedric modified the milestones: Undecided, 1.3.0 a day ago

**Comment by Legedric** [comment]
Yes, GitHub doesn't show what milestone got removed and which one got added ;)

**Comment by DomoKB** [comment]
This is awesome.  Thanks for the implementation and looking forward to 1.3.0!

**Comment by JaySNL** [comment]
Thanks for implementing this. Two question though:
"ALL_sell_value_OFFSETPERCENT": -100 > my feeling says it should be all buy instead of all sell. I could be wrong ofcourse, what's the reason it's all sell?

Is there a way to do an "AND" on the days trigger? i.e trigger different settings for a new listing (12hours old) but not taking into account the general younger than 30 days rule?

{
  "SettingName": "InstaBuyNewCoin",
  "TriggerConnection": "OR",
  "Triggers": [
    {
      "AgeDaysLowerThan": 0.25
    }
  ],
  "PairsProperties": {
    "ALL_buy_value_OFFSETPERCENT": +0.01
  }
}
{
  "SettingName": "BlackListandHodl",
  "TriggerConnection": "OR",
  "Triggers": [
    {
      "AgeDaysHigherThan": 0.25
      "AgeDaysLowerThan": 30
    }
  ],
  "PairsProperties": {
    "ALL_buy_value_OFFSETPERCENT": -300
    "ALL_sell_value_OFFSETPERCENT": +25
  }
}

**Comment by Legedric** [comment]
1. Yes that's correct. Buy value is the one that should be modified there.
2. The trigger only takes integer values, so the smallest value is 1 in that case and it doesn't exist a trigger "AgeDaysHigherThan"

**Comment by JaySNL** [comment]
@Legedric thanks for the affirmation. Regarding point 2, does the logic check it in order? Say if we put "AgeDaysLowerThan": 1 first, would that be overruled if we add "AgeDaysLowerThan": 30 after that? Or would we need to do it the other way around? The idea is to have a coin that's just listed to insta buy, but not touch it when it's over that threshold and apply the general 'blacklist'.

**Comment by adam-gweleg** [comment]
Guys I can't find the new feature do I have to add this feature manually to my settings or how?

**Comment by Legedric** [comment]
@adam-gweleg Look into the settings.analyzer.json in the folder _default settings and you can see at the very bottom how you may use this.

**Comment by Tosko4** [comment]
When you download the zip file, you have two folders in there. pt magic and _default. 

You should not only overwrite the files in your pt magic installation folder with the files within the pt magic folder inside the zip file. But also compare the files that are in _default in the zip file. There i saw that new commands are added to the general setting file (like off set timezone) but also in the analyzer file a part with the blacklist section.

**Comment by JaySNL** [comment]
@Legedric so how and in which order would we trigger my idea?
- First check if coin is younger than 1 day and buy -100%
- then check if coin is younger than 30 days, dont buy it, SOM mode +25%

**Comment by Legedric** [comment]
```
{
  "SettingName": "BuyNewCoin",
  "TriggerConnection": "OR",
  "Triggers": [
    {
      "AgeDaysLowerThan": 1
    }
  ],
  "PairsProperties": {
    "ALL_buy_value_OFFSETPERCENT": -100
  }
},
{
  "SettingName": "BlockTradingNewCoin",
  "TriggerConnection": "OR",
  "Triggers": [
    {
      "AgeDaysLowerThan": 30
    }
  ],
  "PairsProperties": {
    "ALL_sell_only_mode": true,
    "ALL_sell_value_OFFSETPERCENT": 25
  }
}
```
