### ISSUE TITLE
Unhandled exception

### ISSUE THREAD

**Issue by Shanuman** [Legedric/ptmagic#108]
I seem to be getting this error that is causing the process to exit after running through initial startup.

![image](https://user-images.githubusercontent.com/36702880/36485557-7ba31e6a-1757-11e8-9816-8abe2ace8db5.png)

**Comment by Legedric** [comment]
Can you please upload your pairs.properties here (drag & drop the file into the comment text box)? It seems like there is an issue with some pairs configs there.

**Comment by Shanuman** [comment]
Thanks for the reply Legedric. Here you go mate.

Had to change the extension to .txt to get it to upload.

[PAIRS.properties.txt](https://github.com/Legedric/ptmagic/files/1745602/PAIRS.properties.txt)

**Comment by Legedric** [comment]
Thanks, this will be fixed in the next release.

**Comment by Shanuman** [comment]
Thank you mate.
