### ISSUE TITLE
PTMagic didn't start .net error? 

### ISSUE THREAD

**Issue by Fortoona** [Legedric/ptmagic#109]
How can I fix this?

![2131](https://user-images.githubusercontent.com/36703270/36486406-b85c6dae-171e-11e8-8f24-1dbafe9db56a.PNG)

**Comment by TwixRaider** [comment]
Did you download and install .NET Core following these [instructions](https://github.com/Legedric/ptmagic/wiki/Setup-PT-Magic-on-Windows)? Did the installation finish without errors?

**Comment by Zamboniman** [comment]
Looks like you're attempting to follow the wrong instructions. That appears to be Windows, follow the Windows instructions instead.

**Comment by Fortoona** [comment]
OK, somehow Windows forced me to run ptmagic with administrator privileges... case closed. Thanks for tips
