### ISSUE TITLE
Futurte release for Apple users?

### ISSUE THREAD

**Issue by robarbo** [Legedric/ptmagic#11]
Looks like a great add on!
And would definitely like to try it, however.. I am running PT on a Mac..
Will there be a version for Mac users in addition the current Windows and lLinux versions? Would be great.
Good luck and keep it up!
 Grtz Robarbo

**Comment by TwixRaider** [comment]
This should run on Mac right now as .NET Core supports this.  However we did not try this because we have no Mac :) We will include this in our Wiki as well:

https://www.microsoft.com/net/learn/get-started/macos

**Comment by robarbo** [comment]
Thanks for the quick response!

Op za 17 feb. 2018 om 15:38 schreef TwixRaider <notifications@github.com>
