### ISSUE TITLE
monitor error

### ISSUE THREAD

**Issue by Auhunter61** [Legedric/ptmagic#111]
getting this issue and not sure how to fix

C:\Users\Auhunter\Desktop\PTMagic 1.0.3\PTMagic>dotnet Monitor/Monitor.dll

Unhandled Exception: System.IO.FileNotFoundException: The configuration file 'settings.general.json' was not found and is not optional. The physical path is 'C:\Users\Auhunter\Desktop\PTMagic 1.0.3\settings.general.json'.
   at Monitor.Program.Main(String[] args) in D:\Tools\PTMagic\Monitor\Program.cs:line 32

C:\Users\Auhunter\Desktop\PTMagic 1.0.3\PTMagic>pause
Press any key to continue . . .

**Comment by Legedric** [comment]
Please check of the file that the error message is complaining about is existing.

**Comment by Auhunter61** [comment]
this file does not exist
D:\Tools\PTMagic\Monitor\Program.cs:line 32

**Comment by Legedric** [comment]
Sorry, I meant this file:
C:\Users\Auhunter\Desktop\PTMagic 1.0.3\settings.general.json

**Comment by Auhunter61** [comment]
Yes that does exist

**Comment by Legedric** [comment]
Please double check if you missed any step listed here:
https://github.com/Legedric/ptmagic/wiki/Setup-PT-Magic-on-Windows

**Comment by Auhunter61** [comment]
I'm going to install a fresh set up

**Comment by Auhunter61** [comment]
I've just downloaded the latest version and done everything and i get this 
![image](https://user-images.githubusercontent.com/36681442/36517504-0e4db4c0-17ce-11e8-92ca-fa0a31b30ae7.png)

**Comment by Auhunter61** [comment]
Solved the issue the files werent in the correct place when downloaded and had to move them from _default settings and place the the PTMagic folder

**Comment by Auhunter61** [comment]
we are all good
