### ISSUE TITLE
Monitor Error 

### ISSUE THREAD

**Issue by ShiftLizard** [Legedric/ptmagic#113]
Hey Legedric, I have PTM running but I get an error on the monitor that no one can seem to find a solution for.

C:\Users\ShiftLizard\Desktop\PTM\PTMagic 1.0.3\PTMagic>dotnet Monitor/Monitor.dll
Error:
  An assembly specified in the application dependencies manifest (Monitor.deps.json) was not found:
    package: 'Microsoft.AspNetCore.Mvc.Abstractions', version: '2.0.2'
    path: 'lib/netstandard2.0/Microsoft.AspNetCore.Mvc.Abstractions.dll'
  This assembly was expected to be in the local runtime store as the application was published using the following target manifest files:
    aspnetcore-store-2.0.5.xml

C:\Users\ShiftLizard\Desktop\PTM\PTMagic 1.0.3\PTMagic>pause
Press any key to continue . . .

Please help me out :)

**Comment by ShiftLizard** [comment]
I skipped the very first step >.< sorry I got it running

**Comment by Londoncool** [comment]
What step did you miss? I have the same problem

**Comment by ShiftLizard** [comment]
2. Download ".NET Core Runtime 2.0.5" and "ASP.NET Core Runtime 2.0.5" here:

This step Londoncool
