### ISSUE TITLE
Enhancement For DCAProperties

### ISSUE THREAD

**Issue by NACrushers** [Legedric/ptmagic#114]
"SettingName": "Boring",
        "TriggerConnection": "AND",
        "Triggers": [
          {
            "MarketTrendName": "Exchange1h",
            "MaxChange": .20
          },
          {
            "MarketTrendName": "Exchange12h",
            "MaxChange": 0
          },
          {
            "MarketTrendName": "Exchange24h",
            "MaxChange": 0.5,
            "MinChange": -3
          }
        ],
        "PairsProperties": {
          "ALL_buy_value": -0.99,
		  "ALL_trailing_buy": 0.149,
          "ALL_sell_value": 0.89,
          "ALL_trailing_profit": 0.149
        },
        "DCAProperties": {
          "sell_value": 0.89,
          "trailing_profit": 0.149,
          "trailing_buy": 0.149

Be able to change Buy triggers,Buy strategy,Buy Style in DCAProperties for different market conditions

Example:
"DCAProperties": {
          "sell_value": 0.89,
          "trailing_profit": 0.149,
          "trailing_buy": 0.149,
          "buy_strategy" = "ANDERSON",
          "buy_style" = "DOUBLEDOWN",
          "buy_trigger_1" = -2,
          "buy_trigger_2" = -2,
          "buy_trigger_3" = -2,
          "buy_trigger_4" = -2,
          "buy_trigger_5" = -2,
          "buy_trigger_6" = -2

I tried to do this but get errors

**Comment by Legedric** [comment]
What errors? This should be possible with PT Magic.

**Comment by NACrushers** [comment]
2018/02/21 12:33:17.408 INFO - ########################################################## 
2018/02/21 12:33:17.408 INFO -  
2018/02/21 12:35:58.241 INFO -  
2018/02/21 12:35:58.499 INFO -   ██████╗ ████████╗    ███╗   ███╗ █████╗  ██████╗ ██╗ ██████╗ 
2018/02/21 12:35:58.499 INFO -   ██╔══██╗╚══██╔══╝    ████╗ ████║██╔══██╗██╔════╝ ██║██╔════╝ 
2018/02/21 12:35:58.510 INFO -   ██████╔╝   ██║       ██╔████╔██║███████║██║  ███╗██║██║      
2018/02/21 12:35:58.510 INFO -   ██╔═══╝    ██║       ██║╚██╔╝██║██╔══██║██║   ██║██║██║      
2018/02/21 12:35:58.510 INFO -   ██║        ██║       ██║ ╚═╝ ██║██║  ██║╚██████╔╝██║╚██████╗ 
2018/02/21 12:35:58.510 INFO -   ╚═╝        ╚═╝       ╚═╝     ╚═╝╚═╝  ╚═╝ ╚═════╝ ╚═╝ ╚═════╝ 
2018/02/21 12:35:58.510 INFO -                          Version 1.0.3 
2018/02/21 12:35:58.510 INFO -  
2018/02/21 12:35:59.055 FATAL - Error loading configuration! System.FormatException Could not parse the JSON file. Error on line number '122': '"trailing_buy": 0.149,
"buy_strategy" = "ANDERSON",'.    at Microsoft.Extensions.Configuration.FileConfigurationProvider.Load(Boolean reload)
   at Microsoft.Extensions.Configuration.ConfigurationRoot..ctor(IList`1 providers)
   at Microsoft.Extensions.Configuration.ConfigurationBuilder.Build()
   at Globals.SystemConfiguration.LoadSettings(String basePath) in D:\Tools\PTMagic\Globals\SystemConfiguration.cs:line 35
   at PTMagic.Program.Main(String[] args) in D:\Tools\PTMagic\PTMagic\Program.cs:line 41

**Comment by NACrushers** [comment]
},
        "DCAProperties": {
          "sell_value": 0.89,
          "trailing_profit": 0.149,
          "trailing_buy": 0.149
		  "buy_strategy" = "ANDERSON",
          "buy_style" = "DOUBLEDOWN",
          "buy_trigger_1" = -2,
          "buy_trigger_2" = -2,
          "buy_trigger_3" = -2,
          "buy_trigger_4" = -2,
          "buy_trigger_5" = -2,
          "buy_trigger_6" = -2
        }

**Comment by NACrushers** [comment]
},
        "DCAProperties": {
          "sell_value": 0.89,
          "trailing_profit": 0.149,
          "trailing_buy": 0.149,
          "buy_strategy" = "ANDERSON",
          "buy_style" = "DOUBLEDOWN",
          "buy_trigger_1" = -2,
          "buy_trigger_2" = -2,
          "buy_trigger_3" = -2,
          "buy_trigger_4" = -2,
          "buy_trigger_5" = -2,
          "buy_trigger_6" = -2
      },

**Comment by NACrushers** [comment]
By the way I LOVE this program, Great job!

**Comment by Legedric** [comment]
Your JSON format is incorrect. You missed the ":" behind the property names and the "=" is not allowed there. Please compare the line for "trailing_buy" with the next line "buy_strategy". That's the error.

The correct block would like like this:
```
"DCAProperties": {
      "sell_value": 0.89,
      "trailing_profit": 0.149,
      "trailing_buy": 0.149,
      "buy_strategy": "ANDERSON",
      "buy_style": "DOUBLEDOWN",
      "buy_trigger_1": -2,
      "buy_trigger_2": -2,
      "buy_trigger_3": -2,
      "buy_trigger_4": -2,
      "buy_trigger_5": -2,
      "buy_trigger_6": -2
  },
```

**Comment by NACrushers** [comment]
Thanks, Sorry I completely missed that.
