### ISSUE TITLE
Trand Market did not update.

### ISSUE THREAD

**Issue by juato4** [Legedric/ptmagic#116]
Market Trends:
CMC24h: -10.71%
Exchange1h: 0.03%
Exchange12h: 0.03%
Exchange24h: 0.03%

all hrs same %…

**Comment by Legedric** [comment]
We need a bit more info on that:
- Which exchange?
- What markets?
- How long is the bot already running?

**Comment by juato4** [comment]
- Binance
- BTC
- 1 hr.

**Comment by Legedric** [comment]
Thanks, do you see changes of the trends in your monitor?

**Comment by juato4** [comment]
<img width="1410" alt="captura de pantalla 2018-02-21 a la s 17 44 31" src="https://user-images.githubusercontent.com/35824627/36504327-e96c77ee-172e-11e8-97be-7e15acbbf5a0.png">

**Comment by Legedric** [comment]
What does the left graph on your dashboard look like, please?
Because that's where I can see the actual changes.

**Comment by juato4** [comment]
<img width="852" alt="captura de pantalla 2018-02-21 a la s 17 50 52" src="https://user-images.githubusercontent.com/35824627/36504582-c97389b8-172f-11e8-9a11-dc8af649884a.png">

**Comment by juato4** [comment]
<img width="692" alt="captura de pantalla 2018-02-21 a la s 17 53 10" src="https://user-images.githubusercontent.com/35824627/36504687-1cc5b3fc-1730-11e8-992a-d82320adf5ce.png">

**Comment by Legedric** [comment]
That's quite strange, I never had that happen before.

When you look at your bot, cann you see some lines like this?
![image](https://user-images.githubusercontent.com/8308141/36504747-d8549c02-1751-11e8-8ef0-b8f4a32dc609.png)

If so, please post a screenshot of those lines here.

**Comment by Legedric** [comment]
Is it possible that you started the bot once, then turned it off for severalk hours and started it again?

**Comment by juato4** [comment]
<img width="957" alt="captura de pantalla 2018-02-21 a la s 17 58 11" src="https://user-images.githubusercontent.com/35824627/36504928-ce0183e4-1730-11e8-840d-254ea5ec57bb.png">

**Comment by juato4** [comment]
"Is it possible that you started the bot once, then turned it off for severalk hours and started it again?
"

yes,

**Comment by Legedric** [comment]
Ok, then please follow these steps:
- Stop PT Magic (the one bot that has these errors)
- Delete the folder named "Exchange" inside "_data" in PT Magic
- Start the bot again (it will take up to 15 minutes again to rebuild the exchange data)

**Comment by juato4** [comment]
Ok!
