### ISSUE TITLE
command PT does not excist

### ISSUE THREAD

**Issue by Peet911** [Legedric/ptmagic#117]
ALL_trailing_profit_OFFSETPERCENT

i find this setting in single market settings of PTM at FREEFALLBLOCK, cant find it on PT Wiki??

**Comment by Legedric** [comment]
It is no PT setting, it is one for PT Magic. (see here: https://github.com/Legedric/ptmagic/wiki/Writing-Properties)

It sill set your ALL_trailing_profit to an offset of your current value.

So in case your trailing profit is 0.1, this setting wil reduce your trailing profit for a pair by 30%, setting the trailing_profit to 0.7

**Comment by Peet911** [comment]
Thanks!


2018-02-21 22:46 GMT+01:00 Legedric <notifications@github.com>:
