### ISSUE TITLE
PT Magic Monitor refuses to run. Gives error message

### ISSUE THREAD

**Issue by Londoncool** [Legedric/ptmagic#118]
I have successfully run PT Magic but have not been able to run PT Magic Monitor, it doesn't run. I get the following ERROR message.

Error:
  An assembly specified in the application dependencies manifest (Monitor.deps.json) was not found:
    package: 'Microsoft.ApplicationInsights.AspNetCore', version: '2.1.1'
    path: 'lib/netstandard1.6/Microsoft.ApplicationInsights.AspNetCore.dll'

  This assembly was expected to be in the local runtime store as the application was published using the following target manifest files:
    aspnetcore-store-2.0.0-linux-x64.xml;aspnetcore-store-2.0.0-osx-x64.xml;aspnetcore-store-2.0.0-win7-x64.xml;aspnetcore-store-2.0.0-win7-x86.xml

Kindly let me know what I need to do. I did download the Asp .Net.Core v2.0.5. Thanks

**Comment by Zamboniman** [comment]
Check #65

**Comment by Londoncool** [comment]
I have checked the Issue #65 thread and have not found any solution there. Thanks

**Comment by Londoncool** [comment]
Sorted.
