### ISSUE TITLE
[SOLVED] Installation on Debian - Segfault error

### ISSUE THREAD

**Issue by Arararararagi** [Legedric/ptmagic#119]
I just helped a guy solved an issue related to Debian and dotnet. Googling a bit, I also found other people with the same issue [here](https://github.com/dotnet/core-setup/issues/1490).

![](https://cdn.discordapp.com/attachments/415995900477964310/415996227629481984/unknown.png)

Solution:
`sudo apt remove libssl1.0.0/now`
`sudo apt-get update`
`sudo apt-get upgrade`
`sudo apt-get install libssl1.0.2`

Result:

![](https://cdn.discordapp.com/attachments/415995900477964310/416003400228929536/unknown.png)

One happy french user.

I think it would be great to add this to the wiki.

**Comment by Legedric** [comment]
Thankls, added to the wiki!
