### ISSUE TITLE
The file is missing: LastRuntimeSummary.json

### ISSUE THREAD

**Issue by innerpartycolt** [Legedric/ptmagic#12]
After launching `dotnet Monitor/Monitor.dll` I get this error in the browser:

```
Could not find a part of the path '/home/user/ptmagic/ptmagic/_data/LastRuntimeSummary.json'.
```

Indeed, there is no such file. The '_data' folder isn't there either.

The version of ptmagic I'm using is 1.0.1

**Comment by TwixRaider** [comment]
Did the program in the PT Magic window finished its first run? This can take up to 10-15 minutes because it collects a lot of data from the exchange for the last 24 hours to build the market trends. The summary file as well as the _data folder is created after that has been completed.

**Comment by innerpartycolt** [comment]
Indeed, this was the issue. Now everything is working.
Thanks!
