### ISSUE TITLE
Unable to start Monitor

### ISSUE THREAD

**Issue by Londoncool** [Legedric/ptmagic#120]
When starting the PT Magic Monitor I got this message.

C:\Users\richa\Desktop\ProfitTrailer\PTMagic 1.0.3\PTMagic>dotnet Monitor/Monitor.dll

Unhandled Exception: System.IO.FileNotFoundException: The configuration file 'settings.general.json' was not found and is not optional. The physical path is 'C:\Users\richa\Desktop\ProfitTrailer\PTMagic 1.0.3\settings.general.json'.
   at Monitor.Program.Main(String[] args) in D:\Tools\PTMagic\Monitor\Program.cs:line 32.

Any guide on what to do please to get it starting

**Comment by creakyjoints** [comment]
did same for me. i put profit trailers path in instead of path for profit trailer magic.

**Comment by Londoncool** [comment]
Sorted now. I changed the path.
