### ISSUE TITLE
Analyzer Settings - Cost/Percentage

### ISSUE THREAD

**Issue by Cryptonic2** [Legedric/ptmagic#121]
Is there a way to OFFSET the all_max_cost and/or all_max_cost_percentage? Let’s say PTM throws PT into “To the Moon” mode and I have a max cost percent of 3%. Specifically, I would like the ability to scale my 3% percentage cost by, let’s say 10%, which would bring it to 3.3%. I don’t use max cost anymore, but for the people who do I think it might be useful for them as well.

**Comment by Legedric** [comment]
Yes, you can do that using the _OFFSET or _OFFSETPERCENT suffixes as listed here:
https://github.com/Legedric/ptmagic/wiki/Writing-Properties
