### ISSUE TITLE
Runtime

### ISSUE THREAD

**Issue by RichardKeschinger** [Legedric/ptmagic#122]
is the last runtime suppose to be when you last start it or the interval you have set in min? because mine hasn't changed in 6 hours

**Comment by RichardKeschinger** [comment]
fixed it, but still freezes cmd in PT even with quick edit mode off

**Comment by Legedric** [comment]
Any errors when it freezes?
Can you post a screenshot?

**Comment by RichardKeschinger** [comment]
It really has to do with PT and I think my whole VPS which may affect magic, and forget everything else as this picture was a while ago, but the last line happens all the time

![fa641178-fe23-41f9-b9c9-bc21bba33267](https://user-images.githubusercontent.com/36017175/36523392-f8b9f572-1766-11e8-9739-f5b301d1f80e.png)

**Comment by Legedric** [comment]
Well, the screenshot you posted is from Profit Trailer itself, not PT Magic. So there is nothing we can do about it from our side.
