### ISSUE TITLE
PT command window error

### ISSUE THREAD

**Issue by vishsom** [Legedric/ptmagic#126]
After running PT Magic, PT seems to be running normally, but every 5 minutes or so I get a message on the PT command window saying "There is something wrong with your Bot, let me try to restore it". This wasn't happening before I started running PT Magic, is this normal or something I need to address. Thanks!

**Comment by Legedric** [comment]
I never had that before. Can you please post a screenshot of that message?

**Comment by vishsom** [comment]
Thanks for the quick response. I’m attaching the screenshot.

**Comment by vishsom** [comment]
So i restarted PT and PT Magic and that specific message is not showing up
anymore. But I noticed every now and then it seems like either PT or PT
Magic is stopping.

The last Runtime indicator turns red every now and then. And I also got a
couple of different errors. I have attached them to this email as well.

**Comment by Legedric** [comment]
Sorry but I do not see any pictures, you will have to upload them here, not attach them in an email.

**Comment by vishsom** [comment]
I updated PT magic and haven’t been getting any of those errors

**Comment by vishsom** [comment]
Actually it just happened again

**Comment by vishsom** [comment]
![ff9c2eea-d123-4b9a-a87b-48240bbdacf9](https://user-images.githubusercontent.com/36733429/36596744-bb41f1fe-1874-11e8-91a9-3487ffdd19ea.png)
![0c41cbd1-b6d7-438e-8f54-0d6c661da071](https://user-images.githubusercontent.com/36733429/36596745-bb5d31da-1874-11e8-9d90-8857790679f4.png)
![294a0f39-f8f7-4a27-b755-90cf42ed3256](https://user-images.githubusercontent.com/36733429/36596746-bb6ef71c-1874-11e8-8b21-7809f9eefce0.png)

**Comment by Legedric** [comment]
Are you using more than one instance of PT Magic?
Seems like you are running more than one as only PT Magic accesses these files that are shown in your error messages.

**Comment by vishsom** [comment]
I only have one instance of PT Magic running and it’s on a VPS

**Comment by Legedric** [comment]
Please follow these steps:
- Stop PT Magic
- Delete the folder "Exchange" in "_data" in PT Magic
- Start PT Magic (It will take up to 15 minutes as it will rebuild the data)

**Comment by vishsom** [comment]
Okay, I’ve done that. Going to see if that error comes up again. I did get this on my PT command window 

![5976e596-16c1-4c40-898d-30aeef6203ac](https://user-images.githubusercontent.com/36733429/36598634-d7acb56c-187a-11e8-9af3-4a819091230e.png)
