### ISSUE TITLE
Market Trends are all the same for USDT

### ISSUE THREAD

**Issue by Crypto-Bites** [Legedric/ptmagic#127]
Hi, 

Great update, but I notice that all the trends in USDT for the 1hr, 12hr and 24hr are the same. 
![capture](https://user-images.githubusercontent.com/36629846/36540029-5b5aab58-17b3-11e8-8b46-a672e32640be.PNG)

**Comment by Legedric** [comment]
Please follow these steps:
- Stop PT Magic
- Delete the folder "Exchange" in "_data" in PT Magic
- Start PT Magic (It will take up to 15 minutes as it will rebuild the data)

**Comment by Crypto-Bites** [comment]
Thanks that did the trick.
