### ISSUE TITLE
Issue #46 still appearing in v.1.1.0

### ISSUE THREAD

**Issue by ADWilkinson** [Legedric/ptmagic#128]
As requested, the issue I raised in the previous version has still surfaced in the current version - #46 to be reopened please if possible. I would love this to be fixed as it currently spams PT log files too as the configuration keeps getting written over (even if its in the same state).

Thanks a lot for the current progress so far on this great add-on

**Comment by Legedric** [comment]
Thanks, I reopened issue #46
