### ISSUE TITLE
Discussion place ?

### ISSUE THREAD

**Issue by JeanGalt** [Legedric/ptmagic#129]
Are you there a place (Discord, Telegram, ...) to discuss or ask questions about the use (and not the development) of PTMagic?

For example, I would like to know :
- if we can use such Analyzer settings as is, and if they do not risk too much to change my current strategy, 
- or if there is a way to launch both PTMagic and Monitor with a single command placed on the Windows desktop, without going to the PTMagic directory

**Comment by Zamboniman** [comment]
https://discord.gg/NgS52wj

**Comment by JeanGalt** [comment]
Thanks !
