### ISSUE TITLE
Error when launching PT Magic first time; can not find settings.general.json ?

### ISSUE THREAD

**Issue by RobinopdeBeek** [Legedric/ptmagic#130]
![pt magic error](https://user-images.githubusercontent.com/31888353/36544047-78d666f4-17b3-11e8-8ed7-8bc5f80612b0.PNG)

I get this error when launching PTMagic for first time. Anyone know what to do?

**Comment by Legedric** [comment]
Please check this guide and double check if you missed a step:
https://github.com/Legedric/ptmagic/wiki/Setup-PT-Magic-on-Windows

**Comment by Legedric** [comment]
Closing as there was no feedback for several days.
