### ISSUE TITLE
Incorrect TRA Status

### ISSUE THREAD

**Issue by clippart** [Legedric/ptmagic#131]
Hi Legedric and the team!
Thank you for your product. It's great.

Today I sorted out pairs that do not want to trade

####---GavnoEbanoe---
AEBTC_trading_enabled = false
AMBBTC_trading_enabled = false
ARKBTC_trading_enabled = false
...etc

and saw the following in the monitor. it is correct ?

![default](https://user-images.githubusercontent.com/33903011/36546676-97151a8c-181e-11e8-83ac-e7ca014b030a.PNG)

**Comment by Legedric** [comment]
Thanks, checking that one.
