### ISSUE TITLE
Settings error for PAIRS.PROPERTIES & DCA.PROPERTIES by settings.analyzer.json

### ISSUE THREAD

**Issue by novex1984** [Legedric/ptmagic#132]
I been tested and confirm. alphabet rewrite by ptmagic to profit trailer files is always small letters which cause error to profit trailer. profit trailer only recognize capital letter. For example;

"ALL_sell_strategy": "GAIN" from settings.analyzer.json rewrite to pairs.properties will become ALL_sell_strategy = gain

![ptm make pt error](https://user-images.githubusercontent.com/12774765/36547794-a00c49ac-1829-11e8-90ec-3ef185a4b58a.jpg)

**Comment by Legedric** [comment]
Thanks, will be fixed in 1.1.1
