### ISSUE TITLE
Another settings errors (Minor) from settings.analyzer.json.

### ISSUE THREAD

**Issue by novex1984** [Legedric/ptmagic#133]
If change settings by folder for example.

  {
        "SettingName": "03 - BearSighted",
        "TriggerConnection": "AND",
        "Triggers": [
          {
            "MarketTrendName": "Exchange1h",
            "MaxChange": 1
          },
          {
            "MarketTrendName": "Exchange12h",
            "MaxChange": 0
          },
          {
            "MarketTrendName": "Exchange24h",
            "MaxChange": -1,
            "MinChange": -3
          }
        ],
        "PairsProperties": {
          "File": "PAIRS.PROPERTIES"
        },
        "DCAProperties": {
          "File": "DCA.PROPERTIES"
        },
        "IndicatorsProperties": {
          "File": "INDICATORS.PROPERTIES"
        }
      },

It will cause an error. Please refer to my screenshot.
![ptm make pt error2](https://user-images.githubusercontent.com/12774765/36548183-987325a2-182a-11e8-9061-e49c2d1bf6f1.jpg)

**Comment by Legedric** [comment]
The error you posted there is from Profit Trailer itself that it cannot save the data file properly. That's got nothing to do with PT Magic.
I had that error already when PT Magic wasn't there :)
