### ISSUE TITLE
Rasberry Pi Compatibility

### ISSUE THREAD

**Issue by TallPaulC** [Legedric/ptmagic#135]
Will there be any release for the Raspberry PI?

I am running PT on a Pi3 with Raspbian Stretch. Many users are running this "Profit Pi" Configuration.

I have tried but from some articles I have read, it looks like the Dotnet SDK cannot be loaded onto the Pi, something to do with the fact it has an ARM processor.

This looks like a great project and would love to be able to use this on my setup.

**Comment by Legedric** [comment]
Duplicate of #81
