### ISSUE TITLE
Constant login when running two monitors in the same browser

### ISSUE THREAD

**Issue by aqueiroz** [Legedric/ptmagic#136]
Great work on the new version.

I it just me or do we get prompted for password, every time PTmagic does a check? in my case every 3 minutes I have to re-login.

Am running 2 instances, happens on both.

Regards

**Comment by Legedric** [comment]
Usually not, the diel timeout is 15 minutes (so it should never be idle when you have the auto refresh.
But there may be an issue with having two instances open in the same browser.

**Comment by aqueiroz** [comment]
cool thanks. Let me know if you need some logs

**Comment by djbadders** [comment]
Yup really like the UI, but I can confirm having different instances in two tabs or more causes constant password prompts. Maybe use the new session storage in the browser for the context as this is isolated per tab

**Comment by Legedric** [comment]
This issue will be fixed in the next release.

**Comment by aqueiroz** [comment]
I can confirm if I open one instance on Chrome and another on IE the issue does NOT happen

**Comment by Legedric** [comment]
Please check if version 1.1.1 fixed this issue (using one browser).
