### ISSUE TITLE
No graphs 

### ISSUE THREAD

**Issue by Siege88** [Legedric/ptmagic#137]
After the update, the graphs at the bottom aren't showing up, I restarted twice. 
![no graph](https://user-images.githubusercontent.com/36741679/36555203-4a1bd648-17cf-11e8-9457-200f0646108f.PNG)

**Comment by rodolpho2211** [comment]
Samething here!!

**Comment by Legedric** [comment]
Can you post a screenshot of the whole page, please?

**Comment by Siege88** [comment]
![whole page](https://user-images.githubusercontent.com/36741679/36559194-3c375b04-17db-11e8-84fe-0e77e01d79a3.PNG)

**Comment by Legedric** [comment]
Please press F12 in your browser, refresh the page and look if there are some erros listed in the console (that windows you opened with F12).

**Comment by Siege88** [comment]
Not seeing errors I don't think this, and PT console is fine other than my bnb bought price which is another issue that keeps happening but I don't think it's from PT magic. 
![no errors](https://user-images.githubusercontent.com/36741679/36559942-65f6d792-17dd-11e8-9bcf-9c55ae02069a.PNG)

**Comment by Legedric** [comment]
Thanks, but I mean the console I put a circle around in that screen here. That's where I want to see the errors :)
![image](https://user-images.githubusercontent.com/8308141/36560019-e6af150c-180f-11e8-9ca0-265273112118.png)

**Comment by Siege88** [comment]
Oh ok, here you go..thank you btw. 
![errors1](https://user-images.githubusercontent.com/36741679/36560232-2e61cd54-17de-11e8-8f5a-9a6ef1234a49.PNG)

**Comment by rodolpho2211** [comment]
![image](https://user-images.githubusercontent.com/36743487/36560873-e3dda526-17c6-11e8-8bdd-65ec71fc35d0.jpg)


![image](https://user-images.githubusercontent.com/36743487/36560922-0eb54b50-17c7-11e8-891f-5091d768285d.jpg)

**Comment by nsater** [comment]
Seeing the issue as well. Upgraded to 1.1.0 from 1.0.3
Firefox 58.0.2
![2018-02-22 22_42_07-mail](https://user-images.githubusercontent.com/30016839/36583147-3f733ae2-1829-11e8-8e48-d2f1da2668c5.png)

**Comment by Legedric** [comment]
Please follow these steps:
- Navigate to http://localhost:5000/_get/MainPage (replace localhost by whatever you use to access the monitor)
- You will see a strange looking site with just white background and text on it
- Right click anywhere on the screen
- Select "Show source" (or similar, depending on your browser)
- Scroll to the very bottom of the window that just opened
- Please post a screenshot of what you are seing there here, it should look something like this:
![image](https://user-images.githubusercontent.com/8308141/36583807-737f16dc-1877-11e8-9a75-06d91118bc58.png)

**Comment by Legedric** [comment]
PS: Do you have the same problem on the Sales Analyzer page?

**Comment by Siege88** [comment]
I can't say that I have the same problem on sales analyzer page because I haven't made any sales yet with ETH as my base.
![eth sales](https://user-images.githubusercontent.com/36741679/36585551-4ee2459a-184c-11e8-8d09-fef610895695.PNG)

**Comment by Siege88** [comment]
![source](https://user-images.githubusercontent.com/36741679/36585666-cbaae410-184c-11e8-88f4-3327a792f8d8.PNG)

**Comment by Legedric** [comment]
Ok thanks.

How about the others @rodolpho2211 and @nsater ?

**Comment by Legedric** [comment]
The original issue of @Siege88  will be fixed in the next release.

**Comment by Siege88** [comment]
@Legedric  Awesome! thank you again man.

**Comment by rodolpho2211** [comment]
![image](https://user-images.githubusercontent.com/36743487/36588393-cc5124ca-183c-11e8-8200-bc5bbc242186.jpg)
![image](https://user-images.githubusercontent.com/36743487/36588463-032adba8-183d-11e8-8aff-97467f71d12c.jpg)

**Comment by rodolpho2211** [comment]
@Legedric sorry for the pics, but as you can see graphics are not showing still, also upgrade already but still getting msg from prompt and screem... I just drop the new files also monitor at the old folder...

**Comment by Siege88** [comment]
@Legedric just a small update, I have not installed the newest version but overnight my bot did make a couple sales....and now the graph has started populating.
![made sales](https://user-images.githubusercontent.com/36741679/36607056-7dc815dc-1893-11e8-9067-0b9273e862aa.PNG)
