### ISSUE TITLE
usage of OFFSET

### ISSUE THREAD

**Issue by miladzamani** [Legedric/ptmagic#138]
hi sry but i didnt get the correct usage of offset or offset percentage .
this is what wiki said : 
Offset by value

You can set a Profit Trailer property to a an offset of the current value BY a fixed value.

Example:
"ALL_buy_value_OFFSET": -0.1
can someone help me ?

**Comment by Legedric** [comment]
We will extend the wiki on that one soon.

**Example for OFFSET:**
- The current setting for ALL_buy_value is -1
- You use "ALL_buy_value_OFFSET": -0.1
- The new setting for ALL_buy_value will be -1.1
=> So the original value got offset by a fixed value

**Example for OFFSETPERCENT:**
- The current setting for ALL_buy_value is -1
- You use "ALL_buy_value_OFFSETPERCENT": -20
- The new setting for ALL_buy_value will be -1.2
=> So the original value got offset by -20%
