### ISSUE TITLE
Monitor not displaying in Windows Server - Chrome, Edge

### ISSUE THREAD

**Issue by ughitisntworking** [Legedric/ptmagic#139]
The exact same thing is happening for me as in issue #75 - It worked fine in 1.0.2, stopped working on 1.0;3, and continues to not work in the latest release.  I'm getting the same error information as was in 75 when checking console.  I even attempted checking if it was a port issue but that isn't causing it either.  
I can attempt to open up the port for accessing it from my home computer to see if it will display correctly from a remote computer but I am not holding my breath.

**Comment by Legedric** [comment]
So you are getting 404 errors for the assets files?

**Comment by ughitisntworking** [comment]
Uncaught ReferenceError: $ is not defined
    at (index):182

I don't know if it's for the assets file, where should I look? Above is just one line from the console and I'm looking at that via my home computer.

**Comment by Legedric** [comment]
Please check if all files are located in your Monitor folder.

There should be several files and folders like:
wwwroot
wwwroot/assets
wwwroot/assets/css
wwwroot/assets/js

**Comment by ughitisntworking** [comment]
The assets files are there.  Looks like the same list of folders but I'm not sure of the individual files.

**Comment by ughitisntworking** [comment]
I tried uninstalling and reinstalling to no avail.  I could go back and install from the original file and updating version by version to see if that remedies it.

**Comment by Legedric** [comment]
Please check if version 1.1.1 fixed this issue.

**Comment by Legedric** [comment]
Closing as there was no feedback for several days.
