### ISSUE TITLE
System Update - Not issue

### ISSUE THREAD

**Issue by rodolpho2211** [Legedric/ptmagic#140]
**Not an issue
Just wondering and may be the question from many begginers like me! Which file should I copy to update the system! 
Thanks

**Comment by Zamboniman** [comment]
https://github.com/Legedric/ptmagic/wiki/Updating-PT-Magic

**Comment by rodolpho2211** [comment]
Thanks I have my system update working fine, insert password ! Just wondering if I'm still getting msg promp saying my bot is out of date?! Do you know if is because i just copy and paste the files and didnt change the folder name?

**Comment by Legedric** [comment]
It may take 30 minutes for PT Magic do start a new version check recognizing the new version.

**Comment by rodolpho2211** [comment]
Thanks!! Btw awesome addon!! 👍🏻
