### ISSUE TITLE
Monitor - DASHBOARD page Error

### ISSUE THREAD

**Issue by miladzamani** [Legedric/ptmagic#142]
hi , i have this error in
<img width="960" alt="1" src="https://user-images.githubusercontent.com/35540216/36562145-47973a3c-182b-11e8-97af-e7fbc6f42189.png">
 2hours and its only on dashboard page , other page are working fine

**Comment by Legedric** [comment]
Please navigate to thist url:
http://188.165.168.55:5000/_get/MainPage

And see what error comes up there.

**Comment by miladzamani** [comment]
the problem was on analyses file , its solved
