### ISSUE TITLE
I have Two Problems.

### ISSUE THREAD

**Issue by CMalin75** [Legedric/ptmagic#143]
At First the bot was working fine for 2 days along side with PT, then it put up a warning "no market trend change for exchange1h returning 0%" it did the same for exchange12h and exchange24hr. And it would completely crash. It also set my PT to watch only mode, where it is currently stuck. I've completely updated both PTM and PT and still stuck in watchonly. I've also put my pairs back to the stock settings but that didn't help. If I have a low ballance because of dca will 
Ptmagic trigger watchonly? Also after the update PTMagic continues to show the same warning in purple letters and will not trigger any settings. But now it doesn't crash. It just does nothing. Also my monitor screen looks more like a sitemap then the display you have online. Thanks in Advance

**Comment by Legedric** [comment]
Please post a screenshot of the errors/warnings you are getting, thanks.

**Comment by CMalin75** [comment]
I figured out the warnings and made some repairs. All is well with that,
I'm now longer in watchmode. But I am using Windows and its displaying the
monitor like a website map and not showing the dashboard correctly. Thats
the only issue I'm having.

Thanks
Chad

**Comment by vishsom** [comment]
Chad, could you explain what you did to get your PT off of watchonly, seems like I’m having the same issue

**Comment by CMalin75** [comment]
I deleted the coinpairs I put in my pairs file and set it back to trade
all. Make sure you do the same with PT Magic default preset file.

**Comment by CMalin75** [comment]
I also set my min volume up to 850 in hopes of minimizing bagd.
