### ISSUE TITLE
ptmagic>dotnet ptmagic.dll failed to load

### ISSUE THREAD

**Issue by shadowolfs** [Legedric/ptmagic#144]
when i run ptmagic.cmd 
I get this faild msg
Failed to load the dll from [?*], HRESULT: 0x80070057
the library hostfxr.dll was found, but loading it from c:\program files\dotnet\host\fxr\2.0.5\hostfxr.dll failed
  - installing .NET Core prerequisites might help resolve this problem
http://go.microsoft.com/fwlink/?LinkID=798306&clcid=0x409

**Comment by Legedric** [comment]
So did you do what the message suggests?

**Comment by shadowolfs** [comment]
Yes i did. get same thing

**Comment by Legedric** [comment]
Usually that's tied to a missing update in your Windows machine.

A quick search on Google digged up that post from the official dotnet core GitHub:

> Hi
Had this similar issue. I have Win 7 SP1. Installed Windows update from following link and got resolved.
https://www.microsoft.com/en-us/download/details.aspx?id=26767
>Hope it helps

Can you check if you already installed this update right here for your Win 2008 machine:
https://support.microsoft.com/en-us/help/2533623/microsoft-security-advisory-insecure-library-loading-could-allow-remot

That's what I just linked for Win 7 and sometimes it does not get distributed via Windows' automated update system.

> Update for Windows Server 2008 x64 Edition (KB2533623)

> [Download Download the Windows6.0-KB2533623-x64.msu package now](http://www.microsoft.com/downloads/details.aspx?familyid=755cab42-2ce6-499a-bb8e-e5f1c17ce8ad)

.

**Comment by shadowolfs** [comment]
thanks that got it
