### ISSUE TITLE
Monitor GUI not loading -- help :(

### ISSUE THREAD

**Issue by lkowalyk30** [Legedric/ptmagic#146]
The monitor page loads but no GUI. I have a white background with 4 links on the top left. I can click these links and it will give me some info but no interface. 
![capture](https://user-images.githubusercontent.com/36749324/36571221-7a6bfede-17ea-11e8-86c5-d26c39648575.PNG)

**Comment by Legedric** [comment]
Please try if that problem is fixed when the upcoming release is available.
