### ISSUE TITLE
PTMagin\Monitor will not open

### ISSUE THREAD

**Issue by nebgolfer** [Legedric/ptmagic#148]
I have read the settings over and over and watched a couple of set up videos how to set up PTMagic. for Profti Trailer. When I click on the startPTMagicMonitor.comd file the black box opens then I get a black command box with these lines-

c:\ptmagic>dotnet Monitor/Monitor.dll
Hosting Environment: Production
Content root path: C:\|PTMagic\Monitor
Now listening on : http://0.0.0:5000
Application started. Pres Ctrl+C to shut down

That is it the black box just sits and no other information is showing.  When I click on the Start PTMagic the box opens and runs and I see  market information and it told me I was on the wrong update. I have sense updated to the current version but I still do not have the monitor running. 
Thanks for creating this and thanks in advance for your help.
!

**Comment by Legedric** [comment]
The black you are seeing there (the one with those line you listed above) IS the monitor service.
Now open a browser and navigate to http://localhost:5000 to open the actual monitor.
