### ISSUE TITLE
What standard buy strategy for PTMagic?

### ISSUE THREAD

**Issue by crypto-design** [Legedric/ptmagic#15]
After I run PTMagic they have parameter ALL_buy_value for various strategies.
I use LOWBB before with ALL_buy_value positive values, so your ALL_buy_value have negative values -  So what strategy you use for standard from the box - EMASPREAD, EMAGAIN, LOWBB or etc.?

**Comment by Legedric** [comment]
PT Magic itself is not using any buy startegy on its own. It is just using whatever you configure.
The settings found in the "_default settings" folder are specified for EMAGAIN, so they are set to absolute values.

If you are using LOWBB or HIGHBB you may want to set thevalue for ALL_buy_value to a positive percent value as suggested in the Profit Trailer wiki - so as you had it before:
https://wiki.profittrailer.io/doku.php/buy_and_sell_strategies

When you launch the monitor, you can see what your Profit Trailer is currently set to use as buy strategy:
![grafik](https://user-images.githubusercontent.com/8308141/36350453-53dd7900-1498-11e8-96de-7098ef5a1d15.png)
