### ISSUE TITLE
ERROR - No 'default' setting found! Terminating process...

### ISSUE THREAD

**Issue by clippart** [Legedric/ptmagic#150]
Hi!
I wanted to change the name from Default to MyNAme, but got an error:

ERROR - No 'default' setting found! Terminating process...

Is it possible in the future not to become attached to Default and change the default market to its name?

      {
        "SettingName":"MyNAme",
        "PairsProperties":{
          "File":"PAIRS.PROPERTIES"
        },
        "DCAProperties":{
          "File":"DCA.PROPERTIES"
        },
        "IndicatorsProperties":{
          "File":"INDICATORS.PROPERTIES"
        }
      }
![11](https://user-images.githubusercontent.com/33903011/36578883-98e89cc0-1892-11e8-8417-25c9bdc07ef9.PNG)

**Comment by Legedric** [comment]
Nope, default setting is mandatory. But you may name every other setting as you want to.
