### ISSUE TITLE
Feature Request: Market Trends Graph

### ISSUE THREAD

**Issue by HojouFotytu** [Legedric/ptmagic#152]
Is it possible to get a graph spanning the top of the Market Trends page, similar to the trend graph on the dashboard?   

In addition to the Exchange and CMC graph, if it isn't too difficult to add, it could also include a trendline for the base currency, and a single trendline representing the sum of the combined markets in the list?

Something like this:

![markets](https://user-images.githubusercontent.com/36724681/36580838-4fd1aa3e-18ad-11e8-9404-08965a71682c.JPG)

**Comment by Legedric** [comment]
For charting we use a library called nvd3 and this library has no native support for trendlines and we do not plan to develop a trendline option into that.
