### ISSUE TITLE
Getting market data error.

### ISSUE THREAD

**Issue by NrgWolf** [Legedric/ptmagic#153]
2018/02/23 17:30:01.352 INFO - Starting market trend check with Version 1.1.0 
2018/02/23 17:30:01.352 INFO - CoinMarketCap - Getting market data... 
2018/02/23 17:31:41.366 FATAL - The operation has timed out. System.Net.WebException The operation has timed out.    at System.Net.HttpWebRequest.GetResponse()
   at BusinessRules.MarketAnalyzer.BaseAnalyzer.GetSimpleJsonListFromURL(String url, LogHelper log) in D:\Tools\PTMagic\BusinessRules\MarketAnalyzer\BaseAnalyzer.cs:line 73
2018/02/23 17:31:41.406 FATAL - Object reference not set to an instance of an object. System.NullReferenceException Object reference not set to an instance of an object.    at BusinessRules.MarketAnalyzer.CoinMarketCap.GetMarketData(SystemConfiguration systemConfiguration, LogHelper log) in D:\Tools\PTMagic\BusinessRules\MarketAnalyzer\CoinMarketCap.cs:line 19
2018/02/23 17:31:41.406 INFO - Binance - Getting market data... 
2018/02/23 17:33:21.424 FATAL - The operation has timed out. System.Net.WebException The operation has timed out.    at System.Net.HttpWebRequest.GetResponse()
   at BusinessRules.MarketAnalyzer.BaseAnalyzer.GetSimpleJsonArrayFromURL(String url, LogHelper log) in D:\Tools\PTMagic\BusinessRules\MarketAnalyzer\BaseAnalyzer.cs:line 97
2018/02/23 17:33:21.424 FATAL - Exception while getting data for '': Object reference not set to an instance of an object. System.NullReferenceException Object reference not set to an instance of an object.    at BusinessRules.MarketAnalyzer.Binance.GetMarketData(String mainMarket, SystemConfiguration systemConfiguration, LogHelper log) in D:\Tools\PTMagic\BusinessRules\MarketAnalyzer\Binance.cs:line 44
2018/02/23 17:33:21.436 ERROR - No valid pairs found for main market 'BTC' in configured pars list ()! Terminating process... 

After this happens, i can't restart the bot and PT magic until the PC is rebooted.... The interval that it happens is at random anywhere from 20 min to 2 hours.

**Comment by Legedric** [comment]
Seems to be related to the internet connection of the machine you are running your bot on.

Because it may happen when one platform (for example CoinMarketCap) is producing a timeout (meaning it is not able to connect to it) but two platforms at the same time is quite impossible.

**Comment by NrgWolf** [comment]
I did take that into consideration, how ever my net is usually quite stable with generally no issues, 3.5mb upload and 8mb download.... quality Australian net :-P.....
This has only started happening since i started running PTmagic, my bot has been running on the same machine prior with 0 Issues unless i caused them lol.


i will continue to monitor and see if i can find any indicating triggers.

**Comment by jongruud** [comment]
Same problemen here. I cant get it to run because of this..
 22:09:59.856 INFO - CoinMarketCap - Getting market data...
2018/02/23 22:09:59.936 INFO - CoinMarketCap - Market data received for 100 currencies
2018/02/23 22:10:00.202 INFO - CoinMarketCap - 24h market data rebuilt.
2018/02/23 22:10:00.202 INFO - CoinMarketCap - Market data saved.
2018/02/23 22:10:00.202 INFO - CoinMarketCap - Market data cleaned.
2018/02/23 22:10:00.202 ERROR - No valid pairs found for main market 'BTC' in configured pars list ()! Terminating process...

**Comment by Legedric** [comment]
Closing as there was no feedback for several days.
