### ISSUE TITLE
The most important thing...

### ISSUE THREAD

**Issue by HojouFotytu** [Legedric/ptmagic#154]
Would it be possible to have the new setting line printed last in the monitor window?  

I'm guessing I'm not the only one who keeps the monitor open, and other than errors, this is probably of the most important piece of information users might be looking for.  It should be quickly visible without having to scroll back...

Nothing pressing... just a thought.  ;)

![untitled-2](https://user-images.githubusercontent.com/36724681/36586965-ed9c3ee6-18c6-11e8-9a62-6cb1ba707c9e.jpg)

**Comment by Legedric** [comment]
Thanks, just added this to the next release.
![image](https://user-images.githubusercontent.com/8308141/36587824-859f17e0-1886-11e8-9ddb-30b6328cd3a0.png)
