### ISSUE TITLE
Update and Sell Strategy

### ISSUE THREAD

**Issue by vishsom** [Legedric/ptmagic#157]
I've already read the how to update wiki but I just wanted to make sure I understood it correctly. I'm supposed to copy the update PT Magic files into my current PT Magic folder right? And not the other way around.

Also for the last two days I've just been using the settings.analyzer settings straight from the download, as in I haven't changed anything in them. And so far since using PT Magic my Profit trailer Sell Strategy has been at WATHCMODE the while time. I saw one of my pairs go up to 3.5% profit and the bot didn't do anything and now it's back down to 0.4% profit. 
![watch mode](https://user-images.githubusercontent.com/36733429/36594477-3a09beee-186c-11e8-92eb-034129b6391c.PNG)

**Comment by Legedric** [comment]
PT Magic doesn't put anything in watchmode (so basically disable trading for a pair). So please check your Profit Trailer settings what's going on there.

**Comment by vishsom** [comment]
Does PT Magic ever set “enable all trading pairs” to false?

**Comment by Legedric** [comment]
PT Magic only sets things you configure it to do. And the default settings do not touch trading at all.

**Comment by Legedric** [comment]
Closing as there was no feedback for several days.
