### ISSUE TITLE
PTM monitor error

### ISSUE THREAD

**Issue by Auhunter61** [Legedric/ptmagic#158]
Getting this error after copying over as per instructions

![capture 5](https://user-images.githubusercontent.com/36681442/36594703-1031e464-18eb-11e8-9627-8a490cb46a8a.PNG)

**Comment by Legedric** [comment]
So did you check what the message says?
Seems like you did not follow the update instructions properly:
https://github.com/Legedric/ptmagic/wiki/Updating-PT-Magic

**Comment by Auhunter61** [comment]
Fixed now my apologies too late here and blury eyes one to many \\\
