### ISSUE TITLE
Monitor did not change the version when upgrading. 

### ISSUE THREAD

**Issue by juato4** [Legedric/ptmagic#159]
it says v1.0.3, but i am on v1.1.1

**Comment by Legedric** [comment]
Is PT Magic running? So I mean the bot itself?

**Comment by juato4** [comment]
Yes, bot and monitor.. both

**Comment by juato4** [comment]
<img width="376" alt="captura de pantalla 2018-02-23 a la s 10 48 38" src="https://user-images.githubusercontent.com/35824627/36597194-1ee3397c-1887-11e8-86e7-b9ae55b6ff82.png">

**Comment by Legedric** [comment]
What version does your bot say it has?

**Comment by juato4** [comment]
<img width="1141" alt="captura de pantalla 2018-02-23 a la s 10 50 54" src="https://user-images.githubusercontent.com/35824627/36597295-6fe1107e-1887-11e8-96b6-b129f8fcb3e3.png">

**Comment by Legedric** [comment]
Please press CTRL+F5 in your browser to enforce a fresh load and see if that helps.

**Comment by juato4** [comment]
didnt work, and i tried to open it on other browser and i have same thing.

**Comment by Legedric** [comment]
Seems like you monitor is not pointing to the correct bot directory then.
Please check the appsettings.json in your Monitor and see if the setting for PTMagicBasePath is set to the correct PT Magic directory.

**Comment by juato4** [comment]
Yes… now is ok… when i was upgrading.. i didn't change that!. Thanks

**Comment by Legedric** [comment]
Usually there is no need to change that but you somehow didn't follow the update instructions closely.
https://github.com/Legedric/ptmagic/wiki/Updating-PT-Magic
