### ISSUE TITLE
Supporting Poloniex, would it be possible ?

### ISSUE THREAD

**Issue by cakel** [Legedric/ptmagic#16]
Thanks for great tool.
I'm setting up the ptmagic, and I found out that it supports currently exchange bittrex and binance, but not poloniex.

I temporary set-up to poloniex configured Profit Trailer with Binance setting. Well monitored but incompatible result, because as you know, added currency settings are improper to Poloniex.

So, would you have a plan to support Poloniex ?

**Comment by Legedric** [comment]
Supporting Polonie is already on our schedule. However, no ETA on that right now :)

**Comment by cakel** [comment]
Thanks, it'll test it with Binance based environment.

**Comment by cakel** [comment]
I appreciate for your support.
I'll test it to my Poloniex environment.
