### ISSUE TITLE
Posibility to change the UTM TIME...

### ISSUE THREAD

**Issue by juato4** [Legedric/ptmagic#161]
I am on -3, and i cant change it..

**Comment by Legedric** [comment]
Please be more specific? Where in PT Magic do you see wrong times?

**Comment by juato4** [comment]
specialy on day change…. i have sales from yesterday that i did today.

**Comment by juato4** [comment]
i think is because i am on -3

**Comment by Legedric** [comment]
Windows or Unix?

**Comment by juato4** [comment]
windows

**Comment by Legedric** [comment]
So is the clock of your WIndows machone set to your correct timezone?

**Comment by juato4** [comment]
no. My VPS are on 17:53… and i am on 10:53.

**Comment by juato4** [comment]
<img width="230" alt="captura de pantalla 2018-02-23 a la s 10 54 43" src="https://user-images.githubusercontent.com/35824627/36597470-fbd87fa4-1887-11e8-801b-8cd4533a0696.png">

**Comment by juato4** [comment]
my time is 10:54

**Comment by Legedric** [comment]
Then try setting the clock of your VPS to 10:53 and see if that helps

**Comment by juato4** [comment]
Ok, i will

**Comment by Legedric** [comment]
Closing as there was no feedback for several days.
