### ISSUE TITLE
Issue USDT Binance "No market trend found! The pair may have got delisted from your exchange!"

### ISSUE THREAD

**Issue by TheZnuf** [Legedric/ptmagic#162]
Hi,

Thanks a lot for you work!

I have 2 instances and one work great another give me this error : No market trend found! The pair may have got delisted from your exchange!

Thank you

**Comment by Legedric** [comment]
Screenshot please.

**Comment by TheZnuf** [comment]
![pt magic](https://user-images.githubusercontent.com/18206135/36599124-b3317798-18ae-11e8-81f4-397571281f74.png)

**Comment by TheZnuf** [comment]
Working now. Maybe a problem with binance. 
Don't know.
