### ISSUE TITLE
USDT still not displaying the correct profit in the dashboard... 

### ISSUE THREAD

**Issue by mfcholdings** [Legedric/ptmagic#163]
in dashboard ... sales overview ..  the USD profit is still showing 0.00 because there is not a USDT ticker price to base the calculation off ..  please update this.. we under stand its normally around 1to1 but it would be nice to not have a 0 in profit usd..

**Comment by Legedric** [comment]
The price for USDT is set to 1 so this shouldn't happen. Please provide a screenshot of your Sales Analyzer page.

**Comment by mfcholdings** [comment]
![1](https://user-images.githubusercontent.com/36377757/36599183-e9306552-18ae-11e8-8558-46f1a8ca5296.png)

here is the screen showing it still not displaying correcty

also on the btc bots i run.. they all now say v1.1.1 in dashboard... but on the ETH and USDT bots i run they still say v1.0.3    ... the usdt bot no longer has the ticker.. and all bots required password setup so they all have bee updated correct..

**Comment by mfcholdings** [comment]
any update.. still getting no price for USDT

**Comment by mfcholdings** [comment]
also on the btc bots i run.. they all now say v1.1.1 in dashboard... but on the ETH and USDT bots i run they still say v1.0.3 ... the usdt bot no longer has the ticker.. and all bots required password setup so they all have bee updated correct..

**Comment by Legedric** [comment]
Can you please ZIP and upload your ProfitTrailerData.json here? This way I would be able to track the issue down better. I am only trading BTC so the sell values are of course way lower than with USDT.

**Comment by Legedric** [comment]
I tested this myself using USDT and I have no problems. In addition there was no feedback for a couple of days now so I am assuming this issue is no longer occuring.
![image](https://user-images.githubusercontent.com/8308141/36934399-08ad8d66-1ee9-11e8-9128-e6cce14a7fbe.png)
