### ISSUE TITLE
Volatility Reading

### ISSUE THREAD

**Issue by Gitulu** [Legedric/ptmagic#166]
Hello guys,

It seems after a time the volatility 
calculation crash because of the same values.
I have tested this in the version "1.1.1".

![volatility](https://user-images.githubusercontent.com/35115314/36607336-9b7c92be-18c6-11e8-8c2d-d9cd2323983e.png)

Attached you will find my log file.

[2018-02-23.txt](https://github.com/Legedric/ptmagic/files/1752527/2018-02-23.txt)

**Comment by Legedric** [comment]
Please follow these steps:
- Stop PT Magic
- Delete the folder "Exchange" in "_data" in PT Magic
- Start PT Magic (It will take up to 15 minutes as it will rebuild the data)

**Comment by Gitulu** [comment]
Thanks a lot Legedric
