### ISSUE TITLE
Monitor Error

### ISSUE THREAD

**Issue by BeldarConehead** [Legedric/ptmagic#168]
I'm running PTMagic on a Mac, PTMagic runs fine, no errors, but when I try to run "dotnnet Monitor.dll" I get this error: 
Error:
  An assembly specified in the application dependencies manifest (Monitor.deps.json) was not found:
    package: 'Microsoft.AspNetCore.Mvc.Abstractions', version: '2.0.2'
    path: 'lib/netstandard2.0/Microsoft.AspNetCore.Mvc.Abstractions.dll'
  This assembly was expected to be in the local runtime store as the application was published using the following target manifest files:
    aspnetcore-store-2.0.5.xml

I'm also running the latest ProfitTrailer, 1.2.6.19 if that makes any difference.

**Comment by BeldarConehead** [comment]
Has this been fixed or did you just close the ticket?? I'm unable to use your product until this is resolved.

**Comment by Legedric** [comment]
We are no Mac OS users and the issue is not a problem in PT Magic but with your.Net Core installation on your Mac. As no other Mac user provided any input on this for almost 3 weeks now I closed this issue. You may try if someone is able to help you on Discord.
