### ISSUE TITLE
Monitor ERROR on Windows VPS

### ISSUE THREAD

**Issue by paul-seo** [Legedric/ptmagic#169]
My PTMagic (ver 1.1.1) is running on VPS well but I can't run Monitor. Every time I click Start PTMagic Monitor.cmd file it keeps saying the same:

**C:\Users\Administrator\Desktop\PTMagic>botnet Monitor/Monitor.dll
ERROR: PT Magic settings not found: ‘C:\Users\Administrator\Desktop\ProfitTrailer_Binance\settings.general.json’. Please check if you setup PT Magic correctly!**

I've set it up exactly by instructions and also by following the last video from datacrypto. So I wonder why it expects **settings.general.json** file in my PT folder? Is it normal? If yes, does it mean I need to copy **settings.general.json** to my PT folder?
![screen shot 2018-02-23 at 23 00 34](https://user-images.githubusercontent.com/36458500/36616957-c1cdc78c-18f6-11e8-8f5d-06cbc9a57d45.png)

**Comment by paul-seo** [comment]
![screen shot 2018-02-23 at 23 00 34](https://user-images.githubusercontent.com/36458500/36616937-aaa5bea2-18f6-11e8-87c9-fe17d802b39d.png)

**Comment by Legedric** [comment]
Please check the appsettings.json file in your Monitopr folder and see what the path for PTMagicBasePath is in there.

**Comment by paul-seo** [comment]
I followed rule about double slash for sure. Here are the screenshots:

Here is the real path
![path](https://user-images.githubusercontent.com/36458500/36627511-05625090-1955-11e8-9a37-f332b66626a7.jpg)

Here is my appsettings.json file in my Monitor folder
![path01](https://user-images.githubusercontent.com/36458500/36627538-537a32d4-1955-11e8-9edc-e951a37ce8b1.jpg)

**Comment by Legedric** [comment]
Yes, your PT MagicBasePath is obviously pointing to your PT directory and NOT to the PT Magic directory :)

**Comment by paul-seo** [comment]
OMG...l

Looks like Dumb and Dumber movie was about me lol

THANK YOU!!
