### ISSUE TITLE
Telegram chat ID issue

### ISSUE THREAD

**Issue by innerpartycolt** [Legedric/ptmagic#17]
If the chat ID is too big, the following error is displayed in browser:

>Error.
>An error occurred while processing your request.
>Request ID: 0HLBMR8RCS0RQ:00000001
>Failed to convert '-1234567891234' to type 'System.Int32'.

I guess it's because the id is bigger than 2,147,483,647

**Comment by Legedric** [comment]
Thanks for posting this issue. It will be fixed with the next release.
