### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by sitespagando** [Legedric/ptmagic#170]
Many people do not know what strategy to use in the PT, would there be some form of PT MAGIC, analyze the market and say what the best buying and selling strategy is (to make the most of our capital and modality). The application is very good, but it's still not automatic, because we should configure what PT will do. As we see he analyzes the brokerage's market, he should sit down with professionals from the trade area, LETING the PT to act at all, in case we would only change the amount of PAR and VALUE OF THE BANK, would be excellent.

Congratulations on the job! I would love to use this tool and be able to earn at least 2% a day with no effort to keep changing my PT settings.

**Comment by Legedric** [comment]
Well, as much as we like the automated change of settings, we still want to keep it in a way the user may see through what PT magic does and make it somewhat "predictable" and reliable. Proposing buy and sell strategies would be quite a lot of analyzation and would still more or less be vague only. So it is quite unlikely to get added to PT Magic.
