### ISSUE TITLE
settings.secure.json

### ISSUE THREAD

**Issue by FrankM77** [Legedric/ptmagic#173]
Hello Legedric,
I'm getting an error when I go to the Monitor webUI.  I put in my password and it throws back an error.  I tried checking my settings.secure.json file but I cannot find this file anywhere.  I downloaded version 1.1.1 zip and looked and could not find the file in this zip package either.  Any suggestions?

**Comment by Legedric** [comment]
Please provide a screenshot of the error you are receiving.

**Comment by TwixRaider** [comment]
The file settings.secure.json is not in the zip. It is created as soon as you create your password when first asked.

**Comment by FrankM77** [comment]
Hey guys,
I woke up this morning and turned everything on again the same as last night.  And now everything is working.  Which is weird because I did nothing differently.  It's working now.  Not sure how.  Thank you!
