### ISSUE TITLE
Suggestion: Auto SOM all pairs but MaxTopMarkets or MaxMarkets

### ISSUE THREAD

**Issue by bvebve** [Legedric/ptmagic#174]
I think it'll be usefull a kind of automatic black list (sell only mode) with all pairs except MaxTopMarkets  and/or MaxTopMarkets.

On PT it's only possible to filter by minimum fixed price or fixed volume. It would be great to work only with top market pairs without filtering by volume or price.

**Comment by HojouFotytu** [comment]
I think you can use the single pairs section of the analyzer to approximate this effect.   Perhaps not by ranking, but by using a comparison you should be able to isolate pairs that come close to something like this...  i'm just not sure what those settings would be?
