### ISSUE TITLE
Suggestion: Combined logic operators for Triggers

### ISSUE THREAD

**Issue by bvebve** [Legedric/ptmagic#175]
It would be fantastic to be design more flexible (chained) operators for triggers on GlobalSettings and SingleMarketSettings.

Example: 
    Mastertrigger1: (OR triggers1) AND (OR triggers2)
    Mastertrigger2: (AND triggers1) OR (AND triggers2)

**Comment by Legedric** [comment]
We will consider it, but it doesn't have a high priority.

**Comment by xAndyxNL** [comment]
Sounds like a good plan, i have a set of x + y + z triggers (AND) and would like to combine it with an OR.
For now i've just created a new global setting with identical changes but a different trigger (OR).

**Comment by Legedric** [comment]
PTM is already quite complex and as we try not to over engineer things we decided to decline this feature request.
