### ISSUE TITLE
Stuck on writing pairs.properties for single market settings...

### ISSUE THREAD

**Issue by Juleseck** [Legedric/ptmagic#178]
PTMagic V1.1.1 
It ran fine for a couple hours until it started freezing while writing to pairs.properties. This happens to me randomly and it won't continue anymore after.
![image](https://user-images.githubusercontent.com/15907940/36623359-30902612-1904-11e8-9ada-0ce85d06bdfe.png)

**Comment by Juleseck** [comment]
Thank you! Appreciate your work a lot.

**Comment by Legedric** [comment]
This should be fixed with the next release.
