### ISSUE TITLE
Windows VPS Monitor

### ISSUE THREAD

**Issue by DragonBtc93** [Legedric/ptmagic#179]
How can I make it so I can see my monitor on a remote computer?

**Comment by TwixRaider** [comment]
There are guides in this Wiki on how to use Apache, Nginx and Caddy as a remote proxy for that on Linux https://github.com/Legedric/ptmagic/wiki/FAQ-and-Tips

For a windos machine you only have to create a incoming firewall rule for port 5000: https://wiki.mcneel.com/zoo/window7firewall
