### ISSUE TITLE
Does not switch settings when "exchange24h" surpasses 3%

### ISSUE THREAD

**Issue by cx040156** [Legedric/ptmagic#181]
For the default settings, once we enter "Ready for lift off" mode and "exchange24h" surpasses 3%, it will switch back to the default settings. However, if I delete the line "MaxChange": 3 in "Ready for lift off" mode, it does not automatically switch to "To the moon" settings when the market goes up more(e.g. 3.5% in "exchange24h") because all parameters still fit "ready to lift off" mode. I'd prefer if the bot can check routinely for the most suitable mode, or is there any other way to tweak the settings around? 
Thanks a lot.

**Comment by Legedric** [comment]
Well, these are just the standard settings and you could of course tweak them as you need to, if you are knowing what you are doing. :)
