### ISSUE TITLE
Pair Volumne

### ISSUE THREAD

**Issue by db49erfan1** [Legedric/ptmagic#182]
Any chance on adding pair volumne in the next rendition?
Great work btw!

**Comment by Legedric** [comment]
It is planned to observe the volume in a future release. No ETA though.

**Comment by goferit** [comment]
+1

Have created settings to avoid P&Ds, but avoid good upswings too. A good way to beat a P&D is to base a trade on average volume over a longer period than 24 hours, as the day of the P&D, there is high volume meeting PT min volume criteria, volume which never returns till the next P&D, trapping you in DCA if you unluckily bought. This can be avoided with short interval SOM, triggered by PTM, but again, you miss good high average volume markets when they go on a run. Which is some of the most profitable trading to participate in.
