### ISSUE TITLE
Monitor won't Start and no Error Message

### ISSUE THREAD

**Issue by Cryptoflys** [Legedric/ptmagic#183]
PTMagic was running on installed version 1.0.4. Next morning server had lost connection with program. Tried to start monitor to no avail. Downloaded and installed 1.1.0 and ran, but monitor would not start also. Today I downloaded 1.1.1, PTMagic is running but still no monitor. Double clicking on "Start PTMagic Monitor"and no action and no message. 
![pt magic monitor fail](https://user-images.githubusercontent.com/36783707/36626155-f1d0739e-1978-11e8-819f-71cc8fb425f8.png)a
appsettings.json seem ok
 "PTMagicBasePath": "C:\\Users\\Administrator\\Desktop\\PTMagic.1.1.1\\PTMagic 1.1.1", 

Have tried changing port to 5100 and 5200 but still no action. Please help? Love your work!!!
Running PTMagic on server.

**Comment by Legedric** [comment]
Please check when you right click the "Start PTMagic Monitor.cmd" if there is something like "Unblock this program" and try that.

**Comment by Cryptoflys** [comment]
Thank you! Now I can get the .cmd screen, but it now has this error message
C:\Users\Administrator\Desktop\PTMagic.1.1.1\PTMagic 1.1.1\PTMagic>dotnet Monitor/Monitor.dll
ERROR: PT Magic runtime summary not found: 'C:\Users\Administrator\Desktop\PTMagic.1.1.1\PTMagic 1.1.1\PTMagic\_data\LastRuntimeSummary.json'. Please wait for PT Magic to complete its first run!
The PTMagic program is running and re-runs regularly approx every few minutes. The monitor says it is still waiting on the program.
Thanks for the mega fast reply. I am sure you are going to do very well with this program once you have finishing the initial build.

**Comment by Legedric** [comment]
You have to start the PT Magic bot first and wait for its first run to complete :)

**Comment by Cryptoflys** [comment]
C:\Users\Administrator\Desktop\PTMagic.1.1.1\PTMagic 1.1.1\PTMagic>dotnet Monitor/Monitor.dll
ERROR: PT Magic runtime summary not found: 'C:\Users\Administrator\Desktop\PTMagic.1.1.1\PTMagic 1.1.1\PTMagic\_data\LastRuntimeSummary.json'. Please wait for PT Magic to complete its first run!
Same message after 3 hours of Start Monitor attempts.
Next!
Thanks for your support, i'm sure some fix will eventuate

**Comment by Legedric** [comment]
Check the path and see if the file is there:
C:\Users\Administrator\Desktop\PTMagic.1.1.1\PTMagic 1.1.1\PTMagic_data\LastRuntimeSummary.json

If not, you path setup in you Monitor/appsettings.json file may be wrong as the path there looks kinda weird to me.

**Comment by Cryptoflys** [comment]
Thanks so much for your help. Could not find the
_data\lastRuntimeSummary.json in the folders directory, so I restructured
the the PTMagic folder to only 1 level and renamed from PTMagic 1.1.1 to
PTMagic, redirected the app and settings files to the new path and success!
I've been using your PTMagic since you did the interview with Crypto Face
and I was impressed with your vision, as the Profit Trailor bot is quite
static, not a really interactive GUI and Feeder is very basic and
uninspiring. I hope you were prepared for the lack of working hours in a
day, 24 is not enough!!! Kudo's to you guys for having a vision and being
so helpful and hard working. I wish you all the best and look forward to
where you are taking PTMagic.

Cheers,
Daz
