### ISSUE TITLE
Market update bug/flaw

### ISSUE THREAD

**Issue by magyosha** [Legedric/ptmagic#184]
bit of a major flaw or bug.
if you have stopped magic for a lenth of time then re-run it does not fetch new market data.. it uses the existing data it had from before.
the problem is then if there has been any major changes since last run it does not update the market stats correctly.
the workround is to delete all files in the data directory to force it to re fetch all the new data .. 
suggestion : check age of existing data on startup

**Comment by Legedric** [comment]
That's already known and planned for a future release.
