### ISSUE TITLE
Instructions need improvement

### ISSUE THREAD

**Issue by mile6919** [Legedric/ptmagic#189]
I have difficulties to understand logic how for example triggers are used in PT Magic and instructions are lacking quite a lot of needed info.
For example I have set trigger as follows:
------------------
"GlobalSettings": [ // Global settings for Profit Trailer properties
      {
        "SettingName": "EndOfTheWorld", // UNIQUE name of your setting
        "TriggerConnection": "AND", // Define if triggers will be connected by AND or OR
        "Triggers": [ // Your triggers for this setting
          
		  {
            "MarketTrendName": "Exchange1h",
            "MaxChange": 0
          },
		  
          {
            "MarketTrendName": "Exchange12h",
            "MinChange": -3
          }
--------------------

Now PT Magic shows currently market trend of "Exchange1h" to be -0.1% and "Exchange12h" is 1.13%.
Now PT Magic applies "EndOfTheWorld" settings even trigger conditions are not met. Do I not understand how "MinChange" and "MaxChange" work?

How about if I would like to set trigger that is in effect when "Exchange1h" is (-1.5%)-(-0.5%)?
How will i set it?
Like this?
----------------
"MarketTrendName": "Exchange1h",
            "MinChange": -1.5,
            "MaxChange": -0.5
----------------------
Is this correct?

How about if I would like to set trigger that is in effect when "Exchange1h" is (-0.5%)-(0.5%)?
How will i set it?
Like this?
----------------
"MarketTrendName": "Exchange1h",
            "MinChange": -0.5,
            "MaxChange": 0.5
----------------------
Is this correct?

Seriously, instructions of usage of these triggers and other settings need to be improved and examples of usage with explanations of settings are needed in order to better understand how to make this nice tool to work properly. I like this tool already but would like to see some improvements to instructions to get this working properly.

**Comment by Legedric** [comment]
Yes, your both example sare correct.

PT magic is working from negative to positive so lets say MinChange starts at -100% at MaxChange ends at 100%.

You top example with EndOfTheWorld is working as intended as MinChange is set to -3% for the Exchange12 Trend and 1.13% is of course a larger number than -3%.

We know the wiki is lacking some examples on that but the project is just released for a week now and our priority for the very first week was on moving the project forward.

**Comment by goferit** [comment]
@Legedric Strongly agree, please throw up a quick example in the wiki, stared at the settings for 30 minutes straight and just can't figure min/ max out. :(

**Comment by mile6919** [comment]
"You top example with EndOfTheWorld is working as intended as MinChange is set to -3% for the Exchange12 Trend and 1.13% is of course a larger number than -3%."

@Legedric I have to say that I disagree with your statement you gave above (quoted) if I think how my logic works.
My "EndOfTheWorld" example tried to set trigger that goes in effect when "Exchange12h" has lowered at least 3% ((Minimum Change to negative direction, thats how I understand "MinChange": -3), so market trend is negative. If this is not how it works, then I think we need quickly several examples to instructions how these are intended to be used as I'm totally confused now.
Your explanation above (quoted) does not make sense and "EndOfTheWOrld" is not working as I intended. If my "Exchange12h" Trend is +1.13 then this trigger should not be TRUE.

**Comment by Legedric** [comment]
Sorry @mile6919  but you did not quite understand the basics of how the triggers work and I already gave you an example by saying MinChange starts at -100% and MaxChange ends at +100% (in theory it could be higher of course).

How should PT magic know that when you use "MinChange" you mean a negative 3 instead of positive 3?

So if you want to trigger a setting when something goes below -3% then you have to use MaxChange -3%. You have to think of a scale here from bottom (MinChange) to top (MaxChange).

So in your case it would be:
```
{
        "MarketTrendName": "Exchange1h",
        "MaxChange": 0
      },
     {
        "MarketTrendName": "Exchange12h",
        "MaxChange": -3
      }
```

In this case, the setting will trigger as soon as the 1h trend has a trend change of lower than 0 and the 12h trend has a change of lowe than -3. And lower as -3 is -3.1, -4, or even -20. Simply working with numbers here, nothing special.
