### ISSUE TITLE
Raspberry Pi

### ISSUE THREAD

**Issue by disavowedking** [Legedric/ptmagic#19]
Has this been installed and tested on a raspberry pi? - As a side note, amazing project! Can't wait to get this up and running!

**Comment by TwixRaider** [comment]
In theory it runs on every platform that Microsoft .NET Core supports. Not sure if thats the case for Raspberry Pi.

**Comment by TwixRaider** [comment]
Looking at the Github repository of .NET Core it seems that they have a version for that, too. But we never tried this.

https://github.com/dotnet/core/blob/master/samples/RaspberryPiInstructions.md

**Comment by SW-Nicki** [comment]
Gibt es eine Möglichkeit, von Euch zu erfahren, ob es auf einem Raspberry läuft? Wird das noch getestet?
Es gibt unglaublich viele Nutzer, die den PT auf einem Raspberry laufen lassen; hier wäre eine Installationshilfe super und wünschenswert. Nicht jeder ist so fit in tiefgreifende Installationsroutinen.
Das Programm scheint spitzenklasse zu sein, aber wenn man nicht weiß, wie man es zum Laufen bringt..........

**Comment by Baconqueror** [comment]
Starting to speak english would be a start.

**Comment by TwixRaider** [comment]
Wurde noch nicht getestet, da wir keinen Pi haben. Theoretisch könnte das aber funktionieren:

https://github.com/dotnet/core/blob/master/samples/RaspberryPiInstructions.md

**Comment by SW-Nicki** [comment]
ok, daa bin ich leider raus, keine Ahnung, wie man das installiert. Denke, so wird es aber vielen Raspberry-Pi Besitzern gehen............ Schade!

**Comment by Ridonia** [comment]
PT Magic is running good on a ProfitPi, but for the Monitor you need to install the dot.net Framework wich I'm not able to get that done :-/

**Comment by SW-Nicki** [comment]
Hi,

how did you install PT Magic on the Raspberry?

 

Gesendet: Dienstag, 20. Februar 2018 um 15:10 Uhr
Von: Ridonia <notifications@github.com>
An: Legedric/ptmagic <ptmagic@noreply.github.com>
Cc: SW-Nicki <Coin@Niklaus-Web.de>, Comment <comment@noreply.github.com>
Betreff: Re: [Legedric/ptmagic] Raspberry Pi (#19)


PT Magic is running good on a ProfitPi, but for the Monitor you need to install the dot.net Framework wich I'm not able to get that done :-/

**Comment by Ridonia** [comment]
Hi Nicki

 

I use CryptoGnomes ProfitPi wich is running a Raspberian (Stretch).

In that particular case, the dotnet runtime is already installed and you can just install the PTMagic and run it with pm2

 

Von: SW-Nicki <notifications@github.com>
Antworten an: Legedric/ptmagic <reply@reply.github.com>
Datum: Mittwoch, 21. Februar 2018 um 00:26
An: Legedric/ptmagic <ptmagic@noreply.github.com>
Cc: Ridonia <info@krypto-investition.com>, Comment <comment@noreply.github.com>
Betreff: Re: [Legedric/ptmagic] Raspberry Pi (#19)

 


Hi,

how did you install PT Magic on the Raspberry?

 

Gesendet: Dienstag, 20. Februar 2018 um 15:10 Uhr
Von: Ridonia <notifications@github.com>
An: Legedric/ptmagic <ptmagic@noreply.github.com>
Cc: SW-Nicki <Coin@Niklaus-Web.de>, Comment <comment@noreply.github.com>
Betreff: Re: [Legedric/ptmagic] Raspberry Pi (#19)


PT Magic is running good on a ProfitPi, but for the Monitor you need to install the dot.net Framework wich I'm not able to get that done :-/

**Comment by shadowolfs** [comment]
Ridonia,
So you are saying PTMagic Monitor runs on Profitpi?
I can get PTMagic to run but not Monitor
