### ISSUE TITLE
DCA Calculator is not working

### ISSUE THREAD

**Issue by cryptomaj** [Legedric/ptmagic#191]
![error1](https://user-images.githubusercontent.com/36665049/36632616-60210938-1980-11e8-8099-7a66eeaa5d89.JPG)

**Comment by Legedric** [comment]
Please press F12 while on that page, refresh and see what the tab "console" says in the window you just opened with F12.

**Comment by frydrce** [comment]
![img_1025](https://user-images.githubusercontent.com/36804363/36636845-2d9459b6-19c6-11e8-8e62-8a76657c819e.jpg)

Having the same issue.

**Comment by cash-money** [comment]
i have the same problem...blank fields in the results section

**Comment by Legedric** [comment]
This seems to be an IE specific issue that should be fixed in 1.1.2
