### ISSUE TITLE
Unknow error when lauching dotnet PTMagic.dll

### ISSUE THREAD

**Issue by mikdesign02** [Legedric/ptmagic#196]
Please help when lauching dotnet PTMagic.dll, there is this error message and my monitor 
![ptm2](https://user-images.githubusercontent.com/34874555/36637149-6768924a-19cd-11e8-8b6d-e6758939b9b7.JPG)
dont work
![ptm](https://user-images.githubusercontent.com/34874555/36637079-3705e55e-19cc-11e8-8ff0-3c0133babd52.JPG)

![Uploading ptm2.JPG…]()

**Comment by Legedric** [comment]
Please ZIP and upload the file "_data/LastRuntimeSUmmary.json" here. (Do not copy & paste its content, just upload)

**Comment by Legedric** [comment]
Closing this as the last feedback was days ago.
