### ISSUE TITLE
Panic sell a pump/ dump

### ISSUE THREAD

**Issue by goferit** [Legedric/ptmagic#197]
Have the option for PTM to trigger a single market panic sell where a P&D is detected.

**Comment by Legedric** [comment]
So what exactly do you mean by this?
Just setting the variable BTC-XXX_panic_sell_enabled = true? Because that's already possible using PT Magic with a Single Market Setting.

**Comment by goferit** [comment]
So are you saying that ANY of the settings in the 3 PT *.properties files can be updated by PTM, by following the format in the default PTM settings, for settings like "ALL_sell_only_mode" and the like?

**Comment by Legedric** [comment]
Yes, exactly. PTM doesn't use special variables, it just takes whatever you give to it and it will write it to Profit Trailer's files.
