### ISSUE TITLE
Monitor 'Settings' disappear after saved changes.

### ISSUE THREAD

**Issue by goferit** [Legedric/ptmagic#199]
Steps to reproduce:

Launch Monitor in Chrome on Windows Server 2012
Click Settings in the left menu column
Select General
Toggle Password Protection to Off
Click Save
Settings no longer in the left menu column

**Comment by Legedric** [comment]
That's not a bug, that's intended. Settings menu is only available when your monitor is password protected.

**Comment by goferit** [comment]
Got it, makes sense. Funny way to discover it! :)
