### ISSUE TITLE
Copy your PAIRS.PROPERTIES, DCA.PROPERTIES and INDICATORS.PROPERTIES from your Profit Trailer

### ISSUE THREAD

**Issue by Garyl2k** [Legedric/ptmagic#20]
Hi

I have done this, does that mean PTMagic will use these settings as default? Because I have changed these in the location in the guide and the monitor showed that it had set it self to "Default settings" but Profit trailer still using its own settings.

Though I can see that PT Magic has updated the Profit Trailer settings as it has updated with it's own messages on what it is doing.

Also, one more question, can we use PT Magic base settings or is it recommened we change these?

Many thanks
Gary

**Comment by Legedric** [comment]
Hi Gary,

if you do just the standard setup described in the wiki, PT Magic will use the settings located in _presets/Default as default settings for your PT.

For the start you may use the base settings, but with evyrething else, we do not say that our settings are "perfect" of course, this is just the basic set and you may tweak it yourself as you see how your bot is performaning and adopt it to your needs.
