### ISSUE TITLE
Monitor only showing white screen with text

### ISSUE THREAD

**Issue by cryptojeepguy** [Legedric/ptmagic#200]
I am only getting a text based UI when I log into the monitor, no graphs or anything, just a white page with black text.

**Comment by Kcompagna13** [comment]
reporting the same issues on windows vps, set up and got mgic working but moniter is giving me basic text options and not full scae and color detail as i had grown to expect beautifull work other than you cant please everyone i know.  thanks for the efforts!

**Comment by Legedric** [comment]
Which version of PT Magic are you running?
Please make sure your IE(if you are using it) is not running in protected mode.

**Comment by cryptojeepguy** [comment]
I am running Version 1.1.1 and I am using Google Chrome to view it.

**Comment by cryptojeepguy** [comment]
And I am using a Windows based VPS.

**Comment by Kcompagna13** [comment]
same here using windows, attempted using chrome, IE, and fox, all coming back with the same response... running 1.1.1 all on 1&1 vps. everything but moniter is working correctly. moniter just doesnt seem to be loading https://cdn.discordapp.com/attachments/415258465271939072/417337308396912650/image.jpg

**Comment by Legedric** [comment]
Please post a screenshot of your Monitor command line window.

**Comment by Kcompagna13** [comment]
Here is the screen shot

**Comment by Kcompagna13** [comment]
![image](https://user-images.githubusercontent.com/36809361/36644051-33eed472-1a1a-11e8-839e-1134ca0999a2.jpg)

**Comment by Kcompagna13** [comment]
![image](https://user-images.githubusercontent.com/36809361/36644060-5d72687c-1a1a-11e8-9ec9-48c85d458e4e.jpg)

And here is what I get.

**Comment by cryptojeepguy** [comment]
Mine is the same.  Looks like that on my phone too.

**Comment by Kcompagna13** [comment]
Used three different browsers all giving me the same white screen even from my mobile device. Chrome ie and fox

**Comment by Kcompagna13** [comment]
html not coming through properly? or...

**Comment by Legedric** [comment]
The thing is, we are not able to reproduce it. We already made some attempts to fix this issue but as long as this is only affecting some users and we cannot really see it for ourselves we are very much unable to find the cause for this.

**Comment by Legedric** [comment]
Is the issue still present with version 1.2.0?

**Comment by wk4536** [comment]
![ptmagic monitor wont open](https://user-images.githubusercontent.com/36554133/36921126-29a43da2-1e31-11e8-9acf-9a4ec48273e9.JPG)

I recently downloaded 1.2.0 and have been able to launch PTMagic but for some reason can't get the monitor to work. Any tips? I have taken a screenshot of the message I get when I try to start it. Once I hit a key, it closes and nothing happens.

**Comment by Kcompagna13** [comment]
Yes that I see.

**Comment by wk4536** [comment]
Fixed it! Realized I downloaded the wrong .netfile. Wanted to give an update.

**Comment by cryptojeepguy** [comment]
which .netfile did you download?

**Comment by wk4536** [comment]
@cryptojeepguy I used Microsoft .NET Core 2.0.5 - Windows Server Hosting.
