### ISSUE TITLE
Buying still with protection.

### ISSUE THREAD

**Issue by NACrushers** [Legedric/ptmagic#201]
# WINGSBTC - Current active setting: 'PumpNDumpProtection'
# Matching triggers:
# Exchange12h -  - Min: 10.00%% - TrendChange (Relative) = 26.23%
# Exchange24h -  - Min: 10.00%% - TrendChange (Relative) = 48.78%
WINGSBTC_DCA_enabled = false
WINGSBTC_sell_only_mode = true
WINGSBTC_sell_value = 0.623
WINGSBTC_trailing_profit = 0.1341

                                               Date/Pair/24hr%
     Profit Trailer Bought @ 25.02.2018 02:16 (0D) | WINGSBTC | 54.30%

2018/02/25 02:15:45.218 DEBUG - Checking market trends for market 'WINGSBTC' (94/110)... 
2018/02/25 02:15:45.218 DEBUG - Checking triggers for 'PumpNDumpProtection'... 
2018/02/25 02:15:45.218 DEBUG - Trigger 'Exchange15Min' not triggered. TrendChange (Relative) = -2.25% 
2018/02/25 02:15:45.234 DEBUG - Trigger 'Exchange1h' not triggered. TrendChange (Relative) = -5.80% 
2018/02/25 02:15:45.234 DEBUG - Trigger 'Exchange4h' not triggered. TrendChange (Relative) = -4.90% 
2018/02/25 02:15:45.234 DEBUG - Trigger 'Exchange12h' triggered! TrendChange (Relative) = 27.58% 
2018/02/25 02:15:45.234 DEBUG - Trigger 'Exchange24h' triggered! TrendChange (Relative) = 48.24% 

2018/02/25 02:15:45.548 DEBUG - Building single market settings 'PumpNDumpProtection' for 'WINGSBTC'... 
2018/02/25 02:15:45.548 DEBUG - Built single market settings 'PumpNDumpProtection' for 'WINGSBTC'. 

But Profit Trailer still bought the pair just curious as to why?

**Comment by Legedric** [comment]
In what section does this pair appear in your PT monitor? Pairs? DCA?

**Comment by NACrushers** [comment]
It was in Pairs

**Comment by Legedric** [comment]
Then I don't know. PT Magic seems to have worked as intended as the isngle setting was written. No idea what cause PT to buy it anyway.
