### ISSUE TITLE
An error occurred while processing your request.

### ISSUE THREAD

**Issue by edwardleehl7097** [Legedric/ptmagic#203]
i'm running in windows 10, if restart PTmagic Monitoring it's back to normal. However after few hours i refresh the browser and the session is end, after re-login the error prompt up.

**Comment by Legedric** [comment]
Please post a screenshot of the whole windows showing the error message.

**Comment by smoochy** [comment]
I just had the same.

Windows Server 2016 VPS
PTM 1.1.1
PT 1.2.6.20

I noticed in the log file of PT, that it had an issue reaching api.binance.com. The same time, PTM acted up (was running fine before for like 2h) and stopped working.

![ptm](https://user-images.githubusercontent.com/34371932/36759777-ced6afaa-1c18-11e8-9d18-6122bcc5d75f.jpg)

I closed PTM and restarted it:

![ptm2](https://user-images.githubusercontent.com/34371932/36759844-0d0aadd0-1c19-11e8-8bd5-660a4aaca9d8.jpg)


It seems to be related to issues with binance.


Any chance you can quickly update PTM to just try again to connect a few seconds later and not shut down the whole program?

**Comment by Legedric** [comment]
With the next release PT Magic will not stop its process when the exchange is not available.

**Comment by smoochy** [comment]
Thank you :)
