### ISSUE TITLE
Pump and dump Protection

### ISSUE THREAD

**Issue by Spyelite** [Legedric/ptmagic#204]
Hi guys,
I tried to figure out a way to ban the coins that have "SingleMarket" settings active aka pump&dump protection,it didn't work. I added the command "ALL_trading enabled = false" but it doesn't write it,maybe i did something wrong but i doubt.
It would be helpfull if we could just disable them as a trading pair with the command "XYZBTC_trading_enabled = false" so that the bot doesn't even look at them instead of buying them and PT Magic making a few adjustments to sell if faster than the others.

Thank you for your awsome work !

**Comment by Legedric** [comment]
What do you mean by "it didn't write it"?
It should if you setup the settings for it correctly.

**Comment by Spyelite** [comment]
![trading_enabled false](https://user-images.githubusercontent.com/36816263/36642216-dd97a682-1a44-11e8-95cc-3c34f5a08ab9.jpg)
If i did a mistake in the coding i apologise in advance :(

**Comment by Legedric** [comment]
Can you please check you pairs.properties directly and not via the monitor and see if that changed?

**Comment by Legedric** [comment]
Just tested this and for me it is working fine:
![image](https://user-images.githubusercontent.com/8308141/36642608-350b34e0-1a42-11e8-99f4-c955ca72accb.png)

**Comment by Spyelite** [comment]
I checked it did not inject the code at all.Could it be because i am on Binance and the name of the pair is slightly different?

**Comment by Legedric** [comment]
No, this should not make any difference.

Please try stopping and restarting PT Magic, it may be that PT Magic did not recognize your change of the analyzer on the fly.

**Comment by Spyelite** [comment]
I restarted everything and my VPS completely now it works...well lol that was hella weird !
