### ISSUE TITLE
BTC from/to outside source?

### ISSUE THREAD

**Issue by Tjosy** [Legedric/ptmagic#206]
I haven't been able to find a graceful way to account for new BTC (etc.) coming into Binance from an external source. To date, I've just restarted everything.

Scenerio A: Sally adds $250 worth of BTC into Binance every paycheck. 
Scenerio B: John moves 200 Lumens off Binance to his Ledger Nano for longterm cold storage.

How would these affect PT Magics reporting?

**Comment by Legedric** [comment]
At the moment there is no such way in PT magic. But we may add something like manual transactions to it in a future update.
