### ISSUE TITLE
Petition: https://t.me/PTMagic To de wiki (Spanish Community of PTMAGIC)

### ISSUE THREAD

**Issue by juato4** [Legedric/ptmagic#207]
We was started a Spanish community of PTMAGIC on telegram. 

https://t.me/PTMagic

Can it be added to the wiki to help us each other?

**Comment by Legedric** [comment]
Added this to our main wiki page:
https://github.com/Legedric/ptmagic/wiki

**Comment by juato4** [comment]
Thank you very much!
