### ISSUE TITLE
Available settings in Pairs and DCA properties

### ISSUE THREAD

**Issue by rw1773** [Legedric/ptmagic#208]
This is more of a question.  What settings can be set in the PairsProperties and DCAProperties sections of the settings.analyzer.json file?  I want to customize the the following settings based on market condition:

        "PairsProperties": {
          "ALL_min_buy_volume": 500,
          "ALL_sell_only_mode": false,
          "ALL_max_trading_pairs": 4,
          "ALL_max_cost": .0025,
          "ALL_buy_value": -0.7,
          "ALL_trailing_buy": 0.2,
          "ALL_sell_value": 1.1,
          "ALL_trailing_profit": 0.2,
          "ALL_DCA_enabled": -2.5
        },
        "DCAProperties": {
          "sell_value": 0.9,
          "trailing_profit": 0.25,
          "trailing_buy": 0.09,
          "max_buy_times": 3,
          "buy_trigger_1": -2.5,
          "buy_trigger_2": -4.5,
          "buy_trigger_3": -7.5,
        },

Is this possible? because the settings aren't taking.

Great product by the way!

**Comment by Legedric** [comment]
The answer is: Yes, PT Magic takes all properties that Profit Trailer has. So everything you give it in the settings should work for global settings.

What makes you think it doesn't work?

**Comment by jodee8** [comment]
@rw1773 I can see two faults with your code that will cause the json format to fail and an error code to be returned. The first fault is that you forgot to comment the non-numerical text in line 3. and the second fault is that you have included a comma on line 19 when it is the last entry in that blocks list. Try this instead....

    "PairsProperties": {
      "ALL_min_buy_volume": 500,
      "ALL_sell_only_mode": "false",
      "ALL_max_trading_pairs": 4,
      "ALL_max_cost": .0025,
      "ALL_buy_value": -0.7,
      "ALL_trailing_buy": 0.2,
      "ALL_sell_value": 1.1,
      "ALL_trailing_profit": 0.2,
      "ALL_DCA_enabled": -2.5
    },
    "DCAProperties": {
      "sell_value": 0.9,
      "trailing_profit": 0.25,
      "trailing_buy": 0.09,
      "max_buy_times": 3,
      "buy_trigger_1": -2.5,
      "buy_trigger_2": -4.5,
      "buy_trigger_3": -7.5
    },

**Comment by Legedric** [comment]
Some corrections on that:
- Line 3 may be "false" or false (without quotes). JSOn can do both and so can PT Magic
- Line 5 may cause trouble as .0025 is usually not a valid JSON float number, use 0.0025 instead.

**Comment by jodee8** [comment]
@Legedric very good spotting! :)

**Comment by rw1773** [comment]
Thank you both.  I will try again.  Key item I wasn't seeing change was the "ALL_buy_value": -0.7,  No matter what I changed it to, it doesn't seem to change from the default setting.  I will try the updates provided

**Comment by rw1773** [comment]
Thank you, I was able to get the settings to take.  It was a mixture of syntax and stupidity.  Thanks for this great tool!
