### ISSUE TITLE
1.1.1 Unreliable

### ISSUE THREAD

**Issue by wrightc23** [Legedric/ptmagic#209]
Latest release is no where near as reliable for me. It's routinely stopping working and the red error message 'failed to update monitor' is appearing on the dashboard (or words to that effect). Looking at the log it's stopped functioning from 20:23 yesterday evening until I restarted it at 5am this morning.

Great product but going to turn it off for now as it can't be trusted.

**Comment by Legedric** [comment]
Please post a screenshot of the whole window including the error message.

The exists no error message "failed to update monitor" in PT Magic...

**Comment by wrightc23** [comment]
Will do, I'll attach an image when it happens. I suspect the issue might be with the exchange rather than PT Magic. I've set intervals to 5 & 15 minutes. I'm not sure Binance is happy with that?
