### ISSUE TITLE
1.1.1 Market trend not found

### ISSUE THREAD

**Issue by gabzlora** [Legedric/ptmagic#210]
![screen shot 2018-02-26 at 1 49 39 am](https://user-images.githubusercontent.com/4853895/36655169-628aa16c-1a97-11e8-8941-13ce14f0c1be.png)

Issue started showing since yesterday

**Comment by Legedric** [comment]
Please follow these steps:
- Stop PT Magic
- Delete the folder "Exchange" in "_data" in PT Magic
- Start PT Magic (It will take up to 15 minutes as it will rebuild the data)

**Comment by gabzlora** [comment]
This has solved the issue. Thanks for the prompt response.
