### ISSUE TITLE
monitor failing at ConsolePal.ReadKey

### ISSUE THREAD

**Issue by Thermionix** [Legedric/ptmagic#211]
I'm running ptmagic in a docker container, I've written a little script to launch both processes however the monitor process immediately fails, does the process 'need' to read keystrokes?

````
#!/bin/bash
cd /opt/ptmagic/
dotnet Monitor/Monitor.dll &
dotnet PTMagic.dll
````

````
Unhandled Exception: System.InvalidOperationException: Cannot read keys when either application does not have a console or when console input has been redirected. Try Console.Read.
   at System.ConsolePal.ReadKey(Boolean intercept)
   at Monitor.Program.Main(String[] args) in D:\Tools\PTMagic\Monitor\Program.cs:line 56
````

**Comment by Legedric** [comment]
As far as I know you cannot run both in the same console as both are permanent running apps. So even if you do not get this error, it will start the monitor and keep the webserver alive, the 2nd dotnet command will not be executed I believe.

**Comment by Thermionix** [comment]
The ampersand backgrounds the process in bash.

**Comment by Legedric** [comment]
Yes but do they stay running with the ability to receive input?

**Comment by Thermionix** [comment]
subshell to the rescue
````
#!/bin/bash
cd /opt/ptmagic/
(dotnet Monitor/Monitor.dll) &
dotnet PTMagic.dll
````
