### ISSUE TITLE
PT Magic was stuck, restarted and have these warnings

### ISSUE THREAD

**Issue by nstefi** [Legedric/ptmagic#214]
I checked my PT Magic this morning at 11AM and it was stuck since last night at 4:51AM. It looks like it was in the middle of writing some settings. Here is a screenshot when I restarted:
![image](https://user-images.githubusercontent.com/6478474/36682710-d519ca76-1ae9-11e8-8833-4fbe040dfb89.png)
Now since that time I get some warnings at every update:
![image](https://user-images.githubusercontent.com/6478474/36682826-1bbdbf0a-1aea-11e8-9767-0c33d01ffe95.png)
What should I do to make those warnings disappear?

Also, is there a discord channel where I should ask these type of questions instead?

Thanks.

**Comment by Legedric** [comment]
NCASH just got release on Binance so it needs time to build up a history on the exchange. Nothing to worry about.
