### ISSUE TITLE
Graphs not being generated

### ISSUE THREAD

**Issue by sorentorp** [Legedric/ptmagic#215]
Hi PTM.

First of - what a great addon you have made! Love it.

I have an issue, the graphs are not being generated, and I dont know what the problem is. The date is 1970 and it only shows one point of data - the current.

Is there any logs etc I can give you, to resolve this issue?
<img width="1133" alt="screen shot 2018-02-25 at 10 01 43" src="https://user-images.githubusercontent.com/4117997/36695970-1c8f3f90-1b43-11e8-9c9c-5e58ba00d076.png">
<img width="1165" alt="screen shot 2018-02-25 at 09 46 58" src="https://user-images.githubusercontent.com/4117997/36695971-1cabdd4e-1b43-11e8-96c4-062ca1cec06a.png">

**Comment by nsater** [comment]
Are you running the current version, 1.1.1?

**Comment by Legedric** [comment]
Can you please ZIP and upload your ProfitTrailerData.json file here? This way I may investigate what's the problem here with your sales data.

**Comment by sorentorp** [comment]
@Legedric Where do I find that file? Can't seem to find it...

**Comment by sorentorp** [comment]
@nsater yes

**Comment by Legedric** [comment]
You find that in your Profit Trailer folder.

**Comment by sorentorp** [comment]
ahhh, found it.
[ProfitTrailerData.json.zip](https://github.com/Legedric/ptmagic/files/1765986/ProfitTrailerData.json.zip)

**Comment by Legedric** [comment]
That's very strange, when I use your data it is showing the graphs and I did not change anything.

When you go to the SalesAnalyzer page, please right click anywhere on that page and select "Show Source".
In the source window that opens up please scroll to the bottom and look for a block that looks like this and post a screenshot of that here, thanks!
![image](https://user-images.githubusercontent.com/8308141/36777109-7c9d4014-1c68-11e8-8110-8497f6150d31.png)

**Comment by Legedric** [comment]
Forget it, I found the issue and it will be fixed in the next release.

**Comment by sorentorp** [comment]
Sorry I didn't get back to you in time. 

Glad I can contribute to making PTMagic even better and solid! :-)
