### ISSUE TITLE
Trigger logic with negative values

### ISSUE THREAD

**Issue by goferit** [Legedric/ptmagic#216]
Using TankingDown as an example (a downtrending market).

Putting in a value like so -

`"ALL_buy_value_OFFSETPERCENT": -10`

makes the Buy Value actually increase, meaning if it were -1.0, it would change to -0.9 (which is the opposite direction intended).

This is probably because two negatives multiplied make a positive?

Could be fixed with a // comment or "if negative integer, do this" statement? (Not a coder.)

**Comment by Legedric** [comment]
Thanks, this will be fixed in the next release.
