### ISSUE TITLE
 dotnet PTMagic.dll error 

### ISSUE THREAD

**Issue by mikdesign02** [Legedric/ptmagic#217]
Hi,
Can you help me my PTMagic show and error message on lauch. 
![ptm](https://user-images.githubusercontent.com/34874555/36697080-ed91a174-1b3d-11e8-926f-964545f23e27.JPG)

**Comment by Legedric** [comment]
Please try to reset your data and see if the error is still there:
https://github.com/Legedric/ptmagic/wiki/Reset-PT-Magic-Exchange-Data

**Comment by mikdesign02** [comment]
Thanks a lot. It's ok now.

Envoyé depuis Yahoo Mail pour Android 
 
  Le mar., févr. 27, 2018 à 10:34, Legedric<notifications@github.com> a écrit :   
Please try to reset your data and see if the error is still there:
https://github.com/Legedric/ptmagic/wiki/Reset-PT-Magic-Exchange-Data
