### ISSUE TITLE
What does this error mean?

### ISSUE THREAD

**Issue by nstefi** [Legedric/ptmagic#218]
I just checked my PT Magic and found this error:
![image](https://user-images.githubusercontent.com/6478474/36698699-8592294c-1b18-11e8-9cf0-f980712c7b45.png)
What does this mean?
Also it shows some paths like D:\Tools\PTMagic\BusinessRoles\...
I don't know where that comes from, I don't even have a D drive, PT Magic runs on C drive, and I don't have any Tools or BusinessRoles folder.
Thanks.

**Comment by Legedric** [comment]
Ignore the D: Drive things, that's irrelevant. The error means that PT Magic is currently unable to reach out to Bittrex either because their servers have problems or your connection does.

**Comment by nstefi** [comment]
I checked again today morning and it's stuck here again. Does Bittrex have any problems? I don't think is my Internet connection, I never have any problems with that::
![image](https://user-images.githubusercontent.com/6478474/36731006-60fe4b4a-1b97-11e8-8f66-b6f823878ac5.png)

**Comment by Legedric** [comment]
Nope, getting stuck on this line is a known issue.  We weren't able to track this one down so far as it occurs only in very rare situations.

Stopping PTM and starting it again did work for everyone so far.

**Comment by nstefi** [comment]
OK, just saying that I checked back again on both my Binance and Bittrex bots and both were stuck again.
I am travelling and I thought I could leave them on, but it seems like every day they get stuck. It's hard for me to connect back every day.
Here are some screenshots:
From Binance:
![image](https://user-images.githubusercontent.com/6478474/36882850-48cece6e-1da4-11e8-88b6-e65828b7b926.png)
From Bittrex:
![image](https://user-images.githubusercontent.com/6478474/36882873-5c0b6aa0-1da4-11e8-9195-52a1f0b225f6.png)

Thanks.

**Comment by Legedric** [comment]
Version 1.2.0 got released just yesterday to fix both of these errors.
