### ISSUE TITLE
Enable Currency Selection for CMC

### ISSUE THREAD

**Issue by goferit** [Legedric/ptmagic#219]
Assuming the attached doesn't work, because it's not there by default, and do not see an indication in the logs. Assuming CMC is USD fiat by default, based on major difference between CMC and Exchange trends.

Would be useful if the attached worked, or even offered more optionality; for example, all 6 pricing currencies available on CMC.

![image](https://user-images.githubusercontent.com/8900109/36699548-fc45fcd8-1b1a-11e8-80e6-a674f8ea8fbf.png)

**Comment by Legedric** [comment]
Currently CMC is only being used to observe the USD trend of selected markets. If you want to have it tied to your main market, use the Exchange trend instead.

**Comment by goferit** [comment]
Is it prohibitive to make the other CMC trends available?

Here is an example of the value in doing so, when reviewing 3 randomly selected Top 10 markets. Please note this was done quickly by hand and I do not know whether this much variance between CMC aggregated data and Binance exchange data exists. If it does, the ability to choose the CMC base currency has real worth, as it is a better representation of the true market and less susceptible to exchange-specific anomalies.
![image](https://user-images.githubusercontent.com/8900109/36822612-f3a70b6e-1cc6-11e8-868a-b43631de5793.png)

**Comment by goferit** [comment]
@Legedric What do you think?

**Comment by Legedric** [comment]
@goferit I did not have enough time to think about this.

**Comment by goferit** [comment]
Great!
