### ISSUE TITLE
Just Tracking

### ISSUE THREAD

**Issue by AudiInvestor** [Legedric/ptmagic#22]
Hi man,
There's no real issue. I use feeder and want to use this program for profit tracking as I love how it looks. How would I make it do this (i don't want it to trade or change any settings)? My trade history is on 99999

**Comment by Legedric** [comment]
You could run the PT Magic bot in TestMode = true, so it won't write or change any settings and just use the monitor. The PT Magic bot running is still required as it writes a summary that the monitor is reading from.
