### ISSUE TITLE
Allow blacklisting of pairs

### ISSUE THREAD

**Issue by stevenshizzleh** [Legedric/ptmagic#221]
I have been working on a method of using settings.analyzer.json to determine when a situation is favorable for trading as a single market setting. Right now, most of the single market settings are used to mitigate unfavorable market circumstances.

What I wanted to do was:
Condition 1: "If this AND this AND this THEN ALL_enable_trading = true"
Condtion 2: "If this AND this THEN ALL_enable_trading = true"

In the PT settings, ALL_enable_trading would be false, the above settings would enable trading on a pair-by-pair basis. There was only one issue: If BNBBTC pair in Binance met the requirement, it would be enabled. Because BNBBTC_enable_trading = true would come AFTER any settings I have, BNB trading will be enabled if it meets the above conditions. If PTM allowed blacklisting, you could put the disabled pairs at the very end of what is appended to PAIRS.properties, thus allowing me to employ a strategy to enable favorable single markets, instead of disabling them.

**Comment by goferit** [comment]
Agreed but for a different reason relative to BNB: commonly a balance is kept with trading disabled in order to reduce dust and fees. I have tight pump/ dump settings and BNB had a good day and now has single market settings applied to it.

**Comment by HojouFotytu** [comment]
I'm doing the same thing.  Instead of disabling trading, enable som for that pair.  that will ensure it isn't purchased, and if was prior to the change toward unfavorable conditions, it can still be sold.  that will also solve your BNB issue.

**Comment by stevenshizzleh** [comment]
Legedric, upon further reflection, cocnur with HojouFotytu. I'm able to get along without this. It just took a bit of thought. Unless you see any reason otherwise, recommend closing this ticket so you can focus on more important things.

**Comment by Legedric** [comment]
It is not a big deal to implement so no problem :)
