### ISSUE TITLE
Dca not turning off

### ISSUE THREAD

**Issue by juato4** [Legedric/ptmagic#222]
//If a pair has been decreasing in value for the last 15 minutes, then lower trailing profit and sell value to avoid DCA.
        "SettingName": "Descending Value Sell Assist",
        "TriggerConnection": "AND",
        "Triggers": [
          {
            "MarketTrendName": "Exchange15m",
            "MarketTrendRelation": "Absolute", // The relation of the single market trend. Relative = Single market trend compared relative to the market trend / Absolute = Single market trend viewed on its own
            "MaxChange": -0.25,
            "MinChange": -2.99
          }
        ],
        "PairsProperties": {
          "ALL_trailing_profit_OFFSETPERCENT": -33,
		  "ALL_DCA_enabled": false,
          "ALL_sell_value_OFFSETPERCENT": -33
        }

—————————

The condición is ok, but is not turning off DCA

**Comment by Legedric** [comment]
So what does it write to your pairs.properties then for that market?
