### ISSUE TITLE
indicators.properties and DCA info not changing when markets change

### ISSUE THREAD

**Issue by Othon3** [Legedric/ptmagic#223]
I have notice it right now. When the market changed from Default do Boring, the info on the files on PT trading directory did not change. 
I am not using multiple files, because I think its much more work, than to edit all in the analyser settings.
 The pairs.properties changed to BORING, but, indicators.properties and  DCA remained on DEFAULT

**Comment by Othon3** [comment]
Running 1.1.1 PTMAgic and 
P T Ver:  1.2.6.20

**Comment by Legedric** [comment]
So you made your own settings? Or where is that "Boring" coming from?

**Comment by Othon3** [comment]
Yes. I just changed the names. Hope you don´t get upset... ;)  
 But since I looked at the PT backup files, I noticed that the settings actually have changed, but they did it so fast, that I could not keep it up. I set the FloodProtectionMinutes for 10, but since PTMAgic runs the market trends uptade every Interval of 3 Minutes, I thought this could be a bug.

Since the changes on the pairs file happened so fast, I think there might be one time or the other that PT actuallys buys a coin that shloud be in SOM mode, due to the latency between the PTMagic runtime and the uptade information on Pair.properties. Have you experieced that?

Thanks Legedric. I am having a journey learning how to teach my bot how to behave.

**Comment by Othon3** [comment]
I noticed that every 3 minutes PTMagic rewrites the Pairs.properties  They all go into the _backups folder inside PT trading directory.

Why would PTMagic change the file every 3 minutos. Wasn´t it supposed to only rewrite the file if there were any markets changes (general or pair specific ?)

I think this routine of writing adn rewriting again could be causing PT to misunderstood some coins informations about being in SOM mode.
