### ISSUE TITLE
GlobalSettings OFFSETPERCENT  Miscalculations

### ISSUE THREAD

**Issue by HojouFotytu** [Legedric/ptmagic#225]
**in _presets\Default\PAIRS.properties:**
ALL_max_cost_percentage = .4

**in settings.analyzer.json**
"ALL_max_cost_percentage_OFFSETPERCENT": -25,

**resulting Trading\PAIRS.properties:**
PTMagic changed line for setting 'BearSighted' on 2/27/2018 22:04
ALL_max_cost_percentage = 0.1125

**and then after PTmagic changed the settings to "Tanking Down" (OFFSETPERCENT -5o%)**
ALL_max_cost_percentage = 0.02109375

Looking at some of the other settings, it seems like all the offsetpct values in globals settings are being miscalculated.  I didn't notice until after what could've been a few setting changes, so i'm not sure if it was a single miscalculation or a compounded mistake.

**Comment by HojouFotytu** [comment]
So just saw this on the wiki...

"AlwaysLoadDefaultBeforeSwitch
When this is activated, PT Magic will always reload "Default" settings whenever it switches to another setting. This may be helpful if you are mostly using offset values, to ensure that the offset is taking the default value and not an already adjusted value."

So this must be turned on, or it calculates from the current pairs file, rather than the default?

**Comment by Legedric** [comment]
Thanks Hojou. Yes, if you do not have that set to true (which is the default setting) then it will not apply the default settings before it applies the rest.
