### ISSUE TITLE
Unable to get main market price...

### ISSUE THREAD

**Issue by ACETyr** [Legedric/ptmagic#226]
2018/02/27 15:14:29.257 INFO - Binance - Market data received for 271 currencies
2018/02/27 15:14:29.257 INFO - Binance - Getting main market price...
2018/02/27 15:14:30.368 FATAL - The remote server returned an error: (400) Bad Request. System.Net.WebException The remote server returned an error: (400) Bad Request.    at System.Net.HttpWebRequest.GetResponse()
   at BusinessRules.MarketAnalyzer.BaseAnalyzer.GetSimpleJsonObjectFromURL(String url, LogHelper log, Boolean onlyLogDebug) in D:\Tools\PTMagic\BusinessRules\MarketAnalyzer\BaseAnalyzer.cs:line 45
2018/02/27 15:14:30.425 INFO - Binance - Recreating market data for 271 markets over 24 hours. This may take a while... 
2018/02/27 15:14:31.574 FATAL - The remote server returned an error: (400) Bad Request. System.Net.WebException The remote server returned an error: (400) Bad Request.    at System.Net.HttpWebRequest.GetResponse()
   at BusinessRules.MarketAnalyzer.BaseAnalyzer.GetSimpleJsonArrayFromURL(String url, LogHelper log) in D:\Tools\PTMagic\BusinessRules\MarketAnalyzer\BaseAnalyzer.cs:line 97
2018/02/27 15:14:31.586 FATAL - Object reference not set to an instance of an object. System.NullReferenceException Object reference not set to an instance of an object.    at BusinessRules.MarketAnalyzer.Binance.GetMarketTicks(String marketName, SystemConfiguration systemConfiguration, LogHelper log) in D:\Tools\PTMagic\BusinessRules\MarketAnalyzer\Binance.cs:line 108

**Comment by Legedric** [comment]
Please try again every couple of minutes. Seems like Binance is rejecting your API call for whatever reason.

**Comment by ACETyr** [comment]
Been trying for hours now. Issue persists. I surmise it is not an IP ban issue as PT runs error free. To rule out BAN issue I did even switch IP Address to no avail.

Where does this Path come from? I do not have it set anywhere and don't even have a D: drive on my VPS. Hardcoded?

FATAL - Object reference not set to an instance of an object. System.NullReferenceException Object reference not set to an instance of an object. at BusinessRules.MarketAnalyzer.Binance.GetMarketTicks(String marketName, SystemConfiguration systemConfiguration, LogHelper log) in **D:\Tools\PTMagic\BusinessRules\MarketAnalyzer\Binance.cs:line 108**

**Comment by Legedric** [comment]
The path is irrelevant as it just show information for us developers.

However, the error you get in your second post is a whole different one then the first one...

**Comment by ACETyr** [comment]
Excerpt from first one, actually it looks quite the same as posted the second time.

2018/02/27 15:14:31.586 **FATAL - Object reference not set to an instance of an object. System.NullReferenceException Object reference not set to an instance of an object. at BusinessRules.MarketAnalyzer.Binance.GetMarketTicks(String marketName, SystemConfiguration systemConfiguration, LogHelper log) in D:\Tools\PTMagic\BusinessRules\MarketAnalyzer\Binance.cs:line 108**

I can post you the errors again, but they read the same. Took down PT-Magic as situation has not changed over the day. Any further ideas for troubleshooting the issue?

**Comment by ACETyr** [comment]
I have reverted to 1.0.0 -> no Errors. To single out a coincidence I have stopped PT-Magic, made a copy of the folder and upgraded the copy to latest version 1.1.1
I started 1.1.1 and the error is there again. I stopped 1.1.1 and started 1.0.0 -> no Error.
I retries several times. The error occurs reproducably in 1.1.1 and reproducably 1.0.0 runs without error.

**Comment by ACETyr** [comment]
Redownloaded 1.1.1 and did a fresh install. Seems to run errorless. I will keep an eye on it. Sorry to have bothered you. I'll close for now and reopen if necessary. Thanks for your work and efforts!
