### ISSUE TITLE
Won't be able to get market data for more than 72hours

### ISSUE THREAD

**Issue by cx040156** [Legedric/ptmagic#227]
I added this in the market trend settings:
{
          "Name": "Exchange72h",
          "Platform": "Exchange",
          "MaxMarkets": 50,
          "TrendMinutes": 4320,
          "TrendCurrency": "Market"
    }
But according to the numbers it has shown in PT Magic monitor and the P&D protection I implemented, they have the same numbers for the 48h settings I've set up(2880minutes).
Tried changing that to 96h(5760minutes) but still shows the number of 48h.

![20180226221508](https://user-images.githubusercontent.com/10699266/36742864-bd52c042-1c23-11e8-8338-7652c4f24cca.png)
![20180228011155](https://user-images.githubusercontent.com/10699266/36743114-686b7e38-1c24-11e8-8a99-667a1fde2f92.png)

**Comment by Legedric** [comment]
Well, by default PTM only stores data for 24h (see the setting StoreDataMaxHours).
So if you want to have a trend that's larger than 24h you also have to store the data for the appropriate timeframe.
