### ISSUE TITLE
Update link to Linux installations

### ISSUE THREAD

**Issue by enoch85** [Legedric/ptmagic#228]
The link in the wiki is wrong and it won't install the needed packages. This link is MUCH better:
https://docs.microsoft.com/en-us/dotnet/core/linux-prerequisites?tabs=netcore2x

Seen here: https://github.com/Legedric/ptmagic/wiki/Setup-PT-Magic-on-Linux

**Comment by rbkuhn** [comment]
Thanks, that really helped me out.

**Comment by Legedric** [comment]
Thanks, I changed the link in our wiki.
