### ISSUE TITLE
[Enhancement LINUX] Script to update if the file is newer

### ISSUE THREAD

**Issue by enoch85** [Legedric/ptmagic#229]
I just made a script that you could automate if you just want to change in ProfitTrailer GUI.

The script checks if the file in PTmagic is older than in ProfitTrailer and if yes, then copies the changes to PTmagic.

You could set it as a cronjob in Linux to automate the process if you want.

**WARNING**
For those coming here and think they can copy paste this script straight off, **DON'T DO IT!** Please change the PATH to your files before.

```
#!/bin/bash

ptmversion=1.1.1
ptmagicpath="/var/opt/pt_magic/$ptmversion/PTMagic"
profittrailerpath="/var/opt/pt"

update_settings() {
if [[ "$ptmagicpath/_presets/Default/$1" -ot "$profittrailerpath/trading/$1" ]]
then
    cat "$profittrailerpath/trading/$1" > "$ptmagicpath/_presets/Default/$1"
fi
}

update_settings DCA.properties
update_settings INDICATORS.properties
update_settings PAIRS.properties

```

Ref: https://github.com/Legedric/ptmagic/wiki/Manually-updating-settings

**Comment by Tosko4** [comment]
Hi there,

Looks cool, but it then also copies all the settings PT Magic ads to the PAIRS document in PT, to the default in PT Magic. I don't really like that idea.

Is there any way to copy a file only to a certain line or that you put some kind of trigger in the files so this script knows, ok copy until that trigger?

**Comment by enoch85** [comment]
@Tosko4 The idea behind this is that if you want to make changes in ProfitTrailer you don't want to add them in the PTMagic settings manually. So instead, use this script to copy the settings so that the files are identical. That way you only need to change in one place instead of two.

Or, maybe I misunderstood how things work?

**Comment by Tosko4** [comment]
Best practises say:

In PT Magic _presets/Defaults, put the default settings (without any adjustments made to it or whatsoever). 
PT Magic will then update the files in your profit-trailer/traders folder and modify values according to your settings.

It will also add some market settings at the bottom.


When we copy back from Profit Trailer to PT - Magic, the default in PT magic is then also with the altered defaults etc and the whole market settings too.

**Comment by enoch85** [comment]
Hmm, maybe this is a bad idea then?

**Comment by Tosko4** [comment]
It's ok! But the other way around. We want to edit the one in _presets/Default and then push to profit trailer. PT magic will do it's trick and update all values etc.

This is a feature request at PT Magic, and I think @Legedric or @TwixRaider is going to implement it. Not sure though.

**Comment by aries-delossantos** [comment]
It is better if pt magic is watching the default preset so whenever there’s a change it will update the pt.

**Comment by enoch85** [comment]
@aries-delossantos So that means I onlu have to change the default settings I have in ptmagic and it will update in ptrailer as well?
