### ISSUE TITLE
DCA and INDICATORS for SingleMarketSettings

### ISSUE THREAD

**Issue by NikitaSotnikov** [Legedric/ptmagic#232]
Hello!
How i can use DCA and INDICATORS for SingleMarketSettings ?
I tried to add this code (for example):

        "SettingName": "2_Bear", 
        "TriggerConnection": "AND",
        "Triggers": [
          {
           "MarketTrendName": "Exchange12h",
           "MarketTrendRelation": "Absolute",
           "MinChange": -4,
           "MaxChange": -3
          }
        ],
        "PairsProperties": {
           "ALL_buy_value": -15,
           "ALL_buy_strategy": "LOWBB",
           "ALL_DCA_enabled": -2
        },
        "DCAProperties": {
           "buy_trigger_1" = -3.5,
           "buy_trigger_2" = -6.5
        },
        "IndicatorsProperties": {
           "BB_period" = 300,
           "BB_sma" = 20
        }

But it don't work.
I also tried add this code and also add directory with the same name (2_Bear) in PTMagic\_presets.
And add 2 files DCA.PROPERTIES and INDICATORS.PROPERTIES in this directory.

        "SettingName": "2_Bear",
        "TriggerConnection": "AND",
        "Triggers": [
          {
           "MarketTrendName": "Exchange12h",
           "MarketTrendRelation": "Absolute",
           "MinChange": -4,
           "MaxChange": -3
          }
        ],
        "PairsProperties": {
           "ALL_buy_value": -15,
           "ALL_DCA_enabled": -2
        },
        "DCAProperties": {
           "File": "DCA.PROPERTIES"
        },
        "IndicatorsProperties": {
           "File": "INDICATORS.PROPERTIES"
        }

But it also don't work :(

Best regards!

**Comment by Legedric** [comment]
Profit Trailer is currently not able to take DCA and/or indicator settings for single pairs. If PT does accept it at some point of time, PTM will support that.
