### ISSUE TITLE
[Enhancement] Top 50

### ISSUE THREAD

**Issue by frydrce** [Legedric/ptmagic#233]
Any way to pull the top 50 coins from the data you already pull and only allow trading on those set pairs if you so wish? I know certain exchanges only have certain pairs. I’m only using like 34 of the 50 in binance. Just a thought.

**Comment by Legedric** [comment]
You mean your own top 50 coins like listed with the top 20 in the Sales Analyzer?

**Comment by Legedric** [comment]
Closing as no feedback provided for some days now.

**Comment by frydrce** [comment]
Didn’t see your email. What I meant was can you make a list from cmc of the top pairs so that we can trade only those pairs?

**Comment by Legedric** [comment]
That's not possible as the CMC symbols barely match the BTC/ETH/USDT symbols on your exchange.

**Comment by frydrce** [comment]
Ok thanks.
