### ISSUE TITLE
Coins loosing SOM mode status on PT after Magic runtime

### ISSUE THREAD

**Issue by Othon3** [Legedric/ptmagic#234]
I noticed that every 3 minutes PTMagic rewrites the Pairs.properties They all go into the _backups folder inside PT trading directory.

Why would PTMagic change the file every 3 minutes?
 Wasn´t it supposed to only rewrite the file if there were any markets changes (general or pair specific ?)

I think this routine of writing and rewriting again could be causing PT  lag and loose info that some coins informations  are in SOM mode.

It just happened to me a while ago. Coin was in SOM mode for Pump and Dump Protection on PTMAgic Monitor, although after a runtime, PTMagic  took the coin of SOM and bought it, even thought it was still on SOM at PTMagic Monitor.

# PTMagic_SingleMarketSettings - Written on 2/28/2018 12:11:08 AM
# ########################################################################
# NEBLBTC - Current active setting: 'PumpnDump'
# Matching triggers:
# Exchange3h -  - Min: 9.00%% - TrendChange (Relative) = 26.63%
# Exchange6h -  - Min: 9.00%% - TrendChange (Relative) = 26.46%
# Exchange12h -  - Min: 10.00%% - TrendChange (Relative) = 24.87%
# Exchange24h -  - Min: 12.00%% - TrendChange (Relative) = 24.85%
NEBLBTC_DCA_enabled = false
NEBLBTC_min_profit = 1.02
NEBLBTC_sell_value = 1.33
NEBLBTC_trailing_profit = 0.3

and then, on the next run it wrote:  (Without the SOM : true..) ?????

# NEBLBTC - Current active setting: 'PumpnDump'
# Matching triggers:
# Exchange3h -  - Min: 9.00%% - TrendChange (Relative) = 24.93%
# Exchange6h -  - Min: 9.00%% - TrendChange (Relative) = 23.86%
# Exchange12h -  - Min: 10.00%% - TrendChange (Relative) = 23.73%
# Exchange24h -  - Min: 12.00%% - TrendChange (Relative) = 23.45%
NEBLBTC_DCA_enabled = false
NEBLBTC_min_profit = 1.02
NEBLBTC_sell_value = 1.33
NEBLBTC_trailing_profit = 0.3

**Comment by Legedric** [comment]
What does your SIngle Market setting for PumpNDump protection look like?

**Comment by Othon3** [comment]
A bit messy..

Can it conclict with the rules above.

I thought the JSON file worked like.. if it encounters a Single Market condition with all the triggers ok, it would choose that, and not go downwards on the JSON file looking for others conditions.

Inst this true.

If it inst, how can we order the different Single Market conditions, so it would choose the correct one..
I mean, PumpandDump protection and Free Fall protection are very important, but I would like to create others based on different price analysys situations. Sure they can conflict with the rules on PND and FREEFALL, but since they would be down in the code on the JSON file, I did not think it would matter much.

**Comment by Legedric** [comment]
SingleMarket settings are not yet combinable. So only the first setting that matches trigger conditions for a single market will be written.

**Comment by jbraydc** [comment]
Legedric I noticed that if a coin is in sell only mode and the trigger changes to something else directly the coin will stay on SOM. The only way I could get SOM to turn off was to have PTM change to default before switching to the next setting. But this leaves a period of time where SOM is turned off when you may not want it to be due to another trigger that is in effect. The only way around this would be to include SOM on or off in every trigger so when it switches it does it immediately.

**Comment by Legedric** [comment]
So you say that when a coin gets into SOM through PumpNDumpProtection for example and then some time later will get out of this protection it keeps SOM?

Please ZIP and upload your pairs.props here when you encounter this case so I may look into it.
