### ISSUE TITLE
Sales Analyzer inconsistent compared to ProfitTrailer sales log

### ISSUE THREAD

**Issue by aries-delossantos** [Legedric/ptmagic#235]
The sales log on PT is not the same on the PT magic

PT
![image](https://user-images.githubusercontent.com/7146454/36773878-b9886782-1c96-11e8-9042-b62bfc7858f6.png)

PT magic
![image](https://user-images.githubusercontent.com/7146454/36773908-e0ac21b4-1c96-11e8-8468-ab5b61287c74.png)

**Comment by Legedric** [comment]
Is the clock of your VPS matching the timezone you set in your Profit Trailer settings?

**Comment by aries-delossantos** [comment]
I just corrected it a while ago. Will it not correct itself now?

**Comment by Legedric** [comment]
Usually it should show the correct time immediately. What is your GMT offset set to? So I will investigate on this.

**Comment by aries-delossantos** [comment]
on PT it set to +8:00 and i corrected my vps time to Asia/Manila time zone so both are showing the same time now on PT and vps.

![image](https://user-images.githubusercontent.com/7146454/36777532-c78a4040-1ca4-11e8-872f-55fd8c723214.png)

**Comment by Legedric** [comment]
Ok thanks. Could you please ZIP and upload your ProfitTrailerData.json (found iny our PT directory) here? It contains your sales info from PT with timestamps and I need to look at what times PT has saved there for you.

**Comment by aries-delossantos** [comment]
Since I just corrected my vps timezone to where I live I no longer need the offset. So I've set the offset on PT to `00:00` and now at least the sales on both are now sync. :+1:

**Comment by aries-delossantos** [comment]
Looks like it's still not fixed. Inside the json it says Mar.1 but on Sales analyzer it goes to Feb.28 

json
![image](https://user-images.githubusercontent.com/7146454/36828113-a9707832-1d52-11e8-9e04-7b70479059de.png)

sales analyzer
![image](https://user-images.githubusercontent.com/7146454/36828124-bd52bd38-1d52-11e8-91cf-454283d9a323.png)

[ProfitTrailerData.zip](https://github.com/Legedric/ptmagic/files/1769864/ProfitTrailerData.zip)

**Comment by Legedric** [comment]
We will look into this.

**Comment by aries-delossantos** [comment]
I upgrade to `v1.2.0` and now sales log are correct. Apologies.
