### ISSUE TITLE
Monitor DashBoard not loading with more than 10 Markettrends

### ISSUE THREAD

**Issue by Othon3** [Legedric/ptmagic#236]
I built up a 14 different time frames to measure trend on the markets. 
PTMAgic is working ok, So is the Sales Analyser , MArket TRends and others tabs on in the Monitor.

but

The DASHBOARD itself is not loading. Maybe because of the numbber of different time Frames on market trends? Maybe it exceeded some maximum amount to show on Dashboard, or maybe because of  the trend Graphics. Don´t khown why.

Is there a limit of how many MarketsTrends  could be created?
Does it affect PTMAgic functionallity and speed in anyway?

![image](https://user-images.githubusercontent.com/36489267/36786980-2bb450a8-1c67-11e8-9607-2ba072c45167.png)

![capturar2](https://user-images.githubusercontent.com/36489267/36787082-9739c420-1c67-11e8-9e4c-5b62e821d5c1.PNG)

The idea behind  creating so many markets is to have a better resolution of prices from the last 12 hours, to try do code a way so PTMAgic can visualize opportunities to buy, hold or sell certain coins based on Tecnical Analysys, such as Triangles, Wedges, Botton, Flags, Cups, Tops, Bottoms and so on...

I khown, it is a lot of work, but I am willing to test it out and maybe get some unexpected results from the bot trading.

**Comment by Legedric** [comment]
This will be fixed with the next release. I only configured 9 colors for the graph lines as I never thought someone would use that many. I changed that to 20 for the next version.
