### ISSUE TITLE
Max and Min Change settings

### ISSUE THREAD

**Issue by Shanuman** [Legedric/ptmagic#237]
Hi,

I am not sure if this is the place to ask a conceptual question. So apologies in advance if it isn't. Any chance you could elaborate a little more about the max and min change values to determine market trends?

Especially in what case would you use a combination of both max and min values for one duration eg

 "MarketTrendName": "Exchange24h",
 "MaxChange": -1,
 "MinChange": -3

Thanks
Shan

**Comment by Legedric** [comment]
We will extend this part of the wiki during the next couple of days.

Regarding the above example:
The trigger will be met when the trend "Exchange24h" is ABOVE -3% and BELOW -1%. So Min and max are like the brackets for a trigger to be matched.

**Comment by Shanuman** [comment]
Thank you amte

**Comment by Shanuman** [comment]
One last question if I may. Max , min change...if it is 0...is it ignored? Or is it a value?

Thanks in advance mate

**Comment by Legedric** [comment]
0 is a value. If you want to ignore them, remove them.
