### ISSUE TITLE
Telegraph Updates

### ISSUE THREAD

**Issue by CryptoThriver** [Legedric/ptmagic#238]
HI, is there a way to tell the telegraph bot to ONLY send a notification if there was a Setting Switch from one setting to another...not just keeping it at default?

**Comment by Legedric** [comment]
What version are you using and on which OS? PTM only sends a message when it switches settings but some users report that their global settings get changed every run.

**Comment by CryptoThriver** [comment]
Windows- yes- every run it is being changed.  Therefore a notification is being sent every time.

**Comment by Legedric** [comment]
Does your pairs.properties file in your PT directory have any PT Magic related header lines? Are you using any other add ons for PT?

**Comment by CryptoThriver** [comment]
Right now, I have PT Magic on Test- I am using Feeder.  I am dialing in Magic before I turn it on.

**Comment by Legedric** [comment]
Feeder and PT Magic both write to your properties files. Running both does not work.
And when PTM is running in test mode it will not write to your files so it does not recognize that "Default" is already active.

**Comment by CryptoThriver** [comment]
oh- Great! Thanks!

So when it is running, if it is on a setting, it will only notify when it changes.

I appreciate all your efforts!

**Comment by Legedric** [comment]
Yes, exactly. It only notifies if a global setting was applied.
