### ISSUE TITLE
Change absolute URLs to relative

### ISSUE THREAD

**Issue by calebcall** [Legedric/ptmagic#239]
As mentioned in my previous issue #28 instead of moving to relative urls, you moved everything to absolute.  This makes it difficult to run behind a proxy at anything other than the root url.  Even with some workaround in nginx to make it mostly work at a something like /ptmagic, some things still redirect to whatever is running at the root url (PT in my case).

**Comment by Legedric** [comment]
The problem is that some users reported an issue that their assets were not loaded and they had just seen the pure white monitor page. As the implemented Kestrel webserver sometimes had a routing issue with relative paths we had to change this to absolute paths for now. But as this still was not a 100% fix we have to reconsider this again.

**Comment by Legedric** [comment]
We will make the root URL changeable using the settings file with the next release.

**Comment by calebcall** [comment]
This is the nginx changes I've done to make it work:
```
location /PTMagic/ {
        sub_filter '<a href="/" class="waves-effect"><i class="fa fa-dashboard fa-2x">' '<a href="./" class="waves-effect"><i class="fa fa-dashboard fa-2x">';
        sub_filter '<a href="/" class="logo">' '<a href="./" class="logo">';
        sub_filter '<link href="/assets' '<link href="/PTMagic/assets';
        sub_filter '<script src="/assets' '<script src="./assets';
        sub_filter '<link rel="shortcut icon" href="/assets' '<link rel="shortcut icon" href="./assets';
        sub_filter '<li><a href="/' '<li><a href="./';
        sub_filter '<a href="/DCACalculator"' '<a href="./DCACalculator"';
        sub_filter '<a href="/SalesAnalyzer"' '<a href="./SalesAnalyzer"';
        sub_filter '<a href="/MarketTrends"' '<a href="./MarketTrends"';
        sub_filter '<a href="/Login"' '<a href="./Login"';
        sub_filter '<a href="/Donate"' '<a href="./Donate"';
        sub_filter '"/' './';
        sub_filter_once off;
        proxy_pass http://localhost:5000/;
    }
    rewrite ^/(Login.*)$ /PTMagic/$1 last;
    rewrite ^/(SetupPassword.*)$ /PTMagic/$1 last;
}
```

Basically it does a search and replace for the absolute paths and makes them relative including the assets urls.  The only place the assests was weird was on the Login page but that's because it kept forcing it back to the absolute.  

Allowing a root url as configurable would be great!
