### ISSUE TITLE
Open Sub-Category for PTMAGIC on Discord.

### ISSUE THREAD

**Issue by novex1984** [Legedric/ptmagic#24]
Hi Developer, I hope you don't mind. PTMAGIC still very new & many of us is still very confusing on how to use it. Please allow me put a discord link to gather more people who is interested on PTMAGIC, either is installation issue & file settings.

Please join us for any discussion about PTMAGIC.

https://discord.gg/bYkmE4E

**Comment by Legedric** [comment]
Thanks. I joined the channel although I cannot say that I will have time to hang around in there very much :)

**Comment by novex1984** [comment]
Thanks for join in. We need more help on exploring your MAGIC.
