### ISSUE TITLE
"SingleMarket" settings offsets from current "Global Setting"

### ISSUE THREAD

**Issue by Othon3** [Legedric/ptmagic#241]
When using Single Market settings, the value it offsets is using the current Global Settings, not the historical value com the _PRESETS files. 

This is a bit tricky cause since the market changes, we already changed the values on the Pairs.properties, and then, if another Single Market settings comes in play, it will offset even higher or lower (depending on the offsetpercent value we use).

For example, if our Default market uses a buy value of -1 for EMAGAIN. 
If our Single Markets is triggered , and applies 
"ALL_buy_value_OFFSETPERCENT": -50,
 it lowers the value do -0.5 .
But, if we are already on a Bear market, and we use a buy value of -0.6, when the trigger comes into play, it would lower it to -0.3.

Is this the way PTMagic is supposed to work?

**Comment by Legedric** [comment]
Please have a look at the setting **AlwaysLoadDefaultBeforeSwitch** here:
https://github.com/Legedric/ptmagic/wiki/settings.general

I guess you turned that to false? Necause default is true and if it is true, PTM will always take the default settings from your _presets before it applies the single market settings.

**Comment by HojouFotytu** [comment]
perhaps the function of this toggle on the tooltip, or in the wiki, needs to be clarified/re-worded?  

You'll recall I had the same issue after turning it off, and didn't understand why.  I thought this toggle meant if i was in "to the moon" and "too the moon" triggered, it would first go to my default set for 15 mins (according to flood protection) before switching to "tanking down"

**Comment by Othon3** [comment]
I had:

"AlwaysLoadDefaultBeforeSwitch": true,
      "FloodProtectionMinutes": 5,

The thing is, maybe some rules on the  single market settings were conflicting and then it had some issue writing on top of the present Global Setting or something.

I have redone the whole thing and am wacthing the bot.

**Comment by Othon3** [comment]
after reviewing all the setting and rebooting the VPS system, the glich disapeared.
Don´t khown what caused it.
Closing
