### ISSUE TITLE
[Enhancement] Tooltip why Set is chosen and outcome

### ISSUE THREAD

**Issue by smoochy** [Legedric/ptmagic#242]
Hi there,

it would be really helpful, to have a little tooltip next to the "Active Global Setting" name, which explains, why this setting is active at the moment.

Example:

Active Global Setting: SuperBear
Hovering on SuperBear will bring up sth like "Exchange24h < 1.5"

So when I am changing a lot in the settings.analyzer.json file and might lose the overview, I get a hint, why a certain set was chosen.

Maybe in the same tooltip, it can also be shown what the outcome of this is. Like: 

Changes in pairs:
"ALL_sell_only_mode": true,
"ALL_sell_value": 0.5,
"ALL_trailing_profit": 0.1

Changes in DCA:
"trailing_profit": 0.3

**Comment by Legedric** [comment]
It is already planned to have something like a log to see when a setting was activated and what the trends were at that time.

**Comment by HojouFotytu** [comment]
The triggers are already visible in the monitor, but yeah, it couldn't hurt to see it in the monitor as well.

The problem with displaying the changes, is that it could really break the layout.  some of my settings changes affect a large number of settings in the pairs files and DCA files.
