### ISSUE TITLE
Add a GUI "Sell at break even" feature

### ISSUE THREAD

**Issue by stevenshizzleh** [Legedric/ptmagic#244]
Sometimes there are coins that are just barely pushing the envelope of break-even. It'd be cool to have a feature to temporarily add a pair to a "Rapid Sell List" hot config in order to sell a coin ASAP and release the capital back into your pool for more investing. This would temporarily set the all_sell_value of the coin to something pre-configurable like .05 with a all_trailing_profit of .10.

**Comment by RunPlz** [comment]
Maybe this will be easier to achieve once we get the GUI for editing configs, in the meantime this can be done for a specific pair ignoring trailing and setting sell value to "0".

**Comment by Legedric** [comment]
Exactly, you can already do that using PT's properties (or HotConfig) without PTM selling at 0 or very little profit. So you do not need to have that in PTM.
I know working file text files is not the style of 2018 but PT Magic is not here to compensate for Profit Trailer's lacking GUI in the first place :)
