### ISSUE TITLE
FATAL - Exception while getting data for '' - Issue?

### ISSUE THREAD

**Issue by Tosko4** [Legedric/ptmagic#246]
![screenshot 2018-03-01 at 07 23 20](https://user-images.githubusercontent.com/1294707/36831017-54903c52-1d26-11e8-8c81-ddb79945d4f2.png)

Hi There, I don't really know what goes wrong here. I read my bot telling me that this error had occurred and to restart the bot. Obviously, before I do that I wanted to figure out what went wrong to prevent it from happening again. But with this error, I (and maybe crucial to others too) need some help on this and posted an issue here. Please let me know if this was a one-time thing or that this could be a code improvement. 

I am running this but on my Ubuntu VPS, not sure if this info is helpful, but Cant check the logs provided in the error because that path is only accessible through Windows.

**Comment by Legedric** [comment]
Seems like the bot cannot contact Binance to get the market data. So either your connection is having problems or Binance has issues.
With the next release, PT Magic will not stop the process in this case but just retry it with the next interval.

**Comment by Tosko4** [comment]
Thanks @Legedric
