### ISSUE TITLE
Chart going all crazy

### ISSUE THREAD

**Issue by Tosko4** [Legedric/ptmagic#247]
![screenshot 2018-03-01 at 08 11 37](https://user-images.githubusercontent.com/1294707/36831492-38be1650-1d28-11e8-88ea-5747b9887397.png)

Hi there,

This happened to me and there are some other in Telegram and Discord channels facing the same and asking how to fix it. No one has answered yet, so here is my attempt to get a fix for this.

**Comment by Legedric** [comment]
What is the setting for GraphIntervalMinutes set to in your settings.general.json?
![image](https://user-images.githubusercontent.com/8308141/36834667-deedd60e-1d33-11e8-8d41-fa025d8c50ff.png)

**Comment by Tosko4** [comment]
![screenshot 2018-03-01 at 09 37 56](https://user-images.githubusercontent.com/1294707/36834777-3fae93ac-1d34-11e8-8e3f-b8638a14a92b.png)

Same as yours, 60 minutes

**Comment by Legedric** [comment]
Ok and your StoreDataMaxHours iny our settings.analyzer.json?
![image](https://user-images.githubusercontent.com/8308141/36835034-24153302-1d35-11e8-8460-ade69012a351.png)

**Comment by Legedric** [comment]
So to explain what may causes this:
PT Magic will draw a point to your graph for each "GraphIntervalMinutes", so in your case every hour over a timeframe that is set in your "StoreDataMaxHours".

So the default is 1 point being drawn every hour over the last 24 hours. So 24 points on that graph.
If you for example set your StoreDataMaxHours to 7 days (168 hours), you will end up with 168 points being drawn to your graph.

**Comment by Legedric** [comment]
Just seen your answer now. We will implement a new setting that will allow you to set a different timeframe for your trend graph so you may extend your data timeframe without messing up the graph.
