### ISSUE TITLE
Strategy not applied

### ISSUE THREAD

**Issue by Fransenson** [Legedric/ptmagic#248]
It seems that "ALL_buy_strategy" for PT is not applied. 

See Screenshots:

<img width="596" alt="bildschirmfoto 2018-03-01 um 11 41 08" src="https://user-images.githubusercontent.com/5176886/36840535-96d8fbc0-1d45-11e8-994b-4b55182818f7.png">
<img width="286" alt="bildschirmfoto 2018-03-01 um 11 40 39" src="https://user-images.githubusercontent.com/5176886/36840536-96f45406-1d45-11e8-97d5-fb5db4e35e51.png">

PT Magic Monitor also still shows EMAGAIN.

**Comment by Legedric** [comment]
Did the settings you used this in get activated since you added this to your analyzer settings? If it got activated before you added this, then PT Magic will not recognize that you added this line and that your PT is missing this property for example.

**Comment by Fransenson** [comment]
This might be the case. Is there a way to kind of trigger a refresh?

**Comment by Legedric** [comment]
Go to your pairs. properties file in Profit Trailer and remove the PT Magic header.

**Comment by Fransenson** [comment]
That worked, thank you!
