### ISSUE TITLE
No valid pairs found for main market 'BTC' in configured pars list

### ISSUE THREAD

**Issue by sorentorp** [Legedric/ptmagic#249]
Hi

An error occurred today. I have been running PTMagic for a while now, with no problems.

I'm on Debian Stretch.

> 2018/03/01 11:56:48.189 INFO - Starting market trend check with Version 1.1.1
2018/03/01 11:56:48.190 INFO - CoinMarketCap - Getting market data...
2018/03/01 11:56:48.283 INFO - CoinMarketCap - Market data received for 100 currencies
2018/03/01 11:56:48.308 INFO - CoinMarketCap - Market data saved.
2018/03/01 11:56:48.320 INFO - CoinMarketCap - Market data cleaned.
2018/03/01 11:56:48.320 INFO - Binance - Getting market data...
2018/03/01 11:58:28.334 FATAL - The operation has timed out. System.Net.WebException The operation has timed out.    at System.Net.HttpWebRequest.GetResponse()
   at BusinessRules.MarketAnalyzer.BaseAnalyzer.GetSimpleJsonArrayFromURL(String url, LogHelper log) in D:\Tools\PTMagic\BusinessRules\MarketAnalyzer\BaseAnalyzer.cs:line 97
2018/03/01 11:58:28.380 FATAL - Exception while getting data for '': Object reference not set to an instance of an object. System.NullReferenceException Object reference not set to an instance of an object.    at BusinessRules.MarketAnalyzer.Binance.GetMarketData(String mainMarket, SystemConfiguration systemConfiguration, LogHelper log) in D:\Tools\PTMagic\BusinessRules\MarketAnalyzer\Binance.cs:line 44
2018/03/01 11:58:28.384 ERROR - No valid pairs found for main market 'BTC' in configured pars list ()! Terminating process...

**Comment by Legedric** [comment]
Seems like PT Magic was not able to contact Binance for fresh data.
With the next release, PTM will not stop processing in this case and will retry it on the next interval.
