### ISSUE TITLE
How to install in my VPS?

### ISSUE THREAD

**Issue by mikdesign02** [Legedric/ptmagic#25]
my PT is in my VPS can you give us a tuturial to install PTMagic in a VPS? Thanks

**Comment by novex1984** [comment]
Follow this instruction. I just did it on my VPS.
https://github.com/Legedric/ptmagic/wiki/Setup-PT-Magic-on-Windows

**Comment by mikdesign02** [comment]
Plz help me i send the PTmagic forber on my vps now can i see the homepage  

Envoyé depuis Yahoo Mail pour Android 
 
  Le dim., févr. 18, 2018 à 23:35, novex1984<notifications@github.com> a écrit :   
Follow this instruction. I just did it on my VPS.
https://github.com/Legedric/ptmagic/wiki/Setup-PT-Magic-on-Windows

**Comment by mikdesign02** [comment]
Plz help me i send the PTmagic forber on my vps now how can i access  the homepage ?

Envoyé depuis Yahoo Mail pour Android 
 
  Le dim., févr. 18, 2018 à 23:35, novex1984<notifications@github.com> a écrit :   
Follow this instruction. I just did it on my VPS.
https://github.com/Legedric/ptmagic/wiki/Setup-PT-Magic-on-Windows

**Comment by novex1984** [comment]
Do you manage to start ptmagic & ptmagic monitor?

**Comment by novex1984** [comment]
https://discord.gg/bYkmE4E Join the channel. There is an user name @Magic has the experienced with Linux. He just finished installed it.

**Comment by TwixRaider** [comment]
Just updated the Wiki on the topic "Setup PT Magic on Linux". With Linux you have to start the applications from a terminal window with 

> dotnet run PTMagic.dll
> dotnet run Monitor/Monitor.dll

in your PTMagic folder instead of calling "Start PTMagic.CMD" which is Windows only.
