### ISSUE TITLE
Release 1.2.0 - Monitor market trends and display Graph

### ISSUE THREAD

**Issue by Othon3** [Legedric/ptmagic#250]
Great uptade.

Two things:

The order of the trends on the Dashboard are not in time order, so a 1h trend is coming before de 30m trend..

Other issue:   "DisplayGraph": false is not taking the Market trend column out of the DASHBOARD or from the Trends page on Monitor:

          "Name": "Exchange30m",
          "Platform": "Exchange",
          "MaxMarkets": 45,
          "TrendMinutes": 30,
          "TrendCurrency": "Market",
          "DisplayGraph": false

![image](https://user-images.githubusercontent.com/36489267/36848648-a413f128-1d40-11e8-8702-02e8405909df.png)

**Comment by Othon3** [comment]
Oh, I see... When you created "DisplayGraph": false, that is just for the Graphics on the Dashboard...
I thought it would take them out including from the list of Markets trendss..

OK...  But anyways, the order of appearence still out. Is taking into account only the integer number of time.

Thanks guys.. Fantastic work!!!

**Comment by Legedric** [comment]
The thing is, the sorting is being done by a JavaScript library called table saw and they sort the table column by its content.

The default sorting is by name, which is a text column so in text sorting "15m" comes before "1h".

However the timeframe column is sorting by number values but of course a 30m (30) is being interpreted as being larger than 1h (1).

The only way to make that work out of the bix would be to change the timeframe column to show minutes but that's not a convenient solution in our opinion as noone would like to see numbers like 720 for 12h or 1440 for 24h there.

At the moment we are discussing of reverting that change and remove the sortable function from this table and sort it by the actual timeframe again.

**Comment by Fransenson** [comment]
I'd rather have it sorted by actual timeframe than being sortable (and sorting in a "wrong" order that way)

**Comment by HojouFotytu** [comment]
agreed.  there is not point making it sortable if it doesn't sort correctly.

**Comment by Legedric** [comment]
We will revert this change with the next release.

**Comment by goferit** [comment]
Agree the Dashboard Market Trends table should be fixed ascending, but please do not roll back the Market Trends tab! In fact, please add sorting for the first 3 'check' columns if possible (to consolidate SOMs and and blacklisted pairs). Blacklisted pairs may need an 'x', so they sort correctly. "If no check in SOM, and no check in TRA, do X in TRA". Sorting which pairs are in DCA or not is also helpful.

'X' is just a concept to deal with the blanks. Checks may not sort right with the current JS. Could do Y/ N if it works with current JS.

**Comment by Legedric** [comment]
The current release got re-upload to revert the changes for the market trend table on the dashboard,

The market trends table on the Market Trends page was left untouched.
