### ISSUE TITLE
Problem with profit trailer using magic every 12 hours?

### ISSUE THREAD

**Issue by bitnick21** [Legedric/ptmagic#251]
hi, every 12 hours or so using magic i get this error from pt magic:

BINANCE BTC - There is something wrong with your Bot, if it happens 3 times in a row. Restart your bot

When it happens profit trailer freezes and so does magic.

Any ideas how to fix this? thanks

**Comment by RunPlz** [comment]
I believe this may have to do with PT more than PT Magic.

What PT version are you currently running?

2018-03-01 11:37 GMT-03:00 bitnick21 <notifications@github.com>:

**Comment by bitnick21** [comment]
i am using 1.2.6.18 but am also running a script from crypto gnome to restart profit trailer if it crashes but i am guessing its not working. lol.

**Comment by RunPlz** [comment]
I would strongly suggest updating PT version to .20

**Comment by Legedric** [comment]
The error does not come from PT Magic so we cannot investigate anything on this.

**Comment by bitnick21** [comment]
thanks. according to the pt trailer gitman page i am running the latest version? is this something to do with the latest version or am i missing something? do you have a link to the correct page? (also thanks for the super fast reply!)

**Comment by Legedric** [comment]
You can find the latest release of PT (x.x.x.20) here:
https://github.com/taniman/profit-trailer/releases
