### ISSUE TITLE
Release 1.2.0 - DCA Calc : a (very little) problem with the reading of pairs.properties

### ISSUE THREAD

**Issue by JeanGalt** [Legedric/ptmagic#252]
Thanks for this very nice release

My parameters in pairs.properties are:
ALL_max_cost = 0.005
ALL_max_cost_percentage = 0.5
(I left it as is, knowing that max_cost has priority over max_cost percentage)

When I load the DCA Calculator page, I have this:
Max Cost = 0.005 percent (value is being read from your PAIRS.PROPERTIES)

This problem no longer appears by leaving the percentage line in #commentary

Another little problem: I have 25 pairs and only 24 are displayed in the DCA calculator

**Comment by Legedric** [comment]
Regarding the max_cost thing:
Thanks, we will change this with the next release to follow the same priority here as PT does.

>Another little problem: I have 25 pairs and only 24 are displayed in the DCA calculator

Did you try changing the "MacDCAPairs" setting for your monitor to 25? The default is 24 pairs for DCA and that's what you are seeing.

**Comment by JeanGalt** [comment]
Thank you, I did not know this parameter.

It works, but now I have a curious thing (for max_cost=0.005):

![20180301-192820](https://user-images.githubusercontent.com/36671618/36862300-bc506b4a-1d86-11e8-80b1-f300d2f590e6.jpg)

**Comment by Legedric** [comment]
That looks strange indeed. I will have to check this.
