### ISSUE TITLE
1.2.0 DCA Calculator valid balance

### ISSUE THREAD

**Issue by Fransenson** [Legedric/ptmagic#253]
I tried to use the Advanced DCA Calculator.

My balance is (imho) valid with 0.XXXXXXXX (8 digits after the .) 

I get the following error message with advanced as well as simple mode:

`"Please enter a valid balance value on the left to calculate results..."`

**Comment by Legedric** [comment]
Screenshot please :)

**Comment by Fransenson** [comment]
<img width="1011" alt="bildschirmfoto 2018-03-01 um 17 34 38" src="https://user-images.githubusercontent.com/5176886/36856747-feb2bda4-1d76-11e8-8c52-e64b97e1001c.png">

**Comment by Legedric** [comment]
Whats browser are you using?

**Comment by Fransenson** [comment]
Safari currently.

**Comment by Fransenson** [comment]
I restarted the Monitor and now it is working again. #closed
