### ISSUE TITLE
An error occurred while processing your request.  3 pages

### ISSUE THREAD

**Issue by Chainsaw801** [Legedric/ptmagic#254]
Hello and thanks for the updates!  I am getting errors on the following pages

**For the Sales Analyzer page I get:**
Error.
An error occurred while processing your request.
Request ID: 0HLBVI8GB395Q:00000015

Object reference not set to an instance of an object.

**For the Market Trends page I get:**
Error.
An error occurred while processing your request.
Request ID: 0HLBVI8GB395Q:00000016

Object reference not set to an instance of an object.

**For the SettingsGeneral page I get** 
Error.
An error occurred while processing your request.
Request ID: 0HLBVI8GB395Q:00000017

Object reference not set to an instance of an object.

**Comment by Legedric** [comment]
Please do the following:
1. Go to one of those pages
2. Right click and hit "Show Source"
3. Copy the whole text into a text file
4. Upload the file here

Thanks!

**Comment by Chainsaw801** [comment]
[PageError.txt](https://github.com/Legedric/ptmagic/files/1772025/PageError.txt)
Here you go!   Thanks!

**Comment by Legedric** [comment]
Ok, please check what this setting is set to in your settings.general.json:
![image](https://user-images.githubusercontent.com/8308141/36864319-9e922cb4-1d8c-11e8-9b80-797384fe84ef.png)

Seems like it is set to something that's not accepted? (Only "TradingView" and "Exchange" are valid values for that setting)

**Comment by Chainsaw801** [comment]
Perfect.   Mine was set to null.   Close this one as solved.   I appreciate the quick response!
