### ISSUE TITLE
FATAL - Clueless error

### ISSUE THREAD

**Issue by RunPlz** [Legedric/ptmagic#255]
What does this mean?

![image](https://user-images.githubusercontent.com/36750854/36856927-fc80bd0e-1d55-11e8-9670-883032462498.png)

**Comment by Legedric** [comment]
Please restart PT Magic, seems like Bittrex had issues in the middle of your data (re-)creation run.

**Comment by RunPlz** [comment]
Correct and done, just threw the error report here hoping it might be of any use for those literate enough.
