### ISSUE TITLE
Unhandled Exception

### ISSUE THREAD

**Issue by freecoat** [Legedric/ptmagic#256]
Hi, after upgrading to the last version I get this error:
\start
2018/03/01 19:35:56.654 INFO - Starting market trend check with Version 1.2.0
2018/03/01 19:35:57.684 INFO - CoinMarketCap - Getting market data...
2018/03/01 19:35:57.944 INFO - CoinMarketCap - Market data received for 100 currencies
2018/03/01 19:35:58.896 INFO - CoinMarketCap - Market data saved.
2018/03/01 19:35:58.988 INFO - CoinMarketCap - Market data cleaned.

Unhandled Exception: System.NullReferenceException: Object reference not set to an instance of an object.
   at PTMagic.PTMagic.MarketTrendCheckTimer_Elapsed(Object sender, ElapsedEventArgs e) in D:\Tools\PTMagic\PTMagic\PTMagic.cs:line 224
   at PTMagic.Program.Main(String[] args) in D:\Tools\PTMagic\PTMagic\Program.cs:line 141

C:\Users\fricot\Documents\PTMagic\PTMagic>pause
\end

Any clue?
Thanks,
Mat

**Comment by Legedric** [comment]
Which exchange are you using?

**Comment by freecoat** [comment]
Binance

Il 01 Mar 2018 20:20, "Legedric" <notifications@github.com> ha scritto:

**Comment by Legedric** [comment]
Is this still happening with the most recent release?

**Comment by freecoat** [comment]
it looks like 1.2.2 fixed the bug. Thanks for you work man! As soon as the
market will flow again you will get also part of my profits. Keep up the
good work!
Best,
mat

>
