### ISSUE TITLE
Error Report - Another one bites the dust

### ISSUE THREAD

**Issue by RunPlz** [Legedric/ptmagic#257]
Test mode ON.
PT Feeder ON.

![image](https://user-images.githubusercontent.com/36750854/36866108-2452aec2-1d70-11e8-90d6-f50a5e8ab3d3.png)

**Comment by Tosko4** [comment]
Its simple. You read that the file is already being modified by someone or something else. You mention you have Feeder on too. Maybe feeder was writing data at the moment pt magic tried to access the file. 

They also recommend NOT to run both Feeder and Magic at the same time to avoid conflicts

**Comment by RunPlz** [comment]
I'm using it as "monitor" in "test mode".

**Comment by Legedric** [comment]
Tosko4 is absolutely correct. Feeder and PT Magic on the same machine do not work. If you ignore the warnings that we posted on the wiki, you will run into errors.

Although PT Magic does not write to files in TestMode, it opens them to read from it and when that happens at the same time as PT Feeder reads/writes to it, you will run into an error like the one you posted.

There is no way to get around that.

**Comment by RunPlz** [comment]
If you already use Profit Trailer Feeder and want PT Magic to act as an information dashboard only you can run it in Testmode. See this and this. PT Magic then will only collect summary data for the dashboard but will NOT change your settings (that would be Feeders job).

-----

So this is a normal error when using Testmode + Feeder. OK.

**Comment by Legedric** [comment]
Yes it is.
