### ISSUE TITLE
2 Future Enhancement Requests

### ISSUE THREAD

**Issue by ShadowOnTheLand** [Legedric/ptmagic#258]
Thank you for your work. It's appreciated.

First request: Is there a way to pull current pairs and DCA information from Profit Trailer? If so:

It would be SUPER handy if in the Market Trend tab, any pairs that are currently held to be at the top of the list in it's own list apart from the rest of the market pair list. This would allow us to easily load up the correct chart easily without having to scroll around looking for the current pairs we are trading. 

Second Request: When you are in Sales Analyzer, and you click on one of the months in the last 10 months, it opens this FABULOUSLY AMAZING break down of everything that happened in that month.

Can we get an export to spreadsheet button? That was be stellar.

**Comment by Legedric** [comment]
I think all features requested here are implemented into PTM by now having a detailed Buy and Bag Analyzer.
