### ISSUE TITLE
[Bug] DCA Calculator issues

### ISSUE THREAD

**Issue by smoochy** [Legedric/ptmagic#259]
Hi there,

thanks for the nice update to Version 1.20 :)

I've got two things with the DCA Calculator

1) (which already was present in 1.1.1) When I open DCA Calc, it reads the values of balance, pairs and max cost correctly from the files. But it is not reading the DCA levels. It is always set to 0, whenever I open the calculator. Although I have set `max_buy_times = 3` in DCA.properties

2) When opening the advanced view, it is not calculating anything.

![advanced](https://user-images.githubusercontent.com/34371932/36871558-ec55b91e-1da2-11e8-879a-98e48c4bd306.jpg)

The simple view is working (still not taking `max_buy_times =3` by default)

![simple](https://user-images.githubusercontent.com/34371932/36871583-04ca4b54-1da3-11e8-8140-9f8c70723e8b.jpg)

Google Chrome 64.0.3282.186
I already:

- closed and restarted PTM and PTMMonitor
- checked another browser (Firefox 58.0.2 (64-Bit))

Same behaviour.

Anything I can try. Do you need more information from my side?

Thanks.

**Comment by Legedric** [comment]
Please ZIP and upload your dca.properties file here so I can check why it is not loading the buy times and triggers correctly.

**Comment by smoochy** [comment]
Thanks for your reply.

I packed the PTM version of the DCA file and the PT version of the DCA file into one zip:

[Desktop.zip](https://github.com/Legedric/ptmagic/files/1773935/Desktop.zip)

**Comment by Legedric** [comment]
Thanks for the upload. So I looked at your files and I recognized that you did not set max_buy_times anywhere in your PT DCA.properties and that's why PT Magic interpreted this as 0.

In the next release, PT Magic will do the same as PT does when this is set to 0, it will just count the configured triggers and use them as DCA levels.

**Comment by smoochy** [comment]
Max_buy_times is set to 3. In both files. PT and PTM. 

Line 12 in PTM an PT file.


What about the second mentioned issue?

**Comment by Legedric** [comment]
Yeah well, that's not a valid line:
![image](https://user-images.githubusercontent.com/8308141/36897979-1fe0e51c-1e19-11e8-9aae-b8ba583f48ab.png)

"//" does NOT work as comments in Java properties files. So in fact, your Profit Trailer will also probably interpret this as "not set" as it may not be able to read this line. So your PT may even buy a 4th or 5th time with your settings as you set triggers for a 4th and 5th level and this line is invalid.

Same goes for PT Magic, it does not recognize this setting to be valid and so it takes it as "not set" or "0".

So please remove that // commen after the "3" in that line and it will work.

**Comment by Legedric** [comment]
PS: The other issue (adv. mode not calculating anything) is a follow up error on the first one. As PT Magic does not recognize your DCA levels it doesn't know what to calculate there.

**Comment by smoochy** [comment]
Oh gosh. Embarrassing. Thanks for pointing out that issue. 
Yes you are right. Issue two is solved by solving issue one. 

Thanks for your help!
