### ISSUE TITLE
Release 1.20 Telegram now sends a message upon each market interval instead of when it switches mode based on market triggers

### ISSUE THREAD

**Issue by Gorbux** [Legedric/ptmagic#260]
So I currently have PT Magic set to check the market every 5 minutes and it sends a telegram message every 5 minutes of what mode it is in. In all previous versions, it would only send the message if it changes modes.

**Comment by Legedric** [comment]
A couple of questions so we can investigate on this:
- OS of your machine?
- Are you running PT Magic in test mode?
- Please copy and paste the PT Magic header that got written to your pairs.properties file in Profit Trailer/trading here.

**Comment by Legedric** [comment]
Closing this as there is more feedback provided in #266
