### ISSUE TITLE
BTC Market Trend/SOM Feature Request/Issue

### ISSUE THREAD

**Issue by SleazyE** [Legedric/ptmagic#262]
Hey all, thanks so much for what you do, as it does not go unappreciated. 

This issue was brought up with Legedric on the Gnome discord. Currently I'm trying to add a market trend for BTC only, to trigger PT into SOM, given an increase or decrease in X% during XHrs. 

What I tried was to include "ExcludeMainCurrency= false" into the market trend, limit to 1 market on CMC (BTC), and go from there. It appears as though the code is being overwritten though, by the hierarchy of "ExcludeMainCurrency=true" at the top of the analyzer. As you can see below, when Magic is running it is pulling the trend for ETH. 

<img width="983" alt="1" src="https://user-images.githubusercontent.com/36977277/36881825-8845c15e-1d8d-11e8-9c03-4496bb59c28e.png">
<img width="576" alt="2" src="https://user-images.githubusercontent.com/36977277/36881837-95e5db8c-1d8d-11e8-9da0-e47d274a3382.png">
<img width="1154" alt="3" src="https://user-images.githubusercontent.com/36977277/36881839-9fa47746-1d8d-11e8-9bd2-9645ad1fdddc.png">

What I'm wondering, is if "ExcludeMainCurrency=true" can be removed from the top of the analyzer, and implemented into each market trend separately, leaving the user to have true or false values for different market conditions. If not possible, is this a feature that can be added?

**Comment by SleazyE** [comment]
UPDATE!

I've tried removing "ExcludeMainCurrency" from the top of the analyzer and implementing into every market trend which has not worked in regards to tracking the BTC trend only, and is pulling data on the ETH trend. What is VERY concerning to me is the fact that Magic is pulling the 24hr trend % for ETH from CMC even though the trend minutes are set to 60. I was at least expecting to see the 1hr trend for ETH displayed if the code did not work, but the fact that it's showing the 24hr trend is quite odd.  

<img width="923" alt="screen shot 2018-03-01 at 8 49 19 pm" src="https://user-images.githubusercontent.com/36977277/36882757-f3a4348a-1d92-11e8-854f-68d30c899c93.png">
<img width="540" alt="screen shot 2018-03-01 at 8 44 05 pm" src="https://user-images.githubusercontent.com/36977277/36882760-001154c8-1d93-11e8-8852-0337eb771e30.png">
<img width="1152" alt="screen shot 2018-03-01 at 8 43 50 pm" src="https://user-images.githubusercontent.com/36977277/36882764-0787270a-1d93-11e8-82f9-941bd6d669e3.png">

**Comment by Legedric** [comment]
Did you notice the thing about your 1h trend taking the 24h price immediately or after PT Magic ran for some time?

Because when PT Magic starts building data for CMC, it can only initiate data for NOW and 24h back and nothing inbetween. So to have data for 1h it will take 1h to have that data. Unfortunately CMC is not providing an API to pull ticks for the past as we are using it to build up market data for the exchanges for example.

**Comment by SleazyE** [comment]
The 1Hr trend was immediately after restarting magic, so that makes sense. 

As far as the "ExcludeMainCurrency", is there a workaround to be able to set each market trend independently? As you know, when BTC rises, alts are down. It'd be nice to be able to exclude BTC from all trends except for a BTC only trend. Is this possible?

**Comment by Legedric** [comment]
We added the "ExcludeMainCurrency" to the market trends so you may overwrite this for each trend with the next release.
