### ISSUE TITLE
[PTMagic 1.2.0] Graph Max Timeframe Hours -> It does not work properly.

### ISSUE THREAD

**Issue by nicekon** [Legedric/ptmagic#263]
![cap 2018-03-02 21-09-03-420](https://user-images.githubusercontent.com/792574/36898374-f7d0ae50-1e5d-11e8-92c1-570c02f1bc94.png)

Changed the value of [Graph Max Timeframe Hours] to 48 hours.

It's been over a day, but it only shows graphs for the last 24 hours.

Please confirm.

**Comment by Legedric** [comment]
What's your settingf or StoreDataMaxHours in settings.analyzer.json?
If you store data only for 24h (default) then there is of course no data for the other half of 48h.

**Comment by nicekon** [comment]
@Legedric I did not know.
The value I set was 24 hours.

Let's try it.

Thank you.
