### ISSUE TITLE
Time Zone Offset

### ISSUE THREAD

**Issue by axleman27** [Legedric/ptmagic#269]
Would it be possible to set the local timezone?

My timezone is significantly different than the timezone my VPS is in and it causes my data to be off. 

(Right now, PT magic is showing sales for 3/3/18 and it is still 3/2 here.)

Great addon by the way! Thanks for sharing this.

**Comment by NikitaSotnikov** [comment]
@axleman27 @Legedric 
Change timezone in VPS OS (Linux, Windows) to your local timezone. It is working!

**Comment by axleman27** [comment]
Changing the timezone on the server does work. Thanks.

It would still be nice to do this in PTM though as there may be other things running on the server that need the correct local (server) time.

**Comment by Tosko4** [comment]
@NikitaSotnikovI am not allowed to change my VPS timezone. would be nice to have the tool support this instead
