### ISSUE TITLE
Multiple bot instances

### ISSUE THREAD

**Issue by mrhasbean** [Legedric/ptmagic#27]
Hey guys, love your work! I run multiple bots on my VPS. What is required to set up PTMagic to support multiple bots?

**Comment by novex1984** [comment]
Is same process. Just change the port number will do.

**Comment by mrhasbean** [comment]
Ok, so if I put an instance of PTMagic in each active PT directory and set it up for that bot, then run each separate instance of PTMagic, that should work? What is the memory requirement? (In case I have to get more resources for my VPS)

**Comment by Legedric** [comment]
@mrhasbean Yes, the approach is correct to run multiple instances.  

To be honest, we did some memory checks with PT Magic but the most memory it was using was <200MB (yes, MegaByte) but we never tried running more that one bot on a single machine.  
So you may just test it out for yourself and observe if you are getting any slowdowns somewhere.

**Comment by MarcP1001** [comment]
Set up my second instance and everything loaded no problem.  The first instance is in BTC.  Second is in ETH.  The issue with the second is, while is says ETH it is quoting the BTC price.  How do I fix this?
Marc

**Comment by MarcP1001** [comment]
That was it!  Thanks for the help.
Marc
