### ISSUE TITLE
DCA incorrectly displayed in Market Trends

### ISSUE THREAD

**Issue by clippart** [Legedric/ptmagic#270]
Hello Legedric and team!

We have the current settings

 - + Active setting: Bear
2018/03/03 11:45:34.605 INFO - + Global setting changed: Yes

in current settings the following:

        "SettingName": "Bear",
        "TriggerConnection": "AND",
        "Triggers": [
          {
            "MarketTrendName": "Exchange1h",
            "MaxChange": 1
          },
          {
            "MarketTrendName": "Exchange12h",
            "MaxChange": 0
          },
          {
            "MarketTrendName": "Exchange24h",
            "MaxChange": -1,
            "MinChange": -3
          }
        ],
        "PairsProperties": {
          "ALL_DCA_enabled": false
        },

In PAIRS.properties
------- Dca -------
 PTMagic changed line for setting 'Bear' on 3/3/18 11:45 AM
ALL_DCA_enabled = false

But in Market Trends following

![default](https://user-images.githubusercontent.com/33903011/36930699-592d6d70-1ed9-11e8-98c2-4a394f344c13.PNG)

**Comment by Legedric** [comment]
I checked this and for me it is working so I am not able to reproduce this. Did you make sure that there are no other lines in your pairs.properties enabling DCA for these coins?

**Comment by clippart** [comment]
Hello. Yes, it's all right. It was because of the test mode
