### ISSUE TITLE
Changes in Profittrailer

### ISSUE THREAD

**Issue by siquenique** [Legedric/ptmagic#272]
Hi,

When we make changes using profittrailer page they will be over written by the PTMagic. Can't we have a setting that after the initial control of PTMagic than we have  synch from profittrailer to PTMagic?

This happens for example when we block a coin.

**Comment by Legedric** [comment]
No, that's not possible at the moment and we do not plan to implement something liek synching. If you want to make changes to your settings maunally, you have to follow this guide:
https://github.com/Legedric/ptmagic/wiki/Manually-updating-settings

**Comment by mile6919** [comment]
You need to set PTMagic not to overwrite Profit Trailer properties files:

""AlwaysLoadDefaultBeforeSwitch": false, // If this is enabled, PTMagic will always load default settings before switching to another setting"

You need to use this setting from "settings.general.json" -file of PTMagic

**Comment by Legedric** [comment]
@mile6919 If you use that, you may not work properly with offset values! And it will still overwrite your settings when PT magic switches to Default.
