### ISSUE TITLE
An error occurred while processing your request.

### ISSUE THREAD

**Issue by unojazz** [Legedric/ptmagic#273]
<h1 class="text-danger">Error.</h1>
<h2 class="text-danger">An error occurred while processing your request.</h2>

    <p>
        <strong>Request ID:</strong> <code>0HLC10167B31U:00000026</code>
    </p>

      <h2>Access to the path &#x27;/root/ProfitTrailer/ProfitTrailerData.json&#x27; is denied.</h2>

**Comment by Legedric** [comment]
What OS are you running PTM on?

**Comment by unojazz** [comment]
Ubuntu 16.04

**Comment by Legedric** [comment]
Seems like for whatever reason the access to the path/file /root/ProfitTrailer/ProfitTrailerData.json is blocked for PT Magic monitor.  

I am no Unix expert so you will have to find out what's wrong there by yourself or with the help of other Unix users.

**Comment by Tosko4** [comment]
the account you run it with does not have the appropriate permissions to access the files. You can try to run it with sudo command or ensure the entire folder and files have the right chmod permissions
