### ISSUE TITLE
Id love to see a daily/total profit goal, as seen here.

### ISSUE THREAD

**Issue by OhLongJonson** [Legedric/ptmagic#274]
![screenshot 51](https://user-images.githubusercontent.com/36889676/36937522-cefb4460-1ee2-11e8-8064-e380573288a5.png)

**Comment by Legedric** [comment]
Where are those "goal" things coming from? Is that something you enter somewhere?

**Comment by jbraydc** [comment]
I think he wants to be able to set a profit target - similar to like what you can do on some banking software. So you say I want to make 0.5% profit per day or 2% profit per week etc and you can compare actual result with what you were aiming for.

**Comment by Legedric** [comment]
We will put this on the list but do not expect this anytime soon (if ever).
