### ISSUE TITLE
[Feature Request] Support For Other Fiat Currencies

### ISSUE THREAD

**Issue by smoochy** [Legedric/ptmagic#276]
Hi there :)
For all non US folks it would be very beneficial to be able to select another Fiat currency like EUR etc.
Prices of trades, profits etc should be converted according to the selected currency.

**Comment by Legedric** [comment]
The problem is that most exchanges only provide a rate from BTC/ETH to USDT and this means we have to get the rate from somewhere else or find the rate from USD to XYZ to calculate the value for EUR or AUD for example.

So I am not saying it won't happen, but it is not something to expect in the next few releases.

**Comment by smoochy** [comment]
Wouldn't it be possible by using google for that? I don't know though, if they provide an API for that.

**Comment by Legedric** [comment]
Maybe. I know they have an API for that for their Spreadsheets but I never digged into that to see if they have it available for something that's not related to one of their products.

**Comment by jbraydc** [comment]
If anyone can help to provide suggestions for this it would be a welcomed upgrade. I would like to be able to display 2 currencies USD and AUD maybe from a dropdown box.

**Comment by jbraydc** [comment]
http://fixer.io/ maybe this will help Legedric? It is an opensource api for currency.

**Comment by jbraydc** [comment]
https://currencylayer.com/
https://openexchangerates.org/

**Comment by smoochy** [comment]
Thank you for making this possible 👍

**Comment by Legedric** [comment]
Always a pleasure :)
