### ISSUE TITLE
Question about PTMagic settings adjustment

### ISSUE THREAD

**Issue by wk4536** [Legedric/ptmagic#277]
Does PTMagic adjust the number of pairs and/or the max cost of each purchase, or changes to DCA as it changes settings or does the program just follow whatever I had in PT Trailer? I wasn't sure if the calculator is where it goes to run our numbers and decide on a safe level based on our usage limits or if it was there for us to use to go and change our settings.

**Comment by Legedric** [comment]
PT Magic does nothing on its own. It just does what you configure it to do in your settings.analyzer.json file.

So although it is called PT Magic there is no real magic behaviour behind that you are not aware of.
