### ISSUE TITLE
[Enhancement] Add Date to Dashboard Graph / make it bigger

### ISSUE THREAD

**Issue by smoochy** [Legedric/ptmagic#278]
Hi there,

I would like to suggest two improvements to the graph in the dashboard:

1) Add a date in front of the time, which is shown in the top of the tooltip, when hovering the graph (excuse my phenomenal photoshop skills):

![graph](https://user-images.githubusercontent.com/34371932/36947381-0c022fd4-1fcb-11e8-8e3d-f75b9d6b4a2a.jpg)

As the graph is covering several days, I do not know which day it is exactly what I am hovering over.

2) In addition I would love to be able to view the graph larger. Meaning, maybe like in an overlay (like when clicking in the Sales Analyzer on any day). Reason: As you can see on the screenshot above it is hardly possible to distinguish single lines from each other, as they are mostly laying above each other.

**Comment by Legedric** [comment]
Well, the graph wasn't intended to be used for days of data. The default is 24h for a reason.

I now some people are using this with days of data in there and it looks like yours, but that's still not how it was planned in the first place.

We may change this with a future release to add dates to the times there but the library we are using for the charting will only allow to set the date to every data slot. Meaning that if we add a date to the time there, it will not only show on the tooltip but also on the x-axis labels which will most likely make this look like a mess then. But we will take a look at this and see how we can handle this.

**Comment by HojouFotytu** [comment]
I've mentioned before... I think a larger (thus easier to read) version of this at the top of the markets page would make a lot of sense, since it's mostly the same data, just in graph format.

**Comment by Legedric** [comment]
As we added a larger market trends graph to teh Market Analyzer page with 1.5.0 I believe this request is completed :)
