### ISSUE TITLE
Graph position % Change

### ISSUE THREAD

**Issue by CryptoJD** [Legedric/ptmagic#279]
Would be nice to have a page that shows all active positions and Graph the % change + or - % like we do with the market Data. but maybe 1 small 2x4 graph for each pair that you are currently holding a position. Basicly the 
![image](https://user-images.githubusercontent.com/6138139/36952769-63698fb4-1fd1-11e8-97d1-f8ab662276bd.png)
as it changes on a graph. But allow a pop out on the graph. if you click on it it pulls out to be larger over the rest of the page behind it.

Also would be great to have an option to load my positions from my exchange IE Binance on a view only API key that would see my current positions,  all current positions. buy price, current price. and % change. Possibly a graph for that coin  also to show the change over the last week. This way i can keep track of my long term hold also that are held on the exchange. but not traded by the bot. As i trade USDT pairs and my long term holds are BTC Pairs.

**Comment by Legedric** [comment]
It is quite unlikely that we will add charting to our monitor as this usually just causes issues we don't want to deal with.  

And no to API functions, not for any purpose.
