### ISSUE TITLE
When running behind a proxy on something other than / some of the URLs are broken

### ISSUE THREAD

**Issue by calebcall** [Legedric/ptmagic#28]
Some of the URLs are absolute paths and some are relative.  Assets are relative and all the others (/DCACalculator, SalesAnalyzer, etc) are absolute.  All should be relative so that it's much easier to setup behind an apache/nginx proxy (and it's good to be consistent).

**Comment by Legedric** [comment]
Thanks, it will be changed in the next release.

**Comment by calebcall** [comment]
So all the paths were updated to be absolute.  They should be relative so they can more easily support #60.  Right now, if you use a proxy path (i.e. /PTMagic) and your PT instance runs at /, then every time you log in, it redirects you to your PT UI.  I've put some ugly nginx rules in place that help fix it, but if we could get relative paths, it would "just work" without the ugly rules.
