### ISSUE TITLE
PTMagic hangs while recreating market data on first launch v1.2.1

### ISSUE THREAD

**Issue by Moussier** [Legedric/ptmagic#280]
Hi, 

I tried to do a fresh install of v1.2.1 on my Raspbian Pi 3 but the process hangs while retrieving Binance data. I tried to reboot the Pi, but nothing better hapened.

![image](https://user-images.githubusercontent.com/24268913/36953082-eb729158-2017-11e8-98b0-839996d08ee4.png)

Thanks, keep up the good work !

Edit : It actually works with v1.2.0 

![image](https://user-images.githubusercontent.com/24268913/36953237-6586355c-2019-11e8-840f-84441f684ccf.png)

**Comment by Legedric** [comment]
This will be fixed in an emergency release right now.
