### ISSUE TITLE
Exessive log file size

### ISSUE THREAD

**Issue by nsater** [Legedric/ptmagic#281]
Daily logs are reaching ~350 megs per day. 94% of the log is on the DEBUG level, which for the average user is not needed. 

Suggestion to change the default logging level to INFO, and leave DEBUG as an option that can be enabled in the settings if needed.

![2018-03-04 22_53_14-trader](https://user-images.githubusercontent.com/30016839/36961288-7c32238e-1fff-11e8-825b-a4e29bb841ef.png)

P.S. If you have been running PTM for awhile you might want to take a look at your '_logs' directory and purge some of the old logs.

**Comment by Legedric** [comment]
Thanks, I already changed the log level to Info a while back but during one of the most recent releases I copied the development nlog.config to the release package by accident.

**Comment by nsater** [comment]
Perfect, thanks.
