### ISSUE TITLE
Request ( Sort by SOM, DCA or TRA )

### ISSUE THREAD

**Issue by juato4** [Legedric/ptmagic#282]
would very useful if we can sort by SOM, DCA or TRA

<img width="1421" alt="captura de pantalla 2018-03-05 a la s 14 05 47" src="https://user-images.githubusercontent.com/35824627/36988760-67f40c3c-207e-11e8-948c-fc303852795d.png">

**Comment by Legedric** [comment]
UNfortunately the library we are using for that sorting does not support this out of the box so it will not happen anytime soon (if ever).

**Comment by SPANDOOS** [comment]
+1

**Comment by cybermizrach** [comment]
+1
