### ISSUE TITLE
PT Magic 1.2.2 Advanced Tab for manual adjustments on monitor disappeared ? 

### ISSUE THREAD

**Issue by cryptomail2018** [Legedric/ptmagic#283]
where it gone ?
can we have it back please 
thank you

**Comment by Legedric** [comment]
What exactly do you think has disappeared? We did not remove anything from the monitor.

**Comment by Tosko4** [comment]
@cryptomail2018 it works for me, I guess it's an issue with either your browser or cache.
Ensure you clean your browser up and try again.

**Comment by Legedric** [comment]
Closing this as there was no feedback for more than 2 days now.
