### ISSUE TITLE
PT Magic Monitor doesn't show trends chart

### ISSUE THREAD

**Issue by nstefi** [Legedric/ptmagic#284]
I upgraded PT Magic to 1.2.2 for both my Bittrex and Binance bots, and the Bittrex one doesn't show the trend chart right now. The Binance shows, and I think the Bittrex one showed too yesterday after the upgrade, but today when I checked it looks like this:
![image](https://user-images.githubusercontent.com/6478474/37072071-a55935e2-218d-11e8-9cff-3a46401e64b6.png)

**Comment by Legedric** [comment]
When you hit F12 in your browser and look at the "Console" tab. Press F5 in your browser and see if you see any errors popping up there in the Console.

**Comment by nstefi** [comment]
Thanks for your answer.
Yes, I see these errors:
![image](https://user-images.githubusercontent.com/6478474/37073325-397069f2-2194-11e8-92f6-2641494bd417.png)

**Comment by nstefi** [comment]
But my other PT Magic bot on Binance runs in another tab in the same browser (Chrome), and that one doesn't show any errors, just the same warning in yellow:
![image](https://user-images.githubusercontent.com/6478474/37073374-899bcaca-2194-11e8-8957-458c23608f97.png)

**Comment by nstefi** [comment]
OK, here is the file:
[PageSource.txt](https://github.com/Legedric/ptmagic/files/1790751/PageSource.txt)

**Comment by Legedric** [comment]
Ok I found what's causing this.
For some reason I see in line 260 of your source that there is an "infinity" value for one of the trends. Usually this cannot happen but for whatever reason it did. It will get fixed in the next release. But until then you may resolve this issue by resetting the data of this PT Magic bot as instructed here:
https://github.com/Legedric/ptmagic/wiki/Reset-PT-Magic-Exchange-Data

**Comment by nstefi** [comment]
OK, thanks.
I have checked today and both my Bittrex and Binance bots shows some blank white page with some "Oh snap!" message, then I refreshed the pages and both of them show the chart now.
So I haven't done the fix you sent me, I guess it looks fine now.

Thanks.

**Comment by nstefi** [comment]
Hi Legedric,

Today I saw that PT Magic was not showing the chart again on Bittrex. On Binance was fine.
Since last time I didn't do the reset instructions you sent me (I only refreshes the browser that time after that white page was shown with the "Oh snap!" error), I decided now to follow the reset instructions, and in the same time I downloaded the newest version of Profit Trailer (1.2.6.22 - just overwrote the jar file).
So I stopped everything and deleted the "Exchange" folder under "_data", and started everything back (Profit Trailer first, then PT Magic, then PT Magic Monitor), and now I still cannot see the chart.
I see that the Exchange folder is back and it took a while to calculate the data.
Do you have any advice what I should try next?

Thanks,
Steven

**Comment by Legedric** [comment]
Wait for the next release and see if it fixes the issue. We are currently in internal testing and if everything goes well we will release it on Monday.
