### ISSUE TITLE
NO change of "ALL_buy_value"

### ISSUE THREAD

**Issue by kwieser76** [Legedric/ptmagic#285]
HI

may my setting are wrong or the cfg change for this value is not working
 "PairsProperties": {
          "ALL_sell_only_mode": true,
          "ALL_sell_value": 0.59,
          "ALL_trailing_profit": 0.15,
		  "ALL_max_cost_percentage": 0.5,
		  "ALL_min_buy_volume": 1500,
		  "ALL_max_buy_spread": 1,
		  "ALL_max_trading_pairs": 2,
		  "ALL_buy_value": -3.0
        },

#Pump & Dump Protection: 1 conservative, 2 mild, 3 aggressive
# PTMagic changed line for setting 'Super Bear' on 3/7/18 5:28 PM
ALL_max_buy_spread = 1

#Kaufstrategie
ALL_buy_strategy = EMAGAIN
ALL_buy_value = -0.95
#EMA_cross_candles = 6
ALL_trailing_buy = 0.15
ALL_buy_available_volume_trigger = 110
ALL_rebuy_timeout = 60

**Comment by Legedric** [comment]
I need more information on that. Please post the whole block of your settings.analyzer.json (as a text file upload here).

**Comment by kwieser76** [comment]
[settings.txt](https://github.com/Legedric/ptmagic/files/1790510/settings.txt)
Here is the file

**Comment by kwieser76** [comment]
Ok i don't why but i restart PTM and now it is working ... so i close this issue
