### ISSUE TITLE
PT Magic rests my ALL_max_trading_pairs

### ISSUE THREAD

**Issue by ethminerjay** [Legedric/ptmagic#286]
Hello!

Having the issue time and time again where PT Magic will keep resetting my max trading pairs 

Anyone have a fix for this?

**Comment by Legedric** [comment]
PT Magic doesn't reset anything you do not configure it to do.

If you want to manually update your settings, please follow this guide:
https://github.com/Legedric/ptmagic/wiki/Manually-updating-settings

**Comment by ethminerjay** [comment]
Thanks for coming back to me.

I have changed "Always load Default settings before switch" to false, but
that hasn't appeared to resolve the problem.

I've been trying to hunt down the 'max pairs' in the general file but have
had little luck so far. Is that line meant to be in the same, .json file as
the load default setting?

Thanks!

**Comment by Legedric** [comment]
If you are using the default settings for PT Magic then it will not change your max trading pairs. Everything that PT Magic applies to your properties is found in settings.analyzer.json.

**Comment by ethminerjay** [comment]
Unfortunately it does. I run profit trailer and have no issues whatsoever.

I start PT Magic and it resets my max pair settings. Follow the other
comment on this thread its not just myself who is/has experienced this

**Comment by Legedric** [comment]
Sorry but then you are doing something wrong (and the others experiencing this as well).

But to investigate this please ZIP and upload the following files here:
- Your pairs.properties from your PT/trading folder
- Your pairs.properties from your PT Magic/_presets/Default folder
- Your settings.analyzer.json

**Comment by ethminerjay** [comment]
I'm a bellend...Didn't realise the PARIS folder could also be found under presets in the PT Magic folder

Sorry for wasting your time - But thanks for the fix 👍

**Comment by Fransenson** [comment]
Just to clarify: In my case it was not PTM randomly changing values but my own stupidity/misunderstanding of how it works.

You 3 files you have to look at for your max pairs. 
ProfitTrailer/trading/PAIRS.properties
PTMagic/_presets/Default/PAIRS.properties
PTMagic/settings.analyzer.properties

The first to, especially the second one is crucial. Start with the second one and find or set your max pairs. Go on with the first one. Then check the analyzer settings and see if it changes it anywhere. 
I‘d bet a crate of beer that in the second path under _presets your PAIRS.properties changes the max pairs.
