### ISSUE TITLE
[Feature Request / Enhancement] Customize advanced DCA calculator

### ISSUE THREAD

**Issue by Fransenson** [Legedric/ptmagic#287]
Hello there!

I love that the advanced DCA calculator takes my current buy triggers into account, but I was thinking about reducing my pairs and going further down the DCA route. I have no option to calculate this in advanced mode without editing my DCA.properties to actually do more DCAs. 

Therefore my suggestion:

Make the "DCA TRIGGERS" table editable / have input fields above it as we already have for cost and pairs and such. Otherwise I have to rely on the simple calculator which is off by a big chunk depending on my settings. 

Would highly appreciate that!

**Comment by smoochy** [comment]
Hi,

this sounds like a very reasonable feature to have. I am in the same situation right now. I want to go from 4 to 5 DCA levels, but can not use the Advanced DCA Calculator for this.
