### ISSUE TITLE
Is it possible to have different buying strategies depending on the market?

### ISSUE THREAD

**Issue by cash-money** [Legedric/ptmagic#289]
Hi

I find that different strategies work better for different markets e.g. LOWBB works quite well for Bear.
Is it possible to set PT Magic to  change the buying strategies?  e.g. LOWBB for Bear, EMAGAN for Bull?  I have tried to do this my self but ran into problems...

Thanks

**Comment by Fransenson** [comment]
Yes.

```
        "PairsProperties": {
          "ALL_buy_strategy": "LOWBB",
          "ALL_buy_value": -8,
          "ALL_trailing_buy": 0.2
        }
```

Below the Triggers of your desired setting.
