### ISSUE TITLE
DCA parameters for different markets do not apply

### ISSUE THREAD

**Issue by clippart** [Legedric/ptmagic#292]
Hello team!

Encountered the following problem. For different markets, i created different presets for DCA.

![5](https://user-images.githubusercontent.com/33903011/37195314-e3a45d90-23a4-11e8-9e17-ea54d8eb4d76.PNG)

Does not work in any way, in both designs. All time the default buy_trigger_ from the Default folder

        "SettingName": "BearLight",
        "TriggerConnection": "AND",
        "Triggers": [
          {
            "MarketTrendName": "Exchange1h",
            "MaxChange": 1
          },
          {
            "MarketTrendName": "Exchange12h",
            "MaxChange": 0
          },
          {
            "MarketTrendName": "Exchange24h",
            "MaxChange": -1,
            "MinChange": -3
          }
        ],
        "PairsProperties": {
          "ALL_buy_value": -0.45,
          "ALL_trailing_profit": 0.2
        },
        "DCAProperties": {
          "trailing_profit": 0.2,
		  "buy_trigger_1": -2.85,
		  "buy_trigger_2": -4.85,
		  "buy_trigger_3": -6.85,
		  "buy_trigger_4": -10,
		  "buy_trigger_5": -12		  
        }
      },

OR

        "SettingName": "BearLight",
        "TriggerConnection": "AND",
        "Triggers": [
          {
            "MarketTrendName": "Exchange1h",
            "MaxChange": 1
          },
          {
            "MarketTrendName": "Exchange12h",
            "MaxChange": 0
          },
          {
            "MarketTrendName": "Exchange24h",
            "MaxChange": -1,
            "MinChange": -3
          }
        ],
        "PairsProperties": {
          "ALL_buy_value": -0.45,
          "ALL_trailing_profit": 0.2
        },
        "DCAProperties": {
          "File": "DCA.properties"		  
        }
      },

**Comment by Legedric** [comment]
So what files did you actuall put into thise preset folders like "BearLight" etc.?

**Comment by Legedric** [comment]
Thanks, I will check this.

**Comment by HojouFotytu** [comment]
My global settings all have DCA settings, and they've been working fine.

**Comment by Legedric** [comment]
I checked this with my own tests and it is working perfectly for me.

When you start PT Magic and then look into your _presets DCA file, do you see a PT Magic header that got added to it like this?
```
# ####################################
# ####### PTMagic Current Setting ########
# PTMagic_ActiveSetting = Test
# PTMagic_LastChanged = 3/2/2018 10:15 AM
# ####################################
```

Did you make sure the setting really got activated?

Because as I said, I am not able to reproduce this with my own tests so far.

**Comment by clippart** [comment]
Strangely all this, but now the same settings have worked. I was not in the fashion test last time.
Thanks
