### ISSUE TITLE
Parameter mismatch in Test Mode

### ISSUE THREAD

**Issue by clippart** [Legedric/ptmagic#295]
Hello again.
I'm probably already bored with you, but I sat very tightly in your product and today I saw a lot of inconsistencies in the Test Mode.
Maybe this is of course little things, but I was completely confused until I turned off the Test Mode and everything fell into place.
Thank You

![1](https://user-images.githubusercontent.com/33903011/37214836-d6d07c90-23e8-11e8-9854-69c094198aa1.PNG)
![2](https://user-images.githubusercontent.com/33903011/37214837-d6fba118-23e8-11e8-883c-9663274d8441.PNG)
![3](https://user-images.githubusercontent.com/33903011/37214839-d73352ac-23e8-11e8-8d13-3692bead482b.PNG)
![dump](https://user-images.githubusercontent.com/33903011/37214840-d758c5fa-23e8-11e8-925a-536487a11ab6.PNG)
![dump1](https://user-images.githubusercontent.com/33903011/37214841-d79b80b6-23e8-11e8-8453-744a40acb87c.PNG)

**Comment by Legedric** [comment]
So just to get that right: You disabled TestMode and then everything was good?

In TestMode PTM doesn't write to files. However, it does read from them and what it reads will (partly) be shown on the monitor so it is normal to see differences there as the Monitor will reflect your (not changed - as not written) files while PTM is running in TestMode.

**Comment by clippart** [comment]
Thank.
