### ISSUE TITLE
Error convert Null to Double??

### ISSUE THREAD

**Issue by Peet911** [Legedric/ptmagic#296]
Suddenly got this error, nothing is changed in the settings
![knipsel123](https://user-images.githubusercontent.com/36714194/37220870-3bf575c4-23c8-11e8-9222-af47994c5963.PNG)

**Comment by Legedric** [comment]
Is the error coming up every run or did it go away after some time? Because it may be just an issue with CoinMarketCap's API.

**Comment by HojouFotytu** [comment]
Same.  Had it for the first three runs, then went away.

**Comment by Legedric** [comment]
Then it most likely was an issue with CMC's API.

**Comment by Peet911** [comment]
It is gone. Thanks for your answer.

Op vr 9 mrt. 2018 om 21:43 schreef Legedric <notifications@github.com>
