### ISSUE TITLE
secret key issues

### ISSUE THREAD

**Issue by bestinthewest** [Legedric/ptmagic#297]
Hi guys can anyone help. i deleted my profit trailer to download the latest one. once i go back into binance i can get my api keys but it wont show my secret key and there is no icon to click on, to remove the block on it.

**Comment by Legedric** [comment]
This is the GitHub for Profit Trailer Magic, an addon for Profit Trailer. We cannot help with PT issues.

**Comment by bestinthewest** [comment]
ok no problem could you point me in a direction where someone could help
please . thanks legedric

**Comment by Legedric** [comment]
Best would be here:
https://github.com/taniman/profit-trailer/issues

Or on the PT Discord

**Comment by bestinthewest** [comment]
thank you :)
