### ISSUE TITLE
some links not valid to tradingview

### ISSUE THREAD

**Issue by angelsomar** [Legedric/ptmagic#298]
Hello this is not much inconvenience but I think it would be good to take action on these generated links that are not valid, you have to reverse the order of the symbols of the pair

https://www.tradingview.com/chart/?symbol=BINANCE:BTCETH
BTC Market

https://www.tradingview.com/chart/?symbol=BINANCE:USDTBTC
USDT MArket

https://www.tradingview.com/chart/?symbol=BINANCE:USDTETH
USDT Market

**Comment by Legedric** [comment]
Thanks, I will check this.

**Comment by Legedric** [comment]
I checked this and for me the links are all correct. The main market (USDt, BTC and ETH) is always appended at the end.

Where do you see those links? Can you please provide a screenshot?

**Comment by angelsomar** [comment]
![image](https://user-images.githubusercontent.com/36096512/37242690-d47f2560-243b-11e8-9f2c-27d49758f377.png)

![image](https://user-images.githubusercontent.com/36096512/37242711-26167c84-243c-11e8-8cd1-b9ae0204f80b.png)

![image](https://user-images.githubusercontent.com/36096512/37242724-527dda56-243c-11e8-8de9-6cde098b8d45.png)

**Comment by Legedric** [comment]
Thanks, this will be fixed in the next release.
