### ISSUE TITLE
MAC OS help

### ISSUE THREAD

**Issue by michaeltietjen** [Legedric/ptmagic#30]
Can't get this to run on Mac...any decent guide? The directions are lacking in information.

**Comment by cyptog7** [comment]
What errors are you getting ? 

Have a look at the wiki and follow the guide 
[https://github.com/Legedric/ptmagic/wiki/Setup-PT-Magic-on-MacOS](url)

**Comment by michaeltietjen** [comment]
dotnet PTMagic.dll
pause

**Comment by michaeltietjen** [comment]
o executable found matching command "dotnet-PTMagic.dll
/Users/Mike/Desktop/PTMagic 1.0.2/PTMagic/Start PTMagic.cmd: line 2: pause: command not found
logout
Saving session...
...copying shared history...
...saving history...truncating history files...
...completed.

[Process completed]

**Comment by michaeltietjen** [comment]
2018/02/19 14:30:15.719 FATAL - Error loading configuration! System.IO.FileNotFoundException The configuration file 'settings.general.json' was not found and is not optional. The physical path is '/Users/Mike/Desktop/ProfitTrailer/settings.general.json'.    at Microsoft.Extensions.Configuration.FileConfigurationProvider.Load(Boolean reload)
   at Microsoft.Extensions.Configuration.ConfigurationRoot..ctor(IList`1 providers)
   at Microsoft.Extensions.Configuration.ConfigurationBuilder.Build()
   at Globals.SystemConfiguration.LoadSettings(String basePath) in D:\Tools\PTMagic\Globals\SystemConfiguration.cs:line 24
   at PTMagic.Program.Main(String[] args) in D:\Tools\PTMagic\PTMagic\Program.cs:line 41

Unhandled Exception: System.IO.FileNotFoundException: The configuration file 'settings.general.json' was not found and is not optional. The physical path is '/Users/Mike/Desktop/ProfitTrailer/settings.general.json'.
   at PTMagic.Program.Main(String[] args) in D:\Tools\PTMagic\PTMagic\Program.cs:line 59
Abort trap: 6
michaels-mini:ProfitTrailer Mike$

**Comment by jamesblackjr** [comment]
The wiki does not say that the file should be copied/moved from the "_default settings" folder to the "PTMagic" folder location.  I would suggest putting these in the correct location by default.

**Comment by cyptog7** [comment]
@michaeltietjen Am I correct to assume your trying to load the monitor?  in the /monitor/appsettings.json needs to point to the '/Users/Mike/Desktop/PTMagic'

**Comment by cyptog7** [comment]
Strange, I followed their instructions and got magic working on my Mac workout any issues.

**Comment by michaeltietjen** [comment]
You want to teamview my set up? not sure where I've gone wrong
