### ISSUE TITLE
[Bug]Recreating of Market Data not reflected in Dashboard Graph

### ISSUE THREAD

**Issue by smoochy** [Legedric/ptmagic#300]
Hi there,

I recently switched from BTC to ETH market.

For this I deleted everything inside `_data` folder (thx for the hint again, Legedric).
After starting up PTM for the first time, it recreated market data for the last 96 hours (as set in settings.analyzer.json, which took a while).
When opening up PTMMonitor, I was presented with just flat lines for my markets (it looked like everything left from the 21:13 timestamp):

![market](https://user-images.githubusercontent.com/34371932/37247681-4a3831ce-24bf-11e8-9965-8fe1406f50d5.jpg)

PTMMonitor showed values for my exchanges in MARKET TRENDS chart though.

Is it supposed to not represent the past market data in the graph?

**Comment by Legedric** [comment]
It should have recreated the data for your 96h. How many ticks did the log say did it recreate? Should be 5760

**Comment by smoochy** [comment]
> 2018-03-08 22:39 +01:00: 2018/03/08 22:39:22.280 INFO - Binance - Our nanobots are still at work, hang on... 5700/5760 ticks done... 
> 2018-03-08 22:39 +01:00: 2018/03/08 22:39:22.584 INFO - Binance - Initial market data created. Ready to go! 


Yes, it did 5760 ticks according to the logfile. If you want to, I can send you the file, if you are interested?

**Comment by Legedric** [comment]
So according to your logfile it took 36 minutes to create the data? Seems ok.

I will have to test this myself for such a long timeframe (96h) and see what it comes up with.

**Comment by Legedric** [comment]
So I finally had some time to get back to this issue. You are correct. When you start with fresh data, the graph there will not be populated with the "recreated" data.

This is the case for performance reasons as when you first start the bot and recreate data for 24 or even 96 hours PT Magic would have to go through every single tick in that timeframe and build the trend percentages to have that graph.

To avoid making the first starting even longer than today we did not want to do this and "live" with the fact that the graph will get populated with data as you use PTM over time.

**Comment by smoochy** [comment]
Thanks for taking the time to research and explaining.
