### ISSUE TITLE
Listening IP address for PT Magic Monitor

### ISSUE THREAD

**Issue by nstefi** [Legedric/ptmagic#301]
When you start PT Magic Monitor, in the console it says:
Now listening on: http://0.0.0.0:5000
When I try that on Windows it gives an error page, and I always have to replace it with:
http://localhost:5000
Can you change in the console to say the address with localhost instead?

**Comment by Legedric** [comment]
No, http://0.0.0.0:5000 is just a normal placeholder for "http://anything:5000" So if I change that to http://localhost:5000 it would only listen on that and nothing else.

**Comment by nstefi** [comment]
You don't have to change it internally in the bot what address it listens to, but can you change what's shown in the command line (console window)? So people can copy/paste the URL from there to the browser and it works. Currently when you copy/paste http://0.0.0.0:5000 it doesn't work, and you need to change the address to http://localhost:5000 (or if you access remotely, you change to the public address).

**Comment by Legedric** [comment]
No, the address gets posted into the command line from the Kestrel server itself.

**Comment by nstefi** [comment]
OK, thanks.
