### ISSUE TITLE
PTMagic need too much CPU

### ISSUE THREAD

**Issue by kwieser76** [Legedric/ptmagic#305]
HI

I have a problem with the PTMagic

PTMagic need more than 150% of the CPU from my VPS
[ 2] PTMagic     Mem: 243 MB    CPU: 180 %

VPS data: Intel® Xeon® CPU E5520 @ 2.27GHz

**Comment by Legedric** [comment]
Please provide the following information so we arei able to investigate this:
- What OS?
- Is the usage constant or only during a "run" of the bot (which usually takes some seconds)?
- Did you have your monitor open in a browser (not on ythe VPS, just anywhere)?
- Did you try running ONLY the bot or ONLY the monitor to see which of the two causes this?

**Comment by kwieser76** [comment]
What OS?
- Linux
Is the usage constant or only during a "run" of the bot (which usually takes some seconds)?
- if it run than up to 180% if it not run around 98 - 99%
Did you have your monitor open in a browser (not on ythe VPS, just anywhere)?
-NO
Did you try running ONLY the bot or ONLY the monitor to see which of the two causes this?
- run both

**Comment by Legedric** [comment]
What version of libcurl is installed on your machine (if any)?

**Comment by kwieser76** [comment]
root@euve260664:~# curl-config --version
-bash: curl-config: command not found

**Comment by Legedric** [comment]
What version of PT Magic are you running? Did this problem occur with the most recent version or did you encounter it already before that?

**Comment by kwieser76** [comment]
Version 1.2.2

**Comment by Legedric** [comment]
I had just the same issue with another user an on his machine curl 7.47 something was running and an upgrade to curl 7.50 fixed the issue.

I found out that there seems to be a bug in curl/libcurl <7.50.

Even if libcurl/curl is not installed on your machine you may want to install it to see if it fixes the issue, because internally .NET Core seems to use libcurl if it is available on the machine on Unix based systems.

**Comment by Legedric** [comment]
We added this to our wiki, please see if it solves the issue for you as well:
https://github.com/Legedric/ptmagic/wiki/Common-Errors#high-cpu-usage-on-unix-systems

**Comment by stevenshizzleh** [comment]
FYI applied recommendation and verified curl 7.50.3 is installed. Seems like PTMagic is still using a fair proportion of my CPU, but not sure what's expected. Just thought I'd share

```
$ curl --version
curl 7.50.3 (x86_64-pc-linux-gnu) libcurl/7.50.3 OpenSSL/1.0.2g zlib/1.2.8

$ cat /proc/cpuinfo | head

processor	: 0
vendor_id	: GenuineIntel
cpu family	: 6
model		: 63
model name	: Intel(R) Xeon(R) CPU E5-2676 v3 @ 2.40GHz
stepping	: 2
microcode	: 0x3b
cpu MHz		: 2400.058
cache size	: 30720 KB

$ top

  PID %MEM    VIRT    RES   CODE    DATA    SHR nMaj nDRT %CPU COMMAND                                                                
 1371 34.1 2635036 346404      4 2564540  14640  105    0 38.3 java                                                                   
 1447 22.2 7017644 225604    100 6834888  60420  177    0  0.0 dotnet                                                                 
 2113 11.6 2869568 117388    100 2717500  44996    4    0 61.1 dotnet

$ ps -ef | grep 2113 | grep -v grep
ubuntu    2113  2112 59 22:29 ?        00:18:00 dotnet PTMagic.dll


```

**Comment by Legedric** [comment]
Well, for me it is extremely hard to find something about this as I am no Unix expert and on Windows PTM is getting up to around 40% CPU usage during a run and then goes back to 0% when it is waiting for the next interval.

**Comment by stevenshizzleh** [comment]
Doesn't seem to be ruining anything for me. I'm running this on an AWS EC2 instance and haven't noticed a slow down resulting from excessive CPU usage.

**Comment by Legedric** [comment]
The increase in COU usage with 1.3x should be resolved in the next release.
