### ISSUE TITLE
Monitor Last Runtime Showing Incorrect Info?

### ISSUE THREAD

**Issue by stevenshizzleh** [Legedric/ptmagic#307]
PTMagic Site Reporting Last Runtime 9m 39s ago, but it appears to be running based on timestamps and log entries. I have the app set to refresh every 2 minutes instead of every 1, only difference from the baseline that could skew things.

The only curious thing is the last line of this ticket, which shows "WARN - PTMagic already raidning since 3/12/18 10:41:38 PM - Process frozen? Checking things..."

---------------------------

```
$ /var/opt/PTMagic/_logs$ date
Mon Mar 12 22:45:27 EDT 2018

$ ls -l /var/opt/ProfitTrailer/trading/PAIRS.properties
-rw-r--r-- 1 ubuntu ubuntu 74429 Mar 12 22:42 /var/opt/ProfitTrailer/trading/PAIRS.properties

$ ls -l /var/opt/PTMagic/_data/LastRuntimeSummary.json
-rw-rw-r-- 1 ubuntu ubuntu 2759835 Mar 12 22:41 /var/opt/PTMagic/_data/LastRuntimeSummary.json

$ ls -ltr /var/opt/PTMagic/_data/CoinMarketCap/ | tail -1
-rw-rw-r-- 1 ubuntu ubuntu 14738 Mar 12 22:41 MarketData_2018-03-12_22.41.39.json

$ tail -5 $(ls -1tr /var/opt/PTMagic/_logs | tail -1)
2018/03/12 22:42:08.780 INFO - Summary: Market trends saved. 
2018/03/12 22:42:08.780 INFO - Summary: Getting current global properties... 
2018/03/12 22:42:15.916 INFO - Summary: Current global properties saved. 
2018/03/12 22:42:16.075 INFO - Summary: Getting current single market properties... 
2018/03/12 22:43:38.045 WARN - PTMagic already raidning since 3/12/18 10:41:38 PM - Process frozen? Checking things... 
```

**Comment by Legedric** [comment]
So does iti start a new run after this warning or does it get stuck there?

**Comment by stevenshizzleh** [comment]
It started a new run. Watching the monitor as I type. It hangs on "INFO - Summary: Getting current single market properties..." for quite some time. In the past, it got to the "magicbots/cryptodragons summary" pretty quickly.

**Comment by Legedric** [comment]
How many lines does your pairs props have? Seems like may have quite a lot of lines for single markets?

**Comment by stevenshizzleh** [comment]
/PTM/_presets/Default/PAIRS.properties = 60 lines
/PT/trading/PAIRS.properties ~ 1000 lines

**Comment by Legedric** [comment]
Yeah that's what I thought. I will check this, thanks!

**Comment by stevenshizzleh** [comment]
FYI just downgraded to 1.2.2 and it's running without the delay. I had to downgrade because it got so bad it was 22 minutes behind according to Monitor and I didn't want to take the risk on a market setting being active for a coin pair that shouldn't be. Hope this helps. 

2018/03/15 22:15:29.372 INFO - Summary: Getting current global properties... 
2018/03/15 22:15:29.527 INFO - Summary: Current global properties saved.

**Comment by Legedric** [comment]
The delay is there because we changed the behaviour of how single market settings are being handled in 1.3.0.

Before 1.3.0 they were not able to add up/extend each other and ater 1.3.0 they do. I assume you are running lits of single market settings in your file where multiple settings are able to get triggered for each coin together, right?

**Comment by stevenshizzleh** [comment]
Correct. And as I go back to 1.2.2, I notice only one setting is effective for each pair. Whereas in 1.3.0, multiple single market settings can be in place for a pair. Sounds like this might be resolved by StopProcessWhenTriggered.

**Comment by Legedric** [comment]
@stevenshizzleh Yes and I will work on another improvement regarding single market settings during the weekend so that it doesn't write multiple instances of the same variable for the same coin liek for example multiple times ZILBTC_trading_enabled = false/true

**Comment by Legedric** [comment]
Oh and by the way I am doing this using your settings for testing as they have more options than the default ones ;)

**Comment by stevenshizzleh** [comment]
Ahhh awesome!!!

**Comment by stevenshizzleh** [comment]
@Fransenson -- Telegram @stevenshizzle is another way of getting a hold of me :)
