### ISSUE TITLE
Market Analyzer - Active Single Settings "Orange Triangle" hover breaks on sort

### ISSUE THREAD

**Issue by stevenshizzleh** [Legedric/ptmagic#308]
1. Open Market Analyzer
2. Find a market with an active single setting. Hover over the orange triangle. A pop-up appears.
3. Sort by another column. Hover over the orange triangle. Pop-up does not appear.

Safari Version 11.0.3 (13604.5.6)
MacOS 10.13.13

On a side note, I wanted to tell you that PTMagic is absolutely magic! I spent a lot of time looking for "what does a good coin pair look like". I created multiple trends, trying to isolate good situations from bad, and this thing has been rocking it. Thank you so much for creating such a kick-butt program. I can tell you the folks in other communities who have turned away from this are missing out on a truly amazing opportunity.

**Comment by smoochy** [comment]
Can confirm. Same behaviour.

Windows 10. Chrome 65.0.3325.146.
Switching to the Relative tab and back to the Absolute tab brings back the pop-up.
