### ISSUE TITLE
Requested Setting: applyFirstSingleMarketSettingOnly

### ISSUE THREAD

**Issue by stevenshizzleh** [Legedric/ptmagic#309]
I have a few different single market trends that I'm using to characterize the "aggressiveness" of a coin. Let's call them "very bullish", "bullish", "well behaved". Ideally, I'd like my "very bullish" settings to be applied, but they are all being applied in the order in which they appear in settings.analyzer.json. This means the settings for "well behaved" are in effect, superseding those of "very bullish".

I realize I could try to "box" the settings in by use of MinChange and MaxChange, but it's proving hard to do for some of the single market settings. This is because one setting might look at the longer term "health" of a pair, while another setting looks at mid to short-term health of a pair. Thus, some of the market trends in one single market setting do not necessarily apply in another single market setting.

Request a setting to enforce the application of only the first single market setting that evaluates to TRUE, instead of each setting that evaluates to TRUE.

**Comment by Legedric** [comment]
This is from the 1.4.0 release notes (release is not ready but just to show you how it will work:
- Added a new setting "StopProcessWhenTriggered" to settings.analyzer.json for single market settings. If you set this to "true" the process will stop processing other single market settings as soon as this setting got triggered #309 

```
{
  "SettingName": "BlacklistNewCoins",
  "StopProcessWhenTriggered": true,
  "TriggerConnection": "OR",
  "Triggers": [
    {
      "AgeDaysLowerThan": 14
    }
  ],
  "PairsProperties": {
    "ALL_trading_enabled": false,
    "ALL_sell_only_mode": true,
    "ALL_DCA_enabled": false
  }
}
```

**Comment by stevenshizzleh** [comment]
You are AWESOME.
