### ISSUE TITLE
No market trend found! The pair may have got delisted from your exchange!

### ISSUE THREAD

**Issue by ShiftLizard** [Legedric/ptmagic#310]
I tried switching from BTC to ETH pairs, but I keep getting this error "No market trend found! The pair may have got delisted from your exchange!" in the Market Analyzer. And it says "WARN - No market trend changes found for 'Exchange1h'! Trigger ignored!" in Start PTMagic. Can we not use PTMagic for ETH pairs or do I need to set something up for this to function properly?

Thanks.

**Comment by Legedric** [comment]
You can use it for ETH of course.

Did you reset your exchange data before you switched?
https://github.com/Legedric/ptmagic/wiki/Reset-PT-Magic-Exchange-Data

Otherwise your old BTC data will cause conflicts with your new ETH data.

**Comment by ShiftLizard** [comment]
Yes, that worked. Thank you very much once again :)

**Comment by ShiftLizard** [comment]
Is there anyway to HotConfig to tell PT how many times a pair has DCA?
