### ISSUE TITLE
[Feature Request/Enhancement] BTC Exchange Price triggers

### ISSUE THREAD

**Issue by mightysoul** [Legedric/ptmagic#311]
I'm using below config for coinmarketcap data for BTC price to avoid BTC pumps or dumps. However, when I change Platform to "Exchange", it messes market analyzer prices. Since coinmarketcap is refreshed every 5mins, I'm not able to avoid BTC price pump/dump. If I can make a trigger for BTCUSDT it would be groundbreaking feature for me. 

{
          "Name": "BTC1h",
          "Platform": "CoinMarketCap",
          "MaxMarkets": 1,
          "TrendMinutes": 60,
          "TrendCurrency": "Fiat" // Trend Currency to build the trend against. If set to "Fiat", the trend will take the USD value of your main currency into account to build the trend. (Allowed values are: Fiat, Market)
        }

**Comment by nick-ratbert** [comment]
+1 for me. In general it would be useful to be able to build a trend for any coin pair. BTCUSDT would be good, but so would ETHUSDT. I can only imagine what other interesting pairs people might find.

Thanks.

**Comment by JHenneberg** [comment]
this would be definetly very usefull. +1
