### ISSUE TITLE
Version on update to 1.3.1

### ISSUE THREAD

**Issue by siquenique** [Legedric/ptmagic#312]
Hi,

I've updated the PTMagic to version 1.3.1 but in the monitor i can still see the message that is outdated and i am using 1.2.2.

**Comment by Legedric** [comment]
Did your PT Magic bot finish its first run after the update?

**Comment by siquenique** [comment]
No, is still recreating the Binance market.

**Comment by Legedric** [comment]
Then wait for it to finish. The version will be written to the monitor once the first run completes.

**Comment by siquenique** [comment]
You can close, you are right updated and is fine. Thank you
