### ISSUE TITLE
Exclude main currency

### ISSUE THREAD

**Issue by Ichy84** [Legedric/ptmagic#313]
Hey,

Is the option exclude main currency available only in general and not for single market settings (to the moon, tanking down...). I would like to see what Bitcoin is doing and what the market without Bitcoin is doing.
Thank you.
Br, Ichy
P.S.: you are doing a really great job

**Comment by Legedric** [comment]
The exclude main currency setting only works for CoinMarketCap.

As on your exchange the trends only cover your main market pairs anyway and there doesn't exist and BTCBTC for example.

However, separate triggers for the main currency will be implemented in a future release so you may build triggers specifically for your main currency ups and downs.
