### ISSUE TITLE
Spelling mistake

### ISSUE THREAD

**Issue by awhitford** [Legedric/ptmagic#314]
Very minor...

> In simple mode the DCA calculator will only take your number of pairs, DCA levels and max cost and  will calculate the necessary fundings for you. In this mode the ANDERSON DOUBLEDOWN method is  quite inaccurate as wit will calculate the DCA steps by doubling the cost for each DCA level, regardless of what level the price may be at the time the DCA buy will happen.

The *wit* should be *it*:
> ...quite inaccurate as **it** will calculate...

**Comment by Legedric** [comment]
Thanks, will be fixed in the next release.
