### ISSUE TITLE
Add Volatility and Volume for Single Markets

### ISSUE THREAD

**Issue by Bend3smo** [Legedric/ptmagic#315]
Pt feeder just added these features. It would be nice to see them here too.

PT Feeder calculates the volatility of each coin to be used in multiple places.

It does this by looking at all the five minute candles over the period defined in MinutesToMeasureTrend. For example, if MinutesToMeasureTrend was 60 in appsettings.json, then it would use 12 candles for the calculation.

It then takes the open price and the high price to see what was its upside movement of each of these and then gets an average of all the candles in that period. This is what PT Feeder calls the upside volatility. The same applies for the open and low price and is what PT Feeder calls the downside volatility.

**Comment by Legedric** [comment]
Sorry, not gonna happen in PT Magic (anytime soon).

We built PT magic to change settings based on transparent behaviours and for any user to be able to see and comprehend why PTM changed what setting to whatever value based on simple trend values.

We do not want to apply settings that barely anyone is able to track and fully understand.

**Comment by Legedric** [comment]
Oh, regarding volume:
We are working on volume triggers but it will take some more time get these done.

**Comment by Bend3smo** [comment]
What about the possibility to Look at a specific time frame of a coin and its Change in this time frame. 

B----A----NOW

At the moment we can Look at a time frame from A to now or from B to now.
Id Like to Look at a coins change in the time frame A to B.

**Comment by smoochy** [comment]
Well, actually I think this is a very interesting feature to have. It could be used for dynamically adjusting trailing, specificially tailored for each coin.

If a coin is know for being volatile, a higher trailing makes much more sense in regarding to when to buy, when to dca and when to sell.
Having a low trailing for such a coin could mean that you buy too early, buy too early into dca (when coin is dropping even more) and sell too early. So having a higher trailing makes more sense.

If a coin has a low volatility, having a lower trailing would be much more important. As it will never do the bigger swings.

Maybe you could reconsider this :)
