### ISSUE TITLE
Balance prediction

### ISSUE THREAD

**Issue by mfactor50** [Legedric/ptmagic#316]
Not seeing any data in the Sale Analyzer Balance Prediction.

**Comment by Legedric** [comment]
Screenshot please...

**Comment by Legedric** [comment]
Closing as no feedback provied for more than 3 days now.

**Comment by Legedric** [comment]
Did you enter your Starting Balance in your settings.general.json?

**Comment by mfactor50** [comment]
No I did not.  I had been using profit trailer for about a month and a half... and had put about 10 different deposits in. Should I just add up all my deposits and use that?

**Comment by Legedric** [comment]
You can do that but you still need to enter a start balance, otherwise you will have divisions by zero here and these will lead to infinity as a result.
