### ISSUE TITLE
PT Magic unable to get data from binance?

### ISSUE THREAD

**Issue by bitnick21** [Legedric/ptmagic#317]
hi, have been using pt magic for about a month now. my computer crashed, after i restarted pt magic it keeps doing this. i have restarted many times but it keeps doing this. i have reinstalled pt magic and this fixed the problem. i guess something has corrupted? i wasn't sure if it had something to do with my logs being so big (over 1gb) even though the error says it is unable to contact binance? is it possible to remove old logs? thanks.

![untitled](https://user-images.githubusercontent.com/36960786/37482949-6b066530-287d-11e8-9618-8ecb8a0ffe36.jpg)

**Comment by Legedric** [comment]
Yes, you can remove old logs and if you use the nlog.config file from the current release (located in _default settings) you shouldn't get such large logfiles again.

So the error is gone now, right?

**Comment by bitnick21** [comment]
yeah i reinstalled pt magic and it works fine now. wasn't sure if it was the crash or a problem with pt magic. thought i would mention it just in case there was a problem. as always thanks for the super fast reply!
