### ISSUE TITLE
incorrectly calculated global trend 48H

### ISSUE THREAD

**Issue by clippart** [Legedric/ptmagic#320]
Hello!

have the following settings

        {
          "Name": "Exchange48h",
          "Platform": "Exchange",
          "MaxMarkets": 50,
          "TrendMinutes": 2880,
          "TrendCurrency": "Market"
        }

          {
            "MarketTrendName": "Exchange48h",
            "MarketTrendRelation": "Absolute",
	    "MinChange": -10,
            "MaxChange": 10
          }	
BTC-MUE - Current active setting: 'AllowTrading'
Matching triggers:
Exchange1h -  - Min: -7.00% - Max: 10.00%% - TrendChange (Absolute) = -2.05%
Exchange12h -  - Min: -10.00% - Max: 10.00%% - TrendChange (Absolute) = -2.69%
Exchange48h -  - Min: -10.00% - Max: 10.00%% - TrendChange (Absolute) = -8.18%
BTC-MUE_trading_enabled = true

but if we look at the graph of the pair....48H +20% min
![1](https://user-images.githubusercontent.com/33903011/37503921-d2761e3c-290d-11e8-9a83-84c2f7fcd21d.PNG)

**Comment by Legedric** [comment]
Can you please ZIP and upload your settings..analyzer.json here so I can investigate this issue better? Thanks!

**Comment by clippart** [comment]
Of course. I also attach a log that we received when we tried to apply a trigger 4
[settings.analyzer.zip](https://github.com/Legedric/ptmagic/files/1819137/settings.analyzer.zip)
8h
Thanks!

**Comment by clippart** [comment]
1.4.0
![default](https://user-images.githubusercontent.com/33903011/37875692-245bac88-306d-11e8-9dee-e2b647c9d1f0.PNG)

**Comment by Legedric** [comment]
Sorry first of all for the delay on coming back to this issue.

So when I look at your settings I can see that your setting for "StoreDataMaxHours" is set to 24. So you only store trend data for 24 hours but you want to build trends for 48h  hours, which of course does not work as the data simply gets deleted after 24h already.

When you set your StoreDataMaxHours to 48h, the trends will start showing up correctly.
