### ISSUE TITLE
Old link to Market Trends on Dashboard

### ISSUE THREAD

**Issue by tufts2003** [Legedric/ptmagic#321]
Hi Legedric, firstly thanks for the great effort with PTM.  It's a great resource for the community.

The issue I wanted to report was simply a broken / old link on the dashboard in v1.3.1.  In the "PTMagic Status" section of date, the last row is "Active Single Settings".  There is a information "i" icon to the right of this row, it links to the old Market Trends page vice the new Market Analyzer page.  Simple fix, but figured I'd report it.

Thanks!

**Comment by Legedric** [comment]
Thanks, that is already fixed for the next release.
