### ISSUE TITLE
Not using ALL_ prefix on pairs properties does not work (seen in 1.2.2)

### ISSUE THREAD

**Issue by stevenshizzleh** [Legedric/ptmagic#322]
Seen in: PTMagic 1.2.2
Exchange: Binance
Reference: https://github.com/Legedric/ptmagic/wiki/Single-Market-Settings

When dropping the 'ALL_ prefix', the PAIRS.properties entries will appear similar to the following:

ICXETHsell_only_mode = true

Should appear as:

ICXETH_sell_only_mode = true

Once I put ALL_ back onto each of the settings, the PAIRS.properties entries were corrected. If this issue has been fixed since 1.2.2, please disregard.

**Comment by Legedric** [comment]
Thanks, that issue still existed in the current release. Just fixed it now :)
