### ISSUE TITLE
Nested conditions for single market conditions  

### ISSUE THREAD

**Issue by cryptotamilan** [Legedric/ptmagic#324]
Optinto have nested conditions in the single market settings would be very useful,ex: exchange1H>1 and(exchange2h<. 5 or exchange3h<. 7). If this would help analyze marker trends in a better by deciding based on any one positive trend but at த same time make sure it matches a critical trend criteria

**Comment by cybermizrach** [comment]
I think we use have an ability to use combined AND & OR operator and groupings of conditions such as

((Exchange1H >3 OR Exchange 3H > 3) AND  (Exchange 30M < Exchange 1H))

**Comment by Legedric** [comment]
Duplicate of #175
