### ISSUE TITLE
BTC-Market not monitoring

### ISSUE THREAD

**Issue by Nephor80** [Legedric/ptmagic#325]
Hi! 
My setting:
 "AnalyzerSettings": {
    "MarketAnalyzer": {
      "StoreDataMaxHours": 24, // Number of hours to store market data
      "IntervalMinutes": 1, // Interval in minutes for PTMagic to check market trends and triggers
      "ExcludeMainCurrency": false, // Excludes the main currency (for example BTC) from market trend analysis
      "MarketTrends": [
        {
          "Name": "BTC1h", // UNIQUE market trend name (to be referenced by your triggers below)
          "Platform": "Exchange", // Platform to grab prices from (Allowed values are: CoinMarketCap, Exchange)
          "MaxMarkets": 1, // Number of markets/pairs to analyze sorted by 24h volume
          "TrendMinutes": 60 // Number of minutes to build a trend (1440 = 24h, 720 = 12h, 60 = 1h)

ist not monitoring BTC, it is monitoring DGD as the highest volume-coin. How is it possible to monitor BTC and defining triggers on it for single-market-settings? CMC as single-market-setting isn't allowed.
My basic idea was to monitor each single coin vs BTC and defining different strategies via the 1h, 3h and 6h relative trend. Maybe I am wrong and this is solved via the simple absolute value?

THX

**Comment by Legedric** [comment]
There is currently no way to build a trend for your main market using Platform "Exchange" as all markets in this trend would need to be related to your main market and there doesn't exist a market for BTC-BTC.

Furthermore you can only measure a trend of a single coin relative to the overall trend.

For example when you use the default settings there is a 12h trend over ALL of your traded pairs/markets.
When you setup a trigger for a single market it will look at the trend for every single market relative to THIS overall average trend acorss all markets.
So there is no way to set a single coin trend into any relation to the main market trend (for example BTC).

**Comment by Nephor80** [comment]
Thanks!

**Comment by Nephor80** [comment]
Ok, so I see my mistake. I think what I am searching for is the absolute value. Want my settings to change if a single coin drops for example 3% in 3hrs and 5% in 6hrs to Bollinger Bands, the rest of the Market is not important for me. This is, as I understood the classic absolute value.
