### ISSUE TITLE
new version auto update feature 

### ISSUE THREAD

**Issue by cryptomail2018** [Legedric/ptmagic#326]
is it possible to make the PT Magic which is really fantastic to have a auto update feature build in so with a click of a button on the main screen or in automated intervals will look for PT Magic updates and apply accordingly , it be really handy to have as for example i work offshore and not have internet and no control of my main PC at home neither i have the ability to login to the VPS , this way i can be assured all updates are done and i don't have to worry. this is just my personal view but im sure there are many more people like the same .. 
for the rest im very impressed over and above the feeder

**Comment by Legedric** [comment]
It is versy unlikely to happen as this would require the web application to stop and restart the main bot and itself which is quite something to achieve on a cross platform basis I believe.

**Comment by BaGRoS** [comment]
Maybe https://bitbucket.org/cryptopopolis/profittrailer/wiki/Home
easy peasy lemon squeezy

**Comment by securitygeneration** [comment]
I would like this too, and I'm sure we could make it work across Windows, Linux and macOS.

But if a full auto-update is not possible, I'd love a script that at least downloads the latest PTMagic files and overwrites them in the local directory, even if the stopping/starting of the bot is left to me. But it reduces number of steps significantly.

1. User stops PTMagic
2. User runs auto-update script that downloads latest archive from GitHub, unzips and updates relevant files
3. User restarts PTMagic

Probably 30 seconds flat.
