### ISSUE TITLE
pt Magic 1.3.1 issue

### ISSUE THREAD

**Issue by cryptomail2018** [Legedric/ptmagic#327]
on 1 download PTMAGIC 1.3.1 i have the ability to make manual adjustments in the drop down feature of the dashboard and on the other download of PTMAGIC 1.3.1 i am not able to do so as it is just not on the dashboard . 
![ptmagic 1 3 1 with settings](https://user-images.githubusercontent.com/35930742/37520794-0751c62c-2951-11e8-8c23-cd9f9a0817d0.PNG)
![ptmagic 1 3 1 without settings option](https://user-images.githubusercontent.com/35930742/37520795-07872434-2951-11e8-96c0-f973dd6d8ce2.PNG)

**Comment by Legedric** [comment]
The "settings" menu is only available when you set IsPasswordProtected to true for your monitor in your settings.general.json
