### ISSUE TITLE
No indication or alert when "Terminating process..."

### ISSUE THREAD

**Issue by awhitford** [Legedric/ptmagic#329]
I noticed that PTM was reporting that BTC is valued at $8,489.66.  Meanwhile, Coinbase has it at $7895.01...  I then checked the log and noticed:

> 2018/03/16 22:31:12.164 ERROR - No valid pairs found for main market 'BTC' in configured pars list ()! Terminating process...

So, part of PTM had died hours ago, but I didn't know.  It would be nice if there was an indication on the UI, a Telegram message was sent, or the logic be updated to not die.

BTW, I am using Bittrex.

**Comment by Legedric** [comment]
1. Coinbase and Bittrex barely have the same prices and PTM fetches the price from your exchange (Bittrex).
2. There is an indicator on your monitor and when PTM did not fully complete a run for more than X minutes (depending on your interval) the green heart symbol will turn into a red bolt with a tooltip saying you should check PTM's logs.
