### ISSUE TITLE
ERROR ON OPEN, DOES NOT WORK HELP ME

### ISSUE THREAD

**Issue by sitespagando** [Legedric/ptmagic#33]
I did the whole procedure according to the wiki, I installed everything I needed, I followed the manual, but only from error when I open it, can anyone help me please? follows the error that I have attached, I already tried everything and nothing to give RIGHT
![1](https://user-images.githubusercontent.com/36615066/36362501-2fbb539a-1514-11e8-8cd0-a0416a5144a4.jpg)

**Comment by Legedric** [comment]
It seems like there is something wrong in your settings.general.json file.  
Please make sure you are using doublw backslashes in any path if you are running it on windows, so like this:  
`C:\\Profit Trailer\\`

**Comment by Arararararagi** [comment]
Oi Rafael,

If you check the log carefully, it says "use double backlashes for windows." So the ProfitTrailerPath should be "C:\\Users\\Rafael\\Desktop\\ProfitTrailer\\". That might be it.

**Comment by sitespagando** [comment]
THANK YOU SO MUCH ! CORRIGI AND IT WORKED! CONGRATULATIONS YOU ARE TOO !!!!!
