### ISSUE TITLE
Getting the Sales List details just hangs

### ISSUE THREAD

**Issue by calebcall** [Legedric/ptmagic#330]
It looks like on the Sales Analyzer page, if you click a date or month, it just hangs.  I can see it's not applying the root url correctly to that call:

![screen shot 2018-03-17 at 11 37 35 pm](https://user-images.githubusercontent.com/1132262/37563003-4c2fa296-2a3c-11e8-8350-25c0bea6d8e5.png)

![screen shot 2018-03-17 at 11 33 29 pm](https://user-images.githubusercontent.com/1132262/37562987-aa01eeac-2a3b-11e8-9e02-405fe79111d9.png)

![screen shot 2018-03-17 at 11 34 16 pm](https://user-images.githubusercontent.com/1132262/37562989-be41c450-2a3b-11e8-86b0-0ba63c8ca360.png)

I'm on version 1.3.1. (hope this isn't a repeat, I did try searching and didn't find anything)

**Comment by Legedric** [comment]
Thanks, I fixed this for the next release.
