### ISSUE TITLE
[Feature] Active Single Market Settings

### ISSUE THREAD

**Issue by HojouFotytu** [Legedric/ptmagic#333]
Currently the command window shows "Active single market settings: X"

Would it be possible to break this down to show each single market setting (excluding those that are not active on any pairs)?  Eg:

Active single market setting (PumpAndDump Protection): 5
Active single market setting (FreefallBlock): 2

or

Active single market settings:
PumpAndDumpProtection:  5
FreefallBlock: 2

AND

Add this to the top (or bottom) of the market analyzer page?

**Comment by CryptoThriver** [comment]
Is there a way to put a buying timeout for a pair.   

If a pair is a pump and dump- the pair triggers the Min Change in the 1 hour- but it might take 2 or 3 days for the numbers get back to a safe buy.  With PT Magic- we can build several market trends which is fantastic!  Having too many Market trends can get clunky too. 

A Pump and a dump possible function trigger.  
"MarketTrendName": "Exchange1h"
MaxChange = 10
"MarketTrendName": "Exchange6h"
MaxChange = 10
"MarketTrendName": "Exchange24h"
MaxChange = 10

"PairsProperties": {
All_trading_enabled = false 
buying_time_out = 4320  (The time would be editable by the user-I think I would go for 3 days)
ALL_DCA_enabled = false
The clock starts from the time the trigger is hit.  
![image](https://user-images.githubusercontent.com/36651087/37815948-449b800e-2e2e-11e8-8b68-147fd2eccb23.png)

Then if we could have what @HojouFotytu suggested with the indicators, it would give us a chance to build a working reputation for coins, and build a blacklist.


Again- Thank you for all your efforts!

**Comment by Legedric** [comment]
I don't think that PT supports that. But we are currently discussing adding something that will take care of this, although we do not want to post any details on that right now. 😃

**Comment by HojouFotytu** [comment]
I feel hijacked...    I don't see how @CryptoThriver 's post has anything to do with the OP.    ;)
