### ISSUE TITLE
Dotnet has stopped working

### ISSUE THREAD

**Issue by nkilduff** [Legedric/ptmagic#335]
After installing PTmagic, following all the relative steps as on github, even used Brent Dunns installation video. Installed windeows server 2.06.
I am installing the program on a Virmach vps, if that makes any difference.
Start ptmagic then I get the message dotnet has stopped working.

Cmd runs and then stops when the dotnet error shows up,
![2ead27ee-efa4-46ee-bd20-4ed1d4947bad](https://user-images.githubusercontent.com/36867315/37625331-5f4c62a0-2bc3-11e8-8ccf-97e0c0d1369b.png)

**Comment by Legedric** [comment]
You somehow seem to have invalidated your JSOn file, please use a JSON validator to check what#s wrong there:
http://jsonlint.com

**Comment by nkilduff** [comment]
dont really understand, do I just test the line in question or copy the complete script text..?

thx

**Comment by Legedric** [comment]
I do not really know what part of your JSON is invalid, so I cannot assist you on what is actually wrong in there.

According to the error message it seems to be somewhere in here:
![image](https://user-images.githubusercontent.com/8308141/37681917-50befcbe-2c88-11e8-8f87-b11951fa4aa9.png)

**Comment by nkilduff** [comment]
I am going with a fresh install and see if that sorts it.!

**Comment by nkilduff** [comment]
sorted with fresh install... thx
