### ISSUE TITLE
pending log analyses

### ISSUE THREAD

**Issue by aqueiroz** [Legedric/ptmagic#337]
Hi Guys, not sure if everyone is in the same boat.
I have quite a few pending transactions (bad buys, that I been holding for ages in the hope that I can sell it at a profit at some point)

Would it be possible to have a Pending logs analyser like the new Bag analyser feature? Specially if it could advise on Manual buy and sell, so that you can sell the toxic pending transactions?

Hope it makes sense.

Regards

Dre

**Comment by Legedric** [comment]
Please ZIP and upload your ProfitTrailerData.json here so I can check this. I do not have any pending logs in my own data and never had any so I do not really know how that may look like.

**Comment by aqueiroz** [comment]
[ProfitTrailerData.zip](https://github.com/Legedric/ptmagic/files/1829346/ProfitTrailerData.zip)
there you go...

thank you
