### ISSUE TITLE
Cant see the GUI correctly 

### ISSUE THREAD

**Issue by CryptoBullRider** [Legedric/ptmagic#34]
The GUI only shows Hyperlinks, some of the functions work but it's not looking good.
For some reason it's not loading the GUI
![screen shot 02-19-18 at 05 54 am](https://user-images.githubusercontent.com/36610620/36364184-820a5346-153a-11e8-92e4-c411d2be27e0.PNG)
I've tried several browser but with no luck. please help me :)

**Comment by Legedric** [comment]
It seems like there are some CSS etc. files missing. Please make sure that within your "Monitor" a folder "wwwroot" exists and check if the contents of this folder (should be "assets" and inside assets you see "css", "js", etc.) are all there from our ZIP file.

**Comment by CryptoBullRider** [comment]
the files are there, but it's not loading them...

**Comment by CryptoBullRider** [comment]
by the way I'm using a VPS, not sure if it's something related to it

**Comment by TwixRaider** [comment]
Are you running on Linux? If so, please check if the browser process has the correct access rights to the files in the /wwwroot/assets folder.

**Comment by CryptoBullRider** [comment]
Using windows 2012 server

**Comment by TwixRaider** [comment]
Can you see some errors in the browser console (F12)? Something's seem to block the loading of the CSS and JS files...

**Comment by CryptoBullRider** [comment]
Yes I something it's blocking it not sure what. 
It gives this odd error
net::ERR_ABORTED[]
![screenshot_20180219-154107](https://user-images.githubusercontent.com/36610620/36385888-e88f2d66-158b-11e8-9c86-783c5a9b7e00.jpg)

**Comment by TwixRaider** [comment]
Have you tried another port than 5000 for the monitor? Any firewall rules or something that could cause this?

**Comment by nstefi** [comment]
I thought maybe this is because you run it in Internet Explorer with Protected Mode enabled, which is default on the new Windows servers. Maybe try to download Google Chrome and run in that.

**Comment by CryptoBullRider** [comment]
Thanks a lot @nstefi , it solved the problem :+1:

**Comment by cryptomaj** [comment]
Tired switching of protected mode in browser, but still not loading properly.
