### ISSUE TITLE
Market Trend for specific Coin

### ISSUE THREAD

**Issue by JHenneberg** [Legedric/ptmagic#342]
It would be very usefull to be able to watch a single Coin instead of just giving a number of maximum wachet from the top

 {
          "Name": "ETH1h",
          "Platform": "Exchange",
          "Coin":"ETH"
          "TrendMinutes": 60,
          "TrendCurrency": "Fiat"
        },

so you would be able for example to setup your parameters much better. Market in gerneral is going up but your Market Coin is pretty much stable this would mean you should lower your buy_value much more because otherwise you would not be able to buy. Right now this is the exact situation. ETH is going up much slower then other altcoins. 
![image](https://user-images.githubusercontent.com/6606609/37681785-eebeadfc-2c87-11e8-9884-c1d366e805d1.png)

**Comment by Legedric** [comment]
I don't really get your problem here. What exactly do you want to see?

**Comment by JHenneberg** [comment]
Thanks for the new version first of all. I want to watch the trend of a single coin. 
 
{
"Name": "ETH1h",
"Platform": "Exchange",
"Coin":"ETH"
"TrendMinutes": 60,
"TrendCurrency": "USD"
},

**Comment by Legedric** [comment]
Uhm you can do that already today with PTM. Some others are already doing this to track ETH/USDT price on CMC for example.

I do not have the exact setting at hand to do so (as I personally do not run that) but others do. Maybe search this GitHub or join our Discord and see if someone has it there.
