### ISSUE TITLE
[Feature: Single Market Settings] Project Strength Signals - Changes in Github Repo Data

### ISSUE THREAD

**Issue by goferit** [Legedric/ptmagic#347]
See screen capture from RHC of onchainfx.com.

![image](https://user-images.githubusercontent.com/8900109/37709170-b0d3af58-2cdf-11e8-96b6-789f989abc8e.png)

Main project:
https://www.cryptomiso.com/

**Comment by Legedric** [comment]
That's for PT to implement and not for PTM as it directly affects trading and not the settings.

In addition the effort to implement this would be too high for this special usage.
