### ISSUE TITLE
Buy Strategy based Offset Groups

### ISSUE THREAD

**Issue by ITJusus** [Legedric/ptmagic#349]
One of the major complaints about PT is the lack of ability to utilize multiple possible buy strategies, in the same bot, instance in different market conditions.  I'm not talking about using two confirming indicators at the same time (which will be in PT 2.0), but rather the ability to use different strategies when the time and conditions are right to use them.  One could spin up a separate bot instance, using a different port...but then you can't target the same coins (without confusing the bots). You could create a 2nd account on the same exchange (Binance), but this is officially considered a no-no by Binance.  I originally thought of this idea for PTF, which is why some of the values below are in that format, but I'm thinking PTM may benefit from this...since PTF doesn't even have this yet listed in any milestones.  Applications like PTM and PTF have made some strides in getting us closer to addressing this issue, with use of things like Market Conditions and Offset Groups.

But, neither PTM or PTF has not gotten to the point of where it has fully addressed the issue and I think the developers of PTM (who use it for trading themselves) will see the benefit of this for themselves and for the community as well. The final and most important piece to have in PTM, I think, will be Offset Groups that directly measure the very same indicators utilized in each of the PT buy strategies: EMASPREAD, SMASPREAD, EMAGAIN, SMAGAIN, EMACROSS, SMACROSS, LOWBB, and HIGHBB.

This would allow us to apply a particular strategy to a particular coin, based on whether that coin is currently in the range closest to one of these strategy's set buy_value. For example, it would look something like this...

},
"BUYSTRATEGYRANGES": {
"Configs": [
{
"CurrentEMASpreadRange": "-9",
"BuyStrategy": {
"BuyValue": "-8",
"BuyStrategy": "EMASPREAD",
"Weight": "100"
},
"DcaMinBuyBalanceOffset": "-23",
"TrailingBuyOffset": "150"
},
{
"CurrentEMASpreadRange": "-3",
"BuyStrategy": {
"BuyValue": "-2",
"BuyStrategy": "EMASPREAD",
"Weight": "100"
},
"DcaMinBuyBalanceOffset": "-53",
"TrailingBuyOffset": "100"
},
{
"CurrentEMASpreadRange": "1",
"BuyStrategy": {
"BuyValue": "2",
"BuyStrategy": "EMASPREAD",
"Weight": "100"
},
"DcaMinBuyBalanceOffset": "-93",
"TrailingBuyOffset": "50"
},

Never mind the example offsets and above's specific values, just generic values to show the concept.  These can be translated, of course, into naming conventions more suitable to PTM.

Basically, if the EMASPREAD of a specific coin is currently between 1 and -3, then apply the BuyStrategy listed under that range (along with its offsets). If the EMASPREAD for a specific coin is currently found to be in the range between -3 and -9, then apply the BuyStrategy listed under that range (along with its offsets).

This would give us the ability to utilize multiple possible EMASPREAD srtategies, based on what range of the EMASPREAD each coin currently resides in.

The same concept could then be applied for adding say HIGHBB range based triggers into this same Offset Group area ("BUYSTRATEGYRANGES") just below that "CurrentEMASpreadRange" and one could simply make the "Weight" lower or higher based on which strategy is preferred over the other when two or more of these strategy ranges are hit at the same time for the same coin...

{
"CurrentHighBBRange": "20",
"BuyStrategy": {
"BuyValue": "21",
"BuyStrategy": "EMASPREAD",
"Weight": "150"
},
"DcaMinBuyBalanceOffset": "-23",
"TrailingBuyOffset": "150"
},
{
"CurrentHighBBRange": "50",
"BuyStrategy": {
"BuyValue": "51",
"BuyStrategy": "EMASPREAD",
"Weight": "150"
},
"DcaMinBuyBalanceOffset": "-53",
"TrailingBuyOffset": "100"
},
{
"CurrentHighBBRange": "-1",
"BuyStrategy": {
"BuyValue": "-2",
"BuyStrategy": "EMASPREAD",
"Weight": "150"
},
"DcaMinBuyBalanceOffset": "-93",
"TrailingBuyOffset": "50"
},

And I think you get the point.

**Comment by Legedric** [comment]
Thank you very much for your very well written concept here.

At the moment we have no plans to implement any indicators at all to PTM and use them to apply settings. The reason is that we consider PTM to be an addon that mostly limits your risks (the bot) and provides a better overview of what PT is currently doing (the monitor).
Enhancing the actual trading is (at this very moment) not an intention behind this project.

I am not saying it will never come, but I want to be very honest and say that when we will implement indicators into PTM, then it is only a very small step for us to implement the actual trading (just contacting exchange APIs) into this project, rendering Profit Trailer obsolete.
That's not what we plan or intend to do with PTM.
