### ISSUE TITLE
hello Legedric, get error while lunching (Start PTMagic_

### ISSUE THREAD

**Issue by wahbalami** [Legedric/ptmagic#35]
this is the error i m getting after wndows say donet crash, i instaled everything as it should

![image](https://user-images.githubusercontent.com/36618681/36366335-a0d3d2b2-151b-11e8-9381-62b1f7945ee8.png)

**Comment by Legedric** [comment]
Did you remove a market trend from your settings but left it in a trigger for the setting "EndOfTheWorld"?

**Comment by wahbalami** [comment]
Thanks so much for you respond i didn t change nothing
{
  "AnalyzerSettings": {
    "MarketAnalyzer": {
      "StoreDataMaxHours": 24, // Number of hours to store market data
      "IntervalMinutes": 1, // Interval in minutes for PTMagic to check market trends and triggers
      "ExcludeMainCurrency": true, // Excludes the main currency (for example BTC) from market trend analysis
      "MarketTrends": [
        {
          "Name": "CMC24h", // UNIQUE market trend name (to be referenced by your triggers below)
          "Platform": "CoinMarketCap", // Platform to grab prices from (Allowed values are: CoinMarketCap, Exchange)
          "MaxMarkets": 50, // Number of markets/pairs to analyze sorted by 24h volume
          "TrendMinutes": 1440 // Number of minutes to build a trend (1440 = 24h, 720 = 12h, 60 = 1h)
        },
        {
          "Name": "Exchange1h",
          "Platform": "Exchange",
          "MaxMarkets": 50,
          "TrendMinutes": 60,
          "TrendCurrency": "Market" // Trend Currency to build the trend against. If set to "Fiat", the trend will take the USD value of your main currency into account to build the trend. (Allowed values are: Fiat, Market)
        },
        {
          "Name": "Exchange12h",
          "Platform": "Exchange",
          "MaxMarkets": 50,
          "TrendMinutes": 720,
          "TrendCurrency": "Market"
        },
        {
          "Name": "Exchange24h",
          "Platform": "Exchange",
          "MaxMarkets": 50,
          "TrendMinutes": 1440,
          "TrendCurrency": "Market"
        }
      ]
    },
    "GlobalSettings": [ // Global settings for Profit Trailer properties
      {
        "SettingName": "EndOfTheWorld", // UNIQUE name of your setting
        "TriggerConnection": "AND", // Define if triggers will be connected by AND or OR
        "Triggers": [ // Your triggers for this setting
          {
            "MarketTrendName": "Exchange1h", // Reference to the market trend specified above
            "MaxChange": 0 // Maximum trend change % for this setting to get triggered
          },
          {
            "MarketTrendName": "Exchange12h",
            "MaxChange": -1
          },
          {
            "MarketTrendName": "Exchange24h",
            "MaxChange": -5
          }
        ],
        "PairsProperties": { // Properties for PAIRS.PROPERTIES
          "ALL_sell_only_mode": true,
          "ALL_trailing_profit": 0.1
        },
        "DCAProperties": { // Properties for DCA.PROPERTIES
          "trailing_profit": 0.1
        }
      },
      {
        "SettingName": "TankingDown",
        "TriggerConnection": "AND",
        "Triggers": [
          {
            "MarketTrendName": "Exchange1h",
            "MaxChange": 0
          },
          {
            "MarketTrendName": "Exchange12h",
            "MaxChange": 0
          },
          {
            "MarketTrendName": "Exchange24h",
            "MaxChange": -3,
            "MinChange": -5
          }
        ],
        "PairsProperties": {
          "ALL_buy_value": -1.1,
          "ALL_trailing_buy": 0.39,
          "ALL_trailing_profit": 0.1
        },
        "DCAProperties": {
          "trailing_buy": 0.1
        }
      },
      {
        "SettingName": "BearSighted",
        "TriggerConnection": "AND",
        "Triggers": [
          {
            "MarketTrendName": "Exchange1h",
            "MaxChange": 1
          },
          {
            "MarketTrendName": "Exchange12h",
            "MaxChange": 0
          },
          {
            "MarketTrendName": "Exchange24h",
            "MaxChange": -1,
            "MinChange": -3
          }
        ],
        "PairsProperties": {
          "ALL_buy_value": -0.9,
          "ALL_trailing_profit": 0.15
        },
        "DCAProperties": {
          "trailing_profit": 0.15
        }
      },
      {
        "SettingName": "ReadyForLiftOff",
        "TriggerConnection": "AND",
        "Triggers": [
          {
            "MarketTrendName": "Exchange1h",
            "MinChange": -1
          },
          {
            "MarketTrendName": "Exchange12h",
            "MinChange": 0
          },
          {
            "MarketTrendName": "Exchange24h",
            "MinChange": 1,
            "MaxChange": 3
          }
        ],
        "PairsProperties": {
          "ALL_trailing_buy": 0.2,
          "ALL_sell_value": 1.1
        },
        "DCAProperties": {
          "sell_value": 1.1
        }
      },
      {
        "SettingName": "ToTheMoon",
        "TriggerConnection": "AND",
        "Triggers": [
          {
            "MarketTrendName": "Exchange1h",
            "MinChange": 0
          },
          {
            "MarketTrendName": "Exchange12h",
            "MinChange": 1
          },
          {
            "MarketTrendName": "Exchange24h",
            "MinChange": 3
          }
        ],
        "PairsProperties": {
          "ALL_trailing_buy": 0.15,
          "ALL_sell_value": 1.3
        },
        "DCAProperties": {
          "sell_value": 1.3
        }
      },
      {
        "SettingName": "Default",
        "PairsProperties": {
          "File": "PAIRS.PROPERTIES"
        },
        "DCAProperties": {
          "File": "DCA.PROPERTIES"
        },
        "IndicatorsProperties": {
          "File": "INDICATORS.PROPERTIES"
        }
      }
    ],
    "SingleMarketSettings": [ // Single market/pair settings for Profit Trailer properties
      {
        "SettingName": "PumpNDumpProtection",
        "TriggerConnection": "OR",
        "Triggers": [
          {
            "MarketTrendName": "Exchange1h",
            "MarketTrendRelation": "Relative", // The relation of the single market trend. Relative = Single market trend compared relative to the market trend / Absolute = Single market trend viewn on its own
            "MinChange": 10
          },
          {
            "MarketTrendName": "Exchange12h",
            "MarketTrendRelation": "Relative",
            "MinChange": 10
          },
          {
            "MarketTrendName": "Exchange24h",
            "MarketTrendRelation": "Relative",
            "MinChange": 10
          }
        ],
        "PairsProperties": {
          "ALL_trailing_profit_OFFSETPERCENT": -10,
          "ALL_sell_value_OFFSETPERCENT": -30,
          "ALL_sell_only_mode": true,
          "ALL_DCA_enabled": false
        }
      },
      {
        "SettingName": "FreefallBlock",
        "TriggerConnection": "OR",
        "Triggers": [
          {
            "MarketTrendName": "Exchange1h",
            "MarketTrendRelation": "Absolute",
            "MaxChange": -5
          }
        ],
        "PairsProperties": {
          "ALL_trailing_profit_OFFSETPERCENT": -10,
          "ALL_sell_value_OFFSETPERCENT": -30,
          "ALL_sell_only_mode": true,
          "ALL_DCA_enabled": false
        }
      }
    ]
  }
}

**Comment by wahbalami** [comment]
can you help me please?

**Comment by Legedric** [comment]
@wahbalami I added some better logging in that place to find the error. Looks like something is wrong with a market trend in there.

**Comment by wahbalami** [comment]
![image](https://user-images.githubusercontent.com/36618681/36431311-3dbdb17e-1625-11e8-94de-4b5c6a96f193.png)

**Comment by wahbalami** [comment]
i m willing to pay if you can assist me online with teamviewer.
thx

**Comment by Legedric** [comment]
The issue should be fixed in version 1.0.3. I just re-uploaded it a couple of seconds ago. So even if you already updatet to 1.0.3, download it fresh and update again.
