### ISSUE TITLE
Average depth and life of a DCA bag

### ISSUE THREAD

**Issue by mygreeneggsandham** [Legedric/ptmagic#351]
I would like to request a feature that would show the average DCA sales depth and age. 
What I want to see is if having a DCA depth of 6 is a good plan when the average is a DCA of 3. Add to this the average life of a DCA bag and we can be more aggressive in our initial buy if, statistically we only go 3 DCA deep and the position is less than 12 hrs. (Binance)
If I am on Bittrex, I might have to allow for the average of 5 DCA and 24 Hrs. 
If this information were available, It would help fine-tune our strategy for each exchange and base currency.

**Comment by cybermizrach** [comment]
If possible, include the average percentage used per DCA buy level trigger so that we can assess if we are using the right level of buy level triggers.

**Comment by Legedric** [comment]
@cybermizrach Not possible as PT doesn't store this data and PTM has no access to your buy order data,

**Comment by Legedric** [comment]
Yes, the ST is something that is in the sales log.
