### ISSUE TITLE
Monitor update failed (Raspi B3+ / Pi PT Magic v1.4.0)

### ISSUE THREAD

**Issue by Moussier** [Legedric/ptmagic#352]
Hi,

First time trying to use the magic monitor on my raspi. Every page takes a serious time to load, and the monitor can't update the data. Tried to load the monitor both on my PC and on the Raspi itself, same issue.
PTMagic works fine on my raspi.
The Profit Trailer monitor works fine, every page instant loads.

Thank you for your work, keep it up 👍 

PS : Sorry for my english speaking, it's not my native language.

![capture](https://user-images.githubusercontent.com/24268913/37745622-174f1998-2d76-11e8-8a74-06558d7e2cd9.PNG)

**Comment by Legedric** [comment]
Please do the following:

1. Go to http://YOURPTMAGICMONITORADDRESS/_get/MainPage
2. Right click and hit "Show Source"
3. Copy the whole source code into a text file
4. Upload the file here

**Comment by Moussier** [comment]
For some reason, when I launched the monitor today it appeared to work fine. It's still a little bit laggy. Do you still want the sources ?

**Comment by Legedric** [comment]
No, if it is runningf ro you there is no need in that.
