### ISSUE TITLE
Why not release source code? 

### ISSUE THREAD

**Issue by determo13** [Legedric/ptmagic#36]
Hi mate, why not release source code? It's fee anyway... people will fix bugs for you and improve it.....

**Comment by innerpartycolt** [comment]
Why people don't start their own projects? Same result if you ask me.

**Comment by Legedric** [comment]
We may think about it making it open source although it seems to be very unlikely to happen (but never say never).

The main reason is (and that is also the reason why the effort for building such a tool was quite low for us - 2 weeks of spare time): We are using some libraries and techniques in PT Magic that we built during the past 15+ years of our journey in professional software development and we do not want to give that away to everyone for free.

**Comment by determo13** [comment]
That's alright guys, it's simple .net and easy to disassemble. No idea why CryptoGnome community not willing to advertise your app as it's looks fine from inside. They must be after monetizing bits, there for saying all kind of crap about you. Thanks for your effort!

**Comment by Legedric** [comment]
@determo13 I had a chat with CryptoGnome yesterday and their argument is more like that we stole the intelectual property from PT Feeder devs and JB's DCA calculator etc.

I even offered a rundown over the complete source code if someone who is a developer capable of understand the code may judge what we are doing there and find out of we are doing something shady in there (which we are not).

However, I still think CryptoGnome is a good guy in general and I understand if someone is skeptic about what our tool does and that's ok. But saying we stole an IP by building our own tool from scratch with our development skills (btw PTF does not even have any sort of monitor as far as I know) and releasing the project for free is like accusing Tesla for stealing the IP of every other electric car manufacturer that existed before...

**Comment by innerpartycolt** [comment]
@Legedric if PT Feeder is written in anything but .NET, I guess it makes any 'code stealing' argument invalid.

**Comment by Legedric** [comment]
@innerpartycolt Feeder is written in .NET Core just as PT Magic is.

I am working as asoftware developer for more than a decade, I do not need to steal code...

**Comment by determo13** [comment]
@Legedric Sorry to say, but their team not really getting much about code and stuff. PT tracker that they promote so much, got script where it's replaces part of it's js header code on demand, what makes it if not malicious, but at-least dodgy. Even so they said "we've looked through the code and it's looks fine" LOL!

**Comment by determo13** [comment]
@innerpartycolt mate if you words not just and empty space, do things, look through the code, it's takes only 10 mins

**Comment by Legedric** [comment]
It's not my thing to judge other people's projects. I do not know much about Feeder and I never looked at PT Tracker (I had a spreadsheet for that for free).

Bashing other people's project without knowing the code and/or the people behind the project is far below my level. So do not expect me to say something bad about them anywhere.

In fact, everyone who is not trusting us for whatever reason, or is thinking we are the ones ripping someone off here, or is thinking PT Feeder or PT Tracker are doing things better: I am totally fine with it. Go there, buy their products and do not use PT Magic. That's absolutely ok for me.

**Comment by Legedric** [comment]
@innerpartycolt No problem I did not understand your post to be saying we stole something, I was justing answering in general.
