### ISSUE TITLE
Suggestion - Ability to specify the coin in the Market Trends

### ISSUE THREAD

**Issue by cybermizrach** [Legedric/ptmagic#363]
I hope there is an option to specify the coins in the Market Trends. See IncludeCoins field below
        {
          "Name": "Exchange1h",
          "Platform": "Exchange",
          "MaxMarkets": 50,
          "TrendMinutes": 60,
           **"IncludeCoins": "BTC, ETH"**
          "TrendCurrency": "Market"
        },

**Comment by Legedric** [comment]
There is a way to ignore coins already so you may use that until the other way round may (or may not) finds its way into this project.
