### ISSUE TITLE
Suggestion - Average Age of trade

### ISSUE THREAD

**Issue by cybermizrach** [Legedric/ptmagic#364]
Can we have a report that shows the following?
1. The average age of all trades per day, week, month and overall with average profit%
2. The average age of all trades per coin per day, week, month and overall with average profit%

**Comment by Legedric** [comment]
Unfortunately PT stores only the time of the most recent buy of a DCA bag. So although it is called "firstBoughtDate" in PT's data, it is in fact tha "lastBoughtDateTime".

So the actual age of a trade is not something that PTM can display.
