### ISSUE TITLE
Suggestion - Ability to turn-on/off trading based on schedule

### ISSUE THREAD

**Issue by cybermizrach** [Legedric/ptmagic#365]
Can we please add a feature to turn-on/off trading based on a schedule ?
A user can specify the following:
a. start datetime and end datetime
b. recurring schedule (Every 8am to 5pm on weekdays/weekend)

It is a good feature specially to avoid  regular BTC dump. Recently BTC dumps usually happens every 6pm, 11pm, 3am, 6am, 11am

**Comment by xAndyxNL** [comment]
What's the point of disabling trading? If you have set it to disable at 11pm and you've bought a coin at 10.45pm you still have to coin. And it still drops. Or am i missing something here?

Id rather keep looking at what the market / charts do vs predict a market based on time.

**Comment by Legedric** [comment]
We do not see much sense in this and as this did not get any upvotes requests from other users we won't implement this feature.
