### ISSUE TITLE
PTmagic trailing but not buying

### ISSUE THREAD

**Issue by nkilduff** [Legedric/ptmagic#367]
Hi, needs some help, being trailing lots of coins on Magic but not buying.
Market is ETH

Settings file attached. its more than likely my fault as I am new to this.!

Thanks

[settings.analyzer.json.zip](https://github.com/Legedric/ptmagic/files/1843534/settings.analyzer.json.zip)

**Comment by Legedric** [comment]
PT Magic is not responsible for Profit Trailer buying or not buying. So that's a question for Profit Trailer itself.
