### ISSUE TITLE
Documentation Profit Trailer Version 2.0

### ISSUE THREAD

**Issue by angelsomar** [Legedric/ptmagic#368]
I support this with the intention of studying compatibility with the new version, I do not know if they already have it

They are an excellent project, Thanks

https://wiki.profittrailer.com/doku.php?id=pairs.properties2
https://wiki.profittrailer.com/doku.php?id=dca.properties2
https://wiki.profittrailer.com/doku.php?id=indicators.properties2
https://wiki.profittrailer.com/doku.php?id=application.properties2

**Comment by Legedric** [comment]
Thanks but we know already about the new properties and PTM will be prepared for this with the next release.
