### ISSUE TITLE
Sales Analyzer Chart Date is off

### ISSUE THREAD

**Issue by ChipCrypto** [Legedric/ptmagic#369]
The Dates of sales shown on the Sales Analyzer Chart is off from that shown in the "Last 10 Days" list. I have also noticed that sometimes the sales Analyzer chart on the Dashboard Page differs from that on the Sales Analyzer tab.

**Comment by ChipCrypto** [comment]
![image](https://user-images.githubusercontent.com/37139161/37862326-f5db8fae-2f18-11e8-8259-89a138cdfb14.png)

**Comment by msaleh3000** [comment]
I also have the same issue. the the chart is off by one day. that is it displays yesterday's date with today's numbers. This is for both the number of sales and the profit. although the data in the table is correct.
