### ISSUE TITLE
About the "Will PT Steal my API and whatnot..." topic here on GitHub

### ISSUE THREAD

**Issue by Legedric** [Legedric/ptmagic#37]
Hi guys,

when I woke up today I just saw that issue #18 somehow disappeared here on our GitHub.  
Just in case you are wondering, we did not remove the issue! In fact, you cannot even delete issues on GitHub for a good reason (making good answer unavailable) and we were kinda shocked when we saw that the issue is no longer with us.

However, I already contacted GitHub about this issue but it seems like the user that created this issue deleted his entire GitHub account and so all his content he ever created here got removed, including this issue with all its answers and comments...

Please use this topic now to answer questions regarding this topic and we will see what GitHub may be able to do to restoe this original issue.

Best regards,

Legedric

**Comment by determo13** [comment]
Yeah that's looked suspicious, there for my question was regarding openesourced it. Then I decided to look into code myself, disassembled it and looked through, couldn't see any issue... Thanks for free stuff guys! Thumbs up!

**Comment by Legedric** [comment]
Here is my original answer on that topic for clarification:

Yes I am happy to clarify.  

In theory, PT magic has access to the same files, settings and whatever else that Profit Trailer, PT Tracker, PT Feeder and every other software you install or simply run on your computer has. So being careful is of course advisable, no matter what software you are using.  

PT Magic was developed by myself and a working collegue of mine (both being software developers) with the simple intention to build a more complete addon to Profit Trailer than currently existing and without the need for just us two to spend any additional money.  

Somewhere during the development we decided to not just develop this addon for us two only, but to make it available to the public for free.  
In fact, I even used my real name to register a domain for this project etc.  
So why on earth should we do something so stupid to steal from others making it possible to sue the crap out of us?  

We do understand that some people (especially the devs behin the other named two addons) are upset now that we jump right into this "game" and give away something for free - especially when we provide similar functions as they do (or even more, just for free).  

We also do understand that there may be skepsis about our tool, but please be aware that only because our tool is free and others are asking to pay them upfront, that other tools (even like the named ones here) will not steal your things with a future update (not saying they will, just building an example here).  

Having that said, I can assure everyone that PT Magic is **NOT accessing any personal API key**. In fact, it **does not use ANY API key** to build the data as it only uses the public APIs of Bittrex, Binance etc.  

May I ask in which community channel this was posted? Maybe we can arrange a chat with the owners to clarify somtehing or give them a rundown through our code if they are capable of judging it (meaning: being developers themselves).

**Comment by Legedric** [comment]
For anyone wondering why this is not open source and how our opinion on that topic is, go read issue #36

**Comment by Legedric** [comment]
The original topic #18 got restored somehow, so I will close this one :)
