### ISSUE TITLE
No market trend found! The pair may have got delisted from your exchange!

### ISSUE THREAD

**Issue by mavverick** [Legedric/ptmagic#370]
Hi, I m using pt with ETH market on Binance , In the market analyze I get thi error on ALL COINS 

ADAETH | 0.00000000 | 0 | No market trend found! The pair may have got delisted from your exchange!
0.00000000 | 0 | No market trend found! The pair may have got delisted from your exchange!
0.00000000 | 0 | No market trend found! The pair may have got delisted from your exchange!
0.00000000 | 0 | No market trend found! The pair may have got delisted from your exchange!
0.00000000 | 0 | No market trend found! The pair may have got delisted from your exchange!
0.00000000 | 0 | No market trend found! The pair may have got delisted from your exchange!
0.00000000 | 0 | No market trend found! The pair may have got delisted from your exchange!
0.00000000 | 0 | No market trend found! The pair may have got delisted from your exchange!
0.00000000 | 0 | No market trend found! The pair may have got delisted from your exchange!
0.00000000 | 0 | No market trend found! The pair may have got delisted from your exchange!
0.00000000 | 0 | No market trend found! The pair may have got delisted from your exchange!
0.00000000 | 0 | No market trend found! The pair may have got delisted from your exchange!
0.00000000 | 0 | No market trend found! The pair may have got delisted from your exchange!

For btc market works fine , but not for eth market...

**Comment by Legedric** [comment]
Did you try to reset your exchange data for the ETH bot?
https://github.com/Legedric/ptmagic/wiki/Reset-PT-Magic-Exchange-Data

**Comment by mavverick** [comment]
Great . I tried and now its workinkg fine! 
Thanks!
