### ISSUE TITLE
Monitor memory leak

### ISSUE THREAD

**Issue by chriswong23** [Legedric/ptmagic#373]
Ever since running version 1.4.0, the magic monitor will slow down (bad) or crash my server instance (AWS Ubuntu). It takes less than 24 hours of leaving it on. The only way to work around it is to kill the monitor process and let the server run without it and restart it whenever I need to access the GUI.

**Comment by Legedric** [comment]
Seems like an issue that is very special to your environment as many other users on Ubuntu do not report this issue.

So I am sorry but you will have to sort that out for yourself as we do not use Unix and the issue does not sound like something that's quite common.

**Comment by chriswong23** [comment]
👍
