### ISSUE TITLE
IP Banning due to too many requests, and how to fix it.

### ISSUE THREAD

**Issue by ShadowOnTheLand** [Legedric/ptmagic#376]
So, if you're running a single bot; It's not really an issue... But most people that I know have, and run more then 1 bot at a time. This leads to temp bans on a regular basis. This could lead to loss of profits.

My suggestion for a fix is going to require some reworking. I would say this is probably for PTMagic 2.0 in the future. I don't know how complicated it would be to implement.

We only need 1 source of database data. So the first part of PTMagic is ONLY a repository for the Exchange Data. It connects and updates the exchange data just like it does now when you first connect. So we'll call this the PTMagic Server, It will get the data from the exchange and make it available to the second part of the System:

PTMagic Client: This is a Bot Specific client program that works EXACTLY like PTMagic does right now, only instead of getting the data from the exchange, it takes the data from the PTMagic Server. This will allow you to run as many bots as you want without getting IP Banned.

You could roll this secondary part into PTMagic Monitor and use that as the Client Program on a bot by bot basis...

**Comment by Legedric** [comment]
While I do know what you mean it is extremely unlikely to happen that we rebuild PT Magic like this.

And while I do know that some people get IP banned on Binance, I always said that my personal impression is that PT Magic may not really be the reason for that as PT Magic does only one call to Binance on each interval.
This call has a weight of 292 on Binance's API as it weighs 1 for each coin listed on Binance so the result is that PT Magic consumes 292 API rates per minute (if you are running a 1 minute interval).
The maximum is 1200 per minute. So I do not know how many PT itself consumes per minute but even with two PTM bots running you get to like <600 max which still leaves half of the rate open.

However, when we build PTM in February it was never intended to run multiple versions of it on the same machine. Yes, it does work but that doesn't mean that this is what we want to support with development effort.
