### ISSUE TITLE
A message is sent every two minutes that the setting has changed

### ISSUE THREAD

**Issue by smoochy** [Legedric/ptmagic#378]
Every two minutes (I have PTM set to do its check every two minutes) I get a Telegram message that the settings have changed. Although the market staid in the same condition.

I've seen https://github.com/Legedric/ptmagic/issues/266. So I removed all spaces from GlobalSettings and SingleMarketSettings but it is still the same.

- Ubuntu 16.04
- No Testmode
- No PTF or similar, only PT, PTM and PTTracker

For some reason it is, according to my GlobalSettings, correctly setting it to Bullish, but only Default gets written in the pairs, dca and indicator properties files:

```
 # ####################################
 # ####### PTMagic Current Setting ########
 # PTMagic_ActiveSetting = Default
 # PTMagic_LastChanged = 27.03.18 13:38
 # ####################################
```
At 13:38 I removed all spaces from the settings.analyzer.json and removed the PTM header from the 3 properties files.

When I look at the log file, I can always see this repeating:

```
2018-03-27 13:48 +02:00: 2018/03/27 13:48:07.277 INFO - Setting 'Default' currently active. Checking for flood protection...
2018-03-27 13:48 +02:00: 2018/03/27 13:48:07.277 INFO - Switching global settings to 'Bullish'...
```

So for some reason PTM is writing incorrectly Default into the headers, later checks market, sees it is Bullish, sends out the Telegram message but is not writing Bullish into the properties files.

You can find the log file here: https://pastebin.com/7nXAFSWf

Let me know if you need more information from my side.

**Comment by Legedric** [comment]
Please upload your settings.analyzer.json here.

**Comment by smoochy** [comment]
Just as an information for others, until 1.5.0 will be released:

Issue was caused by empty PairsProperties settings (in the `GlobalSettings`)

```
        "PairsProperties": {
        }
```

If you want to workaround the current situation, just add any anything to it, like:

```
        "PairsProperties": {
		"ALL_combined_cancel_pending_trigger": 0
        }
```

pairs.properties File for PT will be updated then.

Thanks Legedric for quickly figuring this out.
