### ISSUE TITLE
Unable to start PTMagic

### ISSUE THREAD

**Issue by DmonicZA** [Legedric/ptmagic#38]
Hi there.

I have gone through the installation steps for PTMagic and it is unable to start. Please find below error. 
![image](https://user-images.githubusercontent.com/36625867/36375781-572ed400-1579-11e8-9fb8-bb0c01d7a73e.png)

I have net enable IIS on my server. Do I need to do this?

I look forward to your response.

**Comment by Legedric** [comment]
You do not need IIS for this. Please make sure you downloaded the Windows Server Hosting (.exe) and installed it as described here on point 2:  
https://github.com/Legedric/ptmagic/wiki/Setup-PT-Magic-on-Windows

**Comment by DmonicZA** [comment]
I have done so, yes.

**Comment by Legedric** [comment]
Did you try what the message suggests? I never ran into that error so it is kinda hard to figure out what .NET is reporting here to be wrong.

A quick search on Google digged up that post from the official dotnet core GitHub:

> Hi
Had this similar issue. I have Win 7 SP1. Installed Windows update from following link and got resolved.
https://www.microsoft.com/en-us/download/details.aspx?id=26767
>Hope it helps

**Comment by DmonicZA** [comment]
It is running on Windows Server 2008 R2 x64. I have performed all the required updates that it suggested but with no luck.

**Comment by Legedric** [comment]
Can you check if you already installed this update right here for your Win 2008 machine:
https://support.microsoft.com/en-us/help/2533623/microsoft-security-advisory-insecure-library-loading-could-allow-remot

That's what I just linked for Win 7 and sometimes it does not get distributed via Windows' automated update system.

> Update for Windows Server 2008 x64 Edition (KB2533623)

> [Download Download the Windows6.0-KB2533623-x64.msu package now](http://www.microsoft.com/downloads/details.aspx?familyid=755cab42-2ce6-499a-bb8e-e5f1c17ce8ad)

.

**Comment by DmonicZA** [comment]
I have fixed the issue. missing security update. Thanks for the assistance.
