### ISSUE TITLE
New Variable for SMS settings

### ISSUE THREAD

**Issue by ShadowOnTheLand** [Legedric/ptmagic#381]
So we talked about RSI and SMS settings the other night. I am less tired now and have come up with a potential way to allow SMS settings to remain written.

Right now you have soemthing like:
"PairsProperties": {
          "ALL_buy_strategy": "LOWBB",
          "ALL_buy_value": -40,
          "ALL_trailing_buy": 0.33,
          "ALL_sell_value": 0.75,
          "ALL_trailing_profit": 0.1
        },
When this is active due to trend data everything is fine. As soon as the Trend Data becomes false, the SMS disappears; This is not ideal for scalp or swing trading. If we added a new variable to the settings:

"PairsProperties": {
          "ALL_buy_strategy": "LOWBB",
          "ALL_buy_value": -40,
          "ALL_trailing_buy": 0.33,
          "ALL_sell_value_PERSIST": 0.75,
          "ALL_trailing_profit_PERSIST": 0.1
        },

This tells PTM to NOT over write this particular pair specific setting if the SMS becomes false, and that it can only be over written if some other setting rewrites to THIS particular pair specific coin.

Seeings how you're in SOM as default, and you only leave SOM when the SMS trigger is active, it doesn't matter if the PERSIST trigger remains forever in the file. Because it's a pair specific setting on a coin that's only in SOM.

I feel like this is a very elegant and light solution to add an extremely powerful trading strategy to PTMagic.

**Comment by Legedric** [comment]
Thanks for your proposal.

We are already working on something to enabled the users to apply SMS for a timeframe that's longer than the trigger itself will allow it to be today. However, I do not want to give any details on that right now 😃
