### ISSUE TITLE
Blacklist coins keeps adding up in pairs.properties of PT

### ISSUE THREAD

**Issue by javdwal83** [Legedric/ptmagic#382]
Hello,

When I enable the blacklist for coins, PTM keeps adding them up while they are already there in the pairs.properties file:

like

# XEMETH - Current active settings: BlacklistNewCoins
# Matching triggers:
# BlacklistNewCoins: 'XEMETH' is only 9 days old on this exchange. Trigger matched!
# XEMETH - Current active settings: BlacklistNewCoins
# Matching triggers:
# BlacklistNewCoins: 'XEMETH' is only 9 days old on this exchange. Trigger matched!
# XEMETH - Current active settings: BlacklistNewCoins
# Matching triggers:
# BlacklistNewCoins: 'XEMETH' is only 9 days old on this exchange. Trigger matched!
# XEMETH - Current active settings: BlacklistNewCoins
# Matching triggers:
# BlacklistNewCoins: 'XEMETH' is only 9 days old on this exchange. Trigger matched!
# XEMETH - Current active settings: BlacklistNewCoins
# Matching triggers:
# BlacklistNewCoins: 'XEMETH' is only 9 days old on this exchange. Trigger matched!
# XEMETH - Current active settings: BlacklistNewCoins
# Matching triggers:
# BlacklistNewCoins: 'XEMETH' is only 9 days old on this exchange. Trigger matched!
# XEMETH - Current active settings: BlacklistNewCoins
# Matching triggers:
# BlacklistNewCoins: 'XEMETH' is only 9 days old on this exchange. Trigger matched!
# XEMETH - Current active settings: BlacklistNewCoins
# Matching triggers:
# BlacklistNewCoins: 'XEMETH' is only 9 days old on this exchange. Trigger matched!
# XEMETH - Current active settings: BlacklistNewCoins
# Matching triggers:
# BlacklistNewCoins: 'XEMETH' is only 9 days old on this exchange. Trigger matched!
XEMETH_sell_only_mode = true

And it keeps growing in time...

**Comment by Legedric** [comment]
Please ZIP and upload you pairs.properties here so I can see the whole picture.

**Comment by Legedric** [comment]
Closing as no feedback was provided for several days now.
