### ISSUE TITLE
Market trends not working properly

### ISSUE THREAD

**Issue by Ichy84** [Legedric/ptmagic#383]
Hello,

I am using multiple market trends, but i get a lot of 0,00% change on numerous trends. Below an example from today. C on the end and CMC in front means Coinmarketcap, E means exchange, BTC means max market 1. The bot is running without pause or changes for a while.

Thank you
Have a great Ostern

![image](https://user-images.githubusercontent.com/36775146/38136199-32ccc366-341d-11e8-8876-100fc5954503.png)

**Comment by Legedric** [comment]
CMC is causing issues at the moment as they seem to have a coin on their API that is producing invalid values.

For all the exchange data: Please check your logs if there are any errors showing up.

If not, try to reset your exchange data:
https://github.com/Legedric/ptmagic/wiki/Reset-PT-Magic-Exchange-Data
