### ISSUE TITLE
Sales overview Total % gain

### ISSUE THREAD

**Issue by Heartinhand** [Legedric/ptmagic#384]
Hello and thank you for your contribution. Very useful!

I tried to update my balance on the GUI as I deposited some more btc to my account.

Now it says the total % gain can't be calculated. I tried to edit the settings.general.jason and now it shows the total but I think it's messing with my calculations. Not sure. 

My question is what's the correct procedure to follow in my case?

Thank you.

**Comment by Legedric** [comment]
You did everything correct in the first place. The total gain cannot be calculated accurately as soon as you add any transaction to your balance. That#s what also the tooltip says.
