### ISSUE TITLE
TCV and TPV against initial investment to be shown in the sales analyser

### ISSUE THREAD

**Issue by djbadders** [Legedric/ptmagic#386]
Hey guys what a great plugin for Profit Trailer.

I did have a suggestion for the Sales Analyser where it would show the TCV and TPV values against initial investment. Currently it only shows your profit made based on sales data, but if I was to pnaic sell it would be really handy to be able to understand my position against the TCV value.

THanks

**Comment by Legedric** [comment]
As TCV is your Total Current Value across all of your trades and assets in PT. How would that be in any relation to a single trade/sale your made?

**Comment by djbadders** [comment]
Hi, I wasn't thinking against individual pairs just as part of the summary for sales.

**Comment by djbadders** [comment]
Yes that would be handy, as some sales the bot isn't aware of, so the TCV is probably the best judge of what profit you actually have at any point. Maybe even a graph that shows TCV over time.

**Comment by Legedric** [comment]
Not seeing a wide range use of this so we decided to drop this feature.
