### ISSUE TITLE
Suggestion - A way to exclude a pair from SingleMarketSettings

### ISSUE THREAD

**Issue by ugeorge-bg** [Legedric/ptmagic#389]
Hello Legedric,

This is my first post so first of all thank you for providing PTMagic and supporting it. It is a great product. 
Recently it came to my mind that it would be nice to have the option to exclude a single/multiple coin pairs from SingleMarketSettings. This is useful in case you buy a coin manually and would like PT to sell it at a higher profit compared to the coins it buys automatically. Problem arises if such a coin starts pumping and falls under the PumpNDump protection rule. Even if coded manually in advance in PAIRS.properties PTMagic adds the PumpNDump protection lines further down in the file. As a result PT has the last one in effect, so it is no longer possible to sell at the desired profit and trailing profit.
One very quick solution would be a special comment line (comment for PT and used by PTMagic) in the PAIRS.properties which will tell PTMagic to write just before this comment, everything after it will get executed after PTmagic settings and will effectively overwrite PTMagic. Of course such an option should be used with caution and so on...
I hope this explanation makes sense and I'm looking forward to your answer.

Best Regards

**Comment by Legedric** [comment]
It's already there:
https://github.com/Legedric/ptmagic/wiki/settings.analyzer#ignoredmarkets-1

Or using the monitor:
![image](https://user-images.githubusercontent.com/8308141/38311067-7fc87a84-381e-11e8-9159-17514ff8209c.png)

**Comment by ugeorge-bg** [comment]
Thanks, I couldn't find it.
