### ISSUE TITLE
Market trend check throwing forbidden

### ISSUE THREAD

**Issue by apondman** [Legedric/ptmagic#39]
market trend is every so often throwing a fatal error:

2018/02/19 12:36:48.715 INFO - Starting market trend check with Version 1.0.2
2018/02/19 12:36:49.095 FATAL - The remote server returned an error: (403) Forbidden. System.Net.WebException The remote server returned an error: (403) Forbidden.    at System.Net.HttpWebRequest.GetResponse()
   at BusinessRules.MarketAnalyzer.BaseAnalyzer.GetSimpleJsonObjectFromURL(String url, LogHelper log) in D:\Tools\PTMagic\BusinessRules\MarketAnalyzer\BaseAnalyzer.cs:line 45
2018/02/19 12:36:49.103 INFO - CoinMarketCap - Getting market data...
2018/02/19 12:36:49.154 INFO - CoinMarketCap - Market data received for 100 currencies

Does seem to work fine regardless. My interval is set to 1 minute.

**Comment by Legedric** [comment]
Seems like this is the version check to GitHub that's blocking too frequent requests. Thanks for posting, I will change this so the version check will not happen every run but only every other hour or so.
