### ISSUE TITLE
Can't sort pairs while ignored market is set

### ISSUE THREAD

**Issue by mightysoul** [Legedric/ptmagic#390]
Version 1.4.0 Steps to reproduce the issue;

1) Set a pair as ignored markets on your market trends
2) Try to sort your pairs on market analyzer page.

**Comment by Legedric** [comment]
For me it is working. What exactly is happening when you try to sort? Can you provide a screenshot, please?

**Comment by mightysoul** [comment]
I've made a video of the problem. You can check from below link.

https://im5.ezgif.com/tmp/ezgif-5-f6561c2ce2.mp4

**Comment by Legedric** [comment]
Thanks, I will check this.
