### ISSUE TITLE
DCA Calculator doesn't work with buy_triggers set as general property

### ISSUE THREAD

**Issue by SPLeon** [Legedric/ptmagic#391]
Hi,

DCA calculator in PTM 1.5 doesnt work anymore. For percentage and for value.

![image](https://user-images.githubusercontent.com/29701268/38362727-2e3c2698-38d2-11e8-929a-483a71c5a2a8.png)

**Comment by SPLeon** [comment]
What do you exactly mean? I also tried to restart PTMagic several times. I did follow the standard update procedure, so close application, copy and replace files and start PTM

**Comment by Legedric** [comment]
Ok when you switch to "Advanced Mode". Please post a screenshot of that screen here showing your triggers etc.

**Comment by SPLeon** [comment]
![image](https://user-images.githubusercontent.com/29701268/38363951-e2242e04-38d6-11e8-81b1-4c454e5e136b.png)

**Comment by Legedric** [comment]
So you did not specify any DCA triggers in your DCA.properties?

**Comment by Legedric** [comment]
Never seen setting the trigger like this before. I will try to handle that with the next release.

**Comment by SPLeon** [comment]
Thanks, for EMAGAIN DCA you don't have a trigger for each tier.
