### ISSUE TITLE
[Enhancement] - Add new columns on the POSSIBLE BUY ANALYZER 

### ISSUE THREAD

**Issue by cybermizrach** [Legedric/ptmagic#392]
Can you add the following columns on the POSSIBLE BUY ANALYZER? 
Single Market Settings Trigger  (separated by comma if it has multiple triggers)
Off Trigger 
24H%
Additional Market Trends (1H, 2H, 3H, 12H, 3 Days, etc)

It is easier to determine why a Pair is in SOM, and why it has a buy value of x. 

Can the columns be sorted?

**Comment by HojouFotytu** [comment]
Most of this information is available on other pages.
