### ISSUE TITLE
[Feature Request/Enhancement] Master overrule setting

### ISSUE THREAD

**Issue by JaySNL** [Legedric/ptmagic#394]
Have the ability to set a 'master' overrule setting, i.e you want to (temporary) set a manual hard percentage  for the bot to sell or buy at (expect it to rise up or down x-percent) but dont want single markets to interfere.

I.e:
Coinpair_sell_value_override = 5 //this would keep it at 5 untill removed or restarted ptm or a different method (when bought/sold)

**Comment by Legedric** [comment]
You could do that already today with PTM. Just configure a single market setting that has that value and set an off trigger for like 10000 hours so it stays active until you reset it through the monitor for example.

**Comment by JaySNL** [comment]
If a coin is already moving/set/determined in a single market, and you determine to buy it, it will already have gained some of these SMS settings. So you're saying i should adjust the SMS, or create a new one, to hold the target i want with offtrigger? This would put all coins who get that trigger to be held for x hours - i just want a few coins to be 'held'. I.e: user doesn't have this coin, just keep on setting the SMS.

A single setting like Coinpair_sell_value_override in pairs would make more sense.

**Comment by Legedric** [comment]
Maybe but that's then for Profit Trailer to implement this and not for PTM.
