### ISSUE TITLE
Error in DCA Calculator

### ISSUE THREAD

**Issue by angelsomar** [Legedric/ptmagic#397]
Hello, it is a small lake that does not affect the good functioning, I hope it is easy to correct it, failing since version 1.5 and 1.5.1

successes

![image](https://user-images.githubusercontent.com/36096512/38455061-0e30a678-3a38-11e8-85ee-27393a25d73d.png)

**Comment by Legedric** [comment]
This should be fixed with the next release

**Comment by angelsomar** [comment]
Improvement But error is generated by customizing probe values with "DCA Levels"

I had 4 change for 6

v. 1.5.2

![image](https://user-images.githubusercontent.com/36096512/38715880-8095c7c4-3ea3-11e8-8976-8f78adf74211.png)

**Comment by Legedric** [comment]
That's a different error and I just fixed that for the next release.
