### ISSUE TITLE
We can help you avoid "We got temp banned.Waiting 5 minutes"

### ISSUE THREAD

**Issue by angelsomar** [Legedric/ptmagic#398]
We can help you avoid "We got temp banned.Waiting 5 minutes"

It would be good if I could connect proxy socks

This not to intervene in the statistics of connection of the api, especially when we run several instances with an ip

**Comment by Legedric** [comment]
It is very unlikely (next to impossible) that PTM is responsible for IP bans as it only does a single request with a weight of like <300 to Binance once per minute at max.

**Comment by angelsomar** [comment]
Hello, please do not rule out the option, I use 4 instances of the bot with 4 of PTMagic

if I leave it working all at 1 minute they go from 1200 per minute which is the binance limit

I have it balanced changing the magic times and work well, if possible not discard thanks for the attention and success in this great project that has served the community so much
