### ISSUE TITLE
Display issue

### ISSUE THREAD

**Issue by mikdesign02** [Legedric/ptmagic#399]
After updating PTM i have a display issue with the menue.
Can you help me?
![y](https://user-images.githubusercontent.com/34874555/38461207-c21a18e6-3ab9-11e8-9a78-85be1a693a47.JPG)

**Comment by Legedric** [comment]
Please make sure that you replace all existings Monitor files correctly, esoecially all files located in wwwroot.

**Comment by Legedric** [comment]
Closing this as no feedback was provided for more than 2 days now.
