### ISSUE TITLE
Many Files not found in assets folder

### ISSUE THREAD

**Issue by flyboy1** [Legedric/ptmagic#4]
Hello,

there are many files missing in assets folder...

no bootstrap files
no jquery files
no plugin folder

![image1](https://user-images.githubusercontent.com/15215265/36318780-29f7b298-1341-11e8-91d2-80fc8729c55c.JPG)

**Comment by Legedric** [comment]
I re-uploaded the release ZIP and fixed the missing files.

Thanks for creating the issue and sorry for the inconvinience!
