### ISSUE TITLE
settings.general.json error

### ISSUE THREAD

**Issue by chisanen** [Legedric/ptmagic#400]
Hello,

I'm trying to run and set up PTM for the first time on a mac, and i keep getting this error: 

ERROR: PT Magic settings not found: '/Users/xxxx/Desktop/PTMagic/settings.general.json'. Please check if you setup PT Magic correctly!

How can I fix this?

**Comment by Legedric** [comment]
Seems like you missed step 6 here:
https://github.com/Legedric/ptmagic/wiki/Setup-PT-Magic-on-Windows

**Comment by TomBos** [comment]
But it worked for some time?

Op zo 8 apr. 2018 10:29 schreef Legedric <notifications@github.com>:

**Comment by chisanen** [comment]
@TomBos  yes there is

@Legedric i believe i  did step 6 right

 i coppied the "appsettings.json" file in the monitor file that was in the "_default settings BTC or ETH" folder which was in the "_default settings PT 1.x" folder..........( but there was also a "_default settings PT 2.x" folder which i did not touch

after i copied the "appsettings.json" file in the  monitor folder, i copied "settings.general.json", "settings.analyzer.json" and "nlog.config" which were in the "_default settings BTC or ETH" folder into the "PTmagic" folder

is this correct or wrong?

**Comment by chisanen** [comment]
<img width="568" alt="screen shot 2018-04-08 at 4 00 04 pm" src="https://user-images.githubusercontent.com/32966123/38472024-99e16030-3b47-11e8-9818-03b7baf37f28.png">

**Comment by Legedric** [comment]
Looks correct but somehow your settings.general.json doesn't seem to be there. There is nothing I can do about that other than telling you to double check it exists and no weird security things are blocking the access to it.

**Comment by TomBos** [comment]
@chisanen I see 2 times a folder (directory) named "ptmagic"

Check if your appsettings.json contains the right path, e.g.:
/Users/[name]/Desktop/PTMagic/PTMagic

**Comment by Legedric** [comment]
Closing this as no feedback was provided for some days now.
