### ISSUE TITLE
SUGGESTION - command execution before each iteration

### ISSUE THREAD

**Issue by bvebve** [Legedric/ptmagic#402]
My PT PAIRS.properties uses a on-the-fly made whitelist pairs. It's a script based on technical indicators that selects best pairs with specific values each (volume, strategies, profits, etc).

It would be great to run the script overwriting _presets (specific section of properties files) just before each PTMagic iteration.

Can you please add settings for external command execution?

**Comment by Legedric** [comment]
Not planning to do anything like this at the moment.
