### ISSUE TITLE
After update pmt from 1.4 to 1.5.1 y get some error 

### ISSUE THREAD

**Issue by mavverick** [Legedric/ptmagic#405]
Hi , after update ptm I get errors like this..

![image](https://user-images.githubusercontent.com/4382042/38474343-215c40e4-3b74-11e8-8fd2-b5bb1a84454d.png)

Thanks for youer help!
Regards

**Comment by mavverick** [comment]
Also this error ...

![image](https://user-images.githubusercontent.com/4382042/38474376-846037a4-3b74-11e8-8b33-229da86bfaba.png)

**Comment by cryptonz** [comment]
Do you use a Raspberry Pi?

**Comment by Legedric** [comment]
This should be fixed with the next release. If not, please report back.
