### ISSUE TITLE
PT selling error after updating to 1.5.x

### ISSUE THREAD

**Issue by agaji** [Legedric/ptmagic#406]
for some reason since updating, my coin specific sell values are being ignored for the default/global setting. 

ex. i have OMGBTC set as OMGBTC_sell_value = 35 , (which i had set for awhile and it was fine til i updated)
but the global setting is in ' bear sighted ' and my ALL_sell_value = .8 ..... PT will now ignore me specific value and sell for the global setting.

this has happened now 3x for me and i haven't changed a thing in PT
and the settings all worked fine for last 2mths 
everything has gone wonky since updating to 1.5.x

i had OMG set to sell at 35 and i had NCASH set to sell for 120 , both were ignored and sold for their respective global setting at the time.

ive had to set the trading_enabled = false feature for specific coins now to stop them from selling

**Comment by Legedric** [comment]
Please provide your pairs.properties and settings.analyzer.json here. (upload them)

**Comment by agaji** [comment]
[PAIRS.txt](https://github.com/Legedric/ptmagic/files/1890593/PAIRS.txt)
[settings.analyzer.txt](https://github.com/Legedric/ptmagic/files/1890598/settings.analyzer.txt)

**Comment by agaji** [comment]
i've uploaded as .txt files

**Comment by agaji** [comment]
sorry, i uploaded the way i have it now 

but my pairs file was like this before 
[PAIRS.txt](https://github.com/Legedric/ptmagic/files/1891552/PAIRS.txt)

**Comment by agaji** [comment]
i can't see anything there that would cause it to sell in global/default setting. but i don't know as much as you. its been like that for some time and it was fine , but i did the update and all of a sudden had this occur. with no other changes made.

im just bringing this up bc the only variable that changed was me updating to 1.5.x ... it could be some other reason, i don't know ... but i thought it was fair to share this with you

**Comment by Legedric** [comment]
Well, Profit Trailer always takes the most bottom occurance of a setting. Although I do not know if having your coin specific values listed ABOVE your global sell_value will make you global value overwrite the coin specific ones but you could definitley give that a try and move the whole block with your long terms holds to somewhere below the line with ALL_sell_value.
