### ISSUE TITLE
How to start PTMagic with pm2

### ISSUE THREAD

**Issue by azenator** [Legedric/ptmagic#41]
Hey folks,

you can start the bot using pm2 with the following File:

pm2.PTMagic.json
```
{
  "apps": [
    {
      "name": "PTMagic",
      "cwd": ".",
      "script": "PTMagic.dll",
      "node_args": [],
      "log_date_format": "YYYY-MM-DD HH:mm Z",
      "exec_interpreter": "dotnet",
      "exec_mode": "fork",
      "autorestart": false
    }
  ]
}
```

Now the Monitor:

pm2.PTM-Monitor.json:
```
{
  "apps": [
    {
      "name": "PTM-Monitor",
      "cwd": ".",
      "script": "Monitor/Monitor.dll",
      "node_args": [],
      "log_date_format": "YYYY-MM-DD HH:mm Z",
      "exec_interpreter": "dotnet",
      "exec_mode": "fork",
      "autorestart": false
    }
  ]
}
```

Put both files in the PTMagic dir and start the processes with:
`pm2 start pm2.PTMagic.json`
`pm2 start pm2.PTM-Monitor.json`

This might be easier to handle for some people.

Best Regards

**Comment by Legedric** [comment]
Thank you @azenator  for posting this! Would it be ok for you when we copy that into our wiki?

**Comment by azenator** [comment]
You are most welcome!

**Comment by azenator** [comment]
I dont want to open a new Issue. This package 

`apt-get install aspnetcore-store-2.0.5`

is needed for running PTMagic on Linux properly. Could be important to know for Linux users from your Wiki.

**Comment by TwixRaider** [comment]
Thanks a lot. Updated the Linux Guide with this info...

**Comment by Cryptoboss420** [comment]
where do I put these files
