### ISSUE TITLE
 ERROR - Unable to contact Binance for fresh market data

### ISSUE THREAD

**Issue by XM137** [Legedric/ptmagic#410]
Got this today and still having issue and I don't have a D:

2018/04/09 20:18:13.599 INFO -  
2018/04/09 20:18:13.655 INFO -   ██████╗ ████████╗    ███╗   ███╗ █████╗  ██████╗ ██╗ ██████╗ 
2018/04/09 20:18:13.655 INFO -   ██╔══██╗╚══██╔══╝    ████╗ ████║██╔══██╗██╔════╝ ██║██╔════╝ 
2018/04/09 20:18:13.655 INFO -   ██████╔╝   ██║       ██╔████╔██║███████║██║  ███╗██║██║      
2018/04/09 20:18:13.655 INFO -   ██╔═══╝    ██║       ██║╚██╔╝██║██╔══██║██║   ██║██║██║      
2018/04/09 20:18:13.655 INFO -   ██║        ██║       ██║ ╚═╝ ██║██║  ██║╚██████╔╝██║╚██████╗ 
2018/04/09 20:18:13.655 INFO -   ╚═╝        ╚═╝       ╚═╝     ╚═╝╚═╝  ╚═╝ ╚═════╝ ╚═╝ ╚═════╝ 
2018/04/09 20:18:13.655 INFO -                          Version 1.5.1 
2018/04/09 20:18:13.655 INFO -  
2018/04/09 20:18:13.882 INFO - Configuration loaded. Found 6 Market Trends, 6 Global Settings and 3 Single Market Settings. 
2018/04/09 20:18:13.882 INFO - Profit Trailer found 
2018/04/09 20:18:13.882 INFO - Trading directory found 
2018/04/09 20:18:13.882 INFO - Checking for Pairs Properties file 
2018/04/09 20:18:13.888 INFO - PAIRS.PROPERTIES found! 
2018/04/09 20:18:13.888 INFO - Checking for DCA Properties file 
2018/04/09 20:18:13.888 INFO - DCA.PROPERTIES found! 
2018/04/09 20:18:13.888 INFO - Checking for Indicators Properties file 
2018/04/09 20:18:13.888 INFO - INDICATORS.PROPERTIES found! 
2018/04/09 20:18:13.888 INFO - Checking automated settings for presets... 
2018/04/09 20:18:13.888 INFO - Prepared PAIRS.properties for 'Default' 
2018/04/09 20:18:13.903 INFO - Prepared DCA.properties for 'Default' 
2018/04/09 20:18:13.903 INFO - Prepared INDICATORS.properties for 'Default' 
2018/04/09 20:18:13.903 INFO - Checking market trends every 5 minutes... 
2018/04/09 20:18:13.976 INFO -  
2018/04/09 20:18:13.976 INFO - ########################################################## 
2018/04/09 20:18:13.976 INFO - #********************************************************# 
2018/04/09 20:18:13.976 INFO - Starting market trend check with Version 1.5.1 
2018/04/09 20:18:14.438 INFO - Loading current Profit Trailer properties files... 
2018/04/09 20:18:14.438 INFO - Files loaded - P (80 lines) - D (37 lines) - I (21 lines). 
2018/04/09 20:18:14.438 INFO - Loading Single Market Setting Summaries... 
2018/04/09 20:18:14.454 INFO - Single Market Setting Summaries loaded. 
2018/04/09 20:18:14.454 INFO - Profit Trailer Version 1.x.y detected... 
2018/04/09 20:18:14.468 INFO - CoinMarketCap - Getting market data... 
2018/04/09 20:18:14.624 INFO - CoinMarketCap - Market data received for 100 currencies 
2018/04/09 20:18:14.776 INFO - CoinMarketCap - 24h market data rebuilt. 
2018/04/09 20:18:14.779 INFO - CoinMarketCap - Market data saved. 
2018/04/09 20:18:14.779 INFO - CoinMarketCap - Market data cleaned. 
2018/04/09 20:18:14.779 INFO - Binance - Getting market data... 
2018/04/09 20:18:15.572 INFO - Binance - Getting main market price... 
2018/04/09 20:18:15.770 INFO - Binance - Market data received for BTCUSDT 
2018/04/09 20:18:15.770 INFO - Binance - Current price for BTCUSDT: 6,758.82 USD 
2018/04/09 20:18:15.777 INFO - Binance - Market data received for 299 currencies 
2018/04/09 20:18:15.777 INFO - Binance - Checking first seen dates for 120 markets. This may take a while... 
2018/04/09 20:18:15.777 FATAL - Exception while getting data for 'GRSBTC': Object reference not set to an instance of an object. System.NullReferenceException Object reference not set to an instance of an object.    at BusinessRules.MarketAnalyzer.Binance.CheckFirstSeenDates(Dictionary`2 markets, Dictionary`2& marketInfos, SystemConfiguration systemConfiguration, LogHelper log) in D:\Tools\PTMagic\BusinessRules\MarketAnalyzer\Binance.cs:line 110
   at BusinessRules.MarketAnalyzer.Binance.GetMarketData(String mainMarket, Dictionary`2& marketInfos, SystemConfiguration systemConfiguration, LogHelper log) in D:\Tools\PTMagic\BusinessRules\MarketAnalyzer\Binance.cs:line 76
2018/04/09 20:18:15.816 ERROR - Unable to contact Binance for fresh market data. Trying again in 5

**Comment by Legedric** [comment]
This should be fixed with the next release.

**Comment by Flexa** [comment]
i have this issue with a fresh installed version. 2.0.1
