### ISSUE TITLE
Wrong Sell Trigger value displayed

### ISSUE THREAD

**Issue by MagicLazy** [Legedric/ptmagic#413]
Wrong Sell Trigger values are displayed in "DCA AND BOUGHT PAIRS ANALYZER" table.
Value are correctly displayed in Profit Trail "Pair logs" and "DCA logs"
![capture](https://user-images.githubusercontent.com/38259749/38573691-25e8a8d0-3cf7-11e8-9b91-2f7446d8ef97.JPG)

**Comment by Legedric** [comment]
Can you please upload your ProfitTrailerData.json here so I can investigate this issue? Thanks!

**Comment by MagicLazy** [comment]
[ProfitTrailerData.zip](https://github.com/Legedric/ptmagic/files/1895926/ProfitTrailerData.zip)
