### ISSUE TITLE
Still unable to contact Binance after 1.52

### ISSUE THREAD

**Issue by romexy** [Legedric/ptmagic#418]
Updated to 1.52 but still getting this:

2018/04/12 15:12:47.506 INFO -
2018/04/12 15:12:47.624 INFO -   ██████╗ ████████╗    ███╗   ███╗ █████╗  ██████╗ ██╗ ██████╗
2018/04/12 15:12:47.624 INFO -   ██╔══██╗╚══██╔══╝    ████╗ ████║██╔══██╗██╔════╝ ██║██╔════╝
2018/04/12 15:12:47.624 INFO -   ██████╔╝   ██║       ██╔████╔██║███████║██║  ███╗██║██║
2018/04/12 15:12:47.624 INFO -   ██╔═══╝    ██║       ██║╚██╔╝██║██╔══██║██║   ██║██║██║
2018/04/12 15:12:47.624 INFO -   ██║        ██║       ██║ ╚═╝ ██║██║  ██║╚██████╔╝██║╚██████╗
2018/04/12 15:12:47.635 INFO -   ╚═╝        ╚═╝       ╚═╝     ╚═╝╚═╝  ╚═╝ ╚═════╝ ╚═╝ ╚═════╝
2018/04/12 15:12:47.635 INFO -                          Version 1.5.2
2018/04/12 15:12:47.635 INFO -
2018/04/12 15:12:48.155 INFO - Configuration loaded. Found 8 Market Trends, 2 Global Settings and 1 Single Market Settings.
2018/04/12 15:12:48.155 INFO - Profit Trailer found
2018/04/12 15:12:48.155 INFO - Trading directory found
2018/04/12 15:12:48.155 INFO - Checking for Pairs Properties file
2018/04/12 15:12:48.155 INFO - PAIRS.PROPERTIES found!
2018/04/12 15:12:48.155 INFO - Checking for DCA Properties file
2018/04/12 15:12:48.167 INFO - DCA.PROPERTIES found!
2018/04/12 15:12:48.167 INFO - Checking for Indicators Properties file
2018/04/12 15:12:48.167 INFO - INDICATORS.PROPERTIES found!
2018/04/12 15:12:48.167 INFO - Checking automated settings for presets...
2018/04/12 15:12:48.187 INFO - Prepared PAIRS.properties for 'Default'
2018/04/12 15:12:48.187 INFO - Prepared DCA.properties for 'Default'
2018/04/12 15:12:48.187 INFO - Prepared INDICATORS.properties for 'Default'
2018/04/12 15:12:48.187 INFO - Checking market trends every 5 minutes...
2018/04/12 15:12:48.314 INFO -
2018/04/12 15:12:48.314 INFO - ##########################################################
2018/04/12 15:12:48.314 INFO - #********************************************************#
2018/04/12 15:12:48.314 INFO - Starting market trend check with Version 1.5.2
2018/04/12 15:12:48.975 INFO - Loading current Profit Trailer properties files...
2018/04/12 15:12:48.983 INFO - Files loaded - P (0 lines) - D (35 lines) - I (27 lines).
2018/04/12 15:12:48.983 INFO - Loading Single Market Setting Summaries...
2018/04/12 15:12:48.983 INFO - Profit Trailer Version 1.x.y detected...
2018/04/12 15:12:49.034 INFO - CoinMarketCap - Getting market data...
2018/04/12 15:12:49.081 INFO - CoinMarketCap - Market data received for 100 currencies
2018/04/12 15:12:49.401 INFO - CoinMarketCap - 24h market data rebuilt.
2018/04/12 15:12:49.401 INFO - CoinMarketCap - Market data saved.
2018/04/12 15:12:49.421 INFO - CoinMarketCap - Market data cleaned.
2018/04/12 15:12:49.431 INFO - Binance - Getting market data...
2018/04/12 15:12:50.429 INFO - Binance - Getting main market price...
2018/04/12 15:12:50.718 FATAL - The remote server returned an error: (400) Bad Request. System.Net.WebException The remote server returned an error: (400) Bad Request.    at System.Net.HttpWebRequest.GetResponse()
   at BusinessRules.MarketAnalyzer.BaseAnalyzer.GetSimpleJsonObjectFromURL(String url, LogHelper log, Boolean onlyLogDebug) in D:\Tools\PTMagic\BusinessRules\MarketAnalyzer\BaseAnalyzer.cs:line 48
2018/04/12 15:12:50.825 FATAL - The remote server returned an error: (400) Bad Request. System.Net.WebException The remote server returned an error: (400) Bad Request.    at BusinessRules.MarketAnalyzer.BaseAnalyzer.GetSimpleJsonObjectFromURL(String url, LogHelper log, Boolean onlyLogDebug) in D:\Tools\PTMagic\BusinessRules\MarketAnalyzer\BaseAnalyzer.cs:line 59
   at BusinessRules.MarketAnalyzer.Binance.GetMainCurrencyPrice(String mainMarket, SystemConfiguration systemConfiguration, LogHelper log) in D:\Tools\PTMagic\BusinessRules\MarketAnalyzer\Binance.cs:line 21
2018/04/12 15:12:50.867 INFO - Binance - Market data received for 299 currencies
2018/04/12 15:12:50.872 ERROR - Binance - Failed to get main market price for .
2018/04/12 15:12:50.872 ERROR - Unable to contact Binance for fresh market data. Trying again in 5 minute(s).

**Comment by angelsomar** [comment]
It happens to me only in the USDT

running BTC and ETH well, only with a price error.

2018/04/12 22:35:19.622 INFO - Binance - Recreating market data for 7 markets over 1d 9h 56m 20s. This may take a while...
2018/04/12 22:35:20.393 FATAL - The remote server returned an error: (400) Bad Request. System.Net.WebException The remote server returned an error: (400) Bad Request.    at System.Net.HttpWebRequest.GetResponse()
   at BusinessRules.MarketAnalyzer.BaseAnalyzer.GetSimpleJsonArrayFromURL(String url, LogHelper log) in D:\Tools\PTMagic\BusinessRules\MarketAnalyzer\BaseAnalyzer.cs:line 106
2018/04/12 22:35:20.393 ERROR - Unable to get data from Binance with URL 'https://api.binance.com/api/v1/klines?interval=1m&symbol=USDTUSDT&endTime=1523590519639&limit=500'! - Code: -1121 - Message: Invalid symbol.
2018/04/12 22:36:29.085 INFO - Binance - Ticks completed.
2018/04/12 22:36:29.085 INFO - Binance - Creating initial market data ticks. This may take another while...
2018/04/12 22:36:29.085 FATAL - Exception while getting data for 'QTUMUSDT': Object reference not set to an instance of an object. System.NullReferenceException Object reference not set to an instance of an object.    at BusinessRules.MarketAnalyzer.Binance.CheckForMarketDataRecreation(String mainMarket, Dictionary`2 markets, SystemConfiguration systemConfiguration, LogHelper log) in D:\Tools\PTMagic\BusinessRules\MarketAnalyzer\Binance.cs:line 303
   at BusinessRules.MarketAnalyzer.Binance.GetMarketData(String mainMarket, Dictionary`2& marketInfos, SystemConfiguration systemConfiguration, LogHelper log) in D:\Tools\PTMagic\BusinessRules\MarketAnalyzer\Binance.cs:line 81
2018/04/12 22:36:29.094 ERROR - Unable to contact Binance for fresh market data. Trying again in 5 minute(s).

![image](https://user-images.githubusercontent.com/36096512/38715737-830fab9c-3ea2-11e8-8b12-5ee8d405c9ce.png)

**Comment by Legedric** [comment]
@angelsomar This is a known issue and will be fixed in the next release.

@romexy It seems to be a connection/routing issue fromy our machine to Binance as there is no additional error information (like seens in the message posted by angelsomar).

**Comment by JustinBanon** [comment]
I am getting this error too.  Has it been fixed? 
![image](https://user-images.githubusercontent.com/4339518/40320237-d6b14adc-5d22-11e8-8c85-5836e5097678.png)

**Comment by Legedric** [comment]
That's a Binance issue, not PTM.

**Comment by JustinBanon** [comment]
Ahh.  Do you know if it is intermittent / likely to resolve or more permanent?
