### ISSUE TITLE
Do I need Windows Server Hosting (.exe)?

### ISSUE THREAD

**Issue by Crypto-Bites** [Legedric/ptmagic#42]
I run PT on my windows PC and was wondering do I need to install Windows Server Hosting (.exe) to make PTM work?

If not, do I need to do anything to allow for http://localhost:5000/ through my firewall?

**Comment by sitespagando** [comment]
yes you need it, do it all CONFORMING THE INSTALLATION MANUAL and be aware that you should put \\ and not just \ at the time of copying the pt and pt magic location

LINK: https://github.com/Legedric/ptmagic/wiki/Setup-PT-Magic-on-Windows
