### ISSUE TITLE
DOTNET CRASH AFTER 1.5.2 UPGRADE

### ISSUE THREAD

**Issue by mfcholdings** [Legedric/ptmagic#422]
my dotnet is now crashing after 1.5.2 install and getting many errors..    saying it can not find pairs....

**Comment by Legedric** [comment]
Screenshot please...

**Comment by mfcholdings** [comment]
can i send you my logs here

**Comment by Legedric** [comment]
Either upüload a txt containing the errors or a screenshot showing them in the command line window.

**Comment by mfcholdings** [comment]
![pt magic 1](https://user-images.githubusercontent.com/36377757/38771574-c2d5b486-4025-11e8-9a7b-5e5faa2a28b1.png)

**Comment by Legedric** [comment]
Did you check what the error is saying? PTM checks now if your presets files are there and if not, throws this error...

**Comment by mfcholdings** [comment]
where would i find this file... i have never had this issue before.. also why would dotnet be crashing because of this..

**Comment by Legedric** [comment]
In your _presets/Default folder.

dotnet is not crashing, PTM is throwing this exception on purpose and terminates the process. If it would not (like before 1.5.2) it would cause trouble with your settings.

**Comment by mfcholdings** [comment]
i have nothing in that folder...  
and when i run ptm my dotnet says it stopped working and closes... 

what is your suggestion.. 
how can i get that file in my folder...

**Comment by Legedric** [comment]
Seems like you missed step 7 of the installation instructions:
https://github.com/Legedric/ptmagic/wiki/Setup-PT-Magic-on-Windows

**Comment by mfcholdings** [comment]
great.. thanks.. your software is great, but your service is even better.. A+++++
