### ISSUE TITLE
[Enhancement/Feature] Override settings for specific coins in bag analyzer

### ISSUE THREAD

**Issue by Fransenson** [Legedric/ptmagic#423]
It would be nice to to be able to set coin specific settings in the bag analyzer.

those settings should override anything the analyzer itself applies for the respective market conditions.

Case that would make this useful: 

Bought a coin manually, have a specific sell value and trailing in mind for it, set it in pairs.properties.

The issue being: those settings are overwritten by PTMs single market settings.

**Comment by Legedric** [comment]
As you can ignore coins in SMS by now I think this should no longer be necessary.
