### ISSUE TITLE
No executable found matching command "dotnet-Monitor/Monitor.dll"

### ISSUE THREAD

**Issue by OatmealTokyo** [Legedric/ptmagic#425]
OS: Mac OS X

Per instructions to start the monitor application with:

dotnet Monitor/Monitor.dll

I am in terminal, in PTMagic folder and entered 'dotnet Monitor/Monitor.dll'

I get the following error:

No executable found matching command "dotnet-Monitor/Monitor.dll"

**Comment by dmzpkts** [comment]
I had the same issue. Installing dotnet-runtime-2.0.0-win-x64 Fixed it for me.

**Comment by dmzpkts** [comment]
You may try the same version for mac

**Comment by OatmealTokyo** [comment]
Per instructions. I downloaded dotnet-sdk-2.1.105-osx-gs-x64.pkg as Step 1 in the instructions.  I tried looking for dotnet-runtime-2.0.0-win-x64 for MAC but the download was not available.  Do you know where I can find it?  In addition I followed the instructions as stated but no look with the 2.1.105. Thanks.
