### ISSUE TITLE
Exclude Main Currency within browser editor reverts back

### ISSUE THREAD

**Issue by jshplayer** [Legedric/ptmagic#428]
When you adjust the exclude main currency it removes the line of code as it's supposed to within the .json but if you then reload the page it shows it's enabled again ( when it's not ) if you then apply any settings it will re-enable the exclude main currency as it's staying toggled on.

**Comment by Legedric** [comment]
Could you please provide a step by step instruction on how to reproduce this issue? Ideally with screenshots?
Thanks!

**Comment by jshplayer** [comment]
Hey man, ps: loving your addon great work - so this is what i'm doing:

I disabled the 
![image](https://user-images.githubusercontent.com/38491909/38922490-6457bec0-434c-11e8-8ce6-0466922090c0.png)



I then tried to disable the markets individual exclude main currency option but i figure this is unnecessary.

I refresh and find all markets with the exclude main currency turned off but the main root level exclude main currency turned on - if i then ever save the page it will re enable it at the root.

I have since left exclude main currency on as i like the in browser editor but using it will always re-enable this function.

**Comment by jshplayer** [comment]
Disabled or enabling that toggle will correctly edit:

![image](https://user-images.githubusercontent.com/38491909/38922559-93f30b8a-434c-11e8-8aad-0f7b53737eba.png)

But always for me default to the on position, as if it isn't reading the correct on off state within the browser.

**Comment by jshplayer** [comment]
This is all fixed thanks man
