### ISSUE TITLE
[suggestion] Multiple-instance dashboard

### ISSUE THREAD

**Issue by boogieman1402** [Legedric/ptmagic#431]
When running multiple PT and PTM instances, it would be great to have a single page overview of all instances at once. Just a simple table listing today's sales overview and (if browser width permits) last week and/or all time for each bot.

**Comment by Legedric** [comment]
While I do know that some people are using multiple instances of PTM, it is not a key feature of our addon and never probably will be. Therefore it doesn't get any priority in the development of extra features.
