### ISSUE TITLE
Freefall settings cant be changed

### ISSUE THREAD

**Issue by Tim19900** [Legedric/ptmagic#434]
I changed my freefall settings but even though my settings dont appear in my PT magic nor my analyzer.json file, the old settings keep coming back in my profittrailer pairs settings file.

**Comment by Legedric** [comment]
This will be fixed with the next release.

**Comment by Tim19900** [comment]
It still happens to me, my old settings for Freefall Block in PT Magic keep appearing.

**Comment by Legedric** [comment]
Please update to PTM 1.6.1 @Tim19900

**Comment by Tim19900** [comment]
Hi, thanks for your response. I did, but it still happens.

**Comment by Legedric** [comment]
Ok then please explain as detailed as possible what you changed and what the result ist (ideally with screenshots).
