### ISSUE TITLE
Not updating the Version

### ISSUE THREAD

**Issue by cryptomail2018** [Legedric/ptmagic#435]
in the CMD screen it still tells the previous version number after installing the new version .. 
tried this several times on all 4 boths running and re-downloaded . this also did not solve this issue

**Comment by Legedric** [comment]
Screenshot please.

**Comment by cryptomail2018** [comment]
![screen shot 2018-04-20 at 20 14 18](https://user-images.githubusercontent.com/35930742/39045886-9add7ee4-44d7-11e8-98da-4d3a86af4b8f.png)

**Comment by cryptomail2018** [comment]
its definitely the Version 1.5.2 what i downloaded from your Github and installed several times

**Comment by Legedric** [comment]
It has to be an issue on your end. The version is directly read from the bot itself so you did not replace the files correctly when updating PTM.
