### ISSUE TITLE
Profit Trailer 2 server side config

### ISSUE THREAD

**Issue by jshplayer** [Legedric/ptmagic#436]
Hey there, just wondering how PT Magic handles the new v2 config files as once they upload they're only editable via the web interface? Putting off the Profit Trailer 2 upgrade until it's stable and i'd rather use the current one if it's not compatible with PT Magic.

**Comment by Legedric** [comment]
PTM is NOT compatible with PT 2.0 yet! We are currently in internal testing of the new PTM version that will work with PT 2.0.
