### ISSUE TITLE
Error 

### ISSUE THREAD

**Issue by Chiddy101** [Legedric/ptmagic#437]
2018/04/20 20:33:46.097 INFO -
2018/04/20 20:33:46.125 INFO - ##########################################################
2018/04/20 20:33:46.186 INFO - #********************************************************#
2018/04/20 20:33:46.232 INFO - Starting market trend check with Version 1.5.1
2018/04/20 20:33:46.252 INFO - Loading current Profit Trailer properties files...
2018/04/20 20:33:46.252 INFO - Files loaded - P (883 lines) - D (35 lines) - I (22 lines).
2018/04/20 20:33:46.270 INFO - Loading Single Market Setting Summaries...
2018/04/20 20:33:46.328 INFO - Single Market Setting Summaries loaded.
2018/04/20 20:33:46.343 INFO - Profit Trailer Version 1.x.y detected...
2018/04/20 20:33:46.353 INFO - CoinMarketCap - Getting market data...
2018/04/20 20:33:46.462 INFO - CoinMarketCap - Market data received for 100 currencies
2018/04/20 20:33:47.638 INFO - CoinMarketCap - Market data saved.
2018/04/20 20:33:47.753 INFO - CoinMarketCap - Market data cleaned.
2018/04/20 20:33:47.753 INFO - Binance - Getting market data...
2018/04/20 20:33:48.336 INFO - Binance - Getting main market price...
2018/04/20 20:33:48.665 INFO - Binance - Market data received for ETHUSDT
2018/04/20 20:33:48.673 INFO - Binance - Current price for ETHUSDT: 615.19 USD
2018/04/20 20:33:48.673 INFO - Binance - Market data received for 302 currencies
2018/04/20 20:33:48.673 INFO - Binance - Checking first seen dates for 119 markets. This may take a while...
_2018/04/20 20:33:48.673 FATAL - Exception while getting data for 'CLOAKETH': Object reference not set to an instance of an object. System.NullReferenceException Object reference not set to an instance of an object.    at BusinessRules.MarketAnalyzer.Binance.CheckFirstSeenDates(Dictionary`2 markets, Dictionary`2& marketInfos, SystemConfiguration systemConfiguration, LogHelper log) in D:\Tools\PTMagic\BusinessRules\MarketAnalyzer\Binance.cs:line 110
   at BusinessRules.MarketAnalyzer.Binance.GetMarketData(String mainMarket, Dictionary`2& marketInfos, SystemConfiguration systemConfiguration, LogHelper log) in D:\Tools\PTMagic\BusinessRules\MarketAnalyzer\Binance.cs:line 76
2018/04/20 20:33:48.699 ERROR - Unable to contact Binance for fresh market data. Trying again in 1 minute(s)._

**Comment by Legedric** [comment]
Closing this as this is related to an old version of PTM.
