### ISSUE TITLE
Telegram - Test Connection

### ISSUE THREAD

**Issue by Cryptonic2** [Legedric/ptmagic#44]
Is there a way to test the telegram connection to PT Magic to ensure it is set up properly? Also, what messages should we expect to receive on Telegram?

**Comment by Legedric** [comment]
Not yet, it should look something like this:
![image](https://user-images.githubusercontent.com/8308141/36391861-b9dd79c4-15a8-11e8-8bbd-0870fef2dcc4.png)

**Comment by Cryptonic2** [comment]
Great thanks! I got it to work for my personal chat ID, but it doesn’t appear to work in group chats for Telegram. Could it be because of the “-“ that goes in front of the Chat ID not being a valid character? PT requires for the dash to be used so I’m wondering if it is necessary or not in PT Magic.

**Comment by jamesblackjr** [comment]
I had to turn this feature off, it was spamming me every minute, I would like to receive a message **only** when the settings change.

**Comment by Legedric** [comment]
@jamesblackjr Usually it does exactly that. I have to figure out what is wrong with your instance as I never had that prohblem.

When you run PT Magic, does it actually change your PT files? Like at least changing the header and adding some comments from PT Magic to it?

**Comment by Legedric** [comment]
#48
