### ISSUE TITLE
ProfitTrailer 2.0?

### ISSUE THREAD

**Issue by LeeUmney** [Legedric/ptmagic#442]
Are there any plans to make the changes for this to work with PT2.0? When I currently try to run Start_PTMagic.cmd using the PT2.0 folder I get the error:
Trading Settings directory not found (C:\ProfitTrailer2\trading)
The *.properties files are kept in %PTFolder%\Initialization now, there isn't a trading folder in 2.0

**Comment by Legedric** [comment]
PTM is NOT compatible with PT 2.0 yet! We are currently in internal testing of the new PTM version that will work with PT 2.0.

**Comment by LeeUmney** [comment]
I agree, I upgraded to PT2.0 but after having PTM on PT1 it really seems to be missing things I liked in 1.0 with PTM.
I still have PT1 with PTM setup on my system so I can just flip back to that until PTM supports 2.0.
