### ISSUE TITLE
In USDT

### ISSUE THREAD

**Issue by angelsomar** [Legedric/ptmagic#445]
2018/04/23 06:59:54.767 FATAL - The remote server returned an error: (429) Too Many Requests. System.Net.WebException The remote server returned an error: (429) Too Many Requests.    at System.Net.HttpWebRequest.GetResponse()
   at BusinessRules.MarketAnalyzer.BaseAnalyzer.GetSimpleJsonArrayFromURL(String url, LogHelper log) in D:\Tools\PTMagic\BusinessRules\MarketAnalyzer\BaseAnalyzer.cs:line 106
2018/04/23 06:59:54.982 ERROR - Unable to get data from Binance with URL 'https://api.binance.com/api/v1/klines?interval=1m&symbol=BTCUSDT&endTime=1524244777442&limit=500'! - Code: -1003 - Message: Too many requests; current limit is 1200 requests per minute. Please use the websocket for live updates to avoid polling the API.
2018/04/23 06:59:57.074 FATAL - The remote server returned an error: (429) Too Many Requests. System.Net.WebException The remote server returned an error: (429) Too Many Requests.    at System.Net.HttpWebRequest.GetResponse()
   at BusinessRules.MarketAnalyzer.BaseAnalyzer.GetSimpleJsonArrayFromURL(String url, LogHelper log) in D:\Tools\PTMagic\BusinessRules\MarketAnalyzer\BaseAnalyzer.cs:line 106
2018/04/23 06:59:57.107 ERROR - Unable to get data from Binance with URL 'https://api.binance.com/api/v1/klines?interval=1m&symbol=ETHUSDT&endTime=1524484794989&limit=500'! - Code: -1003 - Message: Too many requests; current limit is 1200 requests per minute. Please use the websocket for live updates to avoid polling the API.
2018/04/23 06:59:57.958 FATAL - The remote server returned an error: (429) Too Many Requests. System.Net.WebException The remote server returned an error: (429) Too Many Requests.    at System.Net.HttpWebRequest.GetResponse()
   at BusinessRules.MarketAnalyzer.BaseAnalyzer.GetSimpleJsonArrayFromURL(String url, LogHelper log) in D:\Tools\PTMagic\BusinessRules\MarketAnalyzer\BaseAnalyzer.cs:line 106
2018/04/23 06:59:57.995 ERROR - Unable to get data from Binance with URL 'https://api.binance.com/api/v1/klines?interval=1m&symbol=BNBUSDT&endTime=1524484797114&limit=500'! - Code: -1003 - Message: Too many requests; current limit is 1200 requests per minute. Please use the websocket for live updates to avoid polling the API.

2018/04/23 07:03:09.921 FATAL - Exception while getting data for 'ADAUSDT': Object reference not set to an instance of an object. System.NullReferenceException Object reference not set to an instance of an object.    at BusinessRules.MarketAnalyzer.Binance.CheckForMarketDataRecreation(String mainMarket, Dictionary`2 markets, SystemConfiguration systemConfiguration, LogHelper log) in D:\Tools\PTMagic\BusinessRules\MarketAnalyzer\Binance.cs:line 315
   at BusinessRules.MarketAnalyzer.Binance.GetMarketData(String mainMarket, Dictionary`2& marketInfos, SystemConfiguration systemConfiguration, LogHelper log) in D:\Tools\PTMagic\BusinessRules\MarketAnalyzer\Binance.cs:line 81
2018/04/23 07:03:09.948 ERROR - Unable to contact Binance for fresh market data. Trying again in 5 minute(s).

**Comment by Legedric** [comment]
How many bots are you running on that machine/account?

**Comment by angelsomar** [comment]
in 5 minutes it is solved thanks
