### ISSUE TITLE
PT Magic not connecting to PT (v2) that runs on SSL

### ISSUE THREAD

**Issue by xbrand** [Legedric/ptmagic#447]
Does running PTv2 on SSL require specific config for PT Magic or it's just not supported ?

**Comment by Legedric** [comment]
What did you specify as ProfitTrailerMonitorURL?

**Comment by xbrand** [comment]
this is the line in my config:
 "ProfitTrailerMonitorURL": "https://127.0.0.1:8087/", // The URL to your profit trailer monitor (needed to change your settings for PT 2.0 and above)

I tried with the public address as well, but it's same result. 

This is the error I'm seeing:
2018/04/23 19:18:04.666 ERROR - Your Profit Trailer monitor (https://127.0.0.1:8087/) is not 
available! The monitor URL is necessary to adjust your Profit Trailer settings since 2.0

**Comment by Legedric** [comment]
hmmm that may be the case as the certificate may not go through validation.

**Comment by duckybsd** [comment]
Same problem here, used a self-signed certificate, not able to get it working. Can you remove the certificate validation?

**Comment by 7wonders** [comment]
I have a bit of a strange one with this issue. I am using SSL with real domain and letsencrypt signed cert. If I use the https it throws the 'is not available' message but if I use http (which is redirected to https) then it works ¯\_(ツ)_/¯
