### ISSUE TITLE
How is exchange between _presets/Default and PT settings working?

### ISSUE THREAD

**Issue by smoochy** [Legedric/ptmagic#449]
Hi Legedric,

thanks for deciding to continue development on PTM.

I was wondering about how the exchange between the pairs.properties, dca.properties and indicators.properties and PT is working.

Since 2.0 changes will be only accepted via PT Web GUI. Are changes, I made there be put into any of the 3 PTM files?

Will changes in any of these 3 PTM files filled into the PT settings (after removing the header in any of the files)?

Thanks,
smoo

**Comment by Legedric** [comment]
PTM still works the way it did like before. The only thing that changed is the reading and writing of settings.
PTM now reads the settings from the API built into PT's monitor and uses the same way to write to it.

Of course the presets files work just like before, so any change there will get applied to PT in the next run, even withour removing the header as PTM checks for file changes in your presets.

**Comment by RGAlexander216** [comment]
So I know this is closed, but I doubt I really would suggest putting how this on your wiki. I'm was so confused about this, specifically about whether or not the _presets\Default was even needed anymore.

Thanks for everything.
