### ISSUE TITLE
Updated to 1.6.1. The handler does not support custom handling of certificates

### ISSUE THREAD

**Issue by clippart** [Legedric/ptmagic#450]
Good day! I do not use any certificates, what kind of error is that?

3|ptmagic  | 2018-04-24 13:25 +07:00: System.PlatformNotSupportedException: The handler does not support custom handling of certificates with this combination of libcurl (7.59.0) and its SSL backend ("NSS/3.28.4").
3|ptmagic  |    at System.Net.HttpWebRequest.GetResponse()
3|ptmagic  |    at Globals.SystemHelper.UrlIsReachable(String url) in D:\Tools\PTMagic\Globals\SystemHelper.cs:line 810
3|ptmagic  |    at PTMagic.Program.Main(String[] args) in D:\Tools\PTMagic\PTMagic\Program.cs:line 168

**Comment by Legedric** [comment]
Seems like .NET core does not supprt NSS for libcurl so you need to use a libcurl version that uses openssl:
https://curl.haxx.se/docs/install.html

**Comment by Zamboniman** [comment]
I'm using libcurl with openssl.

I just upgraded to 1.6.1 and am also getting this error, so a version of libcurl with openssl doesn't help.

`Unhandled Exception: System.PlatformNotSupportedException: The handler does not support custom │
handling of certificates with this combination of libcurl (7.59.0) and its SSL backend ("OpenSS│
L/1.1.0g").`

**Comment by Legedric** [comment]
Unfortunately you will have to sort this out on your own. We do not use Linux and so we cannot reproduce or help with that issue.

**Comment by Zamboniman** [comment]
The new preview version of dotnet-2.1.0, seems to have solved this issue.

For Linux, I recommend upgrading dotnet to the beta version. If not available in your distro you'll need to download and install it manually. Instructions for this are in Issue 65, but update the files accordingly.

**Comment by raphauy** [comment]
clipart, any solution?
dotnet update?
move to Ubuntu?

**Comment by raphauy** [comment]
does it work for you?
I installed this preview2 following these steps:
sudo rpm -Uvh https://packages.microsoft.com/config/rhel/7/packages-microsoft-prod.rpm
sudo yum update
sudo yum install libunwind libicu
sudo yum install dotnet-runtime-2.1.0-preview2-26406-04

 dotnet --info
.NET Command Line Tools (2.1.4)

Product Information:
 Version:            2.1.4
 Commit SHA-1 hash:  5e8add2190

Runtime Environment:
 OS Name:     centos
 OS Version:  7
 OS Platform: Linux
 RID:         centos.7-x64
 Base Path:   /usr/share/dotnet/sdk/2.1.4/

Host (useful for support):
  Version: 2.1.0-preview2-26406-04
  Commit:  6833f3026b

.NET Core SDKs installed:
  2.1.4 [/usr/share/dotnet/sdk]

.NET Core runtimes installed:
  Microsoft.NETCore.App 2.0.5 [/usr/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.0-preview2-26406-04 [/usr/share/dotnet/shared/Microsoft.NETCore.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download

any ideas?

**Comment by clippart** [comment]
Yes, it work
yum remove dotnet*

do the following
sudo yum install dotnet-runtime-2.1.0-preview2-26406-04

**Comment by raphauy** [comment]
clipart thanks for the reply. I solved the problem recompiling curl with openssl.

I leave the instructions here in case it serves someone:

https://i.gyazo.com/fc6652311c318bda39f95084b971175b.png

Thank you.
