### ISSUE TITLE
Layout of properties files

### ISSUE THREAD

**Issue by TomBos** [Legedric/ptmagic#451]
Is it possible to keep the layout as is?

All whitelines are removed, like:

ETH_dust = 0.00999
#BUY SETTINGS
enabled_pairs = ALL

Was (is in original)
ETH_dust = 0.00999

#BUY SETTINGS

enabled_pairs = ALL

**Comment by Legedric** [comment]
@TomBos 
Unfortunately that's Profit Trailer's API that does that. PTM transfers the data including the empty lines but PT doesn't save it like this through the API for whatever reason.

**Comment by TomBos** [comment]
NP, I'll use some more #-signs!
