### ISSUE TITLE
Enhancement: times_dca as condition for SMS

### ISSUE THREAD

**Issue by Fransenson** [Legedric/ptmagic#455]
Hey there! 

As far as I know, PT stores the boughtTimes of it's pairs with the other data. I'd love to set single market settings depending on the amount of times a coin dca'ed. 

As a small example:

DCA 1 sell value = 2%
DCA 2 sell value = 1%
DCA 3 sell value = 0.8%
...

Having this as trigger would allow for crazy deep customization and better risk management within the DCA log. 

Combining times_dca with something like the 24hr trend could help setting really specific strategies depending on capital I sunk into one pair.

**Comment by HojouFotytu** [comment]
see https://github.com/PTMagicians/PTMagic/issues/119
