### ISSUE TITLE
PTM shuts completely off when PT URL not reachable

### ISSUE THREAD

**Issue by smoochy** [Legedric/ptmagic#457]
Hi there,

I am doing a nightly restart of PT, PTT and PTM.

I noticed this morning, when waking up and checking the status of my 2nd PT Bot (which is running in testmode attached with PTM to it) that I was greeted with the setup screen to select my settings from the dropdown menu.
I logged in. Everything looked to be ok.

When I checked the PTM website, I noticed the little red triangle with exclamation mark, asking me to check log files. So I did.

See the log files here: https://pastebin.com/U7vKCnBC

Here is what is nightly happen with Crontab (Scheduling automatically restart of tasks) :

![image](https://user-images.githubusercontent.com/34371932/39230537-1da63158-4867-11e8-96b9-6bc78f201912.png)

As I know you are not so familiar with Unix (as am I) you can see the syntax of crontab here: https://crontab.guru/

You can see, that I am basically restarting my livebot
pt- ProfitTrailer at 4am
ptt - ProfitTrailer Tracker at 4.01am
ptm - PTMagic at 4.02am and
ptmm - PTMagic Monitor at 4.03am

This worked.

After this is done, I am restarting my testbot instances.
pt2- ProfitTrailer at 4.05am
ptt2 - ProfitTrailer Tracker at 4.06am
ptm2 - PTMagic at 4.07am and
ptmm2 - PTMagic Monitor at 4.08am

At 4.07am, you can see that PTM has issues communicating with PT. I guess, that it is stuck at the "Select your settings or create new" screen of PT.

This did not happen with my live PT bot after the restart of PT, PTM and PTMM though.

Setup:
PT 2.0 with server.disable_online_config = true <<< did not check yet, if there is also issues when using false
PTM 1.6.1 

If I can provide more information, let me know.

**Comment by smoochy** [comment]
I just updated PT. I stopped PT, but let PTM running. 
As PT was offline during a run of PTM, PTM stopped working again while trying to reach PT.

![image](https://user-images.githubusercontent.com/34371932/39274221-8daccc94-48e1-11e8-8874-71f89ab7f198.png)

**Comment by Legedric** [comment]
Yes, PTM dies as soon as it is unable to load the settings via the PT GUI because it expects that it will stay down.
I may change that ina future release to continue to try agan with the next interval.

**Comment by Ridonia** [comment]
I got the same issue.
I understand why PtM is stoping - maybe there should be a retry... But the actual problem is that PT restarts in "setup" after restart when using PTM
