### ISSUE TITLE
How to remove Sell strategies

### ISSUE THREAD

**Issue by chriswong23** [Legedric/ptmagic#458]
I have my default sell strategies as DEFAULT_A_sell_strategy = GAIN & DEFAULT_B_sell_strategy = EMASPREAD. How can I remove one of the strategy in a Global setting and just have one strategy like DEFAULT_A_sell_strategy = GAIN only.

**Comment by Fransenson** [comment]
I think you'd have to overwrite the existing strategy. Like set it to nothing

"DEFAULT_B_sell_strategy": , 

I have not tried this, just an idea. you could also try to set a strategy that is just always true (like LOWBB with -100 to 100 value / limit)

**Comment by Fransenson** [comment]
Found out via the PT Wiki, that “DISABLED” is a valid value for a strategy. Just set it to that then :)
