### ISSUE TITLE
Market Trend Dashboard Order

### ISSUE THREAD

**Issue by jshplayer** [Legedric/ptmagic#465]
This isn't an issue, but could the trend dashboard be ordered based on the order of trends within the config, instead of what currently looks like being based on time frame. 

IE: BTC 24H is actually at the bottom of the config for trends, and telegram orders it correctly on messages, but the dashboard orders it by time frame and then alphabetically by the looks.

thanks for all the hard work :)

![image](https://user-images.githubusercontent.com/38491909/39390099-1d992fc4-4ae4-11e8-8bc7-a689971deb3c.png)

**Comment by Legedric** [comment]
Nope, sorry. But many users wanted exactly this sorting so we will not change it again for now.
