### ISSUE TITLE
Month average should be calculated based on Day average

### ISSUE THREAD

**Issue by ofilipowicz** [Legedric/ptmagic#468]
Right now, in SALES ANALYSIS, month average is calculated based on month gains. The problem is as below:

```
Bot started to work on 31th of January.
It worked only 1 day and made only 1% gains on month January.
It worked for the whole February and made 28%.
AVG/Month is (28%+1%)/2=14.5%.
It should be calculated based on AVG/Day (30 or 31 days) like 30*1%=30%
```

I know the SALES ANALYSIS section conciders past trades and doesn't make predictions. But I still believe month avg should be calculated based on day avg.

**Comment by Legedric** [comment]
No. The monthly average is of course being calculated across months and not days. That wouldn't make sense as it would just be another daily average but split into timeframes.

So what you want would be more like "Daily AVG January", "Daily AVG February" etc. Maybe we will add this sometime to the Last X Months table as a separate column.
