### ISSUE TITLE
Random page refresh difficulties

### ISSUE THREAD

**Issue by JeanGalt** [Legedric/ptmagic#469]
Sometimes the PTMagic Dashboard page has difficulty displaying during periodic updates, with the 2 or 4 blocks at the bottom (graphics and corresponding text) that do not display.
By refreshing the entire page with the browser (with F5), this problem is resolved and the page is displayed very well and very quickly.
My config : PT v.2.0.1 + PTMagic v.1.6.1 + Chrome + Win10 x64

**Comment by Legedric** [comment]
Screenshots, please.

**Comment by djbadders** [comment]
I have seen this to, but I thought the issue was Trading View not being responsive

**Comment by Legedric** [comment]
Closing this as no feedback was provided for some days now.
