### ISSUE TITLE
ETH Balance Tracker

### ISSUE THREAD

**Issue by damajicman3** [Legedric/ptmagic#47]
![image](https://user-images.githubusercontent.com/32244880/36395082-32c31e9e-1585-11e8-8b08-1fc116b06004.png)

Does PT Magic recognize the value in ETH if you're trading on the ETH market?

**Comment by calebcall** [comment]
This is an acknowledged bug.  It'll be fixed.  Values are correct, it just shows BTC instead of ETH.

**Comment by damajicman3** [comment]
thanks!
