### ISSUE TITLE
Migrate to PT2 2018/04/29 15:31:16.030 FATAL - Not able to find preset file PAIRS.properties for 'Default' System.Exception Not able to find preset file PAIRS.properties for 'Default'

### ISSUE THREAD

**Issue by mavverick** [Legedric/ptmagic#470]
Hi,
After migrate PT from 1.x to 2.0 i get this error..

2018/04/29 15:31:16.030 FATAL - Not able to find preset file PAIRS.properties for 'Default' System.Exception Not able to find preset file PAIRS.properties for 'Default'

Regards

**Comment by Legedric** [comment]
Please check what the error message suggests. Check if your presets files are all there.

**Comment by TrueOsiris** [comment]
Sorry, I should have checked first
I've made another issue, but it's about the same thing.
https://github.com/Legedric/ptmagic/issues/474

You could quickly overcome this by copying the initialization folder to a "trading" folder in the profittrailer config root.

**Comment by mavverick** [comment]
Done Thanks!

**Comment by Legedric** [comment]
@TrueOsiris You are mixing things up here. What you are talking about is the trading folder. What the original poster here is having trouble with is the _presets files. Those are not the same.
