### ISSUE TITLE
PT 2.0 monitor cannot be found

### ISSUE THREAD

**Issue by zh4k** [Legedric/ptmagic#472]
I keep getting an error that the PT 2.0 monitor cannot be found.  What's causing this?  Also, all my history when upgrading to PT 2.0 can't be found.

**Comment by Legedric** [comment]
Please post a screenshot of the error message.

**Comment by zh4k** [comment]
I posted a link previously to the error message

**Comment by Legedric** [comment]
Ok thanks. You gotta check if anything on your machine is blocking the access. And of course make sure that PT is up and running.

**Comment by zh4k** [comment]
here's what was wrong.  Apparently PT magic 1.6 forces you to use the 8080 monitor instead of whatever you select.  So you if you want 8081 for example, and you put this in the general settings for PT magic, it ignores this and just uses 8080.  Thus, I had to change PT to 8080 as well as PT magic, and then it worked.  Just a heads up.

**Comment by Legedric** [comment]
That's wrong. I am using port 80 for example and it is working fine.
