### ISSUE TITLE
PT Magic is not working

### ISSUE THREAD

**Issue by Ibradagr8** [Legedric/ptmagic#473]
when i try to start PT Magic.cmd the following error comes 
![capture](https://user-images.githubusercontent.com/37135118/39427724-89b154fc-4c8d-11e8-8434-6c44dc22086e.PNG)

now how to solve this ??

**Comment by Ibradagr8** [comment]
Anything new guys ??

**Comment by Legedric** [comment]
Check your PT monitor URL. Seems like there is something wrong in there.

**Comment by Ibradagr8** [comment]
this is my settings
![image](https://user-images.githubusercontent.com/37135118/39445971-88f2bd70-4cc5-11e8-968d-485c3bc74a3f.png)

**Comment by Ibradagr8** [comment]
also this error shows
![image](https://user-images.githubusercontent.com/37135118/39446238-7a4e0404-4cc6-11e8-9a5f-388e411f6561.png)

**Comment by Legedric** [comment]
The URL is wrong. is has to start with http:// and yours starts with http:/ (one slash only).

**Comment by Ibradagr8** [comment]
it worked great!! 
 thanks for your help Bro. i appreciate your help and your patience.

regards
