### ISSUE TITLE
ptmagic still looking for trading folder in profittrailer

### ISSUE THREAD

**Issue by TrueOsiris** [Legedric/ptmagic#474]
ptmagic 1.6.x should, when using profittrailer v2.x.x or up, look in the initialization folder for the config files PAIRS.properties, DCA.properties and INDICATORS.properties.
Now it's still looking for the "trading" folder.

I've overcome this in my ptmagic docker (and profit-trailer docker) by symlinking "trading" to "initialization".

**Comment by Legedric** [comment]
No, PTM does not look for the trading folder when you set "ProfitTrailerMajorVersion" to 2 in your settings.general.json.

It only checks this when running PT 1.x
