### ISSUE TITLE
DCA calc not working.

### ISSUE THREAD

**Issue by MarcP1001** [Legedric/ptmagic#475]
I am running PT2.0.1.  Just got everything up and running, no errors in CMD at all.  But my DCA calc is empty even when it is filled out. This is on my ETH account. Any ideas how to fix?
![image](https://user-images.githubusercontent.com/37921254/39433248-ed04d7ec-4cc7-11e8-803d-92ebe20c316f.png)
One more issue with my BTC account.  Everything was running great but then suddenly the heartbeat turned red in PTM.  It says PT Magic seems to have a problem, check the logs.  When I check the logs there are no errors in the PT Magic logs.  Any ideas here?
Thanks 
Marc

**Comment by Legedric** [comment]
Have you tried another browser than IE?

**Comment by Legedric** [comment]
Closing this as no feedback was provided for some days now.
