### ISSUE TITLE
implement trigger based on profit

### ISSUE THREAD

**Issue by angelsomar** [Legedric/ptmagic#476]
Congratulations for this great work, I would like you to take this proposal into account.

If I have a winning position in more than one profit of 8% I can decide to increase the XXX_trailing_profit = 2

if the profit goes up by 20%, increase XXX_trailing_profit = 4

this allows us to continue looking to improve profit in a long time but only betting on what has already been earned, avoiding so much red

It is just an opinion and I would appreciate it if you will take it into consideration, be able to make decisions based on profit

successes

**Comment by raphauy** [comment]
This would be wonderful!!!

**Comment by Legedric** [comment]
Please be more precise on what you mean by "If I have a winning position in more than one profit of 8%". That sentence doesn't really make much sense to me to be honest (may be because I am not a native English speaker).

**Comment by angelsomar** [comment]
First, forgive me for my English

if with a trailing_profit = 0.2 I have exceeded 8%, it is just an example

I would be comfortable assuring a 6% profit and keep looking for a better long-term price by increasing the trailing_profit = 2

So I continue looking for a better price, ensuring a good profit

If I get 25% profit, say increase trailing_profit = 5

the maximum risk of the investment is the red moment, if we are in green because leaving with a slight rise and fall if we have a good position, always with the premise of not allowing a winning position to become a losing one

I think it would be to implement a trigger based on the% of profit reached

**Comment by juato4** [comment]
This is a great feature

**Comment by HojouFotytu** [comment]
Now a feature of PT.  trailing profit grow/shrink
