### ISSUE TITLE
Error on startup

### ISSUE THREAD

**Issue by yellobello** [Legedric/ptmagic#478]
Hi,
I am having trouble launching PTMagic.. I encountered this problem on both my windows machine as well as on my VPS when configuring PTMagic independently, and in both cases following the guide on the wiki.
After completing the setup and launching PTMagic for the first time I get this message:

Unhandled Exception: Newtonsoft.Json.JsonReaderException: Bad JSON escape sequence: \P. Path 'GeneralSettings.Application.ProfitTrailerPath', line 7, position 36.
   at PTMagic.Program.Main(String[] args) in D:\Tools\PTMagic\PTMagic\Program.cs:line 70

What is strange is that I neither have a D: drive nor did I specify this path in any config file...

**Comment by Legedric** [comment]
The D: drive there is just an information for us developers.

You invalidated your JSON while setting up PTM. I guess you did not use double backslashes in your ProfitTrailerPath setting.
