### ISSUE TITLE
PTM not recognizing sales

### ISSUE THREAD

**Issue by Nephor80** [Legedric/ptmagic#484]
Hi!
I upgraded to PT2 and the newest PTM-Version.
PTM shows 0 sales for 2 days. The days before all was ok, PTM also seems to work correctly. The path to PT is correct. Any ideas?
THX

**Comment by Nephor80** [comment]
It seems to be a PT-issue. There is no sales data for that days in the
PTData.json. After a restart of PT it lost the values of the last two days
since this issue is happening. I opened a issue in GitHub for PT, it seems
more people have the same Problem.

Legedric <notifications@github.com> schrieb am Do., 3. Mai 2018, 06:19:

**Comment by Legedric** [comment]
Thanks for the information. So we also know that this may not be related to PTM.
