### ISSUE TITLE
Inconsistent Manual Updating for DCA.properties File

### ISSUE THREAD

**Issue by RGAlexander216** [Legedric/ptmagic#488]
I seem to only be having this issue with the DCA.properties as the both the PAIRS & INDICATORS files are actually changing in the ProfitTrailer Config. However, if I make a change to the DCA.properties it sometimes will change the settings of my running ProfitTrailer instance, but most of the time it doesn't do anything. Here's what I've tried so far

1.) Make sure the DCA file is in the same C:\path\to\ptmagic\\_presets\Default as the other two files. 
2.) Check both the logs & _logs files at the time of the change to see if any message was written there that did not appear in the console. 

If I need to do something more than that to get it to work just let me know, but I don't really know why the other two are actually updating. Taking an educated guess, the HTTPS request that PTMagic may be sending for this specific file could be having issues with the headers, but maybe it's something else.

Thank you for all you've done here.

**Comment by RGAlexander216** [comment]
Actually, I just noticed that the top of my DCA Config (In the ProfitTrailer browser interface) says that PTMagic is updating it. I think that will contradict my suggestion of the HTTPS Request Headers. 

Just to be sure I checked again that the DCA.properties file that I updated (and saved) is in the correct C:\path\to\ptmagic\\_presets\Default before posting this.

**Comment by Legedric** [comment]
This should be working and as noone else seems to be reporting this particular issue I assume it has to be something local. The problem is that I cannot investigate this and there is no "lucky" guess here from my side as the Profit Trailer settings API has its very own issues when loading/saving settings which makes it quite hard to get down this rabbit hole.
