### ISSUE TITLE
 FATAL - The remote server returned an error: (403)

### ISSUE THREAD

**Issue by armandossg** [Legedric/ptmagic#490]
Sorry, I'm running PT Magic, I was working on version 1.6.1 and PT 2.0.2, Perfect on my Desktop PC, I run 4 Bot (BTC & ETH BitTrex and BTC & ETH Binance).

Yesterday I mounted them on my VPS (4 core, 8 GB RAM, 60 GB virtual disk only for PT and PTM.

I work a couple of hours and then I get the error 403, I do everything and follow the error, after 1 hour inactive, returns to work another couple of hours, then gives the error.

When I try to boot it it gives me this error (taken from the PTM _log):

2018/05/06 00:06:43.290 INFO - Starting market trend check with Version 1.6.1 
2018/05/06 00:06:43.688 FATAL - The remote server returned an error: (403) Forbidden. System.Net.WebException The remote server returned an error: (403) Forbidden.    at System.Net.HttpWebRequest.GetResponse()
   at BusinessRules.MarketAnalyzer.BaseAnalyzer.GetSimpleJsonObjectFromURL(String url, LogHelper log, Boolean onlyLogDebug) in D:\Tools\PTMagic\BusinessRules\MarketAnalyzer\BaseAnalyzer.cs:line 48
2018/05/06 00:06:43.750 FATAL - The remote server returned an error: (403) Forbidden. System.Net.WebException The remote server returned an error: (403) Forbidden.    at BusinessRules.MarketAnalyzer.BaseAnalyzer.GetSimpleJsonObjectFromURL(String url, LogHelper log, Boolean onlyLogDebug) in D:\Tools\PTMagic\BusinessRules\MarketAnalyzer\BaseAnalyzer.cs:line 59
   at BusinessRules.MarketAnalyzer.BaseAnalyzer.GetLatestGitHubRelease(LogHelper log, String defaultVersion) in D:\Tools\PTMagic\BusinessRules\MarketAnalyzer\BaseAnalyzer.cs:line 132
2018/05/06 00:54:08.217 INFO -

**Comment by Legedric** [comment]
Just restart. I don't know why GitHub refused the version check sometimes but this will be fixed with the next update.
