### ISSUE TITLE
ProfitTrailerMonitorURL?

### ISSUE THREAD

**Issue by daemonhunt** [Legedric/ptmagic#493]
I don't undertand this part of settings.general.json

No matter what I put here always see the error: **Your Profit Trailer monitor (http://localhost:8081/) is not available! The monitor URL is necessary to adjust your Profit Trailer settings since 2.0**

I have tried every URL I can think of (my PT (version 2.0.2) is on port 8081) from 0.0.0.0:8081 to 127.0.0.1:8081. Even tried adding /monitoring to it.

Please be aware that I am accessing my PT and PTM remotely, they are hosted on a headless VPS.

Do I need to install a reverse proxy on Ubuntu for this to work?

**Comment by Legedric** [comment]
Make sure you added this to the correct node (which is application), so it ends up looking like this:
![image](https://user-images.githubusercontent.com/8308141/39739178-db75121c-528f-11e8-8798-59f2a6254c05.png)

However, I don't know about your Ubuntu questions.

**Comment by Legedric** [comment]
The URL looks correct but you need to make sure it is accessible. When curl also brings up an error this seems to be some problem with your local routing or privileges maybe?

On my machine (windows) I am using port 80 (so not standard) and it is working fine.

**Comment by nicholasnelson** [comment]
You definitely should be able to request your local PT monitor with curl. If curl can't do this, how will PT Magic be able to?

`~$ curl http://127.0.0.1:8081/login -v
*   Trying 127.0.0.1...
* Connected to 127.0.0.1 (127.0.0.1) port 8081 (#0)
> GET /login HTTP/1.1
> Host: 127.0.0.1:8081
> User-Agent: curl/7.47.0
> Accept: */*
>
< HTTP/1.1 200 OK
< Date: Tue, 08 May 2018 09:30:41 GMT
<SNIP>
  <meta name="ProfitTrailer" content="The one and only ProfitTrailer Monitor">
`

This sounds more like an issue with your setup / PT than with PT Magic

**Comment by fender21** [comment]
I have been running into this issue as well and have some feedback that hopefully will help.   On a system reboot, PTMagic appears to spin up before ProfitTrailer has fully started which causes this error "Your Profit Trailer monitor (http://localhost:8081/) is not available! ".  If I restart PTMagic after PT is up, it will pull the information correctly and the error goes away.  I will need to look into options to delay the start of the PTMagic service on restart.

**Comment by daemonhunt** [comment]
If this is an issue with 'my setup', then it is an issue with the documentation. There is a note about a reverse proxy or something.

I can get to the bottom of this of course, it's just going to take me time, whereas I thought you may have run into this  before.

**Comment by Legedric** [comment]
No, I did not personally run into this before so I do not have any solution available for this as I also cannot reproduce the issue.
