### ISSUE TITLE
Saving analyser settings seems to overwrite MinChange with a MaxChange setting

### ISSUE THREAD

**Issue by peterpuglisi** [Legedric/ptmagic#494]
I'm using PTM 1.6.1 (still latest I think). The file had ..
        "Triggers": [
          {
            "MarketTrendName": "MainCurrency24h",
            "MinChange": 9.00
          },
          {
            "MarketTrendName": "MainCurrency24h",
            "MaxChange": -9.00
          }

After saving, it changed to this:
     "Triggers": [
          {
            "MarketTrendName": "MainCurrency24h",
            "MaxChange": -9.0
          },
          {
            "MarketTrendName": "MainCurrency24h",
            "MaxChange": -9.0
          }
        ],

And I had changed nothing in the original file, I just hit save.

**Comment by smoochy** [comment]
To add some information:

Original settings file can be seen here: https://pastebin.com/XMzSjt5F

He changed some settings via the WebGui of PTM and the first trigger got changed into a negative value.

Have been able to reproduce this.

Not sure, if syntax needs to be changed, or this is an issue with PTM.

Regards.

**Comment by Legedric** [comment]
You are correct and this doesn't work when you use the GUI.

The problem here is in the settings GUI I use the trend names to identify the triggers.
In this case right here the same trend name (Exchange24h) is being used twiced so they both conflict with each other (in the GUI) when you save that information.

Right now I do not have a solution for this other than not using the GUI for those kind of setting.

**Comment by smoochy** [comment]
Wouldnt it be possible to allow several market trends with different names to use the same trendminutes?

Like

```json
 {
           "Name": "Exchange24hMinChange",
           "Platform": "Exchange",
           "MaxMarkets": 50,
           "TrendMinutes": 1440
         }
```

and

```json
 {
           "Name": "Exchange24hMaxChange",
           "Platform": "Exchange",
           "MaxMarkets": 50,
           "TrendMinutes": 1440
        }
```

You then could create sth like:

```json
 {
         "SettingName": "MainCurrencyTrendCritical",
         "TriggerConnection": "OR",
         "Triggers": [
           {
             "MarketTrendName": "MainCurrency24hMinChange",
             "MinChange": 9
           },
           {
             "MarketTrendName": "MainCurrency24hMaxChange",
             "MaxChange": -9
           }
         ],
```

**Comment by stevenshizzleh** [comment]
@smoochy that looks like a good workaround to the issue. Not sure if there are any problems having two trends with the same time period, but I suspect not.

**Comment by Legedric** [comment]
@smoochy @stevenshizzleh Yes, that would work. Although this may reduce overall performance as the trend needs to be built twice (or more times). If you do it for one trend only this should be ok, but if you do it for lik 3+ trends you may notice an impact.

**Comment by peterpuglisi** [comment]
@smoochy @stevenshizzleh  Looks like we would need to change the ones below as well and assess any performance impacts, may not be an issue:

            "MarketTrendName": "MainCurrency3h",
            "MinChange": 4.00
          },
          {
            "MarketTrendName": "MainCurrency24h",
            "MinChange": 5.00,
            "MaxChange": 8.99
          },
          {
            "MarketTrendName": "MainCurrency3h",
            "MaxChange": -3.50
          },
          {
            "MarketTrendName": "MainCurrency24h",
            "MaxChange": -4.50,
            "MinChange": -8.99

Otherwise it's probably a good idea to add a prominent Warning comment in the header comments of the settings file.

**Comment by stevenshizzleh** [comment]
@smoochy @peterpuglisi it's an implementation issue on my end. I'll mull over either recommending no GUI or making separate trends. Trying to keep things condensed in the analyzer file. Thanks all for your input.
