### ISSUE TITLE
SImple IF statements - Enhancement

### ISSUE THREAD

**Issue by LeeUmney** [Legedric/ptmagic#497]
It would be brilliant if we could use simple if statements against coins, e.g. if(COIN value > -2.9%) { COIN_DCA_DCA_max_buy_times = 3} etc

This would allow you to use simple logic and potentially avoid losses as you could tailor DCA, etc, virtually on a coin basis.

**Comment by Legedric** [comment]
You can already change any DCA setting using single market settings today so I do not see any benefit in making PTM overly complicated with "IF" statements or something similar.
