### ISSUE TITLE
ARCHIVE HELP settings.analyzer.json

### ISSUE THREAD

**Issue by sitespagando** [Legedric/ptmagic#50]
Guys need help, could you give me a strategy for me to use the original MAGIC configuration? Are you using LOWBB? I do not know which one to use.

please tell me what you think of my original

LOWBB = 25
GAIN = 0.5
PROFIT TRAILING = 0.05

I am a layperson and would like at least 2% a day, my wheel 24 hours a day in VPS

AND I'M VERY HAPPY TO BE PART OF THIS TIME MAGIC

**Comment by sitespagando** [comment]
CREATOR PLEASE, WHAT STRATEGY WAS USED FOR ARCHIVE settings.analyzer.json?

EMAGAIN OR LOWBB? TO WORK AGAIN, SHOULD I LEAVE WHAT?

**Comment by Legedric** [comment]
The default strategy we are using is EMAGAIN.

**Comment by sitespagando** [comment]
PLEASE WHAT VALUE DO YOU USE TOGETHER WITH THE MAGIC PT IN THE FILES BELOW ORIGINAL OF THE PT? Did you say you use EMAGAIN?

I NEED VALUES BELOW TO LEAVE THE ORIGINAL TOOL
ALL_buy_strategy = EMAGAIN
ALL_buy_value: ????
ALL_trailing_buy: ????

I WILL LEAVE CONFIGURED AND USE PT MAGIC WITHOUT CHANGING NOTHING AS YOU CREATED OK

**Comment by Legedric** [comment]
1. Please stop posting everything in capitals or your issues will be ignore.

2. I am using:
ALL_buy_strategy = EMAGAIN
ALL_buy_value: -0.75
ALL_trailing_buy: 0.35

But these are just my personal settings.
