### ISSUE TITLE
Unable to reverse proxy PTM except on the root path

### ISSUE THREAD

**Issue by SjaaLom** [Legedric/ptmagic#503]
Hi,
I have request that would make the maintenance of PTM easier and gives more flexibility in the deployment options. 

The problem is that PTM is only able to be run on the root path of a webserver. It's not possible to use a reverse proxy to route a request for https://my.domain.com/ptm to the internal url http://localhost:5000. 

When I try this, I can get the initial page loaded, but all the update calls that are done by the page (via jQuery) are fixed to the root path (/), and not the path it is served at (/ptm).
 
My current setup on a VPS is: 
- 3x PT, each on their own (sub)domain
- 3x PTM, each on their own (sub)domain
- 1x NGINX, used as a reverse proxy

All the PT instances get their own subdomain (https://pt1.domain.com, https://pt2.domain.com, https://pt3.domain.com). What I would like to do is route the path /ptm of all these urls to the PTM instance that are linked to the PT instance (i.e. https://pt1.domain.com/ptm).

The problem that occurs is that the jQuery requests for the DashboardTop, DashboardBottom and TickerWidgets fail, because the requested relative url is rooted (has a / in front of it). 
`$("#ticker-widgets").load('/_get/TickerWidgets'`

My guess is that simply removing the / in front of _get would allow my use case to function, without impacting other users.
It would solve my problem and I'm assuming others have probably tried this as well.

Please, consider this easy fix. I am offering my services to test the improvement.

**Comment by SjaaLom** [comment]
By the way, I have tried to use the Monitor.RootUrl setting from settings.general.json, but this does not seem to work. It redirects me to the /ptm path (/ptm/Login), but there is nothing listening there

**Comment by Legedric** [comment]
It has to be an issue on your local setup as in PTM the RootUrl is being used for every single call. So the $("#ticker-widgets").load('/_get/TickerWidgets' you see there is technically something like this:

`$("#ticker-widgets").load('@Html.Raw(Model.PTMagicConfiguration.GeneralSettings.Monitor.RootUrl)_get/TickerWidgets'`

So in case this doesn't work for whatever reason you need to make sure your monitor's PTBasePath (appsettings.json) is poiting to the correct PTM directory loading the correct settings.general.json file to read the root url config from.

**Comment by SjaaLom** [comment]
So basically if I leave the RootUrl property empty, it would construct the url
"_get/TickerWidgets"? (without the leading slash?). 

Or is there some initialization of that property that prepends a slash if RootUrl does not start with one?

I will give this a try.

**Comment by SjaaLom** [comment]
Hmm, when i set the RootUrl ("Port": 5003,"RootUrl": "/ptm/") and restart the monitor it finds nothing at http://localhost:8083/ptm/
```
/tmp$ wget http://localhost:5003/ptm
--2018-05-10 15:05:51--  http://localhost:5003/ptm
Resolving localhost (localhost)... ::1, 127.0.0.1
Connecting to localhost (localhost)|127.0.0.1|:5003... connected.
HTTP request sent, awaiting response... 404 Not Found
2018-05-10 15:05:51 ERROR 404: Not Found.
```
Connecting to the root sends me to the login page _on the /ptm/ path_, but again it cannot be found. 
```
/tmp$ wget http://localhost:5003/
--2018-05-10 15:06:53--  http://localhost:5003/
Resolving localhost (localhost)... ::1, 127.0.0.1
Connecting to localhost (localhost)|127.0.0.1|:5003... connected.
HTTP request sent, awaiting response... 302 Found
Location: /ptm/Login [following]
--2018-05-10 15:06:53--  http://localhost:5003/ptm/Login
Reusing existing connection to localhost:5003.
HTTP request sent, awaiting response... 404 Not Found
2018-05-10 15:06:53 ERROR 404: Not Found.
```
Is there something else I'm missing here?

**Comment by Legedric** [comment]
Sorry, I have got no experience with reverse proxy setups. All I know is that it is working for many others.

You may try hopping onto the Dirscord channel and see if there is someone who is able to help you or search teh discord channel for similar issues.
