### ISSUE TITLE
Good method for default settings

### ISSUE THREAD

**Issue by But4ler** [Legedric/ptmagic#506]
Good morning,
This is not a bug, possibly a lack of documentation.
Already, thanks for your great work and sharing!

What is the right method to manage the default PT settings?
In PT 2.x, files in the initalization folder are only read by PT at first launch.
The changes you make via the interface arrive more in the trading folder 

Do we have to enter our default configuration in the "GLOBAL SETTING "DEFAULT" section?

**Comment by Legedric** [comment]
Your PT default settings should go into the preset files for your Default global settings.
