### ISSUE TITLE
Refresh function

### ISSUE THREAD

**Issue by Lorcan1001** [Legedric/ptmagic#509]
Hello
I use my own addon for modify the pairs.properties on ptv1 and the http post for modify pairs in ptv2 but when i use ptm i need to modify  too the _preset/default/pairs.properties.
is it possible to add a function for force the refresh the http post through ptmagic ?

**Comment by Legedric** [comment]
Everytime you change your presets file PTM will apply the settings again.

**Comment by Lorcan1001** [comment]
Sorry if i insist but for every modification in the pairs.properties in ptm, this modification is directly implicated without timeout ?

**Comment by Legedric** [comment]
It is applied by PTM during its next run which will happen in x minutes depending on your interval you specified in your settings.

**Comment by Lorcan1001** [comment]
Ok that the point thank you or your response. I continue to  edit the both pair by http for ptv2 and pairs.properties for ptm ( i need to applied asap the modification for my addon)
