### ISSUE TITLE
Dashboard enhancements

### ISSUE THREAD

**Issue by Arararararagi** [Legedric/ptmagic#51]
I think it would be great to add a doughnut chart with the current coins to which we're exposed, and in the middle, the value in the mkt coin (BTC, ETH, other) and % of balance that is invested.

It would also be great to have a list of biggest winners/losers by avg. profit in the sales log.

Great project, by the way!

**Comment by jamesblackjr** [comment]
I was thinking the same thing.  I would like to be able to see interactive charts to visualize which coins make you the most money total/per trade, etc.

**Comment by Legedric** [comment]
Did you navigate to the Sales Analyzer and scroll down a little?
![image](https://user-images.githubusercontent.com/8308141/36408412-7455c4e4-1605-11e8-8d9b-90dc42216d10.png)

But we will think about adding this donut type of chart :)

**Comment by jamesblackjr** [comment]
yeah that's what I was thinking about... you could condense that table and add the charts next to it.

**Comment by Arararararagi** [comment]
That table is pretty close, but it doesn't tell me that every time I trade QTUM (which is in second place for overall profit, 2.92833333333USD per trade), my average profit is higher than ZCL (first place, but only 0.965416666667USD per trade), for example.

**Comment by HojouFotytu** [comment]
It would help if this were sortable by the different columns.

**Comment by cavaliertech** [comment]
Would be great to have PT Magic just pull the balance from PT. Lots of hassles getting that to work, and once I get the balances to match, they are off again the next time a buy happens, especially in DCA.

**Comment by Legedric** [comment]
PT doiesn't save the balance anywhere so that PT Magic would be able to read it.

**Comment by jwk27** [comment]
PT Magic should be able to read from the market going forward using an api

**Comment by Legedric** [comment]
@jwk27 Please elaborate on that more.

**Comment by jwk27** [comment]
He stated that PT magic will have to pull the balance from Profit Trader. I was of the view that with an API call from PT Magic to the market it can get accurate bal and work with it directly

**Comment by Legedric** [comment]
At the moment we do not want to have access to personal API keys. It is somethingw e may consider adding in the future but at the moment it is not on our list.

In fact, the balance is and can always be only an estimation. As the bot is constantly trading, you barely have your BTC (or whatever market you are using) available on your exchange making it always only an estimation of what your balance currently looks like if you have running trades in a couple of pairs.

**Comment by jwk27** [comment]
Ok, good. 

Kudos on the hardwork

**Comment by cavaliertech** [comment]
If PT Magic can't get the balance from the same place PT Monitor does (which I get), a good alternative would be the ability to manually update the balance from the GUI, if that wouldn't mess other stuff up.

**Comment by cavaliertech** [comment]
Oh and I really agree that APIs shouldn't be accessed. Food for those who say PTM is some sort of scam.
