### ISSUE TITLE
Full screen mode 

### ISSUE THREAD

**Issue by bit4boy** [Legedric/ptmagic#513]
Hello,

Would you be able to add a full screen option like profit trailer?

Regards
<img width="78" alt="01" src="https://user-images.githubusercontent.com/38306590/40080835-81df2802-588c-11e8-8052-0b1bc2ac8bd1.png">

**Comment by HojouFotytu** [comment]
Press F11?

**Comment by bit4boy** [comment]
F11 does not eliminate the scroll bar on the right

**Comment by kdessinger** [comment]
This option would be super useful on the Raspberry Pi with a 3.5" LCD Screen.
