### ISSUE TITLE
problem with monitor.dll in Linux ubuntu

### ISSUE THREAD

**Issue by cash-money** [Legedric/ptmagic#514]
hi i am having an issue getting monitor to work! i get the following error..can you help?

from what i can see the www folder is within the monitor folder?

thanks

root@usve262206:/opt/pt-magic# dotnet ./Monitor/Monitor.dll
##########################################################
#********************************************************#
INFO: Starting PT Magic Monitor...
INFO: Beginning startup checks...
INFO: appsettings.json found in /opt/pt-magic
INFO: PT Magic directory found at /opt/pt-magic/
INFO: settings.general.json found at /opt/pt-magic/settings.general.json
INFO: LastRuntimeSummary.json found at /opt/pt-magic/_data/LastRuntimeSummary.json
ERROR: wwwroot directory not found: '/opt/pt-magic/wwwroot'. Did you copy all files as instructed on the wiki?

**Comment by Legedric** [comment]
Can you try if it works to use dotnet Monitor/Monitor.dll?
So without the ./ in there?

**Comment by adamnl** [comment]
ERROR: wwwroot directory not found: '/opt/pt-magic/wwwroot'.

Your www root is located at /opt/pt-magic/Monitor/, not in /opt/pt-magic/

**Comment by cash-money** [comment]
yes it is..that was how it was unzipped (automatic, the most recent
version)?  is this set some where in a config file?  (the location of
wwwroot)

**Comment by cash-money** [comment]
that is already in there....(both are correct)!! any ideas?


  *"GeneralSettings"**:* *{*

    *"Application"**:* *{*

      *"IsEnabled"**:* true*,* // Enables the PTMagic bot (needs restart to
take effe$

      *"TestMode"**:* true*,* // If TestMode is active, no properties files
will be c$

      *"ProfitTrailerMajorVersion"**:** 2**,* // Major version of your
Profit Trailer ($

      *"ProfitTrailerPath"**:** "/var/opt/pt/"**,* /

*{*

  *"PTMagicBasePath"**:** "/opt/pt-magic/"**,* // Path to your Profit
Trailer Magic mai$

  *"Logging"**:* *{*

    *"IncludeScopes"**:* false*,*

    *"LogLevel"**:* *{*

      *"Default"**:** "Warning"*

    *}*

**Comment by adamnl** [comment]
Yes:   create a symlink from /opt/pt-magic/wwwroot to /opt/pt-magic/Monitor/wwwroot

**Comment by cash-money** [comment]
i just moved the directory and now the monitor runs.  however i don't get
any web page when i try and connect?

**Comment by adamnl** [comment]
Don't move the directory, just create a symlink

**Comment by cash-money** [comment]
it ok i seem to have it working now..thanks

**Comment by adamnl** [comment]
Great, good luck with PTMagic!

**Comment by cash-money** [comment]
unfortunately it hadn't worked by moving the folder. i could get access via
the web but then ran into some errors...can you give me the syntax for the
link, i have tried a few but none seem to work


Thanks

Dan

**Comment by adamnl** [comment]
sudo ln -s /opt/pt-magic/Monitor/wwwroot /opt/pt-magic/wwwroot

**Comment by cash-money** [comment]
thanks..that works now...one last question...

i have found that PT Magic runs only when i have the two dot net commands
running from a terminal.  if i disconnect then it stops running.  is there
a way that i can have these commands running in the back ground without
having to be permanently connected via ssh? (its a remote VPS)

Thanks

Dan

**Comment by cash-money** [comment]
thats great..thanks a million
