### ISSUE TITLE
Enhancement Request: Exclude Market

### ISSUE THREAD

**Issue by HojouFotytu** [Legedric/ptmagic#516]
Sometimes it would be nice to exclude a particular market from all Single Market Settings in the analyzer.  For example a coin for which i have a specified profit target in my pairs file.

"IgnoredMarkets" does this for a single SMS, but to do it for all settings, the list would need to be updated and maintained across each single market setting.

Something like "ExludeMarket":  "ETH, VEN," etc... at the top of the Analyzer Settings, maybe?

**Comment by Legedric** [comment]
Sorry, but I will not add this to the list. As you already said it does exist for each SMS individually so you are able to manage this already today.
If you are running like 5+ SMS this may not be convenient but that would not justify the development effort to implement this.
