### ISSUE TITLE
Documentation for how a market trend is calculated

### ISSUE THREAD

**Issue by nick-ratbert** [Legedric/ptmagic#518]
It's not clear, to me at least, how a market trend is built. Is it price at end of period relative to price at start of period?

I'd like to see something like a moving average over a defined period at a defined rate. Example, one hour on 5 minute candles or 24hrs on 1hr candles. That could be reasonably reactive while not swinging wildly on short lived price actions.

**Comment by Legedric** [comment]
PTM is not using candles at all.

It is only comparing the most recent price of a coin (like right now) with the price X minutes/hours/days ago according to your settings of your market trend.
For the global market trend it will build an average trend value across all the coins combined in that trend.

That's it. Pretty simple and straight forward. No complex calculations anywhere in there.

Indicators like Moving Averages (in any way) are not part of PTM and never will be.
