### ISSUE TITLE
PTMagic Error - No valid pairs errors found

### ISSUE THREAD

**Issue by largevodka** [Legedric/ptmagic#519]
Hi,
Wondering if someone can help with this error please? I have PT v2 running just fine. Installed Pttracker as well. All running on a VPS with no issues. So installed PTMagic for the first time yesterday and keep getting this error:
![ptm](https://user-images.githubusercontent.com/37045729/40224255-820d2ffc-5a7d-11e8-82bc-30e0d47d32d4.jpg)
Only thing different to standard PTtrailer settings is that my config is called PTDefault. I changed the "ProfitTrailerDefaultSettingName" to "PTDefault" in the settings json. Any idea what could be wrong please? Thanks.

**Comment by Legedric** [comment]
What did you set the "ProfitTrailerMajorVersion" setting to in your settings.general.json?

**Comment by largevodka** [comment]
Hi,
Thanks for the quick reply! MajorVersion is set to "2" (no quotes) in that json.

**Comment by Legedric** [comment]
Please wait and see if 2.0 fixes this issue. Usually the market list in PT 2.0 should not be checked this way.

**Comment by largevodka** [comment]
Hi. Thanks. Will do. Appreciate the help.
