### ISSUE TITLE
Error Starting PTMagic on Mac

### ISSUE THREAD

**Issue by whatsupjeremy** [Legedric/ptmagic#520]
I am getting a big error when trying to start PTMagic. Below is a screenshot.
![screen shot 2018-05-20 at 7 15 54 pm](https://user-images.githubusercontent.com/11285947/40284809-56cdefc0-5c62-11e8-831e-cc167637050f.png)

**Comment by Legedric** [comment]
You JSON in your settings.general.json is invalid. Please follow the instructions carefully and make sure you use double backslashes and use correct JSON.
