### ISSUE TITLE
Stops working after error

### ISSUE THREAD

**Issue by jokaorgua** [Legedric/ptmagic#521]
Magic stopped its work after the following error

Loading INDICATORS.properties failed for setting 'default': An error occurred while sending the request. SSL connect error System.Net.WebException An error occurred while sending the request. SSL connect error    at System.Net.HttpWebRequest.GetResponse()
   at BusinessRules.PTSettings.SettingsHandler.GetPropertyLinesFromAPI(String ptFileName, SystemConfiguration systemConfiguration, LogHelper log) in D:\Tools\PTMagic\BusinessRules\PTSettings\SettingsHandler.cs:line 49
2018/05/20 12:45:15.165 ERROR - Unable to load all Profit Trailer properties!

The process was in process list but it was not changing anything in ProfitTrailer. Need some kind of restart on such errors

**Comment by clippart** [comment]
I confirm. Because of this error, I typed bags

**Comment by Legedric** [comment]
Duplicate of #457
