### ISSUE TITLE
[Question/suggestion] Ephemeral storage

### ISSUE THREAD

**Issue by 7wonders** [Legedric/ptmagic#522]
I am trying to run ptmagic in docker. Docker is non-ephemeral so unless mounting volumes then settings, logs and required data files are wiped on a reboot. So at the moment that requires a bunch of cp/mv/sed commands in an entrypoint script along with mounting the correct files and directories.

My suggestion/question is threefold:

Which profittrailer directories and files does ptmagic need to access so I can make sure they are mounted?
Which ptmagic files and directories MUST survive a reboot? (_data, _logs, ???)
Suggestion: How about moving all necessary config files to a single _configs directory in the root directory (would make things simpler for initial startup also)?

**Comment by Legedric** [comment]
1. If you are running PT 2.x (which you should) then only the Profit Trailer root directory is relevant.
2. All settings and _data files. Logfiles are not relevant for PTM.
3. No plans to change the current folder setup as this would require all existing users to change their settings locations for "just a few users" that would benefit from this in the first place.

I am not saying it will never be changed, just that there are no plans to do this right now.

**Comment by 7wonders** [comment]
Thanks for the info @Legedric

Normally it would not be an issue for most docker users as they can just mount the necessary files. For me its a bit different as I use NFS (actually EFS) mounting which requires mounting directories. Mounting the whole directory is an option though so I will proceed with something like that. Keep up the good work 👍
