### ISSUE TITLE
PT-Magic updating all of PT instances configs

### ISSUE THREAD

**Issue by megawolt** [Legedric/ptmagic#523]
Hey I run a two instance PT in different folders and ports. Then setup Pt-Magic to the one of them. When price triggers executed, pt-magic changes both of them configs.

Folder Schema:
\
|-pt (8082)
 |-pt-magic 
  |-pt-mon (8100)
|-pt2 (8084)

**Comment by Legedric** [comment]
That's a known issue as far as I know with PT's settings API. In case you are running both PT instances with the same license key and same PT default settings name (for example "default") then PT messes this up.
The root problem for this is that PT itself ties the settings to the settings name (default) and the license key on their server (I guess) and so they cannot be separated.

So in case you run twi instances using the same license key you need to name your default settings like "default-1" and "default-2" to work around this issue.

I know that's not pretty but that's how PT handles those settings things...
