### ISSUE TITLE
[Enhacement] Add bot info analyzer section

### ISSUE THREAD

**Issue by jokaorgua** [Legedric/ptmagic#524]
Would be great to have a section in analyzer where triggers will be based on bot's info. For example
1. Free balance left form start balance or tcv
2. Number of coins in DCA
3. Number of coins in PAIRS
4. TCV raise or drop compared to some interval (like market trend)

In this we would be able to decrease gain when free balance is too low, or set max_pairs when we have a lot of coins in dca etc

**Comment by becikas** [comment]
+

**Comment by HojouFotytu** [comment]
See: https://github.com/PTMagicians/PTMagic/issues/159
