### ISSUE TITLE
Multiple global setting changes when market has not varied

### ISSUE THREAD

**Issue by jshplayer** [Legedric/ptmagic#527]
PT Magic is switching to default (even if default is already applied) every 15minutes (flood protection set) and sending notifications about it after upgrading to PT2.0 (seems to not pick up the first few lines haven't changed and thinks the config is different - applies it)

fyi Great work on the update man, looking good.

**Comment by smoochy** [comment]
Same issue here.

In addition: SMS gets written into the PT Pairs and DCA settings, but not changes made to _presets/Defaults/PAIRS.properties, _presets/Defaults/DCA.properties and _presets/Defaults/INDICATORS.properties.

So for instance when I change _keep_balance_percentage_ from 50 to 50.1, it is not changed in PT Pairs settings and stays at 50.


[DCA.txt](https://github.com/Legedric/ptmagic/files/2028758/DCA.txt)
[INDICATORS.txt](https://github.com/Legedric/ptmagic/files/2028759/INDICATORS.txt)
[PAIRS.txt](https://github.com/Legedric/ptmagic/files/2028760/PAIRS.txt)
[settings.analyzer.txt](https://github.com/Legedric/ptmagic/files/2028761/settings.analyzer.txt)

**Comment by Legedric** [comment]
@smoochy Please open a separate issue for that.

**Comment by jshplayer** [comment]
Adding to this, I just noticed PTMagic isn't actually making any config changes to ProfitTrailer even though it's changing its global market to default, it has left behind my "VeryBadMarket" global market setting which has forced sell only mode. Rolled back to 1.6 for now.

**Comment by jshay21** [comment]
Same issue here.  Global setting are not being overwritten.  SMS setting are being overwritten properly.
