### ISSUE TITLE
PTM does not exit when monitor connection test fail when running using PM2?

### ISSUE THREAD

**Issue by imqct** [Legedric/ptmagic#528]
11|BT_BTC_ | 2018-05-23 00:32 -04:00: 2018/05/23 00:32:55.519 INFO - Configuration loaded. Found 11 Market Trends, 4 Global Settings and 5 Single Market Settings.
11|BT_BTC_ | 2018-05-23 00:32 -04:00: 2018/05/23 00:32:55.551 INFO - Profit Trailer directory found
11|BT_BTC_ | 2018-05-23 00:32 -04:00: 2018/05/23 00:32:55.566 INFO - ========== STARTING CHECKS FOR Profit Trailer 2.x ==========
11|BT_BTC_ | 2018-05-23 00:32 -04:00: 2018/05/23 00:32:55.566 INFO - Profit Trailer 2.x check: Profit Trailer license found
11|BT_BTC_ | 2018/05/23 00:32:55.566 INFO - Profit Trailer 2.x check: Profit Trailer default setting name specified
11|BT_BTC_ | 2018/05/23 00:32:55.566 INFO - Profit Trailer 2.x check: Profit Trailer monitor URL found
11|BT_BTC_ | 2018-05-23 00:32 -04:00: 2018/05/23 00:32:55.827 ERROR - Profit Trailer 2.x check: Your Profit Trailer monitor (https://xxxxx:8080/) is not available! Make sure your Profit Trailer bot is up and running and your monitor is accessible.
11|BT_BTC_ | 2018/05/23 00:32:55.827 INFO - ========== CHECKS FOR Profit Trailer 2.x COMPLETED! ==========

**Comment by Legedric** [comment]
When you startup PTM it still checks for the PT monitor to be available and if it is not, it terminates itself.

When PTM is running and notices that PT monitor is not available, it will just wait for the next interval.
