### ISSUE TITLE
PTM not writing settings changes

### ISSUE THREAD

**Issue by Ichy84** [Legedric/ptmagic#532]
Hello,

First of all, again, great work. Thank you very much

I am using the PT 2.0.7. and PTM 2.0.1. I get a Telegram message that the global settings are switched. I also see it on the PTM cmd window, where it’s stated that the global settings have changed and/or filed have changed. I Also see it the PT notification window – detected configuration changes. But the thing is, PTM is not writing the files into PT. My pairs.properties haven’t changed, although it went from End of the world to To the moon.

I am sorry if I opened a duplicate ticket, I searched for the problem, but couldn’t find any solution, just partial answers.

MfG, Ichy

**Comment by Legedric** [comment]
So does it change the header of your Pairs.properties when you look at them in your PT monitor?

Please keep in mind that since PT 2.0 PTM is no longer changing files on your disk but your online settings for Profit Trailer so you only see the changes in your PT monitor.

**Comment by Ichy84** [comment]
I dont even have a header made by PTM in the pairs.properties.
I have also a problem with the monitor, dont know if its related:
An assembly specified in the application dependencies manifest (Monitor.deps.json) was not found: 
    package: 'Microsoft.ApplicationInsights.AspNetCore', version: '2.1.1' 
    path: 'lib/netstandard1.6/Microsoft.ApplicationInsights.AspNetCore.dll' 
  This assembly was expected to be in the local runtime store as the application was published using the following target manifest files: 
    aspnetcore-store-2.0.0-linux-x64.xml;aspnetcore-store-2.0.0-osx-x64.xml;aspnetcore-store-2.0.0-win7-x64.xml;aspnetcore-store-2.0.0-win7-x86.xml

**Comment by Legedric** [comment]
Seems like you did not install both .NET Core packages as required in step 2 here:
https://github.com/Legedric/ptmagic/wiki/Setup-PT-Magic-on-Windows

**Comment by Ichy84** [comment]
Could be, i have reistalled windows just recently. But i suppose it is not related to my initial problem.

**Comment by DoJoMast3r** [comment]
Same issue here.... Header is being changed however the strategy is blank!
"# The below values are provided by PTMagic
DEFAULT_A_buy_strategy = DISABLED
DEFAULT_A_buy_value = 0
DEFAULT_A_buy_value_limit = 0
DEFAULT_B_buy_strategy = DISABLED
DEFAULT_B_buy_value = 0
DEFAULT_B_buy_value_limit = 0
DEFAULT_C_buy_strategy = DISABLED
DEFAULT_C_buy_value = 0
DEFAULT_C_buy_value_limit = 0
DEFAULT_D_buy_strategy = DISABLED
DEFAULT_D_buy_value = 0
DEFAULT_D_buy_value_limit = 0
DEFAULT_E_buy_strategy = DISABLED
DEFAULT_E_buy_value = 0
DEFAULT_E_buy_value_limit = 0"

**Comment by Legedric** [comment]
@DoJoMast3r That part there doesn't tell me much as I do not know what you expect there from your settings.

What is that I am looking there? Please be as detailed as possible.

**Comment by DoJoMast3r** [comment]
@Legedric It should be changing these values but the only thing that changes is the header, also SOM is not enabled either

**Comment by Legedric** [comment]
@DoJoMast3r I need a screenshot of your PTM settings that should change this and the PT original values to see what is the problem here.

**Comment by Ichy84** [comment]
I have fixed the problem with the monitor, you were right, i havent had both .net packages. Turns out it is not bad to install the right one for your system (x64, x86). But still, PTm is not writting setting to PT files.

**Comment by Legedric** [comment]
@Ichy84 Same applies to you as I wrote above for @DoJoMast3r . I need screenshots and more information.

**Comment by Legedric** [comment]
Closing as feedback is missing for some days now.

**Comment by Ichy84** [comment]
Hey,

I have problems on my pc, i just received my raspberry pi and will install PT and PTM during the weekend. And see if i have same problems. i will update you then.
Thank you

**Comment by Ichy84** [comment]
Hello,

So I managed to install PT and PTM (but not the monitor) to the raspberry pi. The strange thing is, everything is the same, PTM seems to work fine, I get the telegram notification, but again, the setting files in PT are not changing, there is no header. Attached the log file form PTM.
[2018-06-04.txt](https://github.com/Legedric/ptmagic/files/2066954/2018-06-04.txt)
![untitled](https://user-images.githubusercontent.com/36775146/40900040-019581a8-67ca-11e8-9377-5608d5026dc0.jpg)

**Comment by Ichy84** [comment]
Are there maybe some read/write permissions i am not aware off?

**Comment by Legedric** [comment]
Possible, yes. PTM needs to be able to write to your preset files.

**Comment by Ichy84** [comment]
I have changed that too, but no difference. Any other files that PTM writes to? I find it hard to believe i am the only one with this problem, because its clearly not a bug, if the exact same thing is happening on two different setups. What am i not seeing...

**Comment by Legedric** [comment]
No, PTM is only writing to the presets files in that case.

**Comment by Ichy84** [comment]
I will install everything from scratch in the near future. Maybe something happened, besause i copied files from various locations, different backups... I will update you.
