### ISSUE TITLE
PTM HAS ISSUE WITH WRITING ON FILES 

### ISSUE THREAD

**Issue by miladzamani** [Legedric/ptmagic#533]
HI , WHATS THIS ERROR FOR ? AND HOW CAN I FIX THIS ?
![ptm1](https://user-images.githubusercontent.com/35540216/40558472-a694f788-6068-11e8-8f14-07d2af1fbe0a.png)
![ptm2](https://user-images.githubusercontent.com/35540216/40558473-a6cf1cb0-6068-11e8-91bb-a0a1df7d9a81.png)

**Comment by Legedric** [comment]
These are issue with Profit Trailer, not PTM.

**Comment by miladzamani** [comment]
can you help me how can i fix it ?

**Comment by Legedric** [comment]
Unfortunately not as I do not have that issue myself.

**Comment by miladzamani** [comment]
found it , it was because PT was on TEST MODE , 
tnx xx
