### ISSUE TITLE
ptmagic 2.0.1 =  stopped 

### ISSUE THREAD

**Issue by sidney1113** [Legedric/ptmagic#534]
I'm sorry, my English is not very good, I hope you can help me。
system：Linux
profit-trailer：2.0.7  Running...
ptmagic       ：2.0.1
ptmagic =  stopped

`cd ProfitTrailer`
`pm2 start pm2-ProfitTrailer.json`
`cd /opt/PTMagic`
`pm2 start pm2.PTMagic.json`
`pm2 start pm2.PTM-Monitor.json`
PTMagic = online  PTM-Monitor = stopped or PTMagic = stopped  PTM-Monitor = online

`INFO：Not able to find preset file PAIRS.properties for 'Default' System.Exception Not able to find preset file PAIRS.properties for 'Default'。`

settings.general.json
"ProfitTrailerMajorVersion": 2,

"ProfitTrailerPath": "/home/ptbot/ProfitTrailer"

"ProfitTrailerDefaultSettingName": "default"

"AlwaysLoadDefaultBeforeSwitch": true

thanks everyone。

**Comment by chiandh** [comment]
Did you create a directory 'trading' under PTMagic?
If not you need create it and put your PAIRS, DCA, INDICATORS there.

**Comment by Legedric** [comment]
@chiandh Sorry but that's wrong. No need to create a trading folder in PTM.

@sidney1113 Check if you created the presets files in your PTM/_presets/Default folder as instructed in step 6 here:
https://github.com/Legedric/ptmagic/wiki/Setup-Guide

**Comment by sidney1113** [comment]
@Legedric 
thanks 

Check if you created the presets files in your PTM/_presets/Default folder as instructed in step 6 here:

Thank you for your help
