### ISSUE TITLE
[Feature Request] Advanced DCA Calculator > Add SOM_DCA triggers

### ISSUE THREAD

**Issue by HomeY** [Legedric/ptmagic#535]
Hi,

Besides the DEFAULT_DCA_buy_triggers, it's also possible to use SOM DCA buy trigger levels like:
SOM_DCA_buy_trigger_1 = -10
SOM_DCA_buy_trigger_2 = -12.5
SOM_DCA_buy_trigger_3 = -15

Would be great if these could be added to the Advanced DCA Calculator, so we can use the calculator to fine-tune the 'Approx. Drop %' and other values.

**Comment by swanfield1979** [comment]
I would like to see this added also 👍
