### ISSUE TITLE
ALL_max_cost_percentage not used by the PT Magic Monitor

### ISSUE THREAD

**Issue by jamesblackjr** [Legedric/ptmagic#54]
I've noticed that the `ALL_max_cost` is used within the dashboard and DCA calculator, but I use `ALL_max_cost_percentage` and my `ALL_max_cost` is set to 0.  

Maybe the monitor could display/use `ALL_max_cost_percentage` instead if `ALL_max_cost` is 0.

**Comment by Legedric** [comment]
You are correct, thanks!
