### ISSUE TITLE
[Feature Request] Bags Dilution Strategy (split big bags into small bags)

### ISSUE THREAD

**Issue by But4ler** [Legedric/ptmagic#541]
Already, thanks for your great work!

Is it possible to add a bag dilution function to PTM.

Youtubeur Patrick Bier proposes a really not bad method
* [Video 1](https://www.youtube.com/watch?v=FpjgYEA970E)
* [Video 2](https://www.youtube.com/watch?v=V2Fi99p7XWg)
* [PTD: Explanation in detail](https://www.indiegogo.com/projects/ptd-profit-trailer-zero-losses-dilution-add-on-youtube-software--2/x/18825187#/)

Excel file allowing calculations as an attachment
[Bag_Dilution_Spreadsheet_V1.03.xlsx](https://github.com/Legedric/ptmagic/files/2053860/Bag_Dilution_Spreadsheet_V1.03.xlsx)
![image](https://user-images.githubusercontent.com/15019378/40720222-55be3642-6416-11e8-8965-6861e54279c5.png)

I think integrating such a function into PTM would allow:
* Not yet having a software in addition to PT and PTM
* To reduce possible causes of conflicts / errors between PT, PTM and PTD
* To have this great function developed by professionals in an OpenSource project! (very big plus)
* To drastically increase the profitability of the bot
* To have a unified application to evaluate bot performance. With an Addons as PTD, what happens in the PTM stats?
* To be able to adjust the dilution of the bags to market conditions.

**Comment by Puppytherapy** [comment]
Since PT Magic has no information about what coins you actually hold and cannot on its own buy or sellany coin that is all done by PT. But lets wait what the dev himself will tell you.

**Comment by But4ler** [comment]
The necessary information is in PT (Total Amount and AVG Price by coin). 
PTM already displays this information in the Bag Analyzer

On the other hand, this method requires the placing of orders directly on the exchange.
This would clearly be a big evolution of PTM

**Comment by Legedric** [comment]
Although I do like the idea behind this, @Puppytherapy  is correct that PTM has no access to your exchange and so will not be able to place or otherwise interact with an order or your wallet in general.

Adding exchange API functions to PTM would be quite an evolution, yes but it would also make it a trading bot on its own (the step would be tiny to do this then) so this is not an option that we consider to add in the future.
