### ISSUE TITLE
PTM 2.0.2 - Monitor.dll doesn't work.

### ISSUE THREAD

**Issue by XxxSpiritvsxxX** [Legedric/ptmagic#548]
After upgrading DotNet Core to version 2.1.1-rtm-26531-02 on a Raspberry Pi running Raspbian, and upgrading PTM to version 2.0.2, we can run PTMagic.dll but not Monitor.dll

The error message states:
sudo dotnet Monitor.dll
It was not possible to find any compatible framework version
The specified framework 'Microsoft.AspNetCore.All', version '2.1.0' was not found.
  - Check application dependencies and target a framework version installed at:
      /opt/dotnet/
  - Installing .NET Core prerequisites might help resolve this problem:
      http://go.microsoft.com/fwlink/?LinkID=798306&clcid=0x409
  - The .NET Core framework and SDK can be installed from:
      https://aka.ms/dotnet-download

PTM does work without problems, it seems. Only Monitor fails to run.

**Comment by GrumbleGuff** [comment]
I am getting exactly the same error after installing the latest DotNet Core from

https://dotnetcli.blob.core.windows.net/dotnet/Runtime/2.1.0/dotnet-runtime-2.1.0-linux-arm.tar.gz

**Comment by crocal2000** [comment]
Hi,

I just installed everything on windows VPS and I got same problem, on my laptop with same windows was working, and now I installed everything on VPS and PTM monitor is not working...i tried to reinstall everything multiple times but its still same, please help. thank you
![error](https://user-images.githubusercontent.com/38821157/40999967-73ccac00-6947-11e8-94c0-e4ec4f124c33.jpg)

**Comment by cash-money** [comment]
Hi,

I also have the same issue on Unbuntu, looks to be running from the command line however i get a blank screen from the web page...let me know the fix

thanks

**Comment by Legedric** [comment]
@XxxSpiritvsxxX You definitely used the incorrect .NET Core version as there doesn't exist a version 2.1.1 for the Runtime yet.

Go to https://www.microsoft.com/net/download/linux

And sselect and download the correct RUNTIME version for your platform and PTM should work for you.

**Comment by XxxSpiritvsxxX** [comment]
@Legedric 

Of course it exists.
I downloaded it directly from Microsoft's daily builds here:
https://dotnetcli.blob.core.windows.net/dotnet/Runtime/release/2.1/dotnet-runtime-latest-linux-arm.tar.gz

But OK, I followed your advice to download as you requested, version 2.1.0 from https://download.microsoft.com/download/9/1/7/917308D9-6C92-4DA5-B4B1-B4A19451E2D2/dotnet-runtime-2.1.0-linux-arm.tar.gz

Same problem. Monitor doesn't work.

**Comment by crocal2000** [comment]
Hi guys, 
I was trying to reinstall everything many times today and problem was still the same and I realized I had windows 10 home edition on VPS so .net wasn't working. I installed another VPS with windows 2016 and repeated basics steps and it works perfectly... then I realized vultr is offering only windows 2012 and 2016 but I installed 2010 and that was the problem...

good luck

**Comment by cash-money** [comment]
i have made sure i am on the latest version, still have the problem...blank screen using a firefox browser from a mac...

root@usve262206:~# dotnet --info
.NET Core SDK (reflecting any global.json):
 Version:   2.1.300
 Commit:    adab45bf0c

Runtime Environment:
 OS Name:     ubuntu
 OS Version:  16.04
 OS Platform: Linux
 RID:         ubuntu.16.04-x64
 Base Path:   /usr/share/dotnet/sdk/2.1.300/

Host (useful for support):
  Version: 2.1.0
  Commit:  caa7b7e2ba

.NET Core SDKs installed:
  2.1.4 [/usr/share/dotnet/sdk]
  2.1.200 [/usr/share/dotnet/sdk]
  2.1.300 [/usr/share/dotnet/sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.0 [/usr/share/dotnet/shared/Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.0 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.0.5 [/usr/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.0.7 [/usr/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.0 [/usr/share/dotnet/shared/Microsoft.NETCore.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download
root@usve262206:~# 


please help

**Comment by XxxSpiritvsxxX** [comment]
I have it working in my Raspberry pi with the following config

.NET Core SDK (reflecting any global.json):
 Version:   2.1.300
 Commit:    adab45bf0c

Runtime Environment:
 OS Name:     raspbian
 OS Version:  9
 OS Platform: Linux
 RID:         linux-arm
 Base Path:   /opt/dotnet/sdk/2.1.300/

Host (useful for support):
  Version: 2.1.1-rtm-26531-02
  Commit:  f0127975f9

.NET Core SDKs installed:
  2.1.300 [/opt/dotnet/sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.0 [/opt/dotnet/shared/Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.0 [/opt/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.0 [/opt/dotnet/shared/Microsoft.NETCore.App]

**Comment by Legedric** [comment]
I will close this issue as the original issue got solved by installing the SDK and the other issue (not able to open monitor in your browser) is a different issue that may be discussed in issue #549
