### ISSUE TITLE
Error with DETAIL screen ( Tradingview Flashes)

### ISSUE THREAD

**Issue by juato4** [Legedric/ptmagic#553]
Error with Detail screen:

Check the video:

https://www.dropbox.com/s/vb8phra5vgw1lja/errorPTM.mov?dl=0

**Comment by Legedric** [comment]
Low Priority

**Comment by Legedric** [comment]
Here is what I wrote on Discord about this issue:
What browser are you using? I am using Chrome and the TV charts show up in 2 seconds very smoothly.
Same for Firefox.
And IE and Edge. So no problems here with screen flickering.
Maybe it is some addon that influences this?
However, as I cannot reproduce this there is nothing for me to fix here :smiley:

**Comment by juato4** [comment]
I am using Google chrome on mac. I didnt install addon.

I think is a mac render problem

Enviado desde mi iPhone

**Comment by Legedric** [comment]
I checked it with Google Chrome on my MacBook (High Sierra) and I cannot confirm this. So for me it also works on Mac and it loads in just 2-3 seconds.

**Comment by juato4** [comment]
strange!

**Comment by juato4** [comment]
Okk, i was cleaned cache and now work fine.
