### ISSUE TITLE
Is there a time limit for market trends?

### ISSUE THREAD

**Issue by shawn-j** [Legedric/ptmagic#559]
i've been running PTM for the past 2 days or so, and I'm playing around with longer-term market trends, 1 week and 2 week.

I've noticed that in the market analyzer page on the dashboard, the 2 week is innacurate.  in fact, it says the same thing as the 1-week.  so now all buys based on 2-week triggers are innacurate.  (running in testmode so it doesn't matter).  1-week seems to be accurate, and it's been running 2 days, so it must be able to grab historical data. 

 it took a while for the market trend averages graph to fill in all data for the 1 & 2-week trends, and now those lines are identical.   I have "Platform": "Exchange" set for all trends.  using binance.

is there a time limit?  I have "StoreDataMaxHours": 336  in settings.analyzer, enough time to store 2 weeks.

![1_week_2_week_same](https://user-images.githubusercontent.com/19638200/41637145-6dd9b7a0-7420-11e8-97c6-a62a113df734.jpg)

![market_trends_graph](https://user-images.githubusercontent.com/19638200/41637146-6deb4d44-7420-11e8-86a1-45744e63c524.jpg)

**Comment by shawn-j** [comment]
here's all the trends in settings.analyzer.json:


![settings](https://user-images.githubusercontent.com/19638200/41637219-ceeaea8c-7420-11e8-9207-48b6af30961d.jpg)

**Comment by Legedric** [comment]
No, there is no time limit but PTM needs to run for two weeks to have the data for two weeks. Until then it will only have the data for the timeframe you have been running PTM and that's why 1 weeke and 2 weeks trends look the same for you now.

**Comment by shawn-j** [comment]
thanks for the answer!

i've been restarting it several times per day, testing out different settings.. i've added in many trends, and *all* of them seem to load unique values instantly after every restart, except for trends past 1 week.  you can see it in this pic.  and i still installed PTM less than a week ago. 

![more_trends](https://user-images.githubusercontent.com/19638200/41806619-438950ca-768f-11e8-91f3-44d687782746.jpg)


 some of the analysis data seems a bit innacurate when compared to the tradingview & binance charts though..  I've checked to see if i'm mixing up absolute/relative or CMC/exchange and it still appears to be off by a bit.  is that because it needs time to record the trend?  in the graph at the top, it does show flat lines for new trends initially.  but those same trends show unique data in the analyzer below from the moment I restart.  

some of the data has been accurate, like the 3-day for example, is pretty accurate and i put that in less than 3 days after i initially installed PTM.   others seem to be off by a bit..  the 5-minute, 15 & 1hr seem to be  off by a bit more, but they fluctuate, sometimes they're a bit more accurate, sometimes a bit less.

when you say i need to run it long enough for the trend, is this based on absolute run-time from the first time I started it?  or does this data reset every time I restart?

just trying to figure out which variables are at play..  1st install, most recent restart, CMC/exchange, absolute/relative, and any lag time in getting the data, and latency from the VPS.  is there anything else involved?
