### ISSUE TITLE
problem with mac seup

### ISSUE THREAD

**Issue by enigmat** [Legedric/ptmagic#56]
Start PTMagic.cmd: line 2: pause: command not found

**Comment by jamesblackjr** [comment]
The PTMagic.cmd doesn't work for Mac, it's only for windows.

Do **only** Step 1 from here:
[https://www.microsoft.com/net/learn/get-started/macos](https://www.microsoft.com/net/learn/get-started/macos)

Then you should be able to run the following command (from the PTMagic folder):
`dotnet PTMagic.dll`

and, to run the PT Magic Monitor:
`dotnet Monitor/Monitor.dll`

**Comment by enigmat** [comment]
Unhandled Exception: System.ArgumentException: The directory name /Users/billhanoman/Documents/ProfitTrailer-Bittrex/PTMagic/ Bittrex/PTMagic/ is invalid.
Parameter name: path
   at Monitor.Program.Main(String[] args) in D:\Tools\PTMagic\Monitor\Program.cs:line 32
Abort trap: 6

**Comment by Legedric** [comment]
@jamesblackjr PT Magic is platform independant. You should be able to run it on any platform.

However, we do not use Unix and do not own any Mac so we will not be able to support this as we can with using Windows.

@enigmat There seems to be a space in your path "/Users/billhanoman/Documents/ProfitTrailer-Bittrex/PTMagic**/ B**ittrex/PTMagic/" Right in front of that Bittrex there, maybe that's the cause for the path being claimed invalid.
