### ISSUE TITLE
[Feature Suggestion]

### ISSUE THREAD

**Issue by Fransenson** [Legedric/ptmagic#561]
Hey there!

You might have encountered different PTMagic settings that use single market settings heavily. Especially in the current market, I'd like to exclude certain pairs from being modified by PTM (for manual SOM for example). 

Could we get a "ignored pairs list" to leave a pair trading in PT but not modified by PTM? 

Thanks!

**Comment by Legedric** [comment]
You already have the AllowedMarkets and IgnoredMarkets settings for every Single Market Setting you specifiy. This should be quite sufficient for that.

**Comment by Fransenson** [comment]
Oh I thought this would only be to include or exclude markets for the market trends. Even then, if I have like 6-10 SMS I would have to exclude the coin for every one of those. An overarching ignore list would be cleaner.
