### ISSUE TITLE
OffTriggers not working

### ISSUE THREAD

**Issue by shawn-j** [Legedric/ptmagic#562]
i'm trying to get OffTriggers to work..  is there anything wrong with this syntax?

the code isn't pasting in quite right but you get the idea.. I tried starting the whole thing with quotes but it's not working.. it just picks up the quotes from the offtriggers

{
        "SettingName": "Downtrend",
        "TriggerConnection": "OR",
            "OffTriggerConnection": "OR",
        "Triggers": [
          {
            "MarketTrendName": "Exchange24h",
               "MarketTrendRelation": "Absolute",
            "MaxChange": -5
          },
          {
            "MarketTrendName": "Exchange3d",
                "MarketTrendRelation": "Absolute",
            "MaxChange": -4
          },
          {
            "MarketTrendName": "Exchange7d",
              "MarketTrendRelation": "Absolute",
            "MaxChange": -3
          },
          {
            "MarketTrendName": "Exchange14d",
              "MarketTrendRelation": "Absolute",
            "MaxChange": -3
          }
        ],

            "OffTriggers": [

              {
            "MarketTrendName": "Exchange5min",
               "MarketTrendRelation": "Absolute",
            "MaxChange": -2
          },
             {
            "MarketTrendName": "Exchange15min",
               "MarketTrendRelation": "Absolute",
            "MaxChange": -3
          }, 
                 {
            "MarketTrendName": "Exchange3d",
              "MarketTrendRelation": "Absolute",
            "MinChange": 1,
            "MaxChange": 4
          },
          {
            "MarketTrendName": "Exchange7d",
             "MarketTrendRelation": "Absolute",
            "MinChange": -3,
            "MaxChange": 3
          }

        ],

i've seen other people using the same syntax with code posted in the discord, saying it works fine in PTM

these off triggers should take a few coins out of "downtrend" and into 2 other market settings that use those same values as on-triggers, but it's not happening.  any advice?  

also, "StopProcessWhenTriggered": true, doesn't seem to be working either. 

 so i'm stuck with each coin in multiple trends at once, can't shift from one trend to another.

**Comment by Legedric** [comment]
I need your full settings.analyzer.json file to see the entire picture here, please.

**Comment by shawn-j** [comment]
[settings.analyzer.json.zip](https://github.com/Legedric/ptmagic/files/2146206/settings.analyzer.json.zip)

code was still pasting wrong, is a zip ok?

**Comment by shawn-j** [comment]
code pastes well enough to understand at least.. i'll paste it here:

{
  "AnalyzerSettings": {
    "MarketAnalyzer": {
      "StoreDataMaxHours": 336, // Number of hours to store market data
      "IntervalMinutes": 5, // Interval in minutes for PTMagic to check market trends and triggers
      "ExcludeMainCurrency": false, // Excludes the main currency (for example BTC) from market trend analysis
      "MarketTrends": [
        {
          "Name": "Exchange5min",
          "Platform": "Exchange",
          "MaxMarkets": 100,
          "TrendMinutes": 5,
          "TrendCurrency": "Market",
          
        },
          
          {
          "Name": "Exchange15min",
          "Platform": "Exchange",
          "MaxMarkets": 100,
          "TrendMinutes": 15,
          "TrendCurrency": "Market",
          
        },
          
          {
          "Name": "Exchange1h",
          "Platform": "Exchange",
          "MaxMarkets": 30,
          "TrendMinutes": 60,
          "TrendCurrency": "Market" // Trend Currency to build the trend against. If set to "Fiat", the trend will take the USD value of your main currency into account to build the trend. (Allowed values are: Fiat, Market)
        },
        {
          "Name": "Exchange4h",
          "Platform": "Exchange",
          "MaxMarkets": 30,
          "TrendMinutes": 240,
          "TrendCurrency": "Market",
          "DisplayOnMarketAnalyzerList": false
        },
        {
          "Name": "Exchange12h",
          "Platform": "Exchange",
          "MaxMarkets": 30,
          "TrendMinutes": 720,
          "TrendCurrency": "Market",
          "DisplayOnMarketAnalyzerList": false
        },
        {
          "Name": "Exchange24h",
          "Platform": "Exchange",
          "MaxMarkets": 30,
          "TrendMinutes": 1440,
        "TrendCurrency": "CoinMarketCap"
        },
          {
          "Name": "Exchange3d",
          "Platform": "Exchange",
          "MaxMarkets": 30,
          "TrendMinutes": 4320,
         "TrendCurrency": "CoinMarketCap"
        },
          {
          "Name": "Exchange7d",
          "Platform": "Exchange",
          "MaxMarkets": 30,
          "TrendMinutes": 10080,
          "TrendCurrency": "CoinMarketCap"
        },
          
           {
          "Name": "Exchange14d",
          "Platform": "Exchange",
          "MaxMarkets": 30,
          "TrendMinutes": 20160,
          "TrendCurrency": "CoinMarketCap"
        }
         
      ]
    },
    "GlobalSettings": [ // Global settings for Profit Trailer properties
      {
        "SettingName": "EndOfTheWorld", // UNIQUE name of your setting
        "TriggerConnection": "AND", // Define if triggers will be connected by AND or OR
        "Triggers": [ // Your triggers for this setting
          {
            "MarketTrendName": "Exchange1h", // Reference to the market trend specified above
            "MaxChange": 0 // Maximum trend change % for this setting to get triggered
          },
          {
            "MarketTrendName": "Exchange12h",
            "MaxChange": -1
          },
          {
            "MarketTrendName": "Exchange24h",
            "MaxChange": -5
          }
        ],
        "PairsProperties": { // Properties for PAIRS.PROPERTIES
          
          "DEFAULT_trailing_profit_OFFSETPERCENT": -50
          
        },
        "DCAProperties": { // Properties for DCA.PROPERTIES
          "DEFAULT_DCA_trailing_profit_OFFSETPERCENT": -50
        }
      },
      {
        "SettingName": "TankingDown",
        "TriggerConnection": "AND",
        "Triggers": [
          {
            "MarketTrendName": "Exchange1h",
            "MaxChange": 0
          },
          {
            "MarketTrendName": "Exchange12h",
            "MaxChange": 0
          },
          {
            "MarketTrendName": "Exchange24h",
            "MaxChange": -3,
            "MinChange": -5
          }
        ],
        "PairsProperties": {
          "DEFAULT_A_buy_value_OFFSETPERCENT": -10,
          "DEFAULT_B_buy_value_OFFSETPERCENT": -10,
          "DEFAULT_C_buy_value_OFFSETPERCENT": -10,
          "DEFAULT_trailing_buy_OFFSETPERCENT": 10,
          "DEFAULT_trailing_profit_OFFSETPERCENT": -25
        },
        "DCAProperties": {
          "DEFAULT_DCA_trailing_buy_OFFSETPERCENT": -25
        }
      },
      {
        "SettingName": "BearSighted",
        "TriggerConnection": "AND",
        "Triggers": [
          {
            "MarketTrendName": "Exchange1h",
            "MaxChange": 1
          },
          {
            "MarketTrendName": "Exchange12h",
            "MaxChange": 0
          },
          {
            "MarketTrendName": "Exchange24h",
            "MaxChange": -1,
            "MinChange": -3
          }
        ],
        "PairsProperties": {
          "DEFAULT_A_buy_value_OFFSETPERCENT": -15,
          "DEFAULT_B_buy_value_OFFSETPERCENT": -15,
            "DEFAULT_C_buy_value_OFFSETPERCENT": -15,
          "DEFAULT_trailing_profit_OFFSETPERCENT": -10
        },
        "DCAProperties": {
          "DEFAULT_DCA_trailing_profit_OFFSETPERCENT": -10
        }
      },
      {
        "SettingName": "ReadyForLiftOff",
        "TriggerConnection": "AND",
        "Triggers": [
          {
            "MarketTrendName": "Exchange1h",
            "MinChange": -1
          },
          {
            "MarketTrendName": "Exchange12h",
            "MinChange": 0
          },
          {
            "MarketTrendName": "Exchange24h",
            "MinChange": 1,
            "MaxChange": 3
          }
        ],
        "PairsProperties": {
          "DEFAULT_trailing_buy_OFFSETPERCENT": -25,
          "DEFAULT_A_sell_value_OFFSETPERCENT": 10
        },
        "DCAProperties": {
          "DEFAULT_DCA_A_sell_value_OFFSETPERCENT": 10
        }
      },
      {
        "SettingName": "ToTheMoon",
        "TriggerConnection": "AND",
        "Triggers": [
          {
            "MarketTrendName": "Exchange1h",
            "MinChange": 0
          },
          {
            "MarketTrendName": "Exchange12h",
            "MinChange": 1
          },
          {
            "MarketTrendName": "Exchange24h",
            "MinChange": 3
          }
        ],
        "PairsProperties": {
          "DEFAULT_trailing_buy_OFFSETPERCENT": -50,
          "DEFAULT_A_sell_value_OFFSETPERCENT": 25
        },
        "DCAProperties": {
          "DEFAULT_DCA_A_sell_value_OFFSETPERCENT": 25
        }
      },
      {
        "SettingName": "Default",
        "PairsProperties": {
          "File": "PAIRS.properties"
        },
        "DCAProperties": {
          "File": "DCA.properties"
        },
        "IndicatorsProperties": {
          "File": "INDICATORS.properties"
        }
      },
      
    ],
      
      
      
      
      
      
      
      
      
      
      
      
    "SingleMarketSettings": [ // Single market/pair settings for Profit Trailer properties
        
        
        
        
        
        
       
        
        
        
        

        {
        "SettingName": "Downtrend",
        "TriggerConnection": "OR",
            "OffTriggerConnection": "OR",
             
        "Triggers": [
          {
            "MarketTrendName": "Exchange24h",
               "MarketTrendRelation": "Absolute",
            "MaxChange": -5
          },
          {
            "MarketTrendName": "Exchange3d",
                "MarketTrendRelation": "Absolute",
            "MaxChange": -7
          },
          {
            "MarketTrendName": "Exchange7d",
              "MarketTrendRelation": "Absolute",
            "MaxChange": -8
          },
          {
            "MarketTrendName": "Exchange14d",
              "MarketTrendRelation": "Absolute",
            "MaxChange": -11
          }
        ],
            
            "OffTriggers": [
              
              {
            "MarketTrendName": "Exchange5min",
               "MarketTrendRelation": "Absolute",
            "MaxChange": -2
          },  
             {
            "MarketTrendName": "Exchange15min",
               "MarketTrendRelation": "Absolute",
            "MaxChange": -3
          },  
              {
            "MarketTrendName": "Exchange24h",
              "MarketTrendRelation": "Absolute",
            "MinChange": 1
            
          },
          {
            "MarketTrendName": "Exchange7d",
             "MarketTrendRelation": "Absolute",
             "MaxChange": 0
          }  
           
        ],
            
         
        "PairsProperties": {
          "DEFAULT_sell_only_mode_enabled": true, 
          "DEFAULT_DCA_enabled": true
          
        },
        "DCAProperties": {
            "DEFAULT_DCA_A_buy_value_OFFSETPERCENT": -25,
            "DEFAULT_DCA_A_sell_value_OFFSETPERCENT": -50
            
            
        }
      },  

        
        
        
    
        
 
        
        
        
        
        
        {
        "SettingName": "Reversal",
        "TriggerConnection": "AND",
        "Triggers": [
          {
            "MarketTrendName": "Exchange24h",
              "MarketTrendRelation": "Absolute",
            "MinChange": 1
            
          },
          {
            "MarketTrendName": "Exchange7d",
             "MarketTrendRelation": "Absolute",
             "MaxChange": 0
          }
           
        ],
        "PairsProperties": {
          "DEFAULT_trading_enabled": true,
          "DEFAULT_sell_only_mode_enabled": false, 
          "DEFAULT_DCA_enabled": true,
          "DEFAULT_A_buy_value": 45,
          "DEFAULT_B_buy_value": 40,
          "DEFAULT_C_buy_value_OFFSETPERCENT": 50,
          "DEFAULT_trailing_buy_OFFSETPERCENT": -50
        },
            "DCAProperties": {
               "DEFAULT_DCA_A_buy_value_OFFSETPERCENT": 50,
               //"DEFAULT_DCA_C_buy_value_OFFSETPERCENT": 1,
               "DEFAULT_DCA_trailing_buy_OFFSETPERCENT": -50,
               "DEFAULT_DCA_A_sell_value_OFFSETPERCENT": 50,
               "DEFAULT_DCA_B_sell_value_OFFSETPERCENT": 20,
               "DEFAULT_DCA_trailing_profit_OFFSETPERCENT": 20
                
                
            }
        
      },  
        

        
        
        
        
        
        
         {
        "SettingName": "ReversalReversal",
        "TriggerConnection": "AND",
        "Triggers": [
          {
            "MarketTrendName": "Exchange24h",
              "MarketTrendRelation": "Absolute",
            "MaxChange": -2
            
          },
          {
            "MarketTrendName": "Exchange3d",
             "MarketTrendRelation": "Absolute",
             "MinChange": 3
          }
           
        ],
        "PairsProperties": {
          "DEFAULT_trading_enabled": false,
          "DEFAULT_sell_only_mode_enabled": true, 
          "DEFAULT_DCA_enabled": true,
          "DEFAULT_C_buy_value_OFFSETPERCENT": -50,
          "DEFAULT_trailing_buy_OFFSETPERCENT": -50
        },
            "DCAProperties": {
               "DEFAULT_DCA_A_buy_value_OFFSETPERCENT": -25,
               //"DEFAULT_DCA_C_buy_value_OFFSETPERCENT": 1,
               "DEFAULT_DCA_trailing_buy_OFFSETPERCENT": -50,
               "DEFAULT_DCA_A_sell_value_OFFSETPERCENT": -25,
               "DEFAULT_DCA_B_sell_value_OFFSETPERCENT": -20,
               "DEFAULT_DCA_trailing_profit_OFFSETPERCENT": -20
                
                
            }
        
      },  
        
        
        
        
        
        
        
        
        
        
        
        {
        "SettingName": "BlacklistNewCoins",
        "StopProcessWhenTriggered": true,
        "Triggers": [
          {
            "AgeDaysLowerThan": 14
          }
        ],
        "PairsProperties": {
          "DEFAULT_trading_enabled": false,
          "DEFAULT_sell_only_mode_enabled": true,
          "DEFAULT_DCA_enabled": false
        }
      },

        
        
        
        
        {
        "SettingName": "PumpNDumpProtection",
        "TriggerConnection": "OR",
        "Triggers": [
          {
            "MarketTrendName": "Exchange1h",
            "MarketTrendRelation": "Relative", // The relation of the single market trend. Relative = Single market trend compared relative to the market trend / Absolute = Single market trend viewn on its own
            "MinChange": 5
          },
          {
            "MarketTrendName": "Exchange4h",
            "MarketTrendRelation": "Relative",
            "MinChange": 4
          },
          {
            "MarketTrendName": "Exchange12h",
            "MarketTrendRelation": "Relative",
            "MinChange": 4
          },
             {
            "MarketTrendName": "Exchange24h",
            "MarketTrendRelation": "Relative",
            "MinChange": 4
          },
           {
            "MarketTrendName": "Exchange3d",
            "MarketTrendRelation": "Relative",
            "MinChange": 6
          },
             {
            "MarketTrendName": "Exchange7d",
            "MarketTrendRelation": "Relative",
            "MinChange": 8
          },
             {
            "MarketTrendName": "Exchange14d",
            "MarketTrendRelation": "Relative",
            "MinChange": 12
          },
        ],
        "PairsProperties": {
          "DEFAULT_sell_only_mode_enabled": true,
          "DEFAULT_DCA_enabled": true
        }
      },
 
        
        
        
        
        
        
        {
        "SettingName": "FreefallBlock",
        "TriggerConnection": "OR",
            "OffTriggerConnection": "OR",
        "Triggers": [
          {
            "MarketTrendName": "Exchange1h",
            "MarketTrendRelation": "Absolute",
            "MaxChange": -5
          },
          {
            "MarketTrendName": "Exchange12h",
            "MarketTrendRelation": "Absolute",
            "MaxChange": -7
          },
          {
            "MarketTrendName": "Exchange24h",
            "MarketTrendRelation": "Absolute",
            "MaxChange": -10
          }
        ],
            "OffTriggers": [
          {
            "MarketTrendName": "Exchange1h",
            "MarketTrendRelation": "Absolute",
            "MaxChange": 2
          },
          {
            "MarketTrendName": "Exchange12h",
            "MarketTrendRelation": "Absolute",
            "MaxChange": 3
          },
          {
            "MarketTrendName": "Exchange24h",
            "MarketTrendRelation": "Absolute",
            "MaxChange": 5
          }
        ],
        "PairsProperties": {
          "DEFAULT_sell_only_mode_enabled": true,
          "DEFAULT_DCA_enabled": true,
          "DEFAULT_DCA_rebuy_timeout": 1000
            
        },
            "DCAProperties": {
            "DEFAULT_DCA_C_buy_value": 15
            
        }
      },
        
        
        
        
        
        
            
        {
            "SettingName": "QuickDip",
            "TriggerConnection": "OR",
            "StopProcessWhenTriggered": true,
            "Triggers": [
                
              {
            "MarketTrendName": "Exchange5min",
               "MarketTrendRelation": "Absolute",
            "MaxChange": -2
          },  
             {
            "MarketTrendName": "Exchange15min",
               "MarketTrendRelation": "Absolute",
            "MaxChange": -3
          }  
               
            
            ],
            
            "PairsProperties": {
                "DEFAULT_sell_only_mode_enabled": false,
                "DEFAULT_trading_enabled": true,
                "DEFAULT_DCA_enabled": true,
                "DEFAULT_A_buy_value": 45,
                "DEFAULT_B_buy_value": 40,
                "DEFAULT_C_buy_value": -1,
                "DEFAULT_trailing_buy": 0.5,
                "DEFAULT_A_sell_value_OFFSETPERCENT": 10,
                "DEFAULT_B_sell_value_OFFSETPERCENT": 10,
                "DEFAULT_trailing_sell": 0.5,
                "DEFAULT_rebuy_timeout": 0.0001
                   
            },
            "DCAProperties": {
                
              "DEFAULT_DCA_max_buy_times": 7,
              "DEFAULT_DCA_buy_percentage_1": 50,
              "DEFAULT_DCA_buy_percentage_2": 50,
              "DEFAULT_DCA_buy_percentage_3": 50,
              "DEFAULT_DCA_buy_percentage_4": 100,
              "DEFAULT_DCA_buy_percentage_5": 100,
              "DEFAULT_DCA_buy_percentage_6": 150,
              "DEFAULT_DCA_buy_percentage_7": 200,
                
                
              "DEFAULT_DCA_buy_trigger_1": -2,
              "DEFAULT_DCA_buy_trigger_2": -3,
              "DEFAULT_DCA_buy_trigger_3": -4,
              "DEFAULT_DCA_buy_trigger_4": -5,
              "DEFAULT_DCA_buy_trigger_5": -7,
              "DEFAULT_DCA_buy_trigger_6": -10,
              "DEFAULT_DCA_buy_trigger_7": -13,  
                
              "DEFAULT_DCA_A_sell_value_OFFSETPERCENT": -70,
              "DEFAULT_DCA_B_sell_value": 50,  
                "DEFAULT_DCA_trailing_profit": 0.2,
             "DEFAULT_DCA_take_profit_percentage": 1,
             "DEFAULT_DCA_take_profit_reset_percentage_move": 2,
             "DEFAULT_DCA_take_profit_wait_time": 30,
                "DEFAULT_DCA_rebuy_timeout": 15
            
        }
            
        }
        
        
        
        
        
        
        
        
        
        
    ]
  }
}

**Comment by shawn-j** [comment]
i've tried adding an offtrigger to downtrend that should always be true, and it doesn't seem to have any effect:

  
              {
            "MarketTrendName": "Exchange5min",
               "MarketTrendRelation": "Absolute",
            "MinChange": -100,
                  "MaxChange": 100
          },
