### ISSUE TITLE
PT won't start buying due to max pairs and DCA doesn't turn off

### ISSUE THREAD

**Issue by bartgrefte** [Legedric/ptmagic#563]
Yesterday I set up PT 2.0.13 with the CryptoGnome BTC config. After checking if the bot started without errors and was able to load data from Binance I enabled SOM, disabled DCA (due to bad experiences with bags) and then I started working on PTM 2.0.3 using the Windows install guide.

Since then both PT and PTM continuously indicate "max pairs" in PBL, while there's nothing in pairs or DCA, it hasn't made it's first buy yet. So how could it have reached max pairs? It's not like I set it to zero...

And then there's the PTM->Control->Status&Summary page, which indicates DCA level 10, even though I disabled DCA in both PT's webinterface as well as PTMagic\_presets\Default\PAIRS.properties.

I already checked the logs of PT and PTM for errors, didn't see any, and the PTM-settings are pretty much default, I only changed what had to be changed to get things going.

How do you troubleshoot something like this?

**Comment by Legedric** [comment]
So the DCA levels are being listed no matter if you activated DCA or not, that's independent from each other.

About the max pairs problem I am not sure what may influence this. Please check your pairs.properties in your PT monitor and post a screenshot of your max_trading_pairs settings.

**Comment by bartgrefte** [comment]
So the first screenshot with active settings is correct? That only causes confusion since DCA looks active, while it's supposed to be not.

![ptm-activesettings](https://user-images.githubusercontent.com/13036914/42080195-27012610-7b82-11e8-8e76-b4e37de72851.jpg)
![pt-tradingpairs](https://user-images.githubusercontent.com/13036914/42080196-27245a86-7b82-11e8-9202-2f19e6e24830.jpg)
![ptmagic-presets-default](https://user-images.githubusercontent.com/13036914/42080197-2741a44c-7b82-11e8-8d6e-f78c12bbf0c4.jpg)

**Comment by Legedric** [comment]
Looks correct. To really see if DCA is enabled you have to go to your Market Analyzer in PTM Monitor.

So it somehow looks like an issue with Profit Trailer itself. As the settings seem correct and as that is everything that PTM touches it seems like PT is not taking it fully into consideration.
Oh and make sure that there is no other line setting max_trading_pairs further down in your settings as this may overwrite the first setting.

**Comment by bartgrefte** [comment]
Are you referring to those checkmarks? I see none under DCA, so it looks like it's off :)

I couldn't find any other max_trading_pairs line, in any file, so that wasn't it. So I went for the "have you tried turning it off and on again" method (which I should've tried first), guess what, it worked?! No more max pairs. Now let's wait till it actually buys something.

**Comment by bartgrefte** [comment]
The bot seems to be working normally, no clue why the restart helped.

Speaking of restarts, PT has a shutdownbutton in the webinterface. If I need to restart the pc, how do I properly shutdown PTM? Don't see a shutdownbutton in the webinterface.

**Comment by Legedric** [comment]
PTM is always safe to be restarted :)
