### ISSUE TITLE
PTM making "impossible buys"

### ISSUE THREAD

**Issue by shawn-j** [Legedric/ptmagic#566]
i brought this up with a mod in the the PT, and narrowed it down to a PTM issue

PTM is making "impossible buys"- the average cost is much higher than the market price at the time of the 1st buy, even after DCA's.

![untitled](https://user-images.githubusercontent.com/19638200/42412534-1255dc0a-81dc-11e8-8b2d-0863cffbd4cc.jpg)

these are impossible buys:
https://www.binance.com/trade.html?symbol=XVG_BTC
https://www.binance.com/trade.html?symbol=BCC_BTC

this one is ok:
https://www.binance.com/trade.html?symbol=CND_BTC

please help, as this is basically giving me bags that don't exist or that should have been sold off already..  maybe PTM is reporting or displaying data innacurately?

after finding this issue, i ran 2 instances, 1 with PTM, 1 without. (both now updated to the latest version of PT)

sure enough, the PTM version kept on making impossible buys, and the PT version didn't.

**Comment by Legedric** [comment]
The thing is that PTM only does what you set it up to do. as PTM only changes you settings AS YOU CONFIGURE IT, it is impossible to say PTM is making (any) buys as PTM simply does not buy or sell anything.

The thing is, if this would be a realy issue with PTM, you would most certainly not be the only one having this issue. Instead, many others would have this problem and so far you are the only one reporting this.

So again: PTM does not buy anything. It just changes you PT settings in a way you alone configure it to do. Noone else.
