### ISSUE TITLE
SMS not ignoring specific markets

### ISSUE THREAD

**Issue by js8749** [Legedric/ptmagic#567]
Hello,
I use NorthStar Setting 3.0, but make my manual buys to, few days ago, i made a buy and it was in SMS blacklisted coins(this setting hide the coins that are 15 days old)

I was trying to a SMS do not affect a coin and i use SMS ignored markets and it don’t work

**Comment by Legedric** [comment]
Please provide the config lines you used to ignore this market.

**Comment by js8749** [comment]
Hello,



Enviado desde mi iPhone

**Comment by Legedric** [comment]
??

**Comment by js8749** [comment]
],
    "SingleMarketSettings": [
    //Trade Halt settings
      {
        "SettingName": "BlacklistNewCoins",
        "StopProcessWhenTriggered": true,
        "IgnoredMarkets": "MFT",
        "Triggers": [
          {
            "AgeDaysLowerThan": 15
          }
        ],
        "PairsProperties": {
          "DEFAULT_trading_enabled": false,
          "DEFAULT_sell_only_mode_enabled": true,
          "DEFAULT_DCA_enabled": false
        }
      },

**Comment by js8749** [comment]
the gui read the ignored market but it still not ignoring it

**Comment by js8749** [comment]
sorry i closed it by error

**Comment by Legedric** [comment]
Depending on your exchange, try BTC-MFT or MFTBTC and see if that works.

**Comment by js8749** [comment]
I use binance

Enviado desde mi iPhone

**Comment by js8749** [comment]
I will try that and get back to you

**Comment by Legedric** [comment]
Sorry, no clue about that error.

**Comment by js8749** [comment]
thanks Anyways!!
