### ISSUE TITLE
prevent buying coins that are still dropping in value

### ISSUE THREAD

**Issue by bartgrefte** [Legedric/ptmagic#568]
One thing that's always been a problem is that PT buys coins that are still in the process of dropping in value, causing the buying of coins that after buying go down to -20% or even further...

Recently I installed PTM, hoping that PTM would stop that behavior, but it doesn't seem to be doing that, PT still ends up buying coins that are still in the process of dropping in value.

Do the default PTM settings need some finetuning for something like that to work?

PT 2.0.13
PTM 2.0.3
Binance, BTC market.

**Comment by Legedric** [comment]
Yes, the default settings are more like a basic example of what you can do with PTM. To achieve a better protection against what you described and to limit your risks you need to adjust those settings or look for some more advanced "ready to use" settings like for example provided here:
https://github.com/stevenshizzleh
