### ISSUE TITLE
Wich files should I copy when UPGRADE

### ISSUE THREAD

**Issue by rodolpho2211** [Legedric/ptmagic#571]
I just upgrade my PT from 1.8 to 2.0.14 and PTMagic to V2.0.3  use this link was very helpfull and make everything easy ( https://www.youtube.com/watch?v=9Fo0CnWHDzM) .
But one thing is missing, all my previous sales.
Anybody know wich file should I copy and paste to get all the data that I had on my previously PT (Sales Overview, Market Trends etc,,
Thanks

**Comment by HojouFotytu** [comment]
See the notes on how to update.
