### ISSUE TITLE
Market Data Errorr

### ISSUE THREAD

**Issue by msaleh3000** [Legedric/ptmagic#574]
I have this market data error giving me NAN values for all indicators.
I closed PT Magic and deleted the file exchange and restarted but I have the same error.
Here is a photo of how it looks. 
I'm on Poloniex, Base currency USDT, PT Magic ver 2.0.3
![market](https://user-images.githubusercontent.com/8343562/43519688-73e2d42e-955e-11e8-8795-602324997f8a.jpg)

**Comment by HojouFotytu** [comment]
This is due to an error with a single coin not returning a valid trend.  Likely due to the coin being delisted.

Duplicate of #583

**Comment by HojouFotytu** [comment]
#584
