### ISSUE TITLE
PTMagic Monitor Update Failed with PT 2.1 

### ISSUE THREAD

**Issue by nobitacu** [Legedric/ptmagic#575]
Upon updating PT to 2.1, looks like it broke the PTM Monitor, as now it gives me this error:

"Ticker update failed!
PTMagic Monitor failed to update data. If this error does not go away by itself, please check the connection to your hosting PC."

One thing to note, looks like PTM is still updating the properties files just fine in PT. So looks like just the monitor not working update the PT 2.1 update. 

Thanks.

**Comment by smoochy** [comment]
Trying to open the SalesAnalyzer in PTM results in:

> Error.
> An error occurred while processing your request.
> Request ID: 0HLFNQ3JSFUQS:00000001
> 
> **Could not find file '[Path to PT folder]/ProfitTrailerData.json'**.
> at Interop.ThrowExceptionForIoErrno(ErrorInfo errorInfo, String path, Boolean isDirectory, Func`2 errorRewriter) at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String path, OpenFlags flags, Int32 mode) at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options) at System.IO.StreamReader..ctor(String path, Encoding encoding, Boolean detectEncodingFromByteOrderMarks, Int32 bufferSize) at System.IO.File.InternalReadAllText(String path, Encoding encoding) at System.IO.File.ReadAllText(String path) at Core.Main.DataObjects.ProfitTrailerData..ctor(String ptmBasePath, PTMagicConfiguration systemConfiguration) in D:\Tools\ptmagic-github\Core\DataObjects\ProfitTrailerData.cs:line 24 at Monitor.Pages.SalesAnalyzer.BindData() in D:\Tools\ptmagic-github\Monitor\Pages\SalesAnalyzer.cshtml.cs:line 28 at Microsoft.AspNetCore.Mvc.RazorPages.Internal.ExecutorFactory.VoidHandlerMethod.Execute(Object receiver, Object[] arguments) at Microsoft.AspNetCore.Mvc.RazorPages.Internal.PageActionInvoker.InvokeHandlerMethodAsync() at Microsoft.AspNetCore.Mvc.RazorPages.Internal.PageActionInvoker.InvokeNextPageFilterAsync() at Microsoft.AspNetCore.Mvc.RazorPages.Internal.PageActionInvoker.Rethrow(PageHandlerExecutedContext context) at Microsoft.AspNetCore.Mvc.RazorPages.Internal.PageActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted) at Microsoft.AspNetCore.Mvc.RazorPages.Internal.PageActionInvoker.InvokeInnerFilterAsync() at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeNextResourceFilter() at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResourceExecutedContext context) at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted) at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeFilterPipelineAsync() at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeAsync() at Microsoft.AspNetCore.Builder.RouterMiddleware.Invoke(HttpContext httpContext) at Microsoft.AspNetCore.Session.SessionMiddleware.Invoke(HttpContext context) at Microsoft.AspNetCore.Session.SessionMiddleware.Invoke(HttpContext context) at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.Invoke(HttpContext context)

**Comment by djbadders** [comment]
Same here, the issue makes sense as they moved the ProfitTrailerData.json to under the data folder now instead of the root of the PT folder.

**Comment by djbadders** [comment]
Ok so if you are on a Unix VPS run the following command in your Profit Trailer folder:
~~~
ln -s ./data/ProfitTrailerData.json ProfitTrailerData.json
~~~
This will create a symbolic link to the real PT data file and let PTMagic find it

**Comment by smoochy** [comment]
Thank you, that did the trick.

**Comment by djbadders** [comment]
Hmmm I don't think it is related as the command is just making a symbolic link to the moved data file and this error looks more like communicating with the PT configuration web service.

**Comment by AussieTerror** [comment]
Thanks for the quick workaround.

**Comment by bufonmc** [comment]
I~~~~~~ ~~

**Comment by bitnick21** [comment]
sorry i am not a coder, can you provide a step by step guide? thanks

**Comment by Chainsaw801** [comment]
@bitnick21 You need to open the command prompt, right click run as administrator.   Then you need to change directories into your ProfitTrailer folder then type the command @djbadders posted.    I'm not going to explain dos commands to you there is Google for that.     Good luck.  :)

**Comment by js8749** [comment]
@djbadders can you help me with the comand for a RPi with debian?

**Comment by djbadders** [comment]
It would be the same command for any Unix distro:

~~~
ln -s ./data/ProfitTrailerData.json ProfitTrailerData.json
~~~

**Comment by djbadders** [comment]
I have made a fixed version of PTM and you can get it from: https://github.com/djbadders/ptmagic/releases

I have requested a Pull of the changes into the main PTM.

**Comment by cryptomail2018** [comment]
followed all instructions still monitor not working
