### ISSUE TITLE
Monitor not working no more with PT 2.1 even followed djbladder instructions

### ISSUE THREAD

**Issue by cryptomail2018** [Legedric/ptmagic#581]
just a blank screen with Error 500

**Comment by jshplayer** [comment]
You need to create a symlink as a work around, I've been running PT Magic with the latest version for PT without issues doing so.

Put this in a batch file and run within PT directory

@echo off
mklink ProfitTrailerData.json .\data\ProfitTrailerData.json
pause

**Comment by HojouFotytu** [comment]
If you are running 2.0.3 that you downloaded before August 14, it doesn't contain the merged fix.  You need to either re-download 2.0.3 and copy it over to your previous installation, or download the 2.0.4 patch.
