### ISSUE TITLE
Some trends showing as ∞

### ISSUE THREAD

**Issue by Fransenson** [Legedric/ptmagic#583]
On the monitor as well as on the telegram messages, sometimes some trends get shown as "∞".

I am not sure if this impacts the trend detection / settings switch, as I did not have the time to watch more closely. 

Anyone else with this issue? is there a fix?

**Comment by HojouFotytu** [comment]
I've noticed this also -- it seems to be coins that have been de-listed from binance, but for which they still provide data  --  for example VEN...  If you have a closer look on the market analyzer, you will see that all trends are 0% for those coins.

To avoid having them screw up my triggers, I added "IgnoreMarkets": "xxxBTC, xxxBTC" to the top of each market trend.

**Comment by HojouFotytu** [comment]
here is my current list:  "IgnoredMarkets": "VENBTC, HSRBTC, RPXBTC, BCCBTC"
