### ISSUE TITLE
PTMM doesnt show last sales

### ISSUE THREAD

**Issue by khounjay** [Legedric/ptmagic#585]
I installed recently PTM which is working fine but it shows sales before October 10 only and not the sales since PTM was installed. It s pointing to the right PT folder.
It shows some coins that have been sold and not show some that I have right now

Any idea what to do ?

(probably something w the PT json file)

Cheers

**Comment by khounjay** [comment]
Ok I found out why, the link to ProfitTrailerData.json wasnt working

**Comment by HojouFotytu** [comment]
Yep.  This needs to be clarified on the install guide.  On my way to fix it now.
