### ISSUE TITLE
version 2.0.5 monitor issue 

### ISSUE THREAD

**Issue by cryptomail2018** [Legedric/ptmagic#592]
still have same problem with the monitor application GUI running

![mon issue cmd](https://user-images.githubusercontent.com/35930742/49335984-fa68d100-f62b-11e8-8b8b-34d4feff4840.PNG)
![localhost ptm 2 0 5](https://user-images.githubusercontent.com/35930742/49335985-fccb2b00-f62b-11e8-82a4-03cace559cfa.PNG)

**Comment by JackONeill12** [comment]
Did you clean install 2.0.5. It's only an update. So you need 2.0.3 and then update it to 2.0.5.

**Comment by HojouFotytu** [comment]
Some web assets were missing in the build.  

This has been fixed and a new file was posted which contains all the assets.  

Thanks for the notice!

**Comment by cryptomail2018** [comment]
thank you for info i try again 
with kind regards

Crypto Skimmerhttps://www.facebook.com/crypto.skimmer.1

 

    On Sunday, 2 December 2018, 2:36:10 pm GMT+7, JackONeill12 <notifications@github.com> wrote:  
 
 
Did you clean install 2.0.5. It's only an update. So you need 2.0.3 and then update it to 2.0.5.

**Comment by cryptomail2018** [comment]
did exactly what you tell me to do fresh install of 2.0.3 setup all files run it first then shut down install 2.0.5 over it in upgrade . now i have error showing and blank screen with wheel spinning . see attached CMD error 
port is open on 5040 in security as well as 5040 is bot 4 in my instance
![ptm 2nd](https://user-images.githubusercontent.com/35930742/49355767-9f061400-f6fb-11e8-9ebf-e1f06b298391.PNG)

**Comment by cryptomail2018** [comment]
> thank you for info i try again  with kind regards Crypto Skimmerhttps://[www.facebook.com/crypto.skimmer.1](http://www.facebook.com/crypto.skimmer.1) On Sunday, 2 December 2018, 2:36:10 pm GMT+7, JackONeill12 <notifications@github.com> wrote: Did you clean install 2.0.5. It's only an update. So you need 2.0.3 and then update it to 2.0.5. — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or mute the thread.

https://github.com/Legedric/ptmagic/issues/592#issuecomment-443598251

**Comment by cryptomail2018** [comment]
> Some web assets were missing in the build.
> 
> We are working on resolving this. For now follow Jack's advice.

did exactly what you tell me to do fresh install of 2.0.3 setup all files run it first then shut down install 2.0.5 over it in upgrade . now i have error showing and blank screen with wheel spinning . see attached CMD error
port is open on 5040 in security as well as 5040 is bot 4 in my instance.
![ptm 2nd](https://user-images.githubusercontent.com/35930742/49355956-7c282f80-f6fc-11e8-9568-733e149d6ecb.PNG)

**Comment by HojouFotytu** [comment]
This usually happens when you launch a second instance of the monitor without realizing there is already an instance running, hidden  somewhere behind another window.  ;)

**Comment by cryptomail2018** [comment]
not the case of this time , clean fresh install reboot and startup as per instruction 
1 bot only

**Comment by HojouFotytu** [comment]
Well the error states that the port is already in use, so it doesn't seem like a PTM error.  something about the way your VPS is configured perhaps?

**Comment by cryptomail2018** [comment]
yes i noticed that . port 5040 is purely for bot 4 PTM port is open in security settings , i try different port as well but no luck 
with kind regards

Crypto Skimmerhttps://www.facebook.com/crypto.skimmer.1

 

    On Thursday, 6 December 2018, 3:28:18 pm GMT+7, HojouFotytu <notifications@github.com> wrote:  
 
 
Well the error states that the port is already in use, so it doesn't seem like a PTM error. something about the way your VPS is configured perhaps?
