### ISSUE TITLE
updating 2.0.3 to 2.0.5

### ISSUE THREAD

**Issue by netscaline** [Legedric/ptmagic#593]
Hello,
My ptmagic2.0.3 was working fine under Debian9
I've update to 2.0.5 following the steps, and ptmagic don't start anymore complaining about the following : 

System.NullReferenceException: Object reference not set to an instance of an object.
at Core.Main.PTMagic.RunConfigurationChecks() in G:\PTM Dev Bot\ptmagic-master\Core\Main\PTMagic.cs:line 535
at Core.Main.PTMagic.StartProcess() in G:\PTM Dev Bot\ptmagic-master\Core\Main\PTMagic.cs:line 431
at PTMagic.Program.Main(String[] args) in G:\PTM Dev Bot\ptmagic-master\PTMagic\Program.cs:line 21

Strangely, monitor seems running fine....

PS : I provide the following if it can help (remembered struggling with that at first :) 
dpkg -l |grep NET
ii  aspnetcore-runtime-2.1          2.1.6-1                        amd64        Microsoft ASP.NET Core 2.1.6 Shared Framework
ii  aspnetcore-store-2.0.0          2.0.0-1                        amd64        Microsoft ASP.NET Core 2.0.0 Runtime Package Store
ii  aspnetcore-store-2.0.3          2.0.3-1                        amd64        Microsoft ASP.NET Core 2.0.3 Runtime Package Store
ii  aspnetcore-store-2.0.5          2.0.5-1                        amd64        Microsoft ASP.NET Core 2.0.5 Runtime Package Store
ii  dotnet-host                     2.1.6-1                        amd64        Microsoft .NET Core Host - 2.1.6
ii  dotnet-hostfxr-2.0.5            2.0.5-1                        amd64        Microsoft .NET Core Host FX Resolver - 2.0.5 2.0.5
ii  dotnet-hostfxr-2.1              2.1.6-1                        amd64        Microsoft .NET Core Host FX Resolver - 2.1.6 2.1.6
ii  dotnet-runtime-2.0.5            2.0.5-1                        amd64        Microsoft .NET Core Runtime - 2.0.5 Microsoft.NETCore.App 2.0.5
ii  dotnet-runtime-2.1              2.1.6-1                        amd64        Microsoft .NET Core Runtime - 2.1.6 Microsoft.NETCore.App 2.1.6
ii  dotnet-sdk-2.1.4                2.1.4-1                        amd64        Microsoft .NET Core SDK - 2.1.4
ii  net-tools                       1.60+git20161116.90da8a0-1     amd64        NET-3 networking toolkit

**Comment by HojouFotytu** [comment]
Please re-read the release notes.  The patch requires a small update your settings.general file.

**Comment by netscaline** [comment]
Ok my bad, i thought it was not mandatory, only to use that if i want to use CMC data :)

thanks
