### ISSUE TITLE
DCA calculation is incorrect

### ISSUE THREAD

**Issue by yuvalbar84** [Legedric/ptmagic#6]
In each trigger, the bot buys the amount you currently have, but with the new price.
so if you buy with 1 BTC at first, and your first buy trigger is -3,
you'll buy at the price of 0.97.

Can you take into consideration all the buy triggers?

**Comment by Legedric** [comment]
It is already planned to have some kind of "advanced" DCA calculator that takes the triggers into account and provides a more accurate calculation.

**Comment by nstefi** [comment]
Yes, I noticed this too. Compared to this calculation:
[https://docs.google.com/spreadsheets/d/1d-UZuXRiI15oKW-nBNvb8Qheki10OCEYEKkK7irlW6Y/edit#gid=67889719](https://docs.google.com/spreadsheets/d/1d-UZuXRiI15oKW-nBNvb8Qheki10OCEYEKkK7irlW6Y/edit#gid=67889719)

Also I would like to see some additional DCA parameters like max_buy_times, max_cost from DCA, min_buy_balance_percentage (like in the Google Sheet).
Thanks.
