### ISSUE TITLE
Too many backup files of PAIRS file

### ISSUE THREAD

**Issue by nstefi** [Legedric/ptmagic#61]
The bot creates a backup of PAIRS file every minute, even if nothing was changed in the PAIRS file.
That means 60 files in an hour, 1440 files in 1 day, that will fill up my hard drive soon if I'm not watching and deleting files manually once a while from that folder. Or Windows Explorer would have a hard time showing that folder if there are thousands of files.
Can you make the bot to create a backup only when a change is detected to the PAIRS file? Maybe compare the file to the last backup file, and only back up if it's different (or date/time different).
Thanks.

**Comment by Legedric** [comment]
The files are only being kept for 24h so it won't get any larger than 1440. PT Magic backups the files before it makes any changes (single pair settings are changes too and these may happen every minute indeed).
