### ISSUE TITLE
Multiple comments in INDICATORS.properties file

### ISSUE THREAD

**Issue by jamesblackjr** [Legedric/ptmagic#63]
I have several comments like this in my INDICATORS.properties file, every minute it adds another:

```
# ####################################
# ####### PTMagic Current Setting ########
# PTMagic_ActiveSetting = Default
# PTMagic_LastChanged = 2/19/18 7:21 PM
# ####################################

# ####################################
# ####### PTMagic Current Setting ########
# PTMagic_ActiveSetting = Default
# PTMagic_LastChanged = 2/19/18 7:20 PM
# ####################################

# ####################################
# ####### PTMagic Current Setting ########
# PTMagic_ActiveSetting = Default
# PTMagic_LastChanged = 2/19/18 7:19 PM
# ####################################
```

**Comment by Legedric** [comment]
Thanks, that seems to be the root cause of issue #46. I still have to figure out what causes this. Do you see that only in your indicators or also the other files?

**Comment by jamesblackjr** [comment]
yes just the INDICATORS file.

**Comment by Legedric** [comment]
What does the header of your PAIRS file look like? Because that's where the check for the active setting happens in.

**Comment by Legedric** [comment]
Also: Is this the indicators file from your PT/trading directory? If so, how does the one in "_presets" look. Same issue?

**Comment by jamesblackjr** [comment]
I'm looking at the one in the PT/trading directory.  The one in _presets is not changed.

**Comment by Legedric** [comment]
No changed means it has those headers, too or not?

**Comment by Legedric** [comment]
Closing this issue as it seems the cause is the same as for #46
