### ISSUE TITLE
error

### ISSUE THREAD

**Issue by mrkush** [Legedric/ptmagic#64]
![error](https://user-images.githubusercontent.com/13472039/36406939-c58f04fe-15b7-11e8-858c-f43d5b70d492.PNG)

**Comment by Dysrupt** [comment]
I got that error by placing the copied files from default settings to the wrong folder.  I pasted them in PTMagic.1.0.2 when I should have pasted them in PTMagic. double check that

**Comment by mrkush** [comment]
Just reinstall PTMagic and  i pasted Monitor,settings.analyzer.json,settings.general.json in PTMagic mian folder with other stuff going to run it and see

**Comment by Legedric** [comment]
This issue will be fixed in 1.0.3
