### ISSUE TITLE
How to install Caddy as Reverse Proxy with Letsencrypt SSL and Basicauth in less then 5 min

### ISSUE THREAD

**Issue by azenator** [Legedric/ptmagic#69]
Hey there,

this is the way how to install Caddy server as Reverse Proxy with Letsencrypt SSL and Basicauth in less then 5 Minutes.

First you need to add a A entrypointing to the IP of your VPS or ROOT:

`your.doma.in IN A 10.13.37.3`

Getting Caddy and creating dirs and files needed:
```
curl -s https://getcaddy.com | bash -personal
chown -R root:www-data /etc/caddy
touch /etc/caddy/Caddyfile
mkdir /etc/ssl/caddy
chown -R www-data:root /etc/ssl/caddy
chmod 0770 /etc/ssl/caddy
```

Now we need to install Caddy as Service:
`curl -s https://raw.githubusercontent.com/mholt/caddy/master/dist/init/linux-systemd/caddy.service -o /etc/systemd/system/caddy.service`

/etc/caddy/Caddyfile:

```
https://your.domai.in {
  basicauth / user pass
proxy / localhost:5000 {
  websocket
  transparent
  }
}
```
Starting Caddy:
`systemctl start caddy`

Now Caddy will generate an Letsencrypt SSL Certificate. You can check the status in /var/log/syslog:
`tail -f /var/log/syslog`

Sometimes the Nameservers need some minutes to update. If it fails, just wait a couple of minutes and then try again to restart Caddy.

`systemctl restart caddy`

When the syslog says this:
```
Feb 20 08:27:36 myvps caddy[29489]: http://my.doma.in
Feb 20 08:27:36 myvos caddy[29489]: 2018/02/20 08:27:36 http://my.doma.in
Feb 20 08:27:36 myvps caddy[29489]: https://my.doma.in
Feb 20 08:27:36 myvps caddy[29489]: 2018/02/20 08:27:36 https://my.doma.in
```
you're done. Just navigate to your domain with your browser, log in and be happy.

**Comment by Legedric** [comment]
Thanks, very much appreciated!

**Comment by TwixRaider** [comment]
Thanks a lot. Put this in the Wiki under "FAQ / Tips / Additional Guides"
