### ISSUE TITLE
Error: Trend changes not found

### ISSUE THREAD

**Issue by mfcholdings** [Legedric/ptmagic#70]
How do you setup for use with ETH or USDT?

Also i am using binance with your default settings and i am getting 

Matching Triggers
Exchange1h- - Max 0.00%
Exchange12h- - Max 0.00%
Exchange24h- - Min -5.00% - Max: -3.00%

Market Trends
CMC24h: 1.60%
Exchange1h: -0.68%
Exchange1h: -4.97%
Exchange1h- -4.77%

seems like the trends are very incorrect... please help

**Comment by Legedric** [comment]
The Setup for BTC, ETH and USDT is similar, although we never tested USDT so far.

The trend names you got there:
Market Trends
CMC24h: 1.60%
Exchange**1h**: -0.68%
Exchange**1h**: -4.97%
Exchange**1h**- -4.77%

The look indeed weird. Please check what is configured inb you setting.analyzer file as "MarketTrends".

**Comment by mfcholdings** [comment]
"MarketTrends": [
        {
          "Name": "CMC24h", // UNIQUE market trend name (to be referenced by your triggers below)
          "Platform": "CoinMarketCap", // Platform to grab prices from (Allowed values are: CoinMarketCap, Exchange)
          "MaxMarkets": 50, // Number of markets/pairs to analyze sorted by 24h volume
          "TrendMinutes": 1440 // Number of minutes to build a trend (1440 = 24h, 720 = 12h, 60 = 1h)
        },
        {
          "Name": "Exchange1h",
          "Platform": "Exchange",
          "MaxMarkets": 50,
          "TrendMinutes": 60,
          "TrendCurrency": "Market" // Trend Currency to build the trend against. If set to "Fiat", the trend will take the USD value of your main currency into account to build the trend. (Allowed values are: Fiat, Market)
        },
        {
          "Name": "Exchange12h",
          "Platform": "Exchange",
          "MaxMarkets": 50,
          "TrendMinutes": 720,
          "TrendCurrency": "Market"
        },
        {
          "Name": "Exchange24h",
          "Platform": "Exchange",
          "MaxMarkets": 50,
          "TrendMinutes": 1440,
          "TrendCurrency": "Market"
        }

**Comment by Legedric** [comment]
And your telegram message is really showing 3 times Exchange1h or is that probably just a typo?

**Comment by mfcholdings** [comment]
MOST RECENT MESSAGE.... it was a typo.. but i feel the trend data is incorrect..  i am in tanking down setting always .. 

Matching Triggers
Exchange1h- - Max 0.00%
Exchange12h- - Max 0.00%
Exchange24h- - Min -5.00% - Max: -3.00%

Market Trends
CMC24h: -0.45%
Exchange1h: -0.25%
Exchange12h: -3.25%
Exchange24h- -4.99%

**Comment by mfcholdings** [comment]
so for do i need to change anything or will the bot correct itself and display the ETH price
and for USDT?

**Comment by Legedric** [comment]
version 1.0.3 should show your market you configured for Profit Trailer.

The trends are correct. I am also in downwards trends for days now.

**Comment by mfcholdings** [comment]
ok..   i am getting this error when i try to run the second bot ETH
![2 bot error](https://user-images.githubusercontent.com/36377757/36423997-2e4eafaa-1642-11e8-9afc-20c1abb0b260.png)

**Comment by Legedric** [comment]
This seems to be an old version. Please update to version 1.0.3

**Comment by mfcholdings** [comment]
ok... do i just unzip and drag all files into my PT Magic Folder

**Comment by Legedric** [comment]
Please follow the steps listed here:
https://github.com/Legedric/ptmagic/wiki/Updating-PT-Magic

**Comment by mfcholdings** [comment]
i updated and still getting these errors when i try to run the second bot
![2 bot error 1](https://user-images.githubusercontent.com/36377757/36424659-6798a868-1644-11e8-960d-edc6a3feaef5.png)
![2 bot error 2](https://user-images.githubusercontent.com/36377757/36424666-6ba71106-1644-11e8-97c5-aba62dc67394.png)

**Comment by mfcholdings** [comment]
i am using the same settings.analyzer file for both BTC and ETH bot...  BTC bot is running fine but when i go to start the ETH bot i get the above errors

**Comment by Legedric** [comment]
This error is a nasty one to find and the same as in issue #35 
Which exchange are you using, please?

**Comment by Legedric** [comment]
Can you please download and update the bot to this release?
I know it still says 1.0.3 but it is a re-upload with more logging added to it so I can get more information out of the errors.

[PTMagic 1.0.3.zip](https://github.com/Legedric/ptmagic/files/1740092/PTMagic.1.0.3.zip)

**Comment by mfcholdings** [comment]
![1](https://user-images.githubusercontent.com/36377757/36426159-81684262-1649-11e8-9095-7ca561fc6e2d.png)
![2](https://user-images.githubusercontent.com/36377757/36426160-81849782-1649-11e8-98a1-11776397af0a.png)

**Comment by mfcholdings** [comment]
bot 1 BTC is running fine.. but when i try to start bot 2 ETH it does this..  i normally run 4-5 bots so i really would like to have this going for all.. 

PS.. amazing work man love the interface and display.. A+++++

**Comment by Legedric** [comment]
What exchange are you using and what is your config for ALL_enabled_pairs? Is it set to ALL or a whitelist?

**Comment by mfcholdings** [comment]
BINANCE
 where do i find all_enabled pairs..

**Comment by mfcholdings** [comment]
i cant find this setting in PT Magic

**Comment by Legedric** [comment]
Sorry, it is found in your Pairs.properties in Profit Trailer/trading

**Comment by mfcholdings** [comment]
MARKET = ETH
ALL_trading_enabled = false

**Comment by mfcholdings** [comment]
bot 1 BTC        WORKING 
MARKET = BTC
ALL_trading_enabled = false

bot 2 ETH       ERRORS
MARKET = ETH
ALL_trading_enabled = false

**Comment by Legedric** [comment]
Is there no value for "ALL_enabled_pairs"?

**Comment by mfcholdings** [comment]
no its FALSE

**Comment by mfcholdings** [comment]
both are the same but bot 1 works and bot 2 does not

**Comment by mfcholdings** [comment]
also..
"IntervalMinutes": 1
is this ok to run with BINANCE.. will this get IP BAN

**Comment by Legedric** [comment]
Ok thanks. I did not even know that PT allowed it to set ALL_enabled_pairs to false.

I re-uploaded 1.0.3 release to fix this issue.

**Comment by mfcholdings** [comment]
so just download the new one.. 

also..
"IntervalMinutes": 1
is this ok to run with BINANCE.. will this get IP BAN

**Comment by mfcholdings** [comment]
where do i donwload the new version .. on here is shows updated 5 hours ago... 
https://github.com/Legedric/ptmagic/releases

correct link above?

**Comment by Legedric** [comment]
Yes, the one that says re-uploaded (although it says 5 hours ago - which is not correct)

**Comment by mfcholdings** [comment]
still error when i run second bot... 

![1](https://user-images.githubusercontent.com/36377757/36433683-6214aed2-165d-11e8-8c4c-c37e3821908e.png)
![2](https://user-images.githubusercontent.com/36377757/36433684-622c429a-165d-11e8-8a15-1811acfb040a.png)

**Comment by Legedric** [comment]
Please try this:
- Stop PT Magic (the one bot that has these errors)
- Delete the folder named "Exchange" inside "_data" in PT Magic
- Start the bot again (it will take up to 15 minutes again to rebuild the exchange data)

**Comment by mfcholdings** [comment]
that solved the issue...      we are running the second bot...  on ETH but it is still diplaying BTC price in top right of dashboard and all profits $ is showing incorreect based of BTC price.. also i am using the ost recent version but the dashboard shows v1.02 

![1](https://user-images.githubusercontent.com/36377757/36439050-f7e7eea2-166b-11e8-87e6-b34010843f8b.png)

**Comment by mfcholdings** [comment]
this fixed with time...  

i tried to run usdt bot.. 

i get these errors and its been running for 15+min ..  
no price showing in usdt ticker on dashboard also 
![2](https://user-images.githubusercontent.com/36377757/36440606-3e30af6c-1670-11e8-93b9-58de620ea329.png)
![3](https://user-images.githubusercontent.com/36377757/36440607-3e482d4a-1670-11e8-9a27-4f2806a450c3.png)

**Comment by Legedric** [comment]
Yeah, USDt still needs testing. I never used that myself so this is a known issue.

On your second bot, did you adjust the path in your second monitor for the "PTMagicBasePath" to point to your second bot?
It is strange that it doesn't show any market name before the 11,560.97!?

**Comment by mfcholdings** [comment]
the above log is for USDT...   
BTC bot 1 ETH bot 2 are working fine now 
USDT is having the above errors and no price for USDT is showing in the dashboard ticker in top right

**Comment by mfcholdings** [comment]
first picture is in all bots...  BTC and ETH seem to be working correctly...  USDT still not showing price
Second picture is in all bots monitor cmd window.
![4](https://user-images.githubusercontent.com/36377757/36446368-582b38b8-1681-11e8-9be5-4390aeb0c6b1.png)
![5](https://user-images.githubusercontent.com/36377757/36446370-5841f4f4-1681-11e8-9307-e3a3384159fb.png)

**Comment by Legedric** [comment]
That's just the version check to GitHub, this may be ignored. Although I do not know why GitHub is so clunky with their API ;)

**Comment by mfcholdings** [comment]
Any update on usdt price to show correctly in dashboard

**Comment by Legedric** [comment]
Not yet. Some USDT bugs will get fixed with 1.0.4 though.

**Comment by wealthinspire** [comment]
It shows that PT Magic shows the trend in the PT Pairs file, but the strategies shows as disabled.
