### ISSUE TITLE
Get this Error

### ISSUE THREAD

**Issue by funsports** [Legedric/ptmagic#72]
Any idea wat that means?

2018/02/20 10:16:17.564 FATAL - 
The remote server returned an error: 
(403) Forbidden. System.Net.WebException The remote server returned an error: (403) Forbidden.    
at System.Net.HttpWebRequest.GetResponse()
at BusinessRules.MarketAnalyzer.BaseAnalyzer.GetSimpleJsonObjectFromURL(String url, 
LogHelper log) in D:\Tools\PTMagic\BusinessRules\MarketAnalyzer\BaseAnalyzer.cs:line 45

**Comment by Legedric** [comment]
This issue will be fixed in 1.0.3

**Comment by funsports** [comment]
Thx for information.
