### ISSUE TITLE
Password???

### ISSUE THREAD

**Issue by aqueiroz** [Legedric/ptmagic#73]
Hi Guys, just a quick one.
Is there a password option?
Cant see anything on Wiki?

Want to add a password before accessing the dashboard.

Thank you so much. Product looks great

**Comment by Legedric** [comment]
Not right now, but we planned to add this soon.

**Comment by azenator** [comment]
You can protect your PTMagic with Caddy.

https://github.com/Legedric/ptmagic/issues/69

**Comment by aqueiroz** [comment]
Might not use it then. although i do like the product... anyone can look at my stuff. well keep up the good work. I would put adding a password as something quite important. thanks for the quick response

**Comment by Baconqueror** [comment]
Use nginx as a reverse proxy. #52

**Comment by aqueiroz** [comment]
thanks for the options guys.  Although would rather not mess with my VPS instance as im running quite  few things on it.  Would be nice to have something on the settings file like in Proffit trailer server.password =

**Comment by Legedric** [comment]
It won't be that simple, but we are working on a solution right now making it possible to set your own password through the monitor and saving it encrypted. We don't like storing plain text passwords in text files (like PT does).

**Comment by aqueiroz** [comment]
cool.  thanks.

Loving the software... now we just hope the market improves :-)
