### ISSUE TITLE
Update Issue 1.0.3

### ISSUE THREAD

**Issue by Towfikh** [Legedric/ptmagic#74]
Hi, I have followed the steps in updating PTMagic but still comes up with this error Your bot is out of date. The most recent version of PTMagic is ver 1.0.3. when I run it.

**Comment by Legedric** [comment]
Monitor or the bot itself?

**Comment by Towfikh** [comment]
just downloded the version 1.0.3. I believe is the monitor

**Comment by Towfikh** [comment]
PTMagic 1.0.3 - Imporvement, fixes and shoutouts

**Comment by Legedric** [comment]
What is showing you the message I mean. Do you see it in the console log of the PT Magic bot or on the icon (bottom left) of your monitor?

**Comment by Towfikh** [comment]
![capture](https://user-images.githubusercontent.com/35907532/36422830-96a2f938-1635-11e8-8896-4f8fb7144532.PNG)

**Comment by Legedric** [comment]
It seems like you did not really update your bot likei advised here:
https://github.com/Legedric/ptmagic/wiki/Updating-PT-Magic

**Comment by Towfikh** [comment]
I did follow the steps few times but to no avail.
Thanks anyway for trying to help me out but I just reinstalled it from scratch and it's working fine.

**Comment by Legedric** [comment]
Good to know, thanks :)
