### ISSUE TITLE
Why is the Monitor/Dashboard not corretly displayed in Windows Edge/IE?

### ISSUE THREAD

**Issue by cryptomaj** [Legedric/ptmagic#75]
![dashboard](https://user-images.githubusercontent.com/36665049/36424121-2abeffa0-163a-11e8-8a30-ea791fecbaae.JPG)

**Comment by Legedric** [comment]
Something is blocking the load of the css and js files. 
Please see if your IE/Edge is running in protected mode as suggested here in issue #34:
https://github.com/Legedric/ptmagic/issues/34#issuecomment-366836471

**Comment by cryptomaj** [comment]
I've put browser into unprotected mode also tried on Firefox browser. Still same result. 
![mozilla](https://user-images.githubusercontent.com/36665049/36425315-563be0e0-163e-11e8-8fdd-803a003a1239.JPG)

**Comment by Legedric** [comment]
Please check if all files are located in your Monitor folder.

There should be several files and folders like:
wwwroot
wwwroot/assets
wwwroot/assets/css
wwwroot/assets/js

**Comment by cryptomaj** [comment]
Yes checked them before, they are all there: 
![wwwroot](https://user-images.githubusercontent.com/36665049/36425949-7596d7a4-1640-11e8-8fb0-6e6467f631c6.JPG)

**Comment by Legedric** [comment]
When you hit F12 in your browser, what does it say? 404 not found errors? Can you show what path the browser is trying to acess when trying to load one of these files?

**Comment by cryptomaj** [comment]
I don't get 404 error. Attached is screen shot after pressing F12
![error1](https://user-images.githubusercontent.com/36665049/36427102-1509e9f4-1644-11e8-9c02-a54ee8750087.PNG)

**Comment by cryptomaj** [comment]
"PTMagicBasePath": "C:\TraderBotGnome ETH\PTMagic\PTMagic\"
![error2](https://user-images.githubusercontent.com/36665049/36427284-aef07bd2-1644-11e8-89e8-e077163b3dd0.PNG)

**Comment by Legedric** [comment]
When you hit F12 and go to the tab "console" are there any listings there?

**Comment by cryptomaj** [comment]
No that's blank
![error3](https://user-images.githubusercontent.com/36665049/36428327-8cec9dba-1647-11e8-91b8-e7f9dc2cf1ab.PNG)

**Comment by CryptoNewb** [comment]
Failed to load resource: the server responded with a status of 404 (Not Found)
nv.d3.min.css Failed to load resource: the server responded with a status of 404 (Not Found)
bootstrap.min.css Failed to load resource: the server responded with a status of 404 (Not Found)
icons.css Failed to load resource: the server responded with a status of 404 (Not Found)
style_dark.css Failed to load resource: the server responded with a status of 404 (Not Found)
custom.css Failed to load resource: the server responded with a status of 404 (Not Found)
modernizr.min.js Failed to load resource: the server responded with a status of 404 (Not Found)
jquery.min.js Failed to load resource: the server responded with a status of 404 (Not Found)
jquery.blockUI.js Failed to load resource: the server responded with a status of 404 (Not Found)
popper.min.js Failed to load resource: the server responded with a status of 404 (Not Found)
detect.js Failed to load resource: the server responded with a status of 404 (Not Found)
jquery.slimscroll.js Failed to load resource: the server responded with a status of 404 (Not Found)
bootstrap.min.js Failed to load resource: the server responded with a status of 404 (Not Found)
fastclick.js Failed to load resource: the server responded with a status of 404 (Not Found)
waves.js Failed to load resource: the server responded with a status of 404 (Not Found)
wow.min.js Failed to load resource: the server responded with a status of 404 (Not Found)
jquery.nicescroll.js Failed to load resource: the server responded with a status of 404 (Not Found)
jquery.scrollTo.min.js Failed to load resource: the server responded with a status of 404 (Not Found)
custom.js Failed to load resource: the server responded with a status of 404 (Not Found)
tablesaw.js Failed to load resource: the server responded with a status of 404 (Not Found)
d3.min.js Failed to load resource: the server responded with a status of 404 (Not Found)
nv.d3.min.js Failed to load resource: the server responded with a status of 404 (Not Found)
notify.js Failed to load resource: the server responded with a status of 404 (Not Found)
notify-metro.js Failed to load resource: the server responded with a status of 404 (Not Found)
jquery.core.js Failed to load resource: the server responded with a status of 404 (Not Found)
jquery.app.js Failed to load resource: the server responded with a status of 404 (Not Found)
jquery.min.js Failed to load resource: the server responded with a status of 404 (Not Found)
popper.min.js Failed to load resource: the server responded with a status of 404 (Not Found)
bootstrap.min.js Failed to load resource: the server responded with a status of 404 (Not Found)
detect.js Failed to load resource: the server responded with a status of 404 (Not Found)
fastclick.js Failed to load resource: the server responded with a status of 404 (Not Found)
jquery.slimscroll.js Failed to load resource: the server responded with a status of 404 (Not Found)
jquery.blockUI.js Failed to load resource: the server responded with a status of 404 (Not Found)
waves.js Failed to load resource: the server responded with a status of 404 (Not Found)
wow.min.js Failed to load resource: the server responded with a status of 404 (Not Found)
jquery.nicescroll.js Failed to load resource: the server responded with a status of 404 (Not Found)
jquery.scrollTo.min.js Failed to load resource: the server responded with a status of 404 (Not Found)
custom.js Failed to load resource: the server responded with a status of 404 (Not Found)
tablesaw.js Failed to load resource: the server responded with a status of 404 (Not Found)
d3.min.js Failed to load resource: the server responded with a status of 404 (Not Found)
nv.d3.min.js Failed to load resource: the server responded with a status of 404 (Not Found)
notify.js Failed to load resource: the server responded with a status of 404 (Not Found)
notify-metro.js Failed to load resource: the server responded with a status of 404 (Not Found)
(index):174 Uncaught ReferenceError: $ is not defined
    at (index):174
(index):192 Uncaught ReferenceError: $ is not defined
    at (index):192
jquery.core.js Failed to load resource: the server responded with a status of 404 (Not Found)
jquery.app.js Failed to load resource: the server responded with a status of 404 (Not Found)
tablesaw.css Failed to load resource: the server responded with a status of 404 (Not Found)
nv.d3.min.css Failed to load resource: the server responded with a status of 404 (Not Found)
icons.css Failed to load resource: the server responded with a status of 404 (Not Found)
custom.css Failed to load resource: the server responded with a status of 404 (Not Found)
style_dark.css Failed to load resource: the server responded with a status of 404 (Not Found)
bootstrap.min.css Failed to load resource: the server responded with a status of 404 (Not Found)



I got this in my console page... What to do now?

**Comment by Legedric** [comment]
@CryptoNewb At what paths does the browser look for these files?

**Comment by cryptomaj** [comment]
Hi Legedric,

Console screen shot below.

![error4](https://user-images.githubusercontent.com/36665049/36437241-5d054630-165e-11e8-86d0-c322f778c8e0.PNG)

**Comment by Legedric** [comment]
@TwixRaider Any idea?

Error 404 on windows machine with different browsers for the assets. Seems to be some sort of security issue, but what could it be? Usually there shouldn't be something like this on windows.

**Comment by cryptomaj** [comment]
I don't know how, but I managed to resolve the issue by doing a new PT Magic install. Many thanks for your help Legedric.
