### ISSUE TITLE
Graphs don't show latest date

### ISSUE THREAD

**Issue by yllesh** [Legedric/ptmagic#78]
On the dashboard and sales analyzer page the graphs don't show the latest date.
I'm running two instances of ptmagic (connected to two different PT bots) on two different servers.
1 instance shows 6 february as latest date and the other instance shows 16 january as latest date.

The last 10 days view does show the latest date on both instances (20 february).

**Comment by Legedric** [comment]
Screenshot please.

**Comment by yllesh** [comment]
![graph](https://user-images.githubusercontent.com/36665853/36434333-143cc2f6-165f-11e8-8d5f-4e2c756d6466.png)

**Comment by Legedric** [comment]
Is it possible that your bot's last sale happened on that day?

Because my bot is in deep DCA bags and did not sell anything for two days. So my graph is ending on Feb 17th where it did its last sale.

Of course that shouldn't be like this in the graph but it helps finding the issue :)
