### ISSUE TITLE
Do you have donation address?

### ISSUE THREAD

**Issue by blockheadbits** [Legedric/ptmagic#79]
I just stumbled across this and was wondering if you all have a donation address for ETH/BTC set up.  I use profit trailer but haven't been really satisfied with it, particularly trying to get any type of clear guidance on the using the addon (their wiki is pretty lacking).  Going to give this a try later.  If it works better than profit trailer, I'd like to donate (preferably ETH).  Thanks for making this freely available!

**Comment by TwixRaider** [comment]
Thank you for considering a donation. We have donation addresses at the end of the start page of our Wiki:

https://github.com/Legedric/ptmagic/wiki
