### ISSUE TITLE
ERROR - Trading settings directory not found (/var/opt/pttrading/) 

### ISSUE THREAD

**Issue by i1wan** [Legedric/ptmagic#8]
I am trying to run the command:

dotnet PTMagic.dll

But I am getting this error:

2018/02/17 12:37:47.598 ERROR - Trading settings directory not found (/var/opt/pttrading/) 

What am I doing wrong?

my pt directory is "/var/opt/pt/"

I don't know where I change the "Trading settings directory"

**Comment by Legedric** [comment]
Please look into the file "settings.general.json" and see if your Profit Trailer path is set correctly.

**Comment by i1wan** [comment]
Hi, 

The setting in the file "settings.general.json" is set correctly.
"ProfitTrailerPath": "/var/opt/pt/"
But the error is still there ...

**Comment by Legedric** [comment]
It seems like was an issue with trailing slashes on Unix. Please check if release 1.0.1 fixed the issue for you.
If not, please reopen this issue.
