### ISSUE TITLE
This doesn't work with USDT trade?

### ISSUE THREAD

**Issue by Crypto-Bites** [Legedric/ptmagic#82]
![capture](https://user-images.githubusercontent.com/36629846/36431040-1e3d244a-1631-11e8-8a24-9573a0da785b.PNG)

**Comment by Legedric** [comment]
Please re-download 1.0.3 as I just fixed another error (those in yellow in your screenshot). The error in red is occuring as there is no market price for USDT-USDT. This will be fixed in a future release.
