### ISSUE TITLE
Make market columns sortable (and sort by name by default?)

### ISSUE THREAD

**Issue by krims0n32** [Legedric/ptmagic#83]
![screenshot_2018-02-20_16-19-09](https://user-images.githubusercontent.com/661853/36432174-d75dac42-1659-11e8-99ab-0f61a2957871.png)

It would be nice if the market view columns could be sortable.

**Comment by goferit** [comment]
+1

**Comment by Legedric** [comment]
This will be implemented with the next release.
But be aware that the timeframe column is only sortable for timeframes if 1h and greater. If you are using minutes, the sorting will be off as "5m" in that colum is considered larger than "1h" for example.
