### ISSUE TITLE
Request : change the layout of DCA-CALC with DCA in columns

### ISSUE THREAD

**Issue by JeanGalt** [Legedric/ptmagic#86]
It is certainly more common to use more than 12 pairs, than more than 12 DCAs.
Also it would be better to put DCA levels in columns, and pairs in rows.

**Comment by Legedric** [comment]
To be honest I am undecided about this. Having DCA in rows seems more logical to me. But if others aggred to you, they may give this issue a thumbs up and +1 and we will consider a change.

**Comment by Brisco00** [comment]
I agree with displaying DCA levels in columns and pairs in rows.  This could allow the table to grow / contract vertically to match the # of pairs specified in the search criteria.  You could also add column totals to see how much each DCA level will cost.  A grand total of the "DCA column totals" should match the "Total Balance Needed" value.

**Comment by Cryptonic2** [comment]
I think, visually, the DCA calc layout looks as it should. Sometimes though, I have found that I run out of real estate and can’t see the pairs numbers beyond a certain point to the right.

**Comment by JeanGalt** [comment]
Otherwise, it may be possible to leave the choice to each user, by proposing the two layers with a similar manipulation to that used to choose the sorting criterion in the Market Trends ?

**Comment by HojouFotytu** [comment]
Agreed.  DCA in columns, pairs in rows.   More likely that there will be a large number of pairs, and a small number of DCAs.

**Comment by Jaguar143** [comment]
+for this @Legedric I support this i normally went to 16 pairs to 24 pairs which the calculator do not support. The point here is usability of the calculator in the long run. I know its a major restructuring of the code but in the long run it will pay of. Consider that Crypto currency is growing. I can imagine ICO will go bubble too.. Maybe 500 to 750 coins in the coming 5 years.

**Comment by Legedric** [comment]
Ok, the next release will have some changes for the DCA calculator, including this one.

**Comment by Jaguar143** [comment]
Thank you very much @Legedric

**Comment by JeanGalt** [comment]
Thank you @Legedric (and others !)
