### ISSUE TITLE
PTMagic Monitor failed to update data

### ISSUE THREAD

**Issue by XRIICrypto** [Legedric/ptmagic#9]
I've got everything up and running, cmd screen for the monitor is on and I can connect to localhost but then receive this message:

Monitor update failed!
PTMagic Monitor failed to update data. If this error does not go away by itself, please check the connection to your hosting

I've checked everything from the wiki twice. Can't seem to find a solution...

**Comment by Legedric** [comment]
So the main page is showing up but the "inner" content failes to load? Could you please provide a screenshot?

**Comment by XRIICrypto** [comment]
<img width="1904" alt="schermafbeelding 2018-02-17 om 13 59 15" src="https://user-images.githubusercontent.com/33671425/36341193-e0e89770-13ea-11e8-860c-3f0c02f77ab3.png">
<img width="1911" alt="schermafbeelding 2018-02-17 om 13 59 22" src="https://user-images.githubusercontent.com/33671425/36341194-e0fcf0e4-13ea-11e8-8b7e-8aad80ded57b.png">

Sales analyzer returns error 500
Market trends works
DCA calculator returns error 500
Donate works

**Comment by Legedric** [comment]
Is the PT Magic bot running without any issues?
It seems like the is a problem for the monitor to find the file "ProfitTrailerData.json" in your Profit Trailer directory.

Can you please double check if that files exists in your PT directory?

**Comment by XRIICrypto** [comment]
Yes, the bot is running without issues and files are modified.

I've started with a clean install of PT but the data file and backup do exist in the ProfitTrailer folder.

**Comment by Legedric** [comment]
Ok, can you please download the current release (re-uploaded it a minute ago)?
I implemented a new error page so we get some more information out of it instead of just an error 500.

After updating the monitor you should see a detailed error when you try to open the Sales Analyzer. If so, please post a screenshot of the error here.

**Comment by XRIICrypto** [comment]
<img width="1920" alt="schermafbeelding 2018-02-17 om 14 36 04" src="https://user-images.githubusercontent.com/33671425/36341533-e8f55354-13ef-11e8-9e04-05f6bb1eabd3.png">

This is the error I see when I try to open the sales analyser. The dashboard keeps getting the same error message.

**Comment by Legedric** [comment]
Did your PT sell anything so far?

I assume there is an issue within your data file, maybe because you said it is a fresh PT install.

**Comment by XRIICrypto** [comment]
I have no pairs now, only BTC. Data file is empty.

**Comment by Legedric** [comment]
Can you check if the new release (re-uploaded just now) still brings the same error?

Just update the monitor with the current release. I implemented something to handle data files not contaiing any sales so far.

**Comment by XRIICrypto** [comment]
It works now! Only thing I notice is that the balance at the top right is 0 which is incorrect.

**Comment by TwixRaider** [comment]
Did you set a value for "StartBalance" in your settings.general.json file? PT Magic has no access to your exchange (like Profit Trailer itself) so it cannot read the balance from there.

**Comment by XRIICrypto** [comment]
I haven't done that. Changed it now and now it shows my balance. Thank you for support!
