### ISSUE TITLE
Issue on MacOSX 10.13.2

### ISSUE THREAD

**Issue by eiertee** [Legedric/ptmagic#90]
Followed everything as i should and getting following error:

Unhandled Exception: System.InvalidOperationException: Sequence contains no elements
   at System.Linq.Enumerable.Average[TSource](IEnumerable`1 source, Func`2 selector)
   at PTMagic.PTMagic.MarketTrendCheckTimer_Elapsed(Object sender, ElapsedEventArgs e) in D:\Tools\PTMagic\PTMagic\PTMagic.cs:line 393
   at PTMagic.Program.Main(String[] args) in D:\Tools\PTMagic\PTMagic\Program.cs:line 177
Abort trap: 6

At the first run, it did come up and load everything fine. After a reboot it will give me this error after each try to start up

**Comment by Legedric** [comment]
Can you please post a screenshot of the command windows (if that exists on a MAC) so we can see some lines above that?

**Comment by cyberience** [comment]
bash-3.2$ dotnet PTMagic.dll 
2018/02/21 20:18:46.081 INFO -  
2018/02/21 20:18:46.170 INFO -   ██████╗ ████████╗    ███╗   ███╗ █████╗  ██████╗ ██╗ ██████╗ 
2018/02/21 20:18:46.173 INFO -   ██╔══██╗╚══██╔══╝    ████╗ ████║██╔══██╗██╔════╝ ██║██╔════╝ 
2018/02/21 20:18:46.173 INFO -   ██████╔╝   ██║       ██╔████╔██║███████║██║  ███╗██║██║      
2018/02/21 20:18:46.173 INFO -   ██╔═══╝    ██║       ██║╚██╔╝██║██╔══██║██║   ██║██║██║      
2018/02/21 20:18:46.173 INFO -   ██║        ██║       ██║ ╚═╝ ██║██║  ██║╚██████╔╝██║╚██████╗ 
2018/02/21 20:18:46.173 INFO -   ╚═╝        ╚═╝       ╚═╝     ╚═╝╚═╝  ╚═╝ ╚═════╝ ╚═╝ ╚═════╝ 
2018/02/21 20:18:46.174 INFO -                          Version 1.0.3 
2018/02/21 20:18:46.174 INFO -  
2018/02/21 20:18:46.209 FATAL - Error loading configuration! System.IO.FileNotFoundException The configuration file 'settings.general.json' was not found and is not optional. The physical path is '/Users/geoffrey/_dev/PTMagic/settings.general.json'.    at Microsoft.Extensions.Configuration.FileConfigurationProvider.Load(Boolean reload)
   at Microsoft.Extensions.Configuration.ConfigurationRoot..ctor(IList`1 providers)
   at Microsoft.Extensions.Configuration.ConfigurationBuilder.Build()
   at Globals.SystemConfiguration.LoadSettings(String basePath) in D:\Tools\PTMagic\Globals\SystemConfiguration.cs:line 24
   at PTMagic.Program.Main(String[] args) in D:\Tools\PTMagic\PTMagic\Program.cs:line 41

Unhandled Exception: System.IO.FileNotFoundException: The configuration file 'settings.general.json' was not found and is not optional. The physical path is '/Users/geoffrey/_dev/PTMagic/settings.general.json'.
   at PTMagic.Program.Main(String[] args) in D:\Tools\PTMagic\PTMagic\Program.cs:line 59
Abort trap: 6

**Comment by michaeltietjen** [comment]
Cyber, you need to rearrange the folder file structure because of how the zip file unzips.

**Comment by eiertee** [comment]
Nevermind - a removal of .net sdk and a fresh reinstall made the trick on my side. I was also able to replicate the problem - it happens when PTMagic is running, and the configuration file is hot'changed & saved in a texteditor. After doing this, the only way to get it back up is to go for a fresh .net sdk & PT reinstall
