### ISSUE TITLE
Followed Everything Correctly - Windows VPS - Double Click to Start and Spins for a Few Seconds & Does Nothing (Discord Channel?)

### ISSUE THREAD

**Issue by lebwoski** [Legedric/ptmagic#94]
Basically what I said. I have followed step by step and reverified through watching other install videos that I am not missing anything. Whenever I try and open it, it doesn't open. No error. No cmd window pop-up, nothing. Just spins windows mouse for a few sec. 

If it helps: Windows Sever 2016 Datacenter v1607

Also, curious if there is a discord channel setup for PTMagic? EDIT: There is: https://discord.gg/ye3epnY

EDIT: Also, just realized VPS has some updates available, so going to update and see if that makes a difference. 

Thank you.

**Comment by lebwoski** [comment]
Edit 2: Downloaded and installed newest PTMagic - same result. 
Still waiting on server to update.

**Comment by shotam3** [comment]
Did you install net core windows server to your vps??

**Comment by lebwoski** [comment]
Yes, it is installed as well
<img width="759" alt="screen shot 2018-02-20 at 10 32 04 pm" src="https://user-images.githubusercontent.com/36686579/36463208-f42334bc-168d-11e8-97c5-f95289ac1a3d.png">

**Comment by shotam3** [comment]
Or Ok well idk.. but im running ptmagic virmach vps  and it works great

**Comment by Legedric** [comment]
We had users reporting this issue and they found out that something was blocking the start of PT Magic. Unfortunately they did not say exactly what blocked it.

**Comment by lebwoski** [comment]
Installed updates - same result. Hopefully someone who experienced this prior can chime in.

**Comment by creakyjoints** [comment]
works fine on my vps. virmach also

**Comment by Cryptonic2** [comment]
If you right click the CMD file and choose properties, then you should see at the bottom something to the likes of “this has been downloaded from another computer and is blocked. Please unblock yada yada”... just click the unblock box and apply. That fixed the issue for me

**Comment by Legedric** [comment]
@Cryptonic2 Thanks for the info!
