### ISSUE TITLE
Loop stuck

### ISSUE THREAD

**Issue by Zamboniman** [Legedric/ptmagic#96]
This has happened twice now. 

The main loop gets stuck here:

2018/02/20 21:51:40.466 INFO - Starting market trend check with Version 1.0.3                 │
2018/02/20 21:51:40.466 INFO - CoinMarketCap - Getting market data... 

and locks up until ctrl-c and starting again.

Issue with CoinMarketCap maybe? Except it's only happening with USDT as the base, not with BTC or ETH.

**Comment by Zamboniman** [comment]
Seems intermittent. Watched it run through a few more times. Most times it works, but then once again it got stuck until I terminated and restarted.

**Comment by Legedric** [comment]
Hmmm usually there is a timeout as default for that but I will look into it.

On a side note: USDT is still not tested and has many issues with PT Magic.

**Comment by Zamboniman** [comment]
Yeah, it definitely seems USDT related. How long is the timeout? The two times I noticed it was stuck for over 20 minutes before I restarted it.

**Comment by Legedric** [comment]
Not more than 90 seconds usually.

**Comment by Zamboniman** [comment]
It hasn't happened again. Appears to have been something odd that was happening 10-12 hours ago.

**Comment by Legedric** [comment]
Ok thanks anyway! There will also be some USDT fixes in the next release.
