### ISSUE TITLE
PT Magic - Update Version

### ISSUE THREAD

**Issue by Cryptonic2** [Legedric/ptmagic#97]
Is there an easy way to update the version of PT Magic that I am using? Currently I have 1.0.1 and would like to update to the newest version, but don’t want to lose any settings/sales data. Is there a specific file that I would need to replace with the new one in the current folder? Also, can I just jump to the newest one or do I have to update one at a time?

**Comment by Zamboniman** [comment]
https://github.com/Legedric/ptmagic/wiki/Updating-PT-Magic
