### ISSUE TITLE
FATAL - The remote server returned an error: (403) 

### ISSUE THREAD

**Issue by sputnik001** [Legedric/ptmagic#98]
PT Magic runs and I can access the UI (both locally and remotely), however, this error keeps coming up in the Monitor window:
```
FATAL - The remote server returned an error: (403) Forbidden. System.Net.WebException The remote server returned an error: (403) Forbidden.    at System.Net.HttpWebRequest.GetResponse()
   at BusinessRules.MarketAnalyzer.BaseAnalyzer.GetSimpleJsonObjectFromURL(String url, LogHelper log) in D:\Tools\PTMagic\BusinessRules\MarketAnalyzer\BaseAnalyzer.cs:line 45
```

**Comment by rbkuhn** [comment]
I get the same error. I'm running the Monitor on Linux Mint 17 and I've tried Apache2 and Nginx webservers.

**Comment by cmjacques** [comment]
I get the same error and then the monitor crashes. Perhaps it's hitting a rate limit with too many GET requests. I'm going to see if increasing IntervalMinutes in settings.analyzer.json will help.

**Comment by Legedric** [comment]
This error is only related to the version check PT Magic is doing to GitHub. This should not crash or influence the bot or the monitor.
