### ISSUE TITLE
"settings.general.json"

### ISSUE THREAD

**Issue by creakyjoints** [Legedric/ptmagic#99]
go to open gui and says it cant find it? should be opened from command line first and then open in browser on port 5000?

**Comment by TwixRaider** [comment]
The command line starts the web server (Kestrel) that serves the monitor GUI. Browsing to localhost:5000 actually shows it.

**Comment by creakyjoints** [comment]
it will not start because it gives error that it cant find that json file

**Comment by Legedric** [comment]
@creakyjoints Please check if you set your base path correctly as describe in step 11 here:
https://github.com/Legedric/ptmagic/wiki/Setup-PT-Magic-on-Windows

**Comment by creakyjoints** [comment]
that fixed it. i had put in profit trailer path. thanks for the help.
